/********************************************************************
* TFancyHistogramCanvasDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TFancyHistogramCanvasDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTFancyHistogramCanvasDict();
extern void G__cpp_setup_inheritanceTFancyHistogramCanvasDict();
extern void G__cpp_setup_typetableTFancyHistogramCanvasDict();
extern void G__cpp_setup_memvarTFancyHistogramCanvasDict();
extern void G__cpp_setup_globalTFancyHistogramCanvasDict();
extern void G__cpp_setup_memfuncTFancyHistogramCanvasDict();
extern void G__cpp_setup_funcTFancyHistogramCanvasDict();
extern void G__set_cpp_environmentTFancyHistogramCanvasDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TFancyHistogramCanvas.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_TClass;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_TBuffer;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_TMemberInspector;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_string;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_TGCompositeFrame;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_TLegend;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_TDataContainer;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_vectorlETGenericDatamUcOallocatorlETGenericDatamUgRsPgR;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_reverse_iteratorlEvectorlETGenericDatamUcOallocatorlETGenericDatamUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_TGCheckButton;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_TGRadioButton;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_TGNumberEntry;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_TGLabel;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_TCanvasHandleBase;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_TRootanaDisplay;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_vectorlEpairlEintcOTCanvasHandleBasemUgRcOallocatorlEpairlEintcOTCanvasHandleBasemUgRsPgRsPgR;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_reverse_iteratorlEvectorlEpairlEintcOTCanvasHandleBasemUgRcOallocatorlEpairlEintcOTCanvasHandleBasemUgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_THistogramArrayBase;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_TGHButtonGroup;
extern G__linked_taginfo G__TFancyHistogramCanvasDictLN_TFancyHistogramCanvas;

/* STUB derived class for protected member access */
