/********************************************************************
* TMainDisplayWindowDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TMainDisplayWindowDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTMainDisplayWindowDict();
extern void G__cpp_setup_inheritanceTMainDisplayWindowDict();
extern void G__cpp_setup_typetableTMainDisplayWindowDict();
extern void G__cpp_setup_memvarTMainDisplayWindowDict();
extern void G__cpp_setup_globalTMainDisplayWindowDict();
extern void G__cpp_setup_memfuncTMainDisplayWindowDict();
extern void G__cpp_setup_funcTMainDisplayWindowDict();
extern void G__set_cpp_environmentTMainDisplayWindowDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TMainDisplayWindow.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TMainDisplayWindowDictLN_TClass;
extern G__linked_taginfo G__TMainDisplayWindowDictLN_TBuffer;
extern G__linked_taginfo G__TMainDisplayWindowDictLN_TMemberInspector;
extern G__linked_taginfo G__TMainDisplayWindowDictLN_string;
extern G__linked_taginfo G__TMainDisplayWindowDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TMainDisplayWindowDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TMainDisplayWindowDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TMainDisplayWindowDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TMainDisplayWindowDictLN_TGWindow;
extern G__linked_taginfo G__TMainDisplayWindowDictLN_TCanvas;
extern G__linked_taginfo G__TMainDisplayWindowDictLN_TGFrame;
extern G__linked_taginfo G__TMainDisplayWindowDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TMainDisplayWindowDictLN_TGTextButton;
extern G__linked_taginfo G__TMainDisplayWindowDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__TMainDisplayWindowDictLN_TGMainFrame;
extern G__linked_taginfo G__TMainDisplayWindowDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__TMainDisplayWindowDictLN_TGTab;
extern G__linked_taginfo G__TMainDisplayWindowDictLN_TGNumberEntry;
extern G__linked_taginfo G__TMainDisplayWindowDictLN_TMainDisplayWindow;

/* STUB derived class for protected member access */
