/********************************************************************
* TRootanaDisplayDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TRootanaDisplayDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRootanaDisplayDict();
extern void G__cpp_setup_inheritanceTRootanaDisplayDict();
extern void G__cpp_setup_typetableTRootanaDisplayDict();
extern void G__cpp_setup_memvarTRootanaDisplayDict();
extern void G__cpp_setup_globalTRootanaDisplayDict();
extern void G__cpp_setup_memfuncTRootanaDisplayDict();
extern void G__cpp_setup_funcTRootanaDisplayDict();
extern void G__set_cpp_environmentTRootanaDisplayDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TRootanaDisplay.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRootanaDisplayDictLN_TClass;
extern G__linked_taginfo G__TRootanaDisplayDictLN_TBuffer;
extern G__linked_taginfo G__TRootanaDisplayDictLN_TMemberInspector;
extern G__linked_taginfo G__TRootanaDisplayDictLN_string;
extern G__linked_taginfo G__TRootanaDisplayDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRootanaDisplayDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRootanaDisplayDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRootanaDisplayDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRootanaDisplayDictLN_TDataContainer;
extern G__linked_taginfo G__TRootanaDisplayDictLN_vectorlETGenericDatamUcOallocatorlETGenericDatamUgRsPgR;
extern G__linked_taginfo G__TRootanaDisplayDictLN_reverse_iteratorlEvectorlETGenericDatamUcOallocatorlETGenericDatamUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRootanaDisplayDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TRootanaDisplayDictLN_TRootanaEventLoop;
extern G__linked_taginfo G__TRootanaDisplayDictLN_TRootanaDisplay;
extern G__linked_taginfo G__TRootanaDisplayDictLN_TCanvasHandleBase;
extern G__linked_taginfo G__TRootanaDisplayDictLN_TMainDisplayWindow;
extern G__linked_taginfo G__TRootanaDisplayDictLN_vectorlEpairlEintcOTCanvasHandleBasemUgRcOallocatorlEpairlEintcOTCanvasHandleBasemUgRsPgRsPgR;
extern G__linked_taginfo G__TRootanaDisplayDictLN_reverse_iteratorlEvectorlEpairlEintcOTCanvasHandleBasemUgRcOallocatorlEpairlEintcOTCanvasHandleBasemUgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
