/********************************************************************
* src/RoodyDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/RoodyDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableRoodyDict();
extern void G__cpp_setup_inheritanceRoodyDict();
extern void G__cpp_setup_typetableRoodyDict();
extern void G__cpp_setup_memvarRoodyDict();
extern void G__cpp_setup_globalRoodyDict();
extern void G__cpp_setup_memfuncRoodyDict();
extern void G__cpp_setup_funcRoodyDict();
extern void G__set_cpp_environmentRoodyDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/Roody.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RoodyDictLN_TClass;
extern G__linked_taginfo G__RoodyDictLN_TBuffer;
extern G__linked_taginfo G__RoodyDictLN_TMemberInspector;
extern G__linked_taginfo G__RoodyDictLN_TObject;
extern G__linked_taginfo G__RoodyDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__RoodyDictLN_string;
extern G__linked_taginfo G__RoodyDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RoodyDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RoodyDictLN_TTimer;
extern G__linked_taginfo G__RoodyDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__RoodyDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RoodyDictLN_TPeakFindPanel;
extern G__linked_taginfo G__RoodyDictLN_TGListTreeItem;
extern G__linked_taginfo G__RoodyDictLN_MTGListTree;
extern G__linked_taginfo G__RoodyDictLN_RoodyXML;
extern G__linked_taginfo G__RoodyDictLN_TGPopupMenu;
extern G__linked_taginfo G__RoodyDictLN_TGStatusBar;
extern G__linked_taginfo G__RoodyDictLN_TGTextButton;
extern G__linked_taginfo G__RoodyDictLN_TCanvas;
extern G__linked_taginfo G__RoodyDictLN_TVirtualPad;
extern G__linked_taginfo G__RoodyDictLN_mxml_struct;
extern G__linked_taginfo G__RoodyDictLN_CanvasLimits;
extern G__linked_taginfo G__RoodyDictLN_TGObject;
extern G__linked_taginfo G__RoodyDictLN_TQObject;
extern G__linked_taginfo G__RoodyDictLN_TGWindow;
extern G__linked_taginfo G__RoodyDictLN_TGFrame;
extern G__linked_taginfo G__RoodyDictLN_TGCompositeFrame;
extern G__linked_taginfo G__RoodyDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__RoodyDictLN_TGMainFrame;
extern G__linked_taginfo G__RoodyDictLN_ObjectPath;
extern G__linked_taginfo G__RoodyDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__RoodyDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RoodyDictLN_vectorlEObjectPathcOallocatorlEObjectPathgRsPgR;
extern G__linked_taginfo G__RoodyDictLN_reverse_iteratorlEvectorlEObjectPathcOallocatorlEObjectPathgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RoodyDictLN_DataSourceBase;
extern G__linked_taginfo G__RoodyDictLN_PadObjectVec;
extern G__linked_taginfo G__RoodyDictLN_vectorlEPadObjectcOallocatorlEPadObjectgRsPgR;
extern G__linked_taginfo G__RoodyDictLN_reverse_iteratorlEvectorlEPadObjectcOallocatorlEPadObjectgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RoodyDictLN_Roody;
extern G__linked_taginfo G__RoodyDictLN_RoodycLcLECommandMenuEntry;
extern G__linked_taginfo G__RoodyDictLN_RoodycLcLEDrawDestination;
extern G__linked_taginfo G__RoodyDictLN_vectorlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgR;
extern G__linked_taginfo G__RoodyDictLN_reverse_iteratorlEvectorlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RoodyDictLN_maplETVirtualPadmUcOintcOlesslETVirtualPadmUgRcOallocatorlEpairlETVirtualPadmUsPconstcOintgRsPgRsPgR;
extern G__linked_taginfo G__RoodyDictLN_maplEintcOCanvasLimitsmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOCanvasLimitsmUgRsPgRsPgR;

/* STUB derived class for protected member access */
