/********************************************************************
* src/TAxisLimitsDialogDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/TAxisLimitsDialogDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTAxisLimitsDialogDict();
extern void G__cpp_setup_inheritanceTAxisLimitsDialogDict();
extern void G__cpp_setup_typetableTAxisLimitsDialogDict();
extern void G__cpp_setup_memvarTAxisLimitsDialogDict();
extern void G__cpp_setup_globalTAxisLimitsDialogDict();
extern void G__cpp_setup_memfuncTAxisLimitsDialogDict();
extern void G__cpp_setup_funcTAxisLimitsDialogDict();
extern void G__set_cpp_environmentTAxisLimitsDialogDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/TAxisLimitsDialog.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TAxisLimitsDialogDictLN_TClass;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_TBuffer;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_TMemberInspector;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_TObject;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_TGObject;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_TQObject;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_TGWindow;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_TGFrame;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_TGCompositeFrame;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_TGLayoutHints;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_TGMainFrame;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_TGButton;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_TGCheckButton;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_TGTextEntry;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_CanvasLimits;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_vectorlEObjectPathcOallocatorlEObjectPathgRsPgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_reverse_iteratorlEvectorlEObjectPathcOallocatorlEObjectPathgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_vectorlEPadObjectcOallocatorlEPadObjectgRsPgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_reverse_iteratorlEvectorlEPadObjectcOallocatorlEPadObjectgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_Roody;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_vectorlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_reverse_iteratorlEvectorlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_maplETVirtualPadmUcOintcOlesslETVirtualPadmUgRcOallocatorlEpairlETVirtualPadmUsPconstcOintgRsPgRsPgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_maplEintcOCanvasLimitsmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOCanvasLimitsmUgRsPgRsPgR;
extern G__linked_taginfo G__TAxisLimitsDialogDictLN_TAxisLimitsDialog;

/* STUB derived class for protected member access */
