/********************************************************************
* src/TGTextDialogDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/TGTextDialogDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGTextDialogDict();
extern void G__cpp_setup_inheritanceTGTextDialogDict();
extern void G__cpp_setup_typetableTGTextDialogDict();
extern void G__cpp_setup_memvarTGTextDialogDict();
extern void G__cpp_setup_globalTGTextDialogDict();
extern void G__cpp_setup_memfuncTGTextDialogDict();
extern void G__cpp_setup_funcTGTextDialogDict();
extern void G__set_cpp_environmentTGTextDialogDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/TGTextDialog.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGTextDialogDictLN_TClass;
extern G__linked_taginfo G__TGTextDialogDictLN_TBuffer;
extern G__linked_taginfo G__TGTextDialogDictLN_TMemberInspector;
extern G__linked_taginfo G__TGTextDialogDictLN_TObject;
extern G__linked_taginfo G__TGTextDialogDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TGTextDialogDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGTextDialogDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGTextDialogDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGTextDialogDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGTextDialogDictLN_TGObject;
extern G__linked_taginfo G__TGTextDialogDictLN_TQObject;
extern G__linked_taginfo G__TGTextDialogDictLN_TGWindow;
extern G__linked_taginfo G__TGTextDialogDictLN_TObjString;
extern G__linked_taginfo G__TGTextDialogDictLN_TGFrame;
extern G__linked_taginfo G__TGTextDialogDictLN_TGCompositeFrame;
extern G__linked_taginfo G__TGTextDialogDictLN_TGLayoutHints;
extern G__linked_taginfo G__TGTextDialogDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TGTextDialogDictLN_TGMainFrame;
extern G__linked_taginfo G__TGTextDialogDictLN_TGTransientFrame;
extern G__linked_taginfo G__TGTextDialogDictLN_TGButton;
extern G__linked_taginfo G__TGTextDialogDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGTextDialogDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGTextDialogDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGTextDialogDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGTextDialogDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TGTextDialogDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGTextDialogDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__TGTextDialogDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGTextDialogDictLN_TGLabel;
extern G__linked_taginfo G__TGTextDialogDictLN_TGTextBuffer;
extern G__linked_taginfo G__TGTextDialogDictLN_TGTextEntry;
extern G__linked_taginfo G__TGTextDialogDictLN_TGTextDialog;

/* STUB derived class for protected member access */
