/********************************************************************
* src/TPeakFindPanelDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/TPeakFindPanelDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTPeakFindPanelDict();
extern void G__cpp_setup_inheritanceTPeakFindPanelDict();
extern void G__cpp_setup_typetableTPeakFindPanelDict();
extern void G__cpp_setup_memvarTPeakFindPanelDict();
extern void G__cpp_setup_globalTPeakFindPanelDict();
extern void G__cpp_setup_memfuncTPeakFindPanelDict();
extern void G__cpp_setup_funcTPeakFindPanelDict();
extern void G__set_cpp_environmentTPeakFindPanelDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/TPeakFindPanel.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TPeakFindPanelDictLN_TClass;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TBuffer;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TMemberInspector;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TObject;
extern G__linked_taginfo G__TPeakFindPanelDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TPeakFindPanelDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPeakFindPanelDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TPeakFindPanelDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TGObject;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TQObject;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TGWindow;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TGFrame;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TGCompositeFrame;
extern G__linked_taginfo G__TPeakFindPanelDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TGTextButton;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TGVerticalFrame;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TGMainFrame;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TGTransientFrame;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TGCheckButton;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TGNumberEntry;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TF1;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TH1;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TSpectrum;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TPeakFindPanel;
extern G__linked_taginfo G__TPeakFindPanelDictLN_TPeakFindPanelcLcLECommandIdentifiers;

/* STUB derived class for protected member access */
