.TH "/home/nam/sw/daq/midas/drivers/ Directory Reference" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nam/sw/daq/midas/drivers/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcamac\fP"
.br
.ti -1c
.RI "directory \fBclass\fP"
.br
.ti -1c
.RI "directory \fBvme\fP"
.br
.in -1c
