.TH "ADC_CALIBRATION_PARAM" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_CALIBRATION_PARAM \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 40 of file experim.h.
.SH "Field Documentation"
.PP 
.SS "double \fBADC_CALIBRATION_PARAM::histo_threshold\fP"
.PP
Definition at line 43 of file experim.h.
.SS "\fBINT\fP \fBADC_CALIBRATION_PARAM::pedestal\fP[8]"
.PP
Definition at line 41 of file experim.h.
.SS "float \fBADC_CALIBRATION_PARAM::software_gain\fP[8]"
.PP
Definition at line 42 of file experim.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
