.TH "ADC_SUMMING_PARAM" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_SUMMING_PARAM \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 76 of file experim.h.
.SH "Field Documentation"
.PP 
.SS "float \fBADC_SUMMING_PARAM::adc_threshold\fP"
.PP
Definition at line 77 of file experim.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
