.TH "alarm.c" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
alarm.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBINT\fP \fBal_trigger_alarm\fP (const char *alarm_name, const char *alarm_message, const char *default_class, const char *cond_str, \fBINT\fP type)"
.br
.ti -1c
.RI "\fBINT\fP \fBal_reset_alarm\fP (const char *alarm_name)"
.br
.ti -1c
.RI "\fBINT\fP \fBal_check\fP ()"
.br
.ti -1c
.RI "\fBINT\fP \fBal_get_alarms\fP (char *result, int result_size)"
.br
.in -1c
.SH "Detailed Description"
.PP 
dox The Midas Alarm file 
.PP
Definition in file \fBalarm.c\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
