.TH "ANA_OUTPUT_INFO" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ANA_OUTPUT_INFO \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 1146 of file midas.h.
.SH "Field Documentation"
.PP 
.SS "\fBBOOL\fP \fBANA_OUTPUT_INFO::clear_histos\fP"
.PP
Definition at line 1151 of file midas.h.
.SS "\fBBOOL\fP \fBANA_OUTPUT_INFO::events_to_odb\fP"
.PP
Definition at line 1153 of file midas.h.
.SS "char \fBANA_OUTPUT_INFO::filename\fP[256]"
.PP
Definition at line 1147 of file midas.h.
.SS "char \fBANA_OUTPUT_INFO::global_memory_name\fP[8]"
.PP
Definition at line 1154 of file midas.h.
.SS "\fBBOOL\fP \fBANA_OUTPUT_INFO::histo_dump\fP"
.PP
Definition at line 1149 of file midas.h.
.SS "char \fBANA_OUTPUT_INFO::histo_dump_filename\fP[256]"
.PP
Definition at line 1150 of file midas.h.
.SS "char \fBANA_OUTPUT_INFO::last_histo_filename\fP[256]"
.PP
Definition at line 1152 of file midas.h.
.SS "\fBBOOL\fP \fBANA_OUTPUT_INFO::rwnt\fP"
.PP
Definition at line 1148 of file midas.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
