.TH "ANA_TEST" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ANA_TEST \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 1170 of file midas.h.
.SH "Field Documentation"
.PP 
.SS "\fBDWORD\fP \fBANA_TEST::count\fP"
.PP
Definition at line 1173 of file midas.h.
.SS "char \fBANA_TEST::name\fP[80]"
.PP
Definition at line 1171 of file midas.h.
.SS "\fBDWORD\fP \fBANA_TEST::previous_count\fP"
.PP
Definition at line 1174 of file midas.h.
.SS "\fBBOOL\fP \fBANA_TEST::registered\fP"
.PP
Definition at line 1172 of file midas.h.
.SS "\fBBOOL\fP \fBANA_TEST::value\fP"
.PP
Definition at line 1175 of file midas.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
