.TH "AR_STATS" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AR_STATS \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 1113 of file midas.h.
.SH "Field Documentation"
.PP 
.SS "double \fBAR_STATS::events_per_sec\fP"
.PP
Definition at line 1115 of file midas.h.
.SS "double \fBAR_STATS::events_received\fP"
.PP
Definition at line 1114 of file midas.h.
.SS "double \fBAR_STATS::events_written\fP"
.PP
Definition at line 1116 of file midas.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
