.TH "ASUM_BANK" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ASUM_BANK \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 108 of file experim.h.
.SH "Field Documentation"
.PP 
.SS "float \fBASUM_BANK::average\fP"
.PP
Definition at line 110 of file experim.h.
.PP
Referenced by adc_summing().
.SS "float \fBASUM_BANK::sum\fP"
.PP
Definition at line 109 of file experim.h.
.PP
Referenced by adc_summing().

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
