.TH "BANK" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BANK \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [4]"
.br
.ti -1c
.RI "\fBWORD\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBWORD\fP \fBdata_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1051 of file midas.h.
.SH "Field Documentation"
.PP 
.SS "\fBWORD\fP \fBBANK::data_size\fP".IP "\(bu" 2

.PP

.PP
Definition at line 1054 of file midas.h.
.PP
Referenced by bk_close(), bk_create(), bk_find(), bk_iterate(), bk_locate(), bk_swap(), and midas_bank_display().
.SS "char \fBBANK::name\fP[4]".IP "\(bu" 2

.PP

.PP
Definition at line 1052 of file midas.h.
.PP
Referenced by bk_close(), bk_create(), bk_find(), bk_list(), bk_locate(), midas_bank_display(), and update_odb().
.SS "\fBWORD\fP \fBBANK::type\fP".IP "\(bu" 2

.PP

.PP
Definition at line 1053 of file midas.h.
.PP
Referenced by bk_close(), bk_create(), bk_find(), bk_locate(), bk_swap(), midas_bank_display(), and update_odb().

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
