.TH "BANK_LIST" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BANK_LIST \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [9]"
.br
.ti -1c
.RI "\fBWORD\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBsize\fP"
.br
.ti -1c
.RI "char ** \fBinit_str\fP"
.br
.ti -1c
.RI "\fBBOOL\fP \fBoutput_flag\fP"
.br
.ti -1c
.RI "void * \fBaddr\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBn_data\fP"
.br
.ti -1c
.RI "HNDLE \fBdef_key\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1069 of file midas.h.
.SH "Field Documentation"
.PP 
.SS "void* \fBBANK_LIST::addr\fP".IP "\(bu" 2

.PP

.PP
Definition at line 1075 of file midas.h.
.SS "HNDLE \fBBANK_LIST::def_key\fP".IP "\(bu" 2

.PP

.PP
Definition at line 1077 of file midas.h.
.SS "char** \fBBANK_LIST::init_str\fP".IP "\(bu" 2

.PP

.PP
Definition at line 1073 of file midas.h.
.PP
Referenced by register_equipment().
.SS "\fBDWORD\fP \fBBANK_LIST::n_data\fP".IP "\(bu" 2

.PP

.PP
Definition at line 1076 of file midas.h.
.SS "char \fBBANK_LIST::name\fP[9]".IP "\(bu" 2

.PP

.PP
Definition at line 1070 of file midas.h.
.PP
Referenced by register_equipment().
.SS "\fBBOOL\fP \fBBANK_LIST::output_flag\fP".IP "\(bu" 2

.PP

.PP
Definition at line 1074 of file midas.h.
.SS "\fBDWORD\fP \fBBANK_LIST::size\fP".IP "\(bu" 2

.PP

.PP
Definition at line 1072 of file midas.h.
.SS "\fBWORD\fP \fBBANK_LIST::type\fP".IP "\(bu" 2

.PP

.PP
Definition at line 1071 of file midas.h.
.PP
Referenced by register_equipment().

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
