.TH "cnaf_callback.c" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cnaf_callback.c \- 
.SH SYNOPSIS
.br
.PP
.SH "Function Documentation"
.PP 
.SS "\fBINT\fP cnaf_callback (\fBINT\fP index, void * prpc_param[])"
.PP
Definition at line 24 of file cnaf_callback.c.
.PP
Referenced by register_cnaf_callback().
.SS "void register_cnaf_callback (int debug)"
.PP
Definition at line 124 of file cnaf_callback.c.
.PP
Referenced by frontend_init().
.SH "Variable Documentation"
.PP 
.SS "int \fBcnaf_debug\fP = 0\fC [static]\fP"
.PP
Definition at line 22 of file cnaf_callback.c.
.PP
Referenced by cnaf_callback(), and register_cnaf_callback().
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
