.TH "Convention" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Convention \- SECTION 13: Document Navigation and Convention 

.br
  
.br
.IP "\(bu" 2
\fBNavigating this document\fP
.IP "\(bu" 2
\fBDocument Style\fP
.PP
.SH "Navigating this document"
.PP
.IP "\(bu" 2
Use the \fB'Search'\fP box at top right of each page
.IP "\(bu" 2
This document is divided into \fBsections\fP containing one or more \fBpages\fP.
.IP "\(bu" 2
Each page has \fBnavigation\fP \fBicons\fP at the top and bottom to enable navigation between pages and sections.
.IP "  \(bu" 4
\fBblue\fP symbols navigate between \fBpages\fP,
.IP "  \(bu" 4
\fByellow\fP symbols navigate between \fBsections\fP.
.PP

.IP "\(bu" 2
There are also navigation icons to jump to the \fBAlphabetical Documentation Index\fP and the \fBSection Contents\fP.
.PP
.PP

.br
 Navigation  
.PP
PAGE  SECTION  
.PP
.PP
  page down - go to bottom of this page     page up - go to top of this page    go to start of this document     page left - go to bottom of previous page     page right - go to top of next page     page contents - go to list of pages in THIS section     Alphabetical Index to Documentation pages   
.PP
.PP
  section up - go to start of THIS section     section left - go to start of PREVIOUS section     section right - go to start of NEXT section     go to list of sections in this document   
.PP
Placing mouse over navigation symbols will display a description of the tag's destination.
.PP
.PP

.br
.PP

.br
.PP
.SH "Document Style"
.PP
.IP "\(bu" 2
New Features :
.IP "  \(bu" 4
 This feature is new since \fBthis date\fP 
.PP

.IP "\(bu" 2
ODB paths should appears like this :
.IP "  \(bu" 4
 /Equipment/test 
.br

.PP

.IP "\(bu" 2
Midas Utilities :
.IP "  \(bu" 4
midas_utility
.br

.PP

.IP "\(bu" 2
JavaScript functions :
.IP "  \(bu" 4
ODBGet
.br

.PP

.IP "\(bu" 2
HTML tags :
.IP "  \(bu" 4
<img ...> 
.br

.PP

.IP "\(bu" 2
ODB tags (in HTML files) :
.IP "  \(bu" 4
<odb...> 
.br

.PP

.IP "\(bu" 2
Image titles should appear like this :
.IP "  \(bu" 4
 Figure 1 Example 
.br

.PP

.IP "\(bu" 2
Warnings :
.IP "  \(bu" 4
This is a Warning 
.br

.PP

.IP "\(bu" 2
Notes :
.IP "  \(bu" 4
This is important 
.br

.PP

.IP "\(bu" 2
or  so is this
.PP
.PP

.br

.br

.br
.PP
 
.PP

.br
 
