.TH "DEF_RECORD" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DEF_RECORD \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 1206 of file midas.h.
.SH "Field Documentation"
.PP 
.SS "\fBDWORD\fP \fBDEF_RECORD::def_offset\fP"
.PP
Definition at line 1209 of file midas.h.
.SS "\fBDWORD\fP \fBDEF_RECORD::event_id\fP"
.PP
Definition at line 1207 of file midas.h.
.SS "char \fBDEF_RECORD::event_name\fP[NAME_LENGTH]"
.PP
Definition at line 1208 of file midas.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
