.TH "elog.c" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
elog.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBINT\fP \fBel_submit\fP (int run, const char *author, const char *type, const char *syst, const char *subject, const char *text, const char *reply_to, const char *encoding, const char *afilename1, char *buffer1, \fBINT\fP buffer_size1, const char *afilename2, char *buffer2, \fBINT\fP buffer_size2, const char *afilename3, char *buffer3, \fBINT\fP buffer_size3, char *tag, \fBINT\fP tag_size)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
