.TH "EXP_PARAM" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EXP_PARAM \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 26 of file experim.h.
.SH "Field Documentation"
.PP 
.SS "char \fBEXP_PARAM::comment\fP[80]"
.PP
Definition at line 27 of file experim.h.
.PP
Referenced by ana_end_of_run().

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
