.TH "FE_Appendices" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FE_Appendices \- Frontend Appendices 

.br
.PP
 
.br
 
.br
.PP

.br
.PP
.IP "\(bu" 2
\fBData formats written by the frontend\fP
.IP "\(bu" 2
\fBSupported Hardware: MIDAS driver library\fP
.IP "\(bu" 2
\fBCAMAC and VME access function calls\fP
.IP "\(bu" 2
\fBHardware Access utilities\fP  
.PP

