.TH "Features" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Features \- SECTION 4: Features 
.PP

.br
.SH "General Acquisition Principles"
.PP
The MIDAS DAQ system is based on a modular scheme that allows scalability and flexibility. The operation of each component is handled by a subset of functions, but all the components are grouped in a single library (libmidas.a, libmidas.so (UNIX), midas.dll (NT)).
.PP
The overall C-code is over 80,000 lines long and makes up more than 450 functions However, from the user's point of view, only a subset of these routines are needed for most operations.
.PP
Each MIDAS component is briefly described below but links will be provided to more detailed information in the documentation. All these software components are available from the standard package. Basic components such as the \fBThe Buffer Manager\fP, \fBOnline Database (ODB)\fP, \fBMessage System\fP, \fBRun Control\fP are operational by default. Other features need to be enabled by the user, either by starting an application or by activation of the component through the \fBOnline Database (ODB)\fP. 
.br
 
.br
.PP
.IP "\(bu" 2
\fBOverview of the Main Elements of the MIDAS DAQ System\fP
.IP "\(bu" 2
\fBODB Structure\fP
.IP "\(bu" 2
\fBList of MIDAS Utilities\fP
.IP "\(bu" 2
\fBMIDAS Code and Libraries\fP
.IP "\(bu" 2
\fBLogging in MIDAS\fP 
.br

.PP
.PP

.br
  
