.TH "FREE_DESCRIP" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FREE_DESCRIP \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBINT\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBINT\fP \fBnext_free\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 345 of file msystem.h.
.SH "Field Documentation"
.PP 
.SS "\fBINT\fP \fBFREE_DESCRIP::next_free\fP"Address of next free block 
.PP
Definition at line 347 of file msystem.h.
.PP
Referenced by db_open_database().
.SS "\fBINT\fP \fBFREE_DESCRIP::size\fP"size in bytes 
.PP
Definition at line 346 of file msystem.h.
.PP
Referenced by db_open_database().

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
