.TH "GLOBAL_PARAM" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLOBAL_PARAM \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 92 of file experim.h.
.SH "Field Documentation"
.PP 
.SS "float \fBGLOBAL_PARAM::adc_threshold\fP"
.PP
Definition at line 93 of file experim.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
