.TH "Glossary" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Glossary \- Glossary 

.br
  
.br
.PP
 WARNING - this page is under construction 
.PP
.PD 0
.IP "\(bu" 2
\fBbackend\fP 
.IP "\(bu" 2
\fBdriver\fP 
.IP "\(bu" 2
\fBequipment\fP 
.PD 0

.IP "  \(bu" 4
\fBhardware\fP 
.IP "  \(bu" 4
\fBsoftware\fP 
.PP

.IP "\(bu" 2
\fBEvent_definition\fP 
.PD 0

.IP "  \(bu" 4
\fBtrigger\fP 
.PP

.IP "\(bu" 2
\fBfrontend\fP
.PP

.PP
.PP
 
.br
  
.br
 
