.TH "history.c" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
history.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBINT\fP \fBhs_set_path\fP (char *path)"
.br
.ti -1c
.RI "\fBINT\fP \fBhs_dump\fP (\fBDWORD\fP event_id, \fBDWORD\fP start_time, \fBDWORD\fP end_time, \fBDWORD\fP interval, \fBBOOL\fP binary_time)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
