.TH "I_Midas_system_picture" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I_Midas_system_picture \- Diagram of the MIDAS system 

.br
 
.PP

.br
.PP
 A general picture of the MIDAS system is displayed below. The \fBmain elements\fP of the system will be described in \fBSECTION 4: Features\fP .
.PP
  
.PP
For information on the MIDAS features shown here, see the \fBoverview\fP . 
.PP

.br
  
.br
 
