.TH "isegvhs.h" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isegvhs.h \- 
.SH SYNOPSIS
.br
.PP
.SH "Define Documentation"
.PP 
.SS "#define ISEGVHS_CHANNEL_BASE   0x0060"
.PP
Definition at line 23 of file isegvhs.h.
.SS "#define ISEGVHS_CHANNEL_CONTROL   0x0002"
.PP
Definition at line 26 of file isegvhs.h.
.SS "#define ISEGVHS_CHANNEL_OFFSET   0x0030"
.PP
Definition at line 24 of file isegvhs.h.
.SS "#define ISEGVHS_CHANNEL_STATUS   0x0000"
.PP
Definition at line 25 of file isegvhs.h.
.SS "#define ISEGVHS_CURRENT_BOUND   0x001C"
.PP
Definition at line 32 of file isegvhs.h.
.SS "#define ISEGVHS_CURRENT_MAX   0x0020"
.PP
Definition at line 14 of file isegvhs.h.
.PP
Referenced by isegvhs_Status().
.SS "#define ISEGVHS_CURRENT_MAX_SET   0x002C"
.PP
Definition at line 36 of file isegvhs.h.
.SS "#define ISEGVHS_CURRENT_MEASURE   0x0014"
.PP
Definition at line 30 of file isegvhs.h.
.SS "#define ISEGVHS_CURRENT_NOMINAL   0x0024"
.PP
Definition at line 34 of file isegvhs.h.
.SS "#define ISEGVHS_CURRENT_RAMP_SPEED   0x0018"
.PP
Definition at line 12 of file isegvhs.h.
.SS "#define ISEGVHS_CURRENT_SET   0x000C"
.PP
Definition at line 28 of file isegvhs.h.
.SS "#define ISEGVHS_MAX_CHANNELS   12"
.PP
Definition at line 42 of file isegvhs.h.
.SS "#define ISEGVHS_MODULE_CONTROL   0x0002"
.PP
Definition at line 10 of file isegvhs.h.
.PP
Referenced by isegvhs_Status().
.SS "#define ISEGVHS_MODULE_STATUS   0x0000"
.PP
Definition at line 9 of file isegvhs.h.
.PP
Referenced by isegvhs_Status().
.SS "#define ISEGVHS_SERIAL_NUMBER   0x0034"
.PP
Definition at line 19 of file isegvhs.h.
.PP
Referenced by isegvhs_Status().
.SS "#define ISEGVHS_SET_EMCY   0x0020"
.PP
Definition at line 40 of file isegvhs.h.
.SS "#define ISEGVHS_SET_OFF   0x0000"
.PP
Definition at line 39 of file isegvhs.h.
.SS "#define ISEGVHS_SET_ON   0x0008"
.PP
Definition at line 38 of file isegvhs.h.
.SS "#define ISEGVHS_SUPPLY_N12   0x002C"
.PP
Definition at line 17 of file isegvhs.h.
.PP
Referenced by isegvhs_Status().
.SS "#define ISEGVHS_SUPPLY_P12   0x0028"
.PP
Definition at line 16 of file isegvhs.h.
.PP
Referenced by isegvhs_Status().
.SS "#define ISEGVHS_SUPPLY_P5   0x0024"
.PP
Definition at line 15 of file isegvhs.h.
.PP
Referenced by isegvhs_Status().
.SS "#define ISEGVHS_TEMPERATURE   0x0030"
.PP
Definition at line 18 of file isegvhs.h.
.PP
Referenced by isegvhs_Status().
.SS "#define ISEGVHS_VENDOR_ID   0x005C"
.PP
Definition at line 21 of file isegvhs.h.
.PP
Referenced by isegvhs_Status().
.SS "#define ISEGVHS_VOLTAGE_BOUND   0x0018"
.PP
Definition at line 31 of file isegvhs.h.
.SS "#define ISEGVHS_VOLTAGE_MAX   0x001C"
.PP
Definition at line 13 of file isegvhs.h.
.PP
Referenced by isegvhs_Status().
.SS "#define ISEGVHS_VOLTAGE_MAX_SET   0x0028"
.PP
Definition at line 35 of file isegvhs.h.
.SS "#define ISEGVHS_VOLTAGE_MEASURE   0x0010"
.PP
Definition at line 29 of file isegvhs.h.
.SS "#define ISEGVHS_VOLTAGE_NOMINAL   0x0020"
.PP
Definition at line 33 of file isegvhs.h.
.SS "#define ISEGVHS_VOLTAGE_RAMP_SPEED   0x0014"
.PP
Definition at line 11 of file isegvhs.h.
.SS "#define ISEGVHS_VOLTAGE_SET   0x0008"
.PP
Definition at line 27 of file isegvhs.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
