.TH "lrs1151.h" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lrs1151.h \- 
.SH SYNOPSIS
.br
.PP
.SH "Define Documentation"
.PP 
.SS "#define LRS1151_CLEAR_WO   (\fBDWORD\fP) (0x0040)"
.PP
Definition at line 20 of file lrs1151.h.
.PP
Referenced by lrs1151_Clear().
.SS "#define LRS1151_DATA_RO   (\fBDWORD\fP) (0x0080)"
.PP
Definition at line 21 of file lrs1151.h.
.PP
Referenced by lrs1151_Read().
.SH "Function Documentation"
.PP 
.SS "void lrs1151_Clear (\fBMVME_INTERFACE\fP * mvme, \fBDWORD\fP base)"
.PP
Definition at line 31 of file lrs1151.c.
.SS "void lrs1151_Read (\fBMVME_INTERFACE\fP * mvme, \fBDWORD\fP base, \fBDWORD\fP * data)"
.PP
Definition at line 16 of file lrs1151.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
