.TH "lrs1190.c" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lrs1190.c \- 
.SH SYNOPSIS
.br
.PP
.SH "Function Documentation"
.PP 
.SS "int lrs1190_CountRead (\fBMVME_INTERFACE\fP * mvme, \fBDWORD\fP base)"
.PP
Definition at line 67 of file lrs1190.c.
.SS "void lrs1190_Disable (\fBMVME_INTERFACE\fP * mvme, \fBDWORD\fP base)"
.PP
Definition at line 51 of file lrs1190.c.
.SS "void lrs1190_Enable (\fBMVME_INTERFACE\fP * mvme, \fBDWORD\fP base)"
.PP
Definition at line 35 of file lrs1190.c.
.SS "int lrs1190_H2Read (\fBMVME_INTERFACE\fP * mvme, \fBDWORD\fP base, \fBWORD\fP * data, int r)"
.PP
Definition at line 137 of file lrs1190.c.
.SS "int lrs1190_I4Read (\fBMVME_INTERFACE\fP * mvme, \fBDWORD\fP base, \fBDWORD\fP * data, int r)"
.PP
Definition at line 83 of file lrs1190.c.
.SS "int lrs1190_L2Read (\fBMVME_INTERFACE\fP * mvme, \fBDWORD\fP base, \fBWORD\fP * data, int r)"
.PP
Definition at line 113 of file lrs1190.c.
.SS "void lrs1190_Reset (\fBMVME_INTERFACE\fP * mvme, \fBDWORD\fP base)"
.PP
Definition at line 19 of file lrs1190.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
