.TH "lrs1151.c" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lrs1151.c \- 
.SH SYNOPSIS
.br
.PP
.SH "Function Documentation"
.PP 
.SS "void lrs1151_Clear (\fBMVME_INTERFACE\fP * mvme, \fBDWORD\fP base)"
.PP
Definition at line 31 of file lrs1151.c.
.SS "void lrs1151_Read (\fBMVME_INTERFACE\fP * mvme, \fBDWORD\fP base, \fBDWORD\fP * data)"
.PP
Definition at line 16 of file lrs1151.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
