.TH "Bank related" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bank related \- 
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBBANK_HEADER\fP"
.br
.ti -1c
.RI "struct \fBBANK\fP"
.br
.ti -1c
.RI "struct \fBBANK32\fP"
.br
.ti -1c
.RI "struct \fBTAG\fP"
.br
.ti -1c
.RI "struct \fBBANK_LIST\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBBANK_FORMAT_VERSION\fP   1"
.br
.ti -1c
.RI "#define \fBBANK_FORMAT_32BIT\fP   (1<<4)"
.br
.in -1c
.SH "Detailed Description"
.PP 
dox dox 
.SH "Define Documentation"
.PP 
.SS "#define BANK_FORMAT_32BIT   (1<<4)".IP "\(bu" 2

.PP

.PP
Definition at line 1044 of file midas.h.
.PP
Referenced by bk_create(), and bk_init32().
.SS "#define BANK_FORMAT_VERSION   1".IP "\(bu" 2

.PP

.PP
Definition at line 1043 of file midas.h.
.PP
Referenced by bk_init(), and bk_init32().
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
