.TH "Midas Error definition" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Midas Error definition \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBStatus and error codes\fP"
.br
.ti -1c
.RI "\fBBuffer Manager error codes\fP"
.br
.ti -1c
.RI "\fBOnline Database error codes\fP"
.br
.ti -1c
.RI "\fBSystem Services error code\fP"
.br
.ti -1c
.RI "\fBRemote Procedure Calls error codes\fP"
.br
.ti -1c
.RI "\fBOther errors\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
dox dox 
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
