.TH "mdsupport.h" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mdsupport.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMD_SUCCESS\fP   1"
.br
.ti -1c
.RI "#define \fBMD_EVENT_NOT_SWAPPED\fP   2"
.br
.ti -1c
.RI "#define \fBMD_DONE\fP   2"
.br
.ti -1c
.RI "#define \fBMD_WRONG_BANK_TYPE\fP   -100"
.br
.ti -1c
.RI "#define \fBMD_BANK_NOT_FOUND\fP   -101"
.br
.ti -1c
.RI "#define \fBMD_SWAP_ERROR\fP   -102"
.br
.ti -1c
.RI "#define \fBMD_NOMORE_SLOT\fP   -103"
.br
.ti -1c
.RI "#define \fBMD_UNKNOWN_FORMAT\fP   -104"
.br
.ti -1c
.RI "#define \fBD_RECORD\fP   1"
.br
.ti -1c
.RI "#define \fBD_HEADER\fP   2"
.br
.ti -1c
.RI "#define \fBD_EVTLEN\fP   3"
.br
.ti -1c
.RI "#define \fBDSP_RAW\fP   1"
.br
.ti -1c
.RI "#define \fBDSP_RAW_SINGLE\fP   2"
.br
.ti -1c
.RI "#define \fBDSP_BANK\fP   3"
.br
.ti -1c
.RI "#define \fBDSP_BANK_SINGLE\fP   4"
.br
.ti -1c
.RI "#define \fBDSP_UNK\fP   0"
.br
.ti -1c
.RI "#define \fBDSP_DEC\fP   1"
.br
.ti -1c
.RI "#define \fBDSP_HEX\fP   2"
.br
.ti -1c
.RI "#define \fBDSP_ASC\fP   3"
.br
.ti -1c
.RI "#define \fBMD_BANKLIST_MAX\fP   32"
.br
.ti -1c
.RI "#define \fBMD_STRING_BANKLIST_MAX\fP   MD_BANKLIST_MAX * 4"
.br
.in -1c
.SH "Detailed Description"
.PP 
dox The mdsupport include file 
.PP
Definition in file \fBmdsupport.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
