.TH "Midas dump support Define" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Midas dump support Define \- 
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBD_RECORD\fP   1"
.br
.ti -1c
.RI "#define \fBD_HEADER\fP   2"
.br
.ti -1c
.RI "#define \fBD_EVTLEN\fP   3"
.br
.ti -1c
.RI "#define \fBDSP_RAW\fP   1"
.br
.ti -1c
.RI "#define \fBDSP_RAW_SINGLE\fP   2"
.br
.ti -1c
.RI "#define \fBDSP_BANK\fP   3"
.br
.ti -1c
.RI "#define \fBDSP_BANK_SINGLE\fP   4"
.br
.ti -1c
.RI "#define \fBDSP_UNK\fP   0"
.br
.ti -1c
.RI "#define \fBDSP_DEC\fP   1"
.br
.ti -1c
.RI "#define \fBDSP_HEX\fP   2"
.br
.ti -1c
.RI "#define \fBDSP_ASC\fP   3"
.br
.ti -1c
.RI "#define \fBMD_BANKLIST_MAX\fP   32"
.br
.ti -1c
.RI "#define \fBMD_STRING_BANKLIST_MAX\fP   MD_BANKLIST_MAX * 4"
.br
.in -1c
.SH "Detailed Description"
.PP 
dox dox 
.SH "Define Documentation"
.PP 
.SS "#define D_EVTLEN   3"
.PP
Definition at line 80 of file mdsupport.h.
.PP
Referenced by md_all_info_display().
.SS "#define D_HEADER   2"
.PP
Definition at line 79 of file mdsupport.h.
.PP
Referenced by md_all_info_display().
.SS "#define D_RECORD   1"Display \fBparameters\fP 
.PP
Definition at line 78 of file mdsupport.h.
.PP
Referenced by md_all_info_display().
.SS "#define DSP_ASC   3"Display data in ASCII format 
.PP
Definition at line 94 of file mdsupport.h.
.PP
Referenced by md_raw_bank_display(), midas_bank_display(), and midas_bank_display32().
.SS "#define DSP_BANK   3"Display data in bank format 
.PP
Definition at line 86 of file mdsupport.h.
.PP
Referenced by md_event_display().
.SS "#define DSP_BANK_SINGLE   4"Display only requested data in bank format 
.PP
Definition at line 87 of file mdsupport.h.
.PP
Referenced by md_bank_event_display(), and md_event_display().
.SS "#define DSP_DEC   1"Display data in decimal format 
.PP
Definition at line 92 of file mdsupport.h.
.PP
Referenced by md_raw_bank_display(), md_raw_event_display(), midas_bank_display(), and midas_bank_display32().
.SS "#define DSP_HEX   2"Display data in headecimal format 
.PP
Definition at line 93 of file mdsupport.h.
.PP
Referenced by md_raw_bank_display(), midas_bank_display(), and midas_bank_display32().
.SS "#define DSP_RAW   1"Display mode options Display raw data 
.PP
Definition at line 84 of file mdsupport.h.
.PP
Referenced by md_bank_display(), and md_event_display().
.SS "#define DSP_RAW_SINGLE   2"Display raw data (no single mode) 
.PP
Definition at line 85 of file mdsupport.h.
.SS "#define DSP_UNK   0"Display format Display format unknown 
.PP
Definition at line 91 of file mdsupport.h.
.PP
Referenced by midas_bank_display(), and midas_bank_display32().
.SS "#define MD_BANKLIST_MAX   32"maximum number of banks to be found by the \fBbk_list()\fP 
.PP
Definition at line 98 of file mdsupport.h.
.SS "#define MD_STRING_BANKLIST_MAX   MD_BANKLIST_MAX * 4"to be used for \fBbk_list()\fP 
.PP
Definition at line 100 of file mdsupport.h.
.PP
Referenced by md_bank_event_display().
.SS "#define NLINE   8"
.PP
Definition at line 96 of file mdsupport.h.
.PP
Referenced by md_raw_bank_display(), and md_raw_event_display().
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
