.TH "mdsupport.c" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mdsupport.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBINT\fP \fBmd_file_ropen\fP (char *infile, \fBINT\fP data_fmt, \fBINT\fP openzip)"
.br
.in -1c
.SH "Detailed Description"
.PP 
dox The Midas Dump support file 
.PP
Definition in file \fBmdsupport.c\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
