.TH "mesadc32.h" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mesadc32.h \- 
.SH SYNOPSIS
.br
.PP
.SH "Define Documentation"
.PP 
.SS "#define DONE   0"
.PP
Definition at line 106 of file mesadc32.h.
.SS "#define MESADC32_ACQ_START   1"
.PP
Definition at line 103 of file mesadc32.h.
.SS "#define MESADC32_ACQ_STOP   0"
.PP
Definition at line 102 of file mesadc32.h.
.SS "#define MESADC32_ADC_BUSY_TIME_HIHG   0x60A2"
.PP
Definition at line 94 of file mesadc32.h.
.SS "#define MESADC32_ADC_BUSY_TIME_LOW   0x60A0"
.PP
Definition at line 93 of file mesadc32.h.
.SS "#define MESADC32_ADC_OVERRIDE   0x6046"
.PP
Definition at line 51 of file mesadc32.h.
.SS "#define MESADC32_ADC_RESOLUTION   0x6042"
.PP
Definition at line 49 of file mesadc32.h.
.PP
Referenced by mesadc32_ResolutionSet(), mesadc32_Setup(), and mesadc32_Status().
.SS "#define MESADC32_ADD_REG   0x6002"
.PP
Definition at line 24 of file mesadc32.h.
.SS "#define MESADC32_ADD_SOURCE   0x6000"
.PP
Definition at line 23 of file mesadc32.h.
.SS "#define MESADC32_BANK_OPERATION   0x6040"
.PP
Definition at line 48 of file mesadc32.h.
.SS "#define MESADC32_BUF_DATA_LEN   0x6030"
.PP
Definition at line 38 of file mesadc32.h.
.PP
Referenced by mesadc32_ReadData(), and mesadc32_Setup().
.SS "#define MESADC32_CBLT_ADD   0x6022"
.PP
Definition at line 34 of file mesadc32.h.
.SS "#define MESADC32_CBLT_MCST_CTL   0x6020"
.PP
Definition at line 33 of file mesadc32.h.
.SS "#define MESADC32_DATA_LEN_FMT   0x6032"
.PP
Definition at line 39 of file mesadc32.h.
.PP
Referenced by mesadc32_Setup(), and mesadc32_Status().
.SS "#define MESADC32_DATA_READY   0x603E"
.PP
Definition at line 45 of file mesadc32.h.
.PP
Referenced by mesadc32_Setup().
.SS "#define MESADC32_ECL_BUSY   0x6068"
.PP
Definition at line 67 of file mesadc32.h.
.SS "#define MESADC32_ECL_FC_RESET   0x6066"
.PP
Definition at line 66 of file mesadc32.h.
.SS "#define MESADC32_ECL_GATE1_OSC   0x6064"
.PP
Definition at line 65 of file mesadc32.h.
.SS "#define MESADC32_ECL_TERM   0x6062"
.PP
Definition at line 64 of file mesadc32.h.
.SS "#define MESADC32_EMPTY   1"
.PP
Definition at line 14 of file mesadc32.h.
.PP
Referenced by mesadc32_ReadData().
.SS "#define MESADC32_EV_CTL_HIGH   0x6094"
.PP
Definition at line 86 of file mesadc32.h.
.SS "#define MESADC32_EV_CTL_LOW   0x6092"
.PP
Definition at line 85 of file mesadc32.h.
.SS "#define MESADC32_EVENT_READOUT_BUFFER   0x0000"
.PP
Definition at line 16 of file mesadc32.h.
.PP
Referenced by mesadc32_ReadData().
.SS "#define MESADC32_FIFO_RESET   0x603C"
.PP
Definition at line 44 of file mesadc32.h.
.SS "#define MESADC32_FIRM_REV   0x600E"
.PP
Definition at line 27 of file mesadc32.h.
.PP
Referenced by mesadc32_Setup(), and mesadc32_Status().
.SS "#define MESADC32_GATE1_TIME_HIGH   0x60A6"
.PP
Definition at line 96 of file mesadc32.h.
.SS "#define MESADC32_GATE1_TIME_LOW   0x60A4"
.PP
Definition at line 95 of file mesadc32.h.
.SS "#define MESADC32_HOLD_DELAY_0   0x6050"
.PP
Definition at line 56 of file mesadc32.h.
.SS "#define MESADC32_HOLD_DELAY_1   0x6052"
.PP
Definition at line 57 of file mesadc32.h.
.SS "#define MESADC32_HOLD_WIDTH_0   0x6054"
.PP
Definition at line 58 of file mesadc32.h.
.SS "#define MESADC32_HOLD_WIDTH_1   0x6056"
.PP
Definition at line 59 of file mesadc32.h.
.SS "#define MESADC32_INPUT_RANGE   0x6060"
.PP
Definition at line 63 of file mesadc32.h.
.PP
Referenced by mesadc32_Setup(), and mesadc32_Status().
.SS "#define MESADC32_IRQ_LEVEL   0x6010"
.PP
Definition at line 30 of file mesadc32.h.
.SS "#define MESADC32_MARK_EVENT   0"
.PP
Definition at line 105 of file mesadc32.h.
.SS "#define MESADC32_MARK_TIME   1"
.PP
Definition at line 104 of file mesadc32.h.
.SS "#define MESADC32_MARKING_TYPE   0x6038"
.PP
Definition at line 42 of file mesadc32.h.
.PP
Referenced by mesadc32_Setup(), and mesadc32_Status().
.SS "#define MESADC32_MAX_CHANNELS   32"
.PP
Definition at line 15 of file mesadc32.h.
.PP
Referenced by mesadc32_ThresholdGet(), and mesadc32_ThresholdSet().
.SS "#define MESADC32_MCST_ADD   0x6024"
.PP
Definition at line 35 of file mesadc32.h.
.SS "#define MESADC32_MODULE_ID   0x6004"
.PP
Definition at line 25 of file mesadc32.h.
.SS "#define MESADC32_MULTIEVENT   0x6036"
.PP
Definition at line 41 of file mesadc32.h.
.PP
Referenced by mesadc32_Setup(), and mesadc32_Status().
.SS "#define MESADC32_NIM_BUSY   0x606E"
.PP
Definition at line 70 of file mesadc32.h.
.PP
Referenced by mesadc32_MSCF16_GainGet(), mesadc32_MSCF16_GainSet(), mesadc32_MSCF16_IDC(), mesadc32_MSCF16_RCon(), and rcWait().
.SS "#define MESADC32_NIM_FC_RESET   0x606C"
.PP
Definition at line 69 of file mesadc32.h.
.SS "#define MESADC32_NIM_GATE1_OSC   0x606A"
.PP
Definition at line 68 of file mesadc32.h.
.SS "#define MESADC32_OUTPUT_FMT   0x6044"
.PP
Definition at line 50 of file mesadc32.h.
.SS "#define MESADC32_RC_ADDRESS   0x6086"
.PP
Definition at line 79 of file mesadc32.h.
.PP
Referenced by mesadc32_MSCF16_GainGet(), and mesadc32_MSCF16_GainSet().
.SS "#define MESADC32_RC_BUSNO   0x6080"
.PP
Definition at line 76 of file mesadc32.h.
.SS "#define MESADC32_RC_DATA   0x6088"
.PP
Definition at line 80 of file mesadc32.h.
.PP
Referenced by mesadc32_MSCF16_GainGet(), mesadc32_MSCF16_GainSet(), and mesadc32_MSCF16_IDC().
.SS "#define MESADC32_RC_MODNUM   0x6082"
.PP
Definition at line 77 of file mesadc32.h.
.PP
Referenced by mesadc32_MSCF16_GainGet(), mesadc32_MSCF16_GainSet(), mesadc32_MSCF16_IDC(), and mesadc32_MSCF16_RCon().
.SS "#define MESADC32_RC_OPCODE   0x6084"
.PP
Definition at line 78 of file mesadc32.h.
.PP
Referenced by mesadc32_MSCF16_GainGet(), mesadc32_MSCF16_GainSet(), mesadc32_MSCF16_IDC(), and mesadc32_MSCF16_RCon().
.SS "#define MESADC32_RC_SENT_RTN_STAT   0x608A"
.PP
Definition at line 81 of file mesadc32.h.
.PP
Referenced by rcWait().
.SS "#define MESADC32_READOUT_RESET   0x6034"
.PP
Definition at line 40 of file mesadc32.h.
.PP
Referenced by mesadc32_Setup().
.SS "#define MESADC32_RESET_CTL_AB   0x6090"
.PP
Definition at line 84 of file mesadc32.h.
.PP
Referenced by mesadc32_Setup().
.SS "#define MESADC32_SKIP_OORANGE   0x604A"
.PP
Definition at line 53 of file mesadc32.h.
.SS "#define MESADC32_SLC_OFF   0x6048"
.PP
Definition at line 52 of file mesadc32.h.
.SS "#define MESADC32_SOFT_RESET   0x6008"
.PP
Definition at line 26 of file mesadc32.h.
.PP
Referenced by mesadc32_Setup().
.SS "#define MESADC32_START_ACQ   0x603A"
.PP
Definition at line 43 of file mesadc32.h.
.PP
Referenced by mesadc32_Setup().
.SS "#define MESADC32_STOP_CTR   0x60AE"
.PP
Definition at line 100 of file mesadc32.h.
.SS "#define MESADC32_TESTPULSER   0x6070"
.PP
Definition at line 73 of file mesadc32.h.
.PP
Referenced by mesadc32_Status().
.SS "#define MESADC32_THRESHOLD_0   0x4000"
.PP
Definition at line 19 of file mesadc32.h.
.PP
Referenced by mesadc32_ThresholdGet(), and mesadc32_ThresholdSet().
.SS "#define MESADC32_TIME_0   0x60A8"
.PP
Definition at line 97 of file mesadc32.h.
.SS "#define MESADC32_TIME_1   0x60AA"
.PP
Definition at line 98 of file mesadc32.h.
.SS "#define MESADC32_TIME_2   0x60AC"
.PP
Definition at line 99 of file mesadc32.h.
.SS "#define MESADC32_TS_COUNTER_HIGH   0x609E"
.PP
Definition at line 90 of file mesadc32.h.
.SS "#define MESADC32_TS_COUNTER_LOW   0x609C"
.PP
Definition at line 89 of file mesadc32.h.
.SS "#define MESADC32_TS_DIVIDER   0x6098"
.PP
Definition at line 88 of file mesadc32.h.
.SS "#define MESADC32_TS_SOURCE   0x6096"
.PP
Definition at line 87 of file mesadc32.h.
.PP
Referenced by mesadc32_Setup().
.SS "#define MESADC32_USE_GG   0x6058"
.PP
Definition at line 60 of file mesadc32.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
