.TH "History related" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
History related \- 
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBHIST_RECORD\fP"
.br
.ti -1c
.RI "struct \fBDEF_RECORD\fP"
.br
.ti -1c
.RI "struct \fBINDEX_RECORD\fP"
.br
.ti -1c
.RI "struct \fBHISTORY\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
dox dox 
.SH "Define Documentation"
.PP 
.SS "#define RT_DATA   (*((\fBDWORD\fP *) 'HSDA'))"
.PP
Definition at line 1195 of file midas.h.
.SS "#define RT_DEF   (*((\fBDWORD\fP *) 'HSDF'))"
.PP
Definition at line 1196 of file midas.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
