.TH "The mrpc.h & mrpc.c" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
The mrpc.h & mrpc.c \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBRPC Define\fP"
.br
.ti -1c
.RI "\fBMidas RPC_LIST\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
dox 
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
