.TH "mrpc.c" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mrpc.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "static RPC_LIST \fBrpc_list_library\fP []"
.br
.ti -1c
.RI "static RPC_LIST \fBrpc_list_system\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
dox The Midas RPC file 
.PP
Definition in file \fBmrpc.c\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
