.TH "System Define" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System Define \- 
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBDRI_16\fP   (1<<0)"
.br
.ti -1c
.RI "#define \fBDRI_32\fP   (1<<1)"
.br
.ti -1c
.RI "#define \fBDRI_64\fP   (1<<2)"
.br
.ti -1c
.RI "#define \fBDRI_LITTLE_ENDIAN\fP   (1<<3)"
.br
.ti -1c
.RI "#define \fBDRI_BIG_ENDIAN\fP   (1<<4)"
.br
.ti -1c
.RI "#define \fBDRF_IEEE\fP   (1<<5)"
.br
.ti -1c
.RI "#define \fBDRF_G_FLOAT\fP   (1<<6)"
.br
.ti -1c
.RI "#define \fBDR_ASCII\fP   (1<<7)"
.br
.in -1c
.SH "Detailed Description"
.PP 
dox dox 
.SH "Define Documentation"
.PP 
.SS "#define DR_ASCII   (1<<7)".IP "\(bu" 2

.PP

.PP
Definition at line 55 of file msystem.h.
.SS "#define DRF_G_FLOAT   (1<<6)".IP "\(bu" 2

.PP

.PP
Definition at line 54 of file msystem.h.
.SS "#define DRF_IEEE   (1<<5)".IP "\(bu" 2

.PP

.PP
Definition at line 53 of file msystem.h.
.SS "#define DRI_16   (1<<0)"data representations - 
.PP
Definition at line 48 of file msystem.h.
.SS "#define DRI_32   (1<<1)".IP "\(bu" 2

.PP

.PP
Definition at line 49 of file msystem.h.
.SS "#define DRI_64   (1<<2)".IP "\(bu" 2

.PP

.PP
Definition at line 50 of file msystem.h.
.SS "#define DRI_BIG_ENDIAN   (1<<4)".IP "\(bu" 2

.PP

.PP
Definition at line 52 of file msystem.h.
.SS "#define DRI_LITTLE_ENDIAN   (1<<3)".IP "\(bu" 2

.PP

.PP
Definition at line 51 of file msystem.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
