.TH "Midas Structure Declaration" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Midas Structure Declaration \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBBuffer Section\fP"
.br
.ti -1c
.RI "\fBEquipment related\fP"
.br
.ti -1c
.RI "\fBBank related\fP"
.br
.ti -1c
.RI "\fBAnalyzer related\fP"
.br
.ti -1c
.RI "\fBHistory related\fP"
.br
.ti -1c
.RI "\fBODB runinfo related\fP"
.br
.ti -1c
.RI "\fBAlarm related\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
dox 
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
