.TH "System Structure Declaration" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System Structure Declaration \- 
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBFREE_DESCRIP\fP"
.br
.ti -1c
.RI "struct \fBOPEN_RECORD\fP"
.br
.ti -1c
.RI "struct \fBDATABASE_CLIENT\fP"
.br
.ti -1c
.RI "struct \fBDATABASE_HEADER\fP"
.br
.ti -1c
.RI "struct \fBDATABASE\fP"
.br
.ti -1c
.RI "struct \fBRECORD_LIST\fP"
.br
.ti -1c
.RI "struct \fBREQUEST_LIST\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
dox dox dox 
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
