.TH "The msystem.h & system.c" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
The msystem.h & system.c \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBSystem Functions (ss_xxx)\fP"
.br
.ti -1c
.RI "\fBSystem Define\fP"
.br
.ti -1c
.RI "\fBSystem Macros\fP"
.br
.ti -1c
.RI "\fBSystem Structure Declaration\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
dox 
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
