.TH "MVME_INTERFACE" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MVME_INTERFACE \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBinitialized\fP"
.br
.ti -1c
.RI "int \fBhandle\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "void * \fBinfo\fP"
.br
.ti -1c
.RI "int \fBam\fP"
.br
.ti -1c
.RI "int \fBdmode\fP"
.br
.ti -1c
.RI "int \fBblt_mode\fP"
.br
.ti -1c
.RI "void * \fBtable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 135 of file mvmestd.h.
.SH "Field Documentation"
.PP 
.SS "int \fBMVME_INTERFACE::am\fP"Address modifier 
.PP
Definition at line 140 of file mvmestd.h.
.SS "int \fBMVME_INTERFACE::blt_mode\fP"Block transfer mode 
.PP
Definition at line 142 of file mvmestd.h.
.SS "int \fBMVME_INTERFACE::dmode\fP"Data mode (D8,D16,D32,D64) 
.PP
Definition at line 141 of file mvmestd.h.
.SS "int \fBMVME_INTERFACE::handle\fP"internal handle 
.PP
Definition at line 137 of file mvmestd.h.
.SS "int \fBMVME_INTERFACE::index\fP"index of interface 0..n 
.PP
Definition at line 138 of file mvmestd.h.
.SS "void* \fBMVME_INTERFACE::info\fP"internal info structure 
.PP
Definition at line 139 of file mvmestd.h.
.SS "int \fBMVME_INTERFACE::initialized\fP"1 if VME interface initialized 
.PP
Definition at line 136 of file mvmestd.h.
.SS "void* \fBMVME_INTERFACE::table\fP"Optional table for some drivers 
.PP
Definition at line 143 of file mvmestd.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
