.TH "myexpt.html" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
myexpt.html \- 
.SH SYNOPSIS
.br
.PP
.SH "Variable Documentation"
.PP 
.SS "<html><head><title> MyExperiment Demo Status</title><metahttp-equiv='Refresh'content='30'></head><body><formname='form1'method='Get'action='/CS/MyExpt&'><tableborder=3cellpadding=2><tr><thbgcolor='#A0A0FF'> Demo Experiment<th bgcolor='#A0A0FF'> Custom Monitor Control</tr><tr><td><b><fontcolor='#ff0000'> Actions"
.PP
Definition at line 29 of file myexpt.html.
.SS "\fBscale\fP = 12h&amp"
.PP
Definition at line 29 of file myexpt.html.
.SS "\fBwidth\fP"\fBInitial value:\fP
.PP
.nf
250'>
        </th>
        <th> <img src='http:
                        exp=default&amp
.fi
.PP
Definition at line 29 of file myexpt.html.
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
