.TH "O_Contents_Page" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O_Contents_Page \- List of contents of each Section 
 
.br

.br
.PP
.PP

.br
 Section Contents   
.PP

.br
  \fBSECTION 1: Main Page\fP 
.br
   
.br

.br

.br
I
.br
n
.br
t
.br
r
.br
o
.br
    
.br
 \fBSECTION 2: Introduction\fP 
.PD 0

.IP "\(bu" 2
\fBWhat is MIDAS?\fP 
.IP "\(bu" 2
\fBMIDAS is for small and medium sized experiments\fP 
.PD 0

.IP "  \(bu" 4
\fBFrontend(s) and Backend(s)\fP 
.IP "  \(bu" 4
\fBDevice Drivers for MIDAS\fP 
.IP "  \(bu" 4
\fBAnalysis of MIDAS data\fP 
.IP "  \(bu" 4
\fBSlow controls\fP 
.PP

.br
 
.IP "\(bu" 2
\fBDiagram of the MIDAS system\fP 
.PP
 
.br

.br

.br
Q
.br
u
.br
i
.br
c
.br
k
.br
 
.br
S
.br
t
.br
a
.br
r
.br
t
.br
    
.br
 \fBSECTION 3: Quick Start\fP 
.PD 0

.IP "\(bu" 2
\fBIntroduction\fP 
.IP "\(bu" 2
\fBMIDAS Package Source (SVN and tarball)\fP 
.IP "\(bu" 2
\fBMIDAS Installation\fP 
.br
 
.IP "\(bu" 2
\fBQuickstart Linux\fP 
.PD 0

.IP "  \(bu" 4
\fBSystem Requirements\fP 
.IP "  \(bu" 4
\fBInstallation\fP 
.PD 0

.IP "    \(bu" 6
\fBEnvironment Variables\fP 
.IP "    \(bu" 6
\fBROOT Package Installation\fP 
.IP "    \(bu" 6
\fBMIDAS Package Installation\fP 
.IP "    \(bu" 6
\fBROME Package Installation\fP 
.IP "    \(bu" 6
\fBROODY Package Installation\fP 
.PP

.IP "  \(bu" 4
\fBBasic test\fP 
.PD 0

.IP "    \(bu" 6
\fBHardware Requirements\fP 
.IP "    \(bu" 6
\fBSoftware Requirements\fP 
.IP "    \(bu" 6
\fBHow to Setup the MIDAS Experiment\fP 
.PP

.IP "  \(bu" 4
\fBInstallation Considerations\fP 
.PD 0

.IP "    \(bu" 6
\fBRemote Access to the experiment\fP 
.IP "    \(bu" 6
\fBDefinition of Experiments (exptab)\fP 
.PP

.IP "  \(bu" 4
\fBDemo examples\fP 
.PP

.br
 
.IP "\(bu" 2
\fBQuickstart Windows\fP 
.PD 0

.IP "  \(bu" 4
\fBSystem Requirements\fP 
.IP "  \(bu" 4
\fBInstallation\fP 
.PD 0

.IP "    \(bu" 6
\fBEnvironment Variables\fP 
.PP

.IP "  \(bu" 4
\fBBasic test\fP 
.PD 0

.IP "    \(bu" 6
\fBHardware Requirements\fP 
.IP "    \(bu" 6
\fBSoftware Requirements\fP 
.IP "    \(bu" 6
\fBHow to Setup the MIDAS Experiment\fP 
.PP

.PP

.PP
 
.br

.br

.br
F
.br
e
.br
a
.br
t
.br
u
.br
r
.br
e
.br
s
.br
 
.br
 
.br

.br

.br
F
.br
e
.br
a
.br
t
.br
u
.br
r
.br
e
.br
s
.br
 
.br
 
.br

.br

.br
F
.br
e
.br
a
.br
t
.br
u
.br
r
.br
e
.br
s
.br
 
.br
 
.br

.br

.br
F
.br
e
.br
a
.br
t
.br
u
.br
r
.br
e
.br
s
.br
 
.br
 
.br

.br

.br
F
.br
e
.br
a
.br
t
.br
u
.br
r
.br
e
.br
s
.br
    
.br
 \fBSECTION 4: Features\fP 
.PD 0

.IP "\(bu" 2
\fBGeneral Acquisition Principles\fP 
.br
 
.IP "\(bu" 2
\fBOverview of the Main Elements of the MIDAS DAQ System\fP 
.PD 0

.IP "  \(bu" 4
\fBThe Buffer Manager\fP 
.IP "  \(bu" 4
\fBMessage System\fP 
.IP "  \(bu" 4
\fBOnline Database (ODB)\fP 
.IP "  \(bu" 4
\fBMIDAS Server\fP 
.IP "  \(bu" 4
\fBFrontend\fP 
.IP "  \(bu" 4
\fBData Logger\fP 
.IP "  \(bu" 4
\fBAnalyzer\fP 
.IP "  \(bu" 4
\fBRun Control\fP 
.IP "  \(bu" 4
\fBSlow Control\fP 
.IP "  \(bu" 4
\fBHistory system\fP 
.IP "  \(bu" 4
\fBAlarm System\fP 
.IP "  \(bu" 4
\fBElectronic Logbook\fP 
.PP

.br
 
.IP "\(bu" 2
\fBODB Structure\fP 
.br
 
.IP "\(bu" 2
\fBList of MIDAS Utilities\fP 
.PD 0

.IP "  \(bu" 4
\fBCommon Parameters to MIDAS Utilities\fP 
.PP

.br
 
.IP "\(bu" 2
\fBMIDAS Code and Libraries\fP 
.PD 0

.IP "  \(bu" 4
\fBMIDAS Data Types\fP 
.IP "  \(bu" 4
\fBMIDAS Code and Libraries\fP 
.IP "  \(bu" 4
\fBMIDAS Macros\fP 
.PP

.br
 
.IP "\(bu" 2
\fBLogging in MIDAS\fP 
.PD 0

.IP "  \(bu" 4
\fBIntroduction\fP 
.IP "  \(bu" 4
\fBmlogger - MIDAS Logger\fP 
.IP "  \(bu" 4
\fBCustomizing the MIDAS data logging\fP 
.PD 0

.IP "    \(bu" 6
\fB/Logger ODB tree\fP 
.IP "    \(bu" 6
\fBExplanation of the keys in the ODB /Logger tree\fP 
.IP "    \(bu" 6
\fBMultiple Logging Channels\fP 
.IP "    \(bu" 6
\fBExplanation of keys in the ODB /Logger/Channels tree\fP 
.IP "    \(bu" 6
\fB/Logger/Channels/0/Statistics tree\fP 
.IP "    \(bu" 6
\fBOptional SQL subtree in the ODB /Logger tree\fP 
.PP

.IP "  \(bu" 4
\fBMessaging\fP 
.PD 0

.IP "    \(bu" 6
\fBMIDAS Log file\fP 
.IP "    \(bu" 6
\fBm[lx]speaker - audible messaging\fP 
.PP

.IP "  \(bu" 4
\fBLogging information to a mySQL database\fP 
.PD 0

.IP "    \(bu" 6
\fBmySQL\fP 
.IP "    \(bu" 6
\fBExplanation of the keys in the ODB /Logger/SQL tree\fP 
.PP

.IP "  \(bu" 4
\fBHistory Logging\fP 
.PD 0

.IP "    \(bu" 6
\fBMIDAS History System\fP 
.IP "    \(bu" 6
\fBLocation of History Files\fP 
.PD 0

.IP "      \(bu" 8
\fBCreation of ODB Key '/Logger/History dir'\fP 
.PP

.IP "    \(bu" 6
\fBTypes of History Events\fP 
.IP "    \(bu" 6
\fBFrontend History Event\fP 
.PD 0

.IP "      \(bu" 8
\fBEnable the History system for a frontend event\fP 
.PD 0

.IP "        \(bu" 10
\fBNew History Tags\fP 
.IP "        \(bu" 10
\fBDefinition of old-style history tags\fP 
.PP

.IP "      \(bu" 8
\fBExample Frontend History Event (old-style History tags)\fP 
.PP

.IP "    \(bu" 6
\fBODB /History tree\fP 
.IP "    \(bu" 6
\fBExplanation of the keys in the ODB /History tree\fP 
.IP "    \(bu" 6
\fBCustomizing the History logging\fP 
.IP "    \(bu" 6
\fBMIDAS SQL History system\fP 
.PD 0

.IP "      \(bu" 8
\fBHow to enable writing history to SQL\fP 
.IP "      \(bu" 8
\fBHow to enable writing history to SQL\fP 
.IP "      \(bu" 8
\fBLayout of SQL tables:\fP 
.IP "      \(bu" 8
\fBSchema Evolution:\fP 
.PP

.IP "    \(bu" 6
\fBmh2sql - import history files into SQL database.\fP 
.IP "    \(bu" 6
\fBmhist - history data retriever\fP 
.IP "    \(bu" 6
\fBmhdump - dump history files\fP 
.IP "    \(bu" 6
\fBHistory format\fP 
.PP

.IP "  \(bu" 4
\fBElectronic logbook (Elog)\fP 
.PD 0

.IP "    \(bu" 6
\fBIntroduction\fP 
.IP "    \(bu" 6
\fBLocation of Elog Files\fP 
.PD 0

.IP "      \(bu" 8
\fBCreation of ODB Key Elog Dir\fP 
.PP

.IP "    \(bu" 6
\fBCustomizing the Elog\fP 
.PD 0

.IP "      \(bu" 8
\fBThe ODB /Elog Tree\fP 
.IP "      \(bu" 8
\fBMeaning of the keys in the /Elog tree\fP 
.PP

.IP "    \(bu" 6
\fBmelog - submits an entry to the Elog\fP 
.PP

.IP "  \(bu" 4
\fBLogging Utilities\fP 
.PD 0

.IP "    \(bu" 6
\fBlazylogger - logger to copy/move stored files\fP 
.IP "    \(bu" 6
\fBODB /Lazy Tree\fP 
.PD 0

.IP "      \(bu" 8
\fBExample of the ODB /Lazy/<channel_name>/Settings subtree\fP 
.IP "      \(bu" 8
\fBExplanation of the Keys in the ODB /Lazy/<channel_name>/Settings subtree\fP 
.IP "      \(bu" 8
\fBThe ODB /Lazy/<channel_name>/Statistics subtree\fP 
.IP "      \(bu" 8
\fBThe ODB /Lazy/<channel_name>/List subtree\fP 
.PP

.IP "    \(bu" 6
\fBSetting up the Lazylogger\fP 
.PD 0

.IP "      \(bu" 8
\fBOperation of the Lazylogger\fP 
.PP

.IP "    \(bu" 6
\fBmchart - assembles data for stripchart\fP 
.IP "    \(bu" 6
\fBmtape - tape manipulation\fP 
.IP "    \(bu" 6
\fBstripchart - graphical stripchart data display\fP 
.PP

.PP

.PP
 
.br

.br

.br
R
.br
u
.br
n
.br
 
.br
C
.br
o
.br
n
.br
t
.br
r
.br
o
.br
l
.br
 
.br
 
.br

.br

.br
R
.br
u
.br
n
.br
 
.br
C
.br
o
.br
n
.br
t
.br
r
.br
o
.br
l
.br
 
.br
 
.br

.br

.br
R
.br
u
.br
n
.br
 
.br
C
.br
o
.br
n
.br
t
.br
r
.br
o
.br
l
.br
 
.br
 
.br

.br

.br
R
.br
u
.br
n
.br
 
.br
C
.br
o
.br
n
.br
t
.br
r
.br
o
.br
l
.br
 
.br
 
.br

.br

.br
R
.br
u
.br
n
.br
 
.br
C
.br
o
.br
n
.br
t
.br
r
.br
o
.br
l
.br
 
.br
 
.br

.br

.br
R
.br
u
.br
n
.br
 
.br
C
.br
o
.br
n
.br
t
.br
r
.br
o
.br
l
.br
 
.br
 
.br

.br

.br
R
.br
u
.br
n
.br
 
.br
C
.br
o
.br
n
.br
t
.br
r
.br
o
.br
l
.br
 
.br
 
.br

.br

.br
R
.br
u
.br
n
.br
 
.br
C
.br
o
.br
n
.br
t
.br
r
.br
o
.br
l
.br
 
.br
 
.br

.br

.br
R
.br
u
.br
n
.br
 
.br
C
.br
o
.br
n
.br
t
.br
r
.br
o
.br
l
.br
 
.br
 
.br

.br

.br
R
.br
u
.br
n
.br
 
.br
C
.br
o
.br
n
.br
t
.br
r
.br
o
.br
l
.br
 
.br
 
.br

.br

.br
R
.br
u
.br
n
.br
 
.br
C
.br
o
.br
n
.br
t
.br
r
.br
o
.br
l
.br
 
.br
 
.br

.br

.br
R
.br
u
.br
n
.br
 
.br
C
.br
o
.br
n
.br
t
.br
r
.br
o
.br
l
.br
 
.br
 
.br

.br

.br
R
.br
u
.br
n
.br
 
.br
C
.br
o
.br
n
.br
t
.br
r
.br
o
.br
l
.br
    
.br
 \fBSECTION 5: Run Control\fP 
.PD 0

.IP "\(bu" 2
\fBIntroduction\fP 
.br
 
.IP "\(bu" 2
\fBRun States and Transitions\fP 
.PD 0

.IP "  \(bu" 4
\fBMIDAS State and Transition Codes\fP 
.IP "  \(bu" 4
\fBRun Transition Priority\fP 
.PD 0

.IP "    \(bu" 6
\fBRegistering for a run transition\fP 
.PD 0

.IP "      \(bu" 8
\fBMultiple Registration to a Transition\fP 
.PP

.IP "    \(bu" 6
\fBDefault Transition Sequence Numbers\fP 
.IP "    \(bu" 6
\fBReview the Client Transition Sequence Numbers in the ODB\fP 
.IP "    \(bu" 6
\fBChange the Client Sequence Number\fP 
.PP

.IP "  \(bu" 4
\fBDeferred Transitions\fP 
.IP "  \(bu" 4
\fBRun Information\fP 
.PD 0

.IP "    \(bu" 6
\fBODB /RunInfo Tree\fP 
.PP

.PP

.br
 
.IP "\(bu" 2
\fBRun Control Programs\fP 
.PD 0

.IP "  \(bu" 4
\fBodbedit: The ODB Editor and Run Control utility\fP 
.PD 0

.IP "    \(bu" 6
\fBodbedit - ODB Editor and run control utility\fP 
.PD 0

.IP "      \(bu" 8
\fBodbedit command list\fP 
.PP

.IP "    \(bu" 6
\fBUsing odbedit\fP 
.PD 0

.IP "      \(bu" 8
\fBSetting odbedit's prompt\fP 
.PD 0

.IP "        \(bu" 10
\fBExamples of changing the odbedit prompt:\fP 
.PP

.IP "      \(bu" 8
\fBODB Creation\fP 
.IP "      \(bu" 8
\fBODB Key names: UPPER/lower case, spaces in key names\fP 
.IP "      \(bu" 8
\fBCorrupted ODB\fP 
.PD 0

.IP "        \(bu" 10
\fBUsing the external command (the -c argument)\fP 
.IP "        \(bu" 10
\fBExamples of scripts sending odbedit commands\fP 
.PD 0

.IP "          \(bu" 12
\fBShell script run at end-of-run\fP 
.IP "          \(bu" 12
\fBShell script run at beginning of run\fP 
.PP

.PP

.IP "      \(bu" 8
\fBExamples using odbedit commands\fP 
.PD 0

.IP "        \(bu" 10
\fBpwd - show current directory\fP 
.IP "        \(bu" 10
\fBcd - change current directory\fP 
.IP "        \(bu" 10
\fBchat - enter chat mode\fP 
.IP "        \(bu" 10
\fBchmod - change access mode\fP 
.IP "        \(bu" 10
\fBls - list the database entries\fP 
.IP "        \(bu" 10
\fBmkdir - make new subdirectory\fP 
.IP "        \(bu" 10
\fBmsg - send a user message\fP 
.IP "        \(bu" 10
\fBold - display old messages\fP 
.IP "        \(bu" 10
\fBpasswd - change/set up the MIDAS password\fP 
.IP "        \(bu" 10
\fBwebpasswd - change/set up the web password for mhttpd\fP 
.IP "        \(bu" 10
\fBmove - move a key to a new position\fP 
.IP "        \(bu" 10
\fBrename - rename a key\fP 
.IP "        \(bu" 10
\fBcopy - copy a subtree\fP 
.IP "        \(bu" 10
\fBimport - import ASCII file\fP 
.IP "        \(bu" 10
\fBexport - export ASCII file\fP 
.IP "        \(bu" 10
\fBln - create a link\fP 
.IP "        \(bu" 10
\fBcreate - create a key of a certain type\fP 
.IP "        \(bu" 10
\fBset - set the value of a key\fP 
.IP "        \(bu" 10
\fBchmod - change access mode\fP 
.IP "        \(bu" 10
\fBtrunc - truncate a key\fP 
.IP "        \(bu" 10
\fBrm/del - delete a key and its subkeys\fP 
.IP "        \(bu" 10
\fBsor - show open records\fP 
.IP "        \(bu" 10
\fBsave - save database at current position\fP 
.IP "        \(bu" 10
\fBload - load database from a saved file\fP 
.IP "        \(bu" 10
\fBmake - create experim.h\fP 
.IP "        \(bu" 10
\fBscl - show active clients\fP 
.IP "        \(bu" 10
\fBsh - shutdown a client\fP 
.IP "        \(bu" 10
\fBstart - start a run\fP 
.PD 0

.IP "          \(bu" 12
\fBRun start examples\fP 
.IP "          \(bu" 12
\fBRun Start example with 'Edit on Start' parameters\fP 
.IP "          \(bu" 12
\fBRun Start Example with 'start now'\fP 
.IP "          \(bu" 12
\fBRun Start Example with '-v' verbose option\fP 
.PP

.IP "        \(bu" 10
\fBstop - stop a run\fP 
.PP

.PP

.PP

.IP "  \(bu" 4
\fBmhttpd: the MIDAS Web-based Run Control utility\fP 
.PD 0

.IP "    \(bu" 6
\fBIntroduction\fP 
.IP "    \(bu" 6
\fBThe mhttpd daemon\fP 
.PD 0

.IP "      \(bu" 8
\fBStart the mhttpd daemon\fP 
.PD 0

.IP "        \(bu" 10
\fBConnect to the mhttpd webserver\fP 
.PP

.IP "      \(bu" 8
\fBProxy Access to mhttpd\fP 
.PP
.PD 0
.IP "      \(bu" 8
\fBFeatures of mhttpd\fP 
.PP

.IP "    \(bu" 6
\fBMain Status Page\fP 
.PD 0

.IP "      \(bu" 8
\fBStatus Page for a Running Experiment\fP 
.IP "      \(bu" 8
\fBFeatures of the Main Status Page\fP 
.PD 0

.IP "        \(bu" 10
\fBExperiment/Date/Refresh information\fP 
.IP "        \(bu" 10
\fBMenu buttons\fP 
.PD 0

.IP "          \(bu" 12
\fBRun Control buttons\fP 
.IP "          \(bu" 12
\fBPage Switch buttons\fP 
.PP

.IP "        \(bu" 10
\fBOptional Buttons on the main Status page\fP 
.PD 0

.IP "          \(bu" 12
\fBOptional Script buttons\fP 
.PD 0

.IP "            \(bu" 14
\fBDefining Script Buttons on the main Status Page\fP 
.PD 0

.IP "              \(bu" 16
\fBThe ODB /Script tree\fP 
.IP "              \(bu" 16
\fBExample 1: creation of a Script-button; parameters passed to the associated script\fP 
.IP "              \(bu" 16
\fBExample 2: MPET experiment run controller\fP 
.PD 0

.IP "                \(bu" 18
\fBMPET perlscripts to perform run control\fP 
.PP

.IP "              \(bu" 16
\fBExamples of MPET Perlscripts for run control\fP 
.PD 0

.IP "                \(bu" 18
\fBperlmidas.pl\fP 
.IP "                \(bu" 18
\fBperlrc.pl\fP 
.PP

.PP

.PP

.IP "          \(bu" 12
\fBManual-Trigger Buttons\fP 
.IP "          \(bu" 12
\fBAlias-Buttons\fP 
.PP

.IP "        \(bu" 10
\fBRun status information\fP 
.IP "        \(bu" 10
\fBComment and Run Description\fP 
.IP "        \(bu" 10
\fBEquipment information and Event rates\fP 
.PD 0

.IP "          \(bu" 12
\fBMonitor the Equipment variables\fP 
.IP "          \(bu" 12
\fBStatus display of each Equipment\fP 
.IP "          \(bu" 12
\fBEvent Rates\fP 
.IP "          \(bu" 12
\fBNumber of events analyzed\fP 
.PP

.IP "        \(bu" 10
\fBData Logging Information\fP 
.IP "        \(bu" 10
\fBLast system message\fP 
.IP "        \(bu" 10
\fBActive Client list\fP 
.PP

.IP "      \(bu" 8
\fBRedesign of mhttpd Main Status Page\fP 
.PP

.IP "    \(bu" 6
\fBStart page\fP 
.PD 0

.IP "      \(bu" 8
\fBRun Start with defined /Experiment/Edit on Start tree\fP 
.PD 0

.IP "        \(bu" 10
\fBFeatures available for mhttpd only\fP 
.IP "        \(bu" 10
\fBEdit-on-start Parameter Comments\fP 
.IP "        \(bu" 10
\fBPrevent the run number being edited at Run Start\fP 
.PP

.PP

.IP "    \(bu" 6
\fBODB page\fP 
.PD 0

.IP "      \(bu" 8
\fBChanging a variable\fP 
.IP "      \(bu" 8
\fBCreating a subdirectory and an array\fP 
.PP

.IP "    \(bu" 6
\fBEquipment page\fP 
.PD 0

.IP "      \(bu" 8
\fBHow to Display the Equipment Page\fP 
.IP "      \(bu" 8
\fBNaming the Equipment data\fP 
.PD 0

.IP "        \(bu" 10
\fBExamples of named Equipment data\fP 
.PD 0

.IP "          \(bu" 12
\fBData from an Equipment with one bank using the default Names\fP 
.IP "          \(bu" 12
\fBNamed data from an Equipment with one bank\fP 
.IP "          \(bu" 12
\fBNamed data from an Equipment with two banks of the same length\fP 
.IP "          \(bu" 12
\fBEvent containing two Named Banks of different sizes\fP 
.IP "          \(bu" 12
\fBNames array Grouped for a large number of elements in a bank\fP 
.IP "          \(bu" 12
\fBFixed-Format event with named Variables\fP 
.IP "          \(bu" 12
\fBFixed-Format event with defined Names array\fP 
.PP

.PP

.PP

.IP "    \(bu" 6
\fBSlow Control page\fP 
.PD 0

.IP "      \(bu" 8
\fBIntroduction\fP 
.IP "      \(bu" 8
\fBName Syntax for Slow Control Page\fP 
.PP

.IP "    \(bu" 6
\fBMessage page\fP 
.IP "    \(bu" 6
\fBElog page\fP 
.PD 0

.IP "      \(bu" 8
\fBIntroduction\fP 
.PD 0

.IP "        \(bu" 10
\fBInternal Elog\fP 
.PD 0

.IP "          \(bu" 12
\fBThe Shift Check button\fP 
.IP "          \(bu" 12
\fBRunlog Button\fP 
.PP

.IP "        \(bu" 10
\fBExternal Elog\fP 
.PP

.PP

.IP "    \(bu" 6
\fBPrograms page\fP 
.IP "    \(bu" 6
\fBHistory page\fP 
.IP "    \(bu" 6
\fBAlarm page\fP 
.IP "    \(bu" 6
\fBMSCB page\fP 
.IP "    \(bu" 6
\fBCAMAC Access page\fP 
.IP "    \(bu" 6
\fBmhttpd Alias page\fP 
.PD 0

.IP "      \(bu" 8
\fBAlias-Buttons (or Hyperlinks)\fP 
.IP "      \(bu" 8
\fBHow to create Alias-Buttons\fP 
.PD 0

.IP "        \(bu" 10
\fBThe ODB /Alias Tree\fP 
.PP

.PP

.IP "    \(bu" 6
\fBmhttpd Logger page\fP 
.PD 0

.IP "      \(bu" 8
\fBmlogger settings information\fP 
.IP "      \(bu" 8
\fBlazylogger settings information\fP 
.PP

.IP "    \(bu" 6
\fBConfig page\fP 
.IP "    \(bu" 6
\fBCustom pages\fP 
.PD 0

.IP "      \(bu" 8
\fBIntroduction\fP 
.IP "      \(bu" 8
\fBExamples of Custom Webpages\fP 
.IP "      \(bu" 8
\fBCustom Page showing ROOT analyzer output\fP 
.PD 0

.IP "        \(bu" 10
\fBHTML code for the MEG ROOT Analyzer page\fP 
.PP

.IP "      \(bu" 8
\fBCustom Page for MEG gas system\fP 
.IP "      \(bu" 8
\fBCustom Pages for Ebit Experiment\fP 
.IP "      \(bu" 8
\fBMpet Optics Custom Page\fP 
.IP "      \(bu" 8
\fBCustom Pages designed for T2K gas system\fP 
.PD 0

.IP "        \(bu" 10
\fBExample custom page: pop-up window, clickable boxes\fP 
.IP "        \(bu" 10
\fBExample custom page: hidden alias keys\fP 
.PP

.IP "      \(bu" 8
\fBCustom Status Pages for experiments BNMR and BNQR\fP 
.IP "      \(bu" 8
\fBHow to activate custom page(s) in the ODB\fP 
.PD 0

.IP "        \(bu" 10
\fBIntroduction\fP 
.IP "        \(bu" 10
\fBThe /Custom ODB tree\fP 
.PD 0

.IP "          \(bu" 12
\fBKeynames in the /Custom directory\fP 
.IP "          \(bu" 12
\fBCreate a link to an external webpage\fP 
.IP "          \(bu" 12
\fBImport an internal webpage\fP 
.IP "          \(bu" 12
\fBExamples of /Custom keys\fP 
.PP

.IP "        \(bu" 10
\fBHow to replace the default Status page by a Custom Status page\fP 
.PP

.IP "      \(bu" 8
\fBJavaScript built-in library mhttpd.js\fP 
.PD 0

.IP "        \(bu" 10
\fBJavascript Built-In library\fP 
.PD 0

.IP "          \(bu" 12
\fBList of functions in JS library\fP 
.IP "          \(bu" 12
\fBInclude the JS library mhttpd.js in a custom page\fP 
.PP

.PP

.IP "      \(bu" 8
\fBFeatures available on custom pages\fP 
.PD 0

.IP "        \(bu" 10
\fBHow to create a custom page\fP 
.PD 0

.IP "          \(bu" 12
\fBIncluding JavaScript code in an HTML custom page\fP 
.IP "          \(bu" 12
\fBAccess to the ODB from a Custom Page\fP 
.IP "          \(bu" 12
\fBPage refresh\fP 
.PP

.IP "        \(bu" 10
\fBAccess to the standard MIDAS Menu buttons\fP 
.IP "        \(bu" 10
\fBAlias Buttons and Hyperlinks\fP 
.IP "        \(bu" 10
\fBSimple Example of a custom page in HTML\fP 
.IP "        \(bu" 10
\fBCustomScript Buttons\fP 
.PD 0

.IP "          \(bu" 12
\fBODB /CustomScript tree\fP 
.IP "          \(bu" 12
\fBExample of CustomScript buttons and corresponding /CustomScript tree\fP 
.PP

.IP "        \(bu" 10
\fBAccess to message log\fP 
.IP "        \(bu" 10
\fBAccess to the ODB from a Custom page\fP 
.PD 0

.IP "          \(bu" 12
\fBExamples of accessing ODB from a Custom page\fP 
.PD 0

.IP "            \(bu" 14
\fBExample of ODB access with HTML and JavaScript equivalent\fP 
.IP "            \(bu" 14
\fBExample of ODB access with JavaScript functions ODBSet and ODBKey\fP 
.IP "            \(bu" 14
\fBExample of ODB access with arrays\fP 
.PP

.IP "          \(bu" 12
\fBFeatures using ODB access from a Custom page\fP 
.PD 0

.IP "            \(bu" 14
\fBIncluding checkboxes on a custom page\fP 
.IP "            \(bu" 14
\fBExample of Checkboxes using JavaScript and HTML\fP 
.IP "            \(bu" 14
\fBPeriodic update of parts of a custom page\fP 
.IP "            \(bu" 14
\fBPassword protection of ODB variables accessed from a custom page\fP 
.PP
.PD 0
.IP "            \(bu" 14
\fBODB access using HTML tags\fP 
.IP "            \(bu" 14
\fBODB Access using mhttpd JavaScript built-in functions\fP 
.PD 0

.IP "              \(bu" 16
\fBODBGet JavaScript function\fP 
.IP "              \(bu" 16
\fBODBEdit JavaScript function\fP 
.IP "              \(bu" 16
\fBODBSet JavaScript function\fP 
.IP "              \(bu" 16
\fBODBKey JavaScript function\fP 
.PP

.PP

.PP

.IP "        \(bu" 10
\fBODB RPC access\fP 
.IP "        \(bu" 10
\fBInserting an Image into a Custom page\fP 
.PD 0

.IP "          \(bu" 12
\fBInserting a history image in a custom page\fP 
.IP "          \(bu" 12
\fBImage insertion into a Custom page\fP 
.PD 0

.IP "            \(bu" 14
\fBExplanation of the keys in the ODB /Custom/images subtree\fP 
.PP

.IP "          \(bu" 12
\fBMapping active areas onto the image\fP 
.PD 0

.IP "            \(bu" 14
\fBImage Map demo\fP 
.IP "            \(bu" 14
\fBArea map with password check\fP 
.PP

.IP "          \(bu" 12
\fBDisplay mouse position\fP 
.IP "          \(bu" 12
\fBSuperimposing Labels, Bars and Fills onto an image\fP 
.PD 0

.IP "            \(bu" 14
\fBLabels superimposed on an Image\fP 
.IP "            \(bu" 14
\fBExplanation of the keys in the /Custom/images/Labels ODB subtree\fP 
.IP "            \(bu" 14
\fBBars superimposed on an Image\fP 
.IP "            \(bu" 14
\fBExplanation of the keys in the /Custom/Images/Bars ODB subtree\fP 
.PP

.IP "          \(bu" 12
\fBFills superimposed on an Image\fP 
.PD 0

.IP "            \(bu" 14
\fBCreate the custom Fills keys\fP 
.IP "            \(bu" 14
\fBExplanation of the keys in the /Custom/images/fills ODB subtree\fP 
.PD 0

.IP "              \(bu" 16
\fBfills/SRC: Logical calculation\fP 
.PP

.PP

.IP "          \(bu" 12
\fBEdit boxes floating on top of a graphic\fP 
.PD 0

.IP "            \(bu" 14
\fBPassword protection of Edit Boxes\fP 
.PP

.IP "          \(bu" 12
\fBDemo of custom image page\fP 
.IP "          \(bu" 12
\fBInternal custom page\fP 
.PP

.IP "        \(bu" 10
\fBCustom Status page\fP 
.PD 0

.IP "          \(bu" 12
\fBToggle between Default and Custom Status pages\fP 
.PP

.PP

.PP

.PP

.PP

.br
 
.IP "\(bu" 2
\fBMonitoring the Experiment\fP 
.PD 0

.IP "  \(bu" 4
\fBmstat - monitor application display\fP 
.IP "  \(bu" 4
\fBmdump - displays event bank contents (online or offline)\fP 
.PD 0

.IP "    \(bu" 6
\fBExample 1 mdump in offline mode\fP 
.IP "    \(bu" 6
\fBExample 2 : mdump in online mode\fP 
.PP

.IP "  \(bu" 4
\fBrmidas - ROOT Midas application for histograms/run control\fP 
.IP "  \(bu" 4
\fBhvedit - High Voltage editor and GUI\fP 
.PP

.br
 
.IP "\(bu" 2
\fBCustomizing the Experiment\fP 
.PD 0

.IP "  \(bu" 4
\fBIntroduction\fP 
.IP "  \(bu" 4
\fBThe ODB /Experiment tree\fP 
.PD 0

.IP "    \(bu" 6
\fBExplanation of the keys in the ODB /Experiment tree\fP 
.IP "    \(bu" 6
\fBExample of an ODB /Experiment tree with optional subdirectories\fP 
.IP "    \(bu" 6
\fBCustomizing parameters under the ODB /Experiment tree\fP 
.PD 0

.IP "      \(bu" 8
\fBDefining Edit-on-start Parameters\fP 
.PD 0

.IP "        \(bu" 10
\fBParameter Comments subdirectory\fP 
.IP "        \(bu" 10
\fBRun Parameters subdirectory\fP 
.PP

.IP "      \(bu" 8
\fBLock when Running\fP 
.IP "      \(bu" 8
\fBAccess Control (Security) using the ODB\fP 
.PD 0

.IP "        \(bu" 10
\fBHow to Setup Client Access Restrictions\fP 
.IP "        \(bu" 10
\fBAllowed Hosts\fP 
.IP "        \(bu" 10
\fBAllowed programs\fP 
.PP

.IP "      \(bu" 8
\fBHow to Setup Web Access Restriction\fP 
.PD 0

.IP "        \(bu" 10
\fBWeb Password\fP 
.PP

.IP "      \(bu" 8
\fBExamples of Access Control using the ODB Security subtree\fP 
.PD 0

.IP "        \(bu" 10
\fBExample of Full access control setup for an experiment\fP 
.IP "        \(bu" 10
\fBExample of Web-Only access control setup for an experiment\fP 
.PP

.IP "      \(bu" 8
\fBTo Remove Access Restrictions\fP 
.PP

.PP

.IP "  \(bu" 4
\fBCustomize the scripts that start up and shut down the clients.\fP 
.PD 0

.IP "    \(bu" 6
\fBExample of a start-all script\fP 
.IP "    \(bu" 6
\fBExample of a kill-all script\fP 
.PP

.IP "  \(bu" 4
\fBmserver - MIDAS Remote server\fP 
.PD 0

.IP "    \(bu" 6
\fBmserver arguments\fP 
.PP

.IP "  \(bu" 4
\fBThe ODB /Programs tree\fP 
.PD 0

.IP "    \(bu" 6
\fBThe ODB /Programs/<client> subtree\fP 
.IP "    \(bu" 6
\fBCustomize the ODB /Programs tree\fP 
.PP

.IP "  \(bu" 4
\fBMIDAS Alarm System\fP 
.PD 0

.IP "    \(bu" 6
\fBODB /Alarms Tree\fP 
.PD 0

.IP "      \(bu" 8
\fBEvaluated Alarm conditions\fP 
.IP "      \(bu" 8
\fBMeaning of the keys in the /Alarms ODB tree\fP 
.IP "      \(bu" 8
\fBExamples of an /Alarms tree\fP 
.PP

.PP

.IP "  \(bu" 4
\fBAlarm triggers Email or SMS alerts\fP 
.IP "  \(bu" 4
\fBImplementation of the MIDAS Alarm System\fP 
.PP

.br
 
.IP "\(bu" 2
\fBEvent Notification (Hot-Link)\fP 
.PD 0

.IP "  \(bu" 4
\fBIntroduction\fP 
.IP "  \(bu" 4
\fBHow to set up a Hot-Link\fP 
.PP

.PP
 
.br

.br

.br
F
.br
r
.br
o
.br
n
.br
t
.br
e
.br
n
.br
d
.br
 
.br
O
.br
p
.br
e
.br
r
.br
a
.br
t
.br
i
.br
o
.br
n
.br
 
.br
 
.br

.br

.br
F
.br
r
.br
o
.br
n
.br
t
.br
e
.br
n
.br
d
.br
 
.br
O
.br
p
.br
e
.br
r
.br
a
.br
t
.br
i
.br
o
.br
n
.br
 
.br
 
.br

.br

.br
F
.br
r
.br
o
.br
n
.br
t
.br
e
.br
n
.br
d
.br
 
.br
O
.br
p
.br
e
.br
r
.br
a
.br
t
.br
i
.br
o
.br
n
.br
 
.br
 
.br

.br

.br
F
.br
r
.br
o
.br
n
.br
t
.br
e
.br
n
.br
d
.br
 
.br
O
.br
p
.br
e
.br
r
.br
a
.br
t
.br
i
.br
o
.br
n
.br
    
.br
 \fBSECTION 6: Frontend Operation\fP 
.PD 0

.IP "\(bu" 2
\fBIntroduction\fP 
.PD 0

.IP "  \(bu" 4
\fBFrontend Program\fP 
.IP "  \(bu" 4
\fBfrontend - MIDAS Frontend application\fP 
.IP "  \(bu" 4
\fBHardware Modules\fP 
.IP "  \(bu" 4
\fBHardware Drivers\fP 
.IP "  \(bu" 4
\fBSoftware Equipment\fP 
.IP "  \(bu" 4
\fBMultiple Equipments and Frontends\fP 
.IP "  \(bu" 4
\fBFrontend Features\fP 
.IP "  \(bu" 4
\fBData transfer from the frontend\fP 
.PD 0

.IP "    \(bu" 6
\fBOptimizing data transfer\fP 
.PP

.IP "  \(bu" 4
\fBFrontend event triggers\fP 
.IP "  \(bu" 4
\fBEvent Readout Functions\fP 
.PP

.IP "\(bu" 2
\fBEquipment List\fP 
.br
 
.IP "\(bu" 2
\fBThe ODB /Equipment tree\fP 
.PD 0

.IP "  \(bu" 4
\fBThe ODB /Equipment/<equipment-name>/Common subtree\fP 
.PD 0

.IP "    \(bu" 6
\fBHot-linked Equipment/Common parameters\fP 
.PP

.IP "  \(bu" 4
\fBThe ODB /Equipment/<equipment-name>/Variables subtree\fP 
.IP "  \(bu" 4
\fBThe ODB /Equipment/<equipment-name>/Statistics subtree\fP 
.IP "  \(bu" 4
\fBThe ODB /Equipment/<equipment-name>/Settings subtree\fP 
.PP

.br
 
.IP "\(bu" 2
\fBEquipment list for a Frontend\fP 
.PD 0

.IP "  \(bu" 4
\fBExample of equipment declaration\fP 
.IP "  \(bu" 4
\fBROOT structure definition for frontend EQUIPMENT list\fP 
.IP "  \(bu" 4
\fBEquipment Settings in ODB\fP 
.PP

.br
 
.IP "\(bu" 2
\fBExplanation of Equipment list parameters\fP 
.br
 
.IP "\(bu" 2
\fBFrontend code\fP 
.PD 0

.IP "  \(bu" 4
\fBIntroduction\fP 
.PD 0

.IP "    \(bu" 6
\fBCAMAC DAQ Event LAM Macros\fP 
.PP

.IP "  \(bu" 4
\fBFrontend Code Sections\fP 
.PD 0

.IP "    \(bu" 6
\fBInclude files\fP 
.IP "    \(bu" 6
\fBGlobal declarations\fP 
.IP "    \(bu" 6
\fBGlobal User declarations\fP 
.IP "    \(bu" 6
\fBSystem prototype functions\fP 
.IP "    \(bu" 6
\fBUser prototype functions\fP 
.PP

.IP "  \(bu" 4
\fBSequence of operations\fP 
.PD 0

.IP "    \(bu" 6
\fBReporting Equipment status\fP 
.IP "    \(bu" 6
\fBfrontend_init()\fP 
.IP "    \(bu" 6
\fBbegin_of_run\fP 
.IP "    \(bu" 6
\fBpause_run() or resume_run()\fP 
.IP "    \(bu" 6
\fBend_of_run()\fP 
.IP "    \(bu" 6
\fBfrontend_exit()\fP 
.PP

.IP "  \(bu" 4
\fBFrontend Routines associated with Equipments\fP 
.PD 0

.IP "    \(bu" 6
\fBPolled event\fP 
.IP "    \(bu" 6
\fBInterrupt event\fP 
.IP "    \(bu" 6
\fBEvent Readout routines\fP 
.PD 0

.IP "      \(bu" 8
\fBPolled or Interrupt readout routine\fP 
.IP "      \(bu" 8
\fBGeneral readout function\fP 
.IP "      \(bu" 8
\fBFragmented Event\fP 
.IP "      \(bu" 8
\fBManual Trigger\fP 
.PD 0

.IP "        \(bu" 10
\fBHow to determine if trigger was a manual trigger\fP 
.PP

.IP "      \(bu" 8
\fBEquipment declaration for manually-triggered and fragmented event\fP 
.IP "      \(bu" 8
\fBEvent size adjustments for fragmented event\fP 
.IP "      \(bu" 8
\fBReadout routine for fragmented event\fP 
.IP "      \(bu" 8
\fBA Client that Manually Triggers the Equipment\fP 
.PP

.PP

.IP "  \(bu" 4
\fBFrontend Event Notification\fP 
.PD 0

.IP "    \(bu" 6
\fBDeferred Transition\fP 
.PP

.IP "  \(bu" 4
\fBBank construction in an Event readout routine\fP 
.PD 0

.IP "    \(bu" 6
\fBFIXED format Event readout\fP 
.IP "    \(bu" 6
\fBMIDAS event construction\fP 
.PD 0

.IP "      \(bu" 8
\fBMidas Data Types\fP 
.IP "      \(bu" 8
\fBCreation of MIDAS banks\fP 
.IP "      \(bu" 8
\fBMidas Event header manipulation\fP 
.PP

.PP

.IP "  \(bu" 4
\fBSuper-Event\fP 
.PD 0

.IP "    \(bu" 6
\fBSuper-Event Example\fP 
.IP "    \(bu" 6
\fBExample Readout code for Super-Event\fP 
.PP

.IP "  \(bu" 4
\fBEvent Builder Functions\fP 
.PD 0

.IP "    \(bu" 6
\fBmevb - event builder utility\fP 
.IP "    \(bu" 6
\fBIntroduction to Event building in MIDAS\fP 
.IP "    \(bu" 6
\fBPrinciple of the Event Builder and related frontend fragment\fP 
.IP "    \(bu" 6
\fBThe ODB Event Builder Tree\fP 
.IP "    \(bu" 6
\fBEvent builder ODB Tree (version 2)\fP 
.IP "    \(bu" 6
\fBEvent Builder Operation\fP 
.PP

.IP "  \(bu" 4
\fBSlow Control System\fP 
.IP "  \(bu" 4
\fBIncrease the Event Buffer Size(s)\fP 
.IP "  \(bu" 4
\fBFrontend Appendices\fP 
.PD 0

.IP "    \(bu" 6
\fBData formats written by the frontend\fP 
.PD 0

.IP "      \(bu" 8
\fBMIDAS format\fP 
.PD 0

.IP "        \(bu" 10
\fBBank Format\fP 
.IP "        \(bu" 10
\fBFormat\fP 
.PP

.PP

.IP "    \(bu" 6
\fBSupported Hardware: MIDAS driver library\fP 
.PD 0

.IP "      \(bu" 8
\fBCAMAC drivers\fP 
.IP "      \(bu" 8
\fBVME drivers\fP 
.IP "      \(bu" 8
\fBUSB drivers\fP 
.IP "      \(bu" 8
\fBGPIB drivers\fP 
.IP "      \(bu" 8
\fBOther drivers\fP 
.PP

.IP "    \(bu" 6
\fBCAMAC and VME access function calls\fP 
.PD 0

.IP "      \(bu" 8
\fBMIDAS CAMAC standard functions\fP 
.IP "      \(bu" 8
\fBESONE CAMAC standard functions\fP 
.IP "      \(bu" 8
\fBMIDAS VME standard functions\fP 
.IP "      \(bu" 8
\fBComputer Busy Logic\fP 
.PP

.IP "    \(bu" 6
\fBHardware Access utilities\fP 
.PD 0

.IP "      \(bu" 8
\fBmcnaf - CAMAC hardware access\fP 
.IP "      \(bu" 8
\fBdio - direct I/O driver\fP 
.PP

.PP

.PP

.PP

.br
   
.br
 \fBSECTION 7: Data Analysis\fP 
.PD 0

.IP "\(bu" 2
\fBData Analyzers\fP 
.IP "\(bu" 2
\fBanalyzer - event analysis\fP 
.IP "\(bu" 2
\fBMIDAS Analyzer\fP 
.IP "\(bu" 2
\fBMultiStage Concept\fP 
.PD 0

.IP "  \(bu" 4
\fBAnalyzer parameters\fP 
.IP "  \(bu" 4
\fBAnalyzer Module parameters\fP 
.IP "  \(bu" 4
\fBAnalyzer Flow chart\fP 
.IP "  \(bu" 4
\fBHBOOK analyzer description (old doc)\fP 
.IP "  \(bu" 4
\fBOnline usage with PAW\fP 
.IP "  \(bu" 4
\fBOffline usage with PAW\fP 
.PP

.IP "\(bu" 2
\fBByte Swap Macros\fP 
.PP

.br
   
.br
 \fBSECTION 8: Performance\fP  
.br
   
.br
 \fBSECTION 9: Special Configurations\fP   
.br

.br

.br
B
.br
u
.br
i
.br
l
.br
d
.br
i
.br
n
.br
g
.br
 
.br
O
.br
p
.br
t
.br
i
.br
o
.br
n
.br
s
.br
    
.br
 \fBSECTION 10: Build Options\fP 
.PD 0

.IP "\(bu" 2
\fBIntroduction\fP 
.IP "\(bu" 2
\fBMakefile Options\fP 
.IP "\(bu" 2
\fBBuilding Options\fP 
.PD 0

.IP "  \(bu" 4
\fBUSERFLAGS\fP 
.IP "  \(bu" 4
\fBHAVE_ROOT\fP 
.IP "  \(bu" 4
\fBHAVE_HBOOK\fP 
.IP "  \(bu" 4
\fBNEED_MYSQL\fP 
.IP "  \(bu" 4
\fBHAVE_ODBC\fP 
.IP "  \(bu" 4
\fBHAVE_CAMAC\fP 
.IP "  \(bu" 4
\fBMIDAS_MAX_EVENT_SIZE\fP 
.IP "  \(bu" 4
\fBSPECIFIC_OS_PRG\fP 
.IP "  \(bu" 4
\fBNEED_LIBROOTA\fP 
.IP "  \(bu" 4
\fBNEED_ZLIB\fP 
.IP "  \(bu" 4
\fBNEED_RPATH\fP 
.IP "  \(bu" 4
\fBNEED_STRLCPY\fP 
.PP

.IP "\(bu" 2
\fBEnvironment variables\fP 
.PD 0

.IP "  \(bu" 4
\fBMIDASSYS\fP 
.IP "  \(bu" 4
\fBMIDAS_EXPTAB\fP 
.IP "  \(bu" 4
\fBMIDAS_SERVER_HOST\fP 
.IP "  \(bu" 4
\fBMIDAS_EXPT_NAME\fP 
.IP "  \(bu" 4
\fBMIDAS_DIR\fP 
.IP "  \(bu" 4
\fBROOTSYS\fP 
.IP "  \(bu" 4
\fBCERNLIB_PACK\fP 
.IP "  \(bu" 4
\fBMIDAS_FRONTEND_INDEX\fP 
.IP "  \(bu" 4
\fBMCHART_DIR\fP 
.PP

.PP
 
.br

.br

.br
N
.br
e
.br
w
.br
 
.br
F
.br
e
.br
a
.br
t
.br
u
.br
r
.br
e
.br
s
.br
    
.br
 \fBSECTION 11 New Features\fP 
.PD 0

.IP "\(bu" 2
\fBGeneral Information\fP 
.PD 0

.IP "  \(bu" 4
\fBNote on MIDAS Versions\fP 
.PP

.IP "\(bu" 2
\fBNew Documented Features\fP 
.PD 0

.IP "  \(bu" 4
\fBSep 2010\fP 
.IP "  \(bu" 4
\fBMay 2010\fP 
.IP "  \(bu" 4
\fBJan 2010\fP 
.IP "  \(bu" 4
\fBDec 2009\fP 
.IP "  \(bu" 4
\fBNov 2009\fP 
.IP "  \(bu" 4
\fBSep 2009\fP 
.IP "  \(bu" 4
\fBJun 2009\fP 
.IP "  \(bu" 4
\fBJan 2009\fP 
.IP "  \(bu" 4
\fBFeb 2008\fP 
.PP

.PP

.br
   
.br
 \fBSECTION 12: Frequently Asked Questions\fP 
.PD 0

.IP "\(bu" 2
\fBGeneral questions\fP 
.IP "\(bu" 2
\fBQuestions about custom web pages\fP 
.IP "\(bu" 2
\fBQuestions about CAMAC\fP 
.PP

.br
   
.br
 \fBSECTION 13: Document Navigation and Convention\fP 
.PD 0

.IP "\(bu" 2
\fBNavigating this document\fP 
.IP "\(bu" 2
\fBDocument Style\fP 
.PP

.br
   
.br
 \fBSECTION 15: Alphabetical Index to Documentation\fP 
.br

.br
  \fBSECTION 15: MIDAS Manual Contents\fP  
.PD 0

.IP "\(bu" 2
\fBList of Sections in the Midas Manual\fP 
.IP "\(bu" 2
\fBList of contents of each Section\fP 
.PP

.br
   
.br
 
