.TH "The odb.c" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
The odb.c \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBMidas ODB Functions (db_xxx)\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
dox 
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
