.TH "Organization" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Organization \- SECTION 15: MIDAS Manual Contents 
 
.br

.br
.SH "List of Sections in the Midas Manual"
.PP
This manual is divided into the \fBsections\fP listed in the following table:
.PP
.PP
List of Manual Sections  Links to Start of Section Links to Section Index  
.PD 0

.IP "\(bu" 2
\fBSECTION 1: Main\fP 
.IP "\(bu" 2
\fBSECTION 2: Introduction\fP 
.IP "\(bu" 2
\fBSECTION 3: Quick Start\fP 
.IP "\(bu" 2
\fBSECTION 4: Features\fP 
.IP "\(bu" 2
\fBSECTION 5: Run Control\fP 
.IP "\(bu" 2
\fBSECTION 6: Frontend Operation\fP 
.IP "\(bu" 2
\fBSECTION 7: Data Analysis\fP 
.IP "\(bu" 2
\fBSECTION 8: Performance\fP 
.IP "\(bu" 2
\fBSECTION 9: Special Configurations\fP 
.IP "\(bu" 2
\fBSECTION 10: Build Options\fP 
.IP "\(bu" 2
\fBSECTION 11 New Features\fP 
.IP "\(bu" 2
\fBSECTION 12: Frequently Asked Questions\fP 
.IP "\(bu" 2
\fBSECTION 13: Document Navigation and Convention\fP 
.IP "\(bu" 2
\fBSECTION 15: Alphabetical Index to Documentation\fP  
.PP
.PD 0
.IP "\(bu" 2
\fBMain index\fP 
.IP "\(bu" 2
\fBIntro index\fP 
.IP "\(bu" 2
\fBQuick Start index\fP 
.IP "\(bu" 2
\fBFeatures index\fP 
.IP "\(bu" 2
\fBRun Control index\fP 
.IP "\(bu" 2
\fBFrontend Operation index\fP 
.IP "\(bu" 2
\fBData Analysis index\fP 
.IP "\(bu" 2
\fBPerformance index\fP 
.IP "\(bu" 2
\fBSpecial Configurations index\fP 
.IP "\(bu" 2
\fBBuild Options index\fP 
.IP "\(bu" 2
\fBNew Features index\fP 
.IP "\(bu" 2
\fBFrequently Asked Questions index\fP 
.IP "\(bu" 2
\fBConvention index\fP 
.IP "\(bu" 2
\fBAlphabetical index\fP 
.IP "\(bu" 2
\fBManual Contents index\fP 
.PP

.br
 
.PD 0

.IP "\(bu" 2
Each \fB section \fP contains at least one \fB page\fP; most contain multiple pages. 
.IP "\(bu" 2
\fBNavigation icons\fP are located at the top and bottom of each page. 
.IP "\(bu" 2
\fBPage List\fP 
.PP
  
.br
 
