.TH "parameters" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parameters \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 60 of file vppg.h.
.SH "Field Documentation"
.PP 
.SS "unsigned long \fBparameters::branch_addr\fP"
.PP
Definition at line 63 of file vppg.h.
.PP
Referenced by byteOutputOrder(), lineRead(), and VPPGLoad().
.SS "char \fBparameters::branch_width\fP"
.PP
Definition at line 67 of file vppg.h.
.PP
Referenced by VPPGLoad().
.SS "unsigned long \fBparameters::delay\fP"
.PP
Definition at line 64 of file vppg.h.
.PP
Referenced by byteOutputOrder(), lineRead(), and VPPGLoad().
.SS "char \fBparameters::delay_width\fP"
.PP
Definition at line 68 of file vppg.h.
.PP
Referenced by VPPGLoad().
.SS "char \fBparameters::flag_width\fP"
.PP
Definition at line 69 of file vppg.h.
.PP
Referenced by VPPGLoad().
.SS "unsigned long \fBparameters::flags\fP"
.PP
Definition at line 65 of file vppg.h.
.PP
Referenced by byteOutputOrder(), lineRead(), and VPPGLoad().
.SS "unsigned char \fBparameters::opcode\fP"
.PP
Definition at line 62 of file vppg.h.
.PP
Referenced by byteOutputOrder(), lineRead(), and VPPGLoad().
.SS "char \fBparameters::opcode_width\fP"
.PP
Definition at line 66 of file vppg.h.
.PP
Referenced by VPPGLoad().

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
