.TH "PROGRAM_INFO" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PROGRAM_INFO \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Program information structure 
.PP
Definition at line 1280 of file midas.h.
.SH "Field Documentation"
.PP 
.SS "char \fBPROGRAM_INFO::alarm_class\fP[32]"
.PP
Definition at line 1288 of file midas.h.
.PP
Referenced by al_check().
.SS "\fBBOOL\fP \fBPROGRAM_INFO::auto_restart\fP"
.PP
Definition at line 1287 of file midas.h.
.PP
Referenced by al_check().
.SS "\fBBOOL\fP \fBPROGRAM_INFO::auto_start\fP"
.PP
Definition at line 1285 of file midas.h.
.PP
Referenced by cm_transition1().
.SS "\fBBOOL\fP \fBPROGRAM_INFO::auto_stop\fP"
.PP
Definition at line 1286 of file midas.h.
.PP
Referenced by cm_transition1().
.SS "\fBDWORD\fP \fBPROGRAM_INFO::check_interval\fP"
.PP
Definition at line 1283 of file midas.h.
.PP
Referenced by al_check().
.SS "\fBDWORD\fP \fBPROGRAM_INFO::first_failed\fP"
.PP
Definition at line 1289 of file midas.h.
.PP
Referenced by al_check().
.SS "\fBBOOL\fP \fBPROGRAM_INFO::required\fP"
.PP
Definition at line 1281 of file midas.h.
.SS "char \fBPROGRAM_INFO::start_command\fP[256]"
.PP
Definition at line 1284 of file midas.h.
.PP
Referenced by al_check(), and cm_transition1().
.SS "\fBINT\fP \fBPROGRAM_INFO::watchdog_timeout\fP"
.PP
Definition at line 1282 of file midas.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
