.TH "Quickstart" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Quickstart \- SECTION 3: Quick Start 

.br
 
.PP

.br
.SH "Introduction"
.PP
\fB This page is under revision to better reflect the latest installation and basic operation of the \fBMIDAS package\fP. \fP
.PP
These pages contain a step-by-step description of the installation procedure of the MIDAS package on several platforms, as well as the procedure to run a demo sample experiment. Once this is successful, the frontend or the analyzer can be moved to another computer to test the remote connection capability.
.SH "MIDAS Package Source (SVN and tarball)"
.PP
The \fBMIDAS source code\fP is subject to the \fCGPL\fP
.PP
An \fConline SVN web site \fP is available for the latest developments and for easy download. See specific instructions under \fBLinux\fP or \fBWindows\fP.
.PP
The MIDAS Package source (tarball) and some binaries are also kept in \fCPSI \fP or at \fCTRIUMF \fP.
.SH "MIDAS Installation"
.PP
Even though MIDAS is available for multiple platforms, presently only instructions for the following are available:  
.PD 0

.IP "1." 4
\fBMIDAS Linux Installation\fP 
.IP "2." 4
\fBMIDAS Windows Installation\fP 
.PP
.PP

.br
 
.PP
 
