.TH "RC_BNMQR_status" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RC_BNMQR_status \- Custom Status Pages for experiments BNMR and BNQR 

.br
 
.PP
The webpages shown below replace the MIDAS default status pages for the BNMR and BNQR experiments at TRIUMF. A single file (custom_status.html) is used for the custom status pages of both experiments. The colours are different to avoid confusion, since the two experiments may be run simultaneously with the main status page of each displayed on two adjacent consoles. Javascript is used extensively in the .html file. Colours are used to indicate the status of various \fBparameters\fP. Both Custom buttons and the regular buttons (Stop, Status, Messages etc.) are used.
.PP
In the image below the BNMR experiment is \fBrunning\fP, while the BNQR experiment is \fBstopped\fP. Note that with the BNQR run stopped, various PPG Mode buttons appear which are not available when running (compare with BNMR). These buttons allow the user to select the experimental mode. Various alias links allow the user to quickly access experimental \fBparameters\fP.
.PP
 Custom Status Page for the BNMR experiment at TRIUMF  
.br

.br
 Custom Status Page for the BNQR experiment at TRIUMF  
.PP

.br
.PP
.PP

.br
  
