.TH "RC_Ebit_custom_page" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RC_Ebit_custom_page \- Custom Pages for Ebit Experiment 

.br
.PP
.PP

.br
.PP
The following two custom pages are from the EBIT experiment at TRIUMF. They allow the experimenters easy access to the \fBparameters\fP for the TRIUMF Pulse Programmer (PPG) (i.e. pulse width, offset etc.) used to control the experiment.
.PP
Several different modes are available (each with its own custom page). Two of the custom pages are shown, for modes 1c and 1e. The experimenters change modes by clicking one of the customscript buttons (1a...1e). The mode script automatically loads a different set of \fBparameters\fP and a different custom page.
.PP
In the first example, the PPG \fBparameters\fP are changed by clicking on the links on the image. Each value is linked to a parameter in the ODB. Each line on the image represents an output from the Pulse Programmer. The x-axis ( \fBnot\fP to scale) represents the time from when the cycle is started (T0). The boxes on the left allow the polarity of the output signal to be reversed. 
.br
  EBIT experiment custom page (Mode 1c)
.br

.br
   
.br

.br
.PP
For the simplest mode (1e) a timing diagram is not necessary, and a table is used instead. To change the \fBparameters\fP the experimenters click on the links in the table. 
.br

.br
  EBIT experiment custom page (Mode 1e)
.br

.br
  
.PP

.br

.br
.PP
.PP

.br
  
