.TH "RC_mhttpd_Message_page" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RC_mhttpd_Message_page \- Message page 
 
.br
.PP
.PP

.br
.PP
This page (accessed by clicking the \fBMessage button\fP \fBif present\fP on the \fBmain status page\fP ) displays the contents of the MIDAS System log file in blocks of 100 lines starting with the most recent messages. The MIDAS log file resides in the directory defined \fBin the ODB\fP.
.PP

.br

.br

.br
   Message page. 
.br

.br

.br
   
.br

.br

.br
.PP

.br
.PP
.PP

.br
  
