.TH "RC_mhttpd_Logger_page" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RC_mhttpd_Logger_page \- mhttpd Logger page 
 
.br
.PP
.SH "mlogger settings information"
.PP
Provided the MIDAS logger \fBmlogger\fP is running, the mhttpd main status page shows logger information and statistics. 
.br
.PP
mlogger channel information is displayed by clicking on a mlogger channel hyperlink on the mhttpd main status page (see \fBbelow\fP). The subtree /Logger/Channels/<channel-number>/Settings is shown. See \fBmlogger\fP for more information. In the example below, only one mlogger channel is defined (channel 0). If multiple logging channels are active, additional hyperlinks will be present on the main status page. 
.br
   mlogger channel information on mhttpd main status page 
.br

.br

.br
   
.br
.PP

.br
.PP

.br
.SH "lazylogger settings information"
.PP
Provided the MIDAS lazylogger \fBlazylogger\fP is running, the mhttpd \fBmain status page\fP shows lazylogger information and statistics. 
.br
.PP
Lazylogger settings information is displayed by clicking on a lazylogger Label hyperlink on the mhttpd main status page (see \fBabove\fP). The subtree /Lazy/<label>/Settings is shown. See \fBlazylogger\fP for more information.
.PP
  
