.TH "RC_mhttpd_status_page_redesign" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RC_mhttpd_status_page_redesign \- Redesign of mhttpd Main Status Page 
.PP
.PP

.br
   The appearance of the Main Status Page has been changed (in versions after to \fBDec 2009\fP) . 
.PD 0

.IP "\(bu" 2
the \fB'Analyzed'\fP column has been dropped 
.IP "\(bu" 2
the \fB'FE Node'\fP column is now labelled \fB'Status'\fP and may show equipment status information 
.IP "\(bu" 2
the user-defined \fBalias\fP, \fBscript\fP and 'custom' hyperlinks now appear as \fBbuttons\fP 
.IP "\(bu" 2
there are now four different background colors (\fBJan 2010\fP) for the four rows of buttons, i.e. : 
.PD 0

.IP "  \(bu" 4
Main menu buttons, 
.IP "  \(bu" 4
Script buttons, 
.IP "  \(bu" 4
Manually triggered events, 
.IP "  \(bu" 4
Alias & Custom page buttons. 
.PP
.PP
This change has been made because the original alias hyperlinks were hard to read if they included spaces. It also gives a more homogeneous look to the page. A status page of the new format is shown here. 
.PP
.PP

.br
  New format Status page showing four rows of buttons 
.br

.br

.br
   
.br

.br

.br
.PP
  Prior to \fBDec 2009\fP  the Custom Page and Alias hyperlinks appeared as \fBlinks\fP rather than buttons, as shown below: 
.br

.br

.br
  Older version of mhttpd main Status page showing Custom Page and Alias \fBLinks\fP   
.br

.br

.br
.PP
.PP
 
.br
 
