.TH "RC_mhttpd_CNAF_page" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RC_mhttpd_CNAF_page \- CAMAC Access page 
 
.br
.PP
.PP

.br
  By default, the CNAF page has been replaced by the MSCB Page (\fBDec 2009\fP) 
.PP

.br
 The CNAF page is accessed by clicking on the \fBCNAF button\fP (\fBif present\fP) on the Main Status page. 
.br
 It will only be active if one of the active equipments is a CAMAC-based data collector, it will be possible to remotely access CAMAC through this web-based CAMAC page, in which case the frontend is acting as a RPC CAMAC server for the request. 
.br
 The status of the connection is displayed in the top right hand side corner of the window.
.PP

.br

.br

.br
   CAMAC command pages. 
.br

.br

.br
   
.br

.br

.br
.PP

.br
.PP
.PP

.br
.PP
 
