.TH "RC_mhttpd_Main_Status_page" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RC_mhttpd_Main_Status_page \- Main Status Page 
.PP

.br
.PP
 
.br
.PP
 
.SH "Status Page for a Running Experiment"
.PP
The following image shows the main Status Page of one of the experiments at TRIUMF:
.PP
 MIDAS Status Page for a running experiment 
.br

.br

.br
   
.br
.PP
In this case, the experiment has been customized by
.IP "\(bu" 2
creating and starting some frontend(s), which define various equipment(s)
.IP "\(bu" 2
defining 'script' and 'alias' buttons
.IP "\(bu" 2
starting some of the MIDAS utilities (e.g. the MIDAS logger \fBmlogger\fP and the \fBlazylogger\fP )
.PP
.PP
Compared with the \fBminimal status page\fP (where no clients are running) it's clear that the the Status Page above shows a lot more information.
.PP
The main status page will be discussed line-by-line in the following section ( \fBFeatures of the Main Status Page\fP ).
.PP
.IP "\(bu" 2
\fBFeatures of the Main Status Page\fP
.IP "\(bu" 2
\fBRedesign of mhttpd Main Status Page\fP
.PP
.PP
.PP
 
