.TH "RC_mhttpd_History_page" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RC_mhttpd_History_page \- History page 
 
.br
.PP
.PP

.br
 The \fBHistory\fP page is displayed by clicking on the \fBHistory\fP \fBButton\fP on the \fBMain Status Page\fP ( \fBif present\fP).
.PP
This page reflects the \fBHistory System\fP settings.
.PP
It lists on the top of the page the possible group names containing a list of panels defined in the ODB. Next a series of buttons defines the time scale of the graph with predefined time window, \fB '<<','<' '+' '-' '>' '>>' \fP buttons permit the shifting of the graph in the time direction. Other buttons will allow graph resizing, Elog attachment creation, configuration of the panel and custom time frame graph display. By default a single group is created 'Default' containing the trigger rate for the 'Trigger' equipment.
.PP
The configuration options for a given panel consists in:
.IP "\(bu" 2
Zooming capability, run markers, logarithmic scale.
.IP "\(bu" 2
Data query in time.
.IP "\(bu" 2
Time scale in date format.
.IP "\(bu" 2
Web based page creation (button labelled 'New') for up to 10 history channels per page.
.PP
.PP

.br

.br

.br
   History page. 
.br

.br

.br
   
.br

.br

.br
.PP

.br

.br

.br
   History channel selection Page. 
.br

.br

.br
   
.br

.br

.br
.PP

.br
.PP
.PP

.br
  
