.TH "RC_MEG_Gas_Page" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RC_MEG_Gas_Page \- Custom Page for MEG gas system 

.br
.PP
.PP

.br
.PP
This page from the MEG experiment at PSI shows a complex gas system. This shows the use of 'fills' and 'labels'. 
.br
 The valves are represented as green circles. If they are clicked, they close and become red (provided the user successfully supplied the correct password). 
.br
  MEG gas system   
.br
.PP
.PP

.br
  
