.TH "RC_Mpet_custom_page" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RC_Mpet_custom_page \- Mpet Optics Custom Page 

.br
.PP
.PP

.br
.PP
This page shows the optics for the Mpet experiment at TRIUMF displaying the Lorenz steerer \fBparameters\fP.
.PP
  
.PP

.br
.PP
.PP

.br
  
