.TH "RC_mhttpd_custom_RPC_access" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RC_mhttpd_custom_RPC_access \- ODB RPC access 
.PP

.br
.PP
 RPC access has been available from custom webpages since \fBJan 2009\fP . 
.PP
The \fBJavaScript library function\fP \fBODBRpc\fP is defined for RPC access (the library must be \fBincluded\fP) : This permits buttons on MIDAS 'custom' web pages to invoke RPC calls directly into user frontend programs, for example to turn hardware modules on or off.
.PP
\fBTodo\fP
.RS 4
Documentation and examples needed - ODBRpc
.RE
.PP

.br
 JavaScript Function  Purpose  Parameters  
.PP
.PP
.nf
 ODBRpc_rev0(name, rpc, args)
.fi
.PP
  to be filled  name 
.br
  
.PP
rpc 
.br
   args 
.br
   Above: ODB RPC access from JavaScript 
.PP
.PP

.br
  
