.TH "RC_odbedit" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RC_odbedit \- odbedit: The ODB Editor and Run Control utility 

.br
 
.PP

.br
.PP
The \fBodbedit utility\fP is both an \fBOnline Database (ODB)\fP Editor and a \fBRun Control\fP program. 
.br
 This is one of the main applications to interact with the different components of the MIDAS system. It is a simpler alternative to the web-based run control program \fBmhttpd\fP. There are many occasions where \fBodbedit\fP is more convenient and faster to use than mhttpd. \fBodbedit\fP is used to create the initial ODB, and is a powerful editing tool. It is often used for debugging and troubleshooting. 
.br
.PP
.IP "\(bu" 2
\fBodbedit - ODB Editor and run control utility\fP
.IP "\(bu" 2
\fBodbedit command list\fP
.IP "\(bu" 2
\fBUsing odbedit\fP
.PP
.PP

.br
 
.PP

.br
  
