.TH "RC_T2K_Gas_Page" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RC_T2K_Gas_Page \- Custom Pages designed for T2K gas system 

.br
.PP
.PP

.br
.SH "Example custom page: pop-up window, clickable boxes"
.PP
Clicking on one of the valves produces a pop-up window (a flow-control valve A0FC2 is shown), allowing the set value for the flow rate to be changed, and the valve to be opened or closed. Navigation between the more than 20 different pages of this large gas system is done by clicking on one of the blue boxes. The pop-up windows are made using javascript. 'Fills' are used to change the colour of the valves, and 'Labels' are used to display the values of various \fBparameters\fP.
.PP
 T2K Gas System: Gas Analyzer Page showing popup
.br
  
.PP

.br
 
.br
 
.SH "Example custom page: hidden alias keys"
.PP
The following image illustrates the use of hidden alias keys to load webpages from a clickable image map.
.PP
 Custom pages written for the T2K experiment   
.br
 
.PP

.br
  
