.TH "RECORD_LIST" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RECORD_LIST \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 405 of file msystem.h.
.SH "Field Documentation"
.PP 
.SS "\fBWORD\fP \fBRECORD_LIST::access_mode\fP"
.PP
Definition at line 408 of file msystem.h.
.PP
Referenced by db_open_record().
.SS "\fBINT\fP \fBRECORD_LIST::buf_size\fP"
.PP
Definition at line 411 of file msystem.h.
.PP
Referenced by db_open_record(), and db_update_record().
.SS "void* \fBRECORD_LIST::copy\fP"
.PP
Definition at line 410 of file msystem.h.
.PP
Referenced by db_open_record().
.SS "void* \fBRECORD_LIST::data\fP"
.PP
Definition at line 409 of file msystem.h.
.PP
Referenced by db_open_record().
.SS "void(* \fBRECORD_LIST::dispatcher\fP)(\fBINT\fP, \fBINT\fP, void *)"
.PP
Referenced by db_open_record(), and db_update_record().
.SS "HNDLE \fBRECORD_LIST::handle\fP"
.PP
Definition at line 406 of file msystem.h.
.PP
Referenced by db_open_record().
.SS "HNDLE \fBRECORD_LIST::hDB\fP"
.PP
Definition at line 407 of file msystem.h.
.PP
Referenced by db_open_record().
.SS "void* \fBRECORD_LIST::info\fP"
.PP
Definition at line 413 of file msystem.h.
.PP
Referenced by db_open_record().

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
