.TH "REQUEST_LIST" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
REQUEST_LIST \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 419 of file msystem.h.
.SH "Field Documentation"
.PP 
.SS "\fBINT\fP \fBREQUEST_LIST::buffer_handle\fP"
.PP
Definition at line 420 of file msystem.h.
.PP
Referenced by bm_request_event().
.SS "void(* \fBREQUEST_LIST::dispatcher\fP)(HNDLE, HNDLE, \fBEVENT_HEADER\fP *, void *)"
.PP
Referenced by bm_dispatch_event(), and bm_request_event().
.SS "short int \fBREQUEST_LIST::event_id\fP"
.PP
Definition at line 421 of file msystem.h.
.PP
Referenced by bm_request_event().
.SS "short int \fBREQUEST_LIST::trigger_mask\fP"
.PP
Definition at line 422 of file msystem.h.
.PP
Referenced by bm_request_event().

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
