.TH "SCALER_COMMON" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SCALER_COMMON \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 178 of file experim.h.
.SH "Field Documentation"
.PP 
.SS "char \fBSCALER_COMMON::buffer\fP[32]"
.PP
Definition at line 181 of file experim.h.
.SS "\fBBOOL\fP \fBSCALER_COMMON::enabled\fP"
.PP
Definition at line 185 of file experim.h.
.SS "\fBWORD\fP \fBSCALER_COMMON::event_id\fP"
.PP
Definition at line 179 of file experim.h.
.SS "double \fBSCALER_COMMON::event_limit\fP"
.PP
Definition at line 188 of file experim.h.
.SS "char \fBSCALER_COMMON::format\fP[8]"
.PP
Definition at line 184 of file experim.h.
.SS "char \fBSCALER_COMMON::frontend_file_name\fP[256]"
.PP
Definition at line 193 of file experim.h.
.SS "char \fBSCALER_COMMON::frontend_host\fP[32]"
.PP
Definition at line 191 of file experim.h.
.SS "char \fBSCALER_COMMON::frontend_name\fP[32]"
.PP
Definition at line 192 of file experim.h.
.SS "\fBINT\fP \fBSCALER_COMMON::log_history\fP"
.PP
Definition at line 190 of file experim.h.
.SS "\fBDWORD\fP \fBSCALER_COMMON::num_subevents\fP"
.PP
Definition at line 189 of file experim.h.
.SS "\fBINT\fP \fBSCALER_COMMON::period\fP"
.PP
Definition at line 187 of file experim.h.
.SS "\fBINT\fP \fBSCALER_COMMON::read_on\fP"
.PP
Definition at line 186 of file experim.h.
.SS "\fBINT\fP \fBSCALER_COMMON::source\fP"
.PP
Definition at line 183 of file experim.h.
.SS "\fBWORD\fP \fBSCALER_COMMON::trigger_mask\fP"
.PP
Definition at line 180 of file experim.h.
.SS "\fBINT\fP \fBSCALER_COMMON::type\fP"
.PP
Definition at line 182 of file experim.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
