.TH "sis3820.h" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sis3820.h \- 
.SH SYNOPSIS
.br
.PP
.SH "Define Documentation"
.PP 
.SS "#define CTRL_COUNTER_TEST_25MHZ_DISABLE   0x100000"
.PP
Definition at line 145 of file sis3820.h.
.SS "#define CTRL_COUNTER_TEST_25MHZ_ENABLE   0x10"
.PP
Definition at line 146 of file sis3820.h.
.SS "#define CTRL_COUNTER_TEST_MODE_DISABLE   0x200000"
.PP
Definition at line 148 of file sis3820.h.
.SS "#define CTRL_COUNTER_TEST_MODE_ENABLE   0x20"
.PP
Definition at line 149 of file sis3820.h.
.SS "#define CTRL_REFERENCE_CH1_DISABLE   0x400000"
.PP
Definition at line 151 of file sis3820.h.
.SS "#define CTRL_REFERENCE_CH1_ENABLE   0x40"
.PP
Definition at line 152 of file sis3820.h.
.SS "#define CTRL_USER_LED_OFF   0x10000"
.PP
Definition at line 142 of file sis3820.h.
.SS "#define CTRL_USER_LED_ON   0x1"
.PP
Definition at line 143 of file sis3820.h.
.SS "#define SIS3820_ACQUISITION_COUNT   0x14"
.PP
Definition at line 36 of file sis3820.h.
.SS "#define SIS3820_ACQUISITION_PRESET   0x10"
.PP
Definition at line 35 of file sis3820.h.
.SS "#define SIS3820_ACTUAL_VERSION   0x38200101"
.PP
Definition at line 91 of file sis3820.h.
.SS "#define SIS3820_ACTUAL_VERSION_38200102   0x38200102"
.PP
Definition at line 92 of file sis3820.h.
.SS "#define SIS3820_ARM_ENABLE_CHANNEL_N   0x100"
.PP
Definition at line 180 of file sis3820.h.
.SS "#define SIS3820_ARM_ENABLE_CONTROL_SIGNAL   0x000"
.PP
Definition at line 179 of file sis3820.h.
.SS "#define SIS3820_CBLT_BROADCAST_SETUP   0x30"
.PP
Definition at line 44 of file sis3820.h.
.SS "#define SIS3820_CLEARING_MODE   0x0"
.PP
Definition at line 162 of file sis3820.h.
.SS "#define SIS3820_CONTROL_INPUT_MODE0   0x00000"
.PP
Definition at line 188 of file sis3820.h.
.SS "#define SIS3820_CONTROL_INPUT_MODE1   0x10000"
.PP
Definition at line 189 of file sis3820.h.
.SS "#define SIS3820_CONTROL_INPUT_MODE2   0x20000"
.PP
Definition at line 190 of file sis3820.h.
.SS "#define SIS3820_CONTROL_INPUT_MODE3   0x30000"
.PP
Definition at line 191 of file sis3820.h.
.SS "#define SIS3820_CONTROL_INPUT_MODE4   0x40000"
.PP
Definition at line 192 of file sis3820.h.
.SS "#define SIS3820_CONTROL_INPUT_MODE5   0x50000"
.PP
Definition at line 193 of file sis3820.h.
.SS "#define SIS3820_CONTROL_INPUTS_INVERT   0x80000"
.PP
Definition at line 195 of file sis3820.h.
.SS "#define SIS3820_CONTROL_OUTPUT_MODE0   0x000000"
.PP
Definition at line 197 of file sis3820.h.
.SS "#define SIS3820_CONTROL_OUTPUT_MODE1   0x100000"
.PP
Definition at line 198 of file sis3820.h.
.SS "#define SIS3820_CONTROL_OUTPUTS_INVERT   0x800000"
.PP
Definition at line 200 of file sis3820.h.
.SS "#define SIS3820_CONTROL_STATUS   0x0"
.PP
Definition at line 30 of file sis3820.h.
.PP
Referenced by sis3820_Status().
.SS "#define SIS3820_COPY_DISABLE   0x104"
.PP
Definition at line 55 of file sis3820.h.
.SS "#define SIS3820_COUNTER_CH1   0xA00"
.PP
Definition at line 85 of file sis3820.h.
.PP
Referenced by sis3820_ScalerRead().
.SS "#define SIS3820_COUNTER_CLEAR   0x204"
.PP
Definition at line 60 of file sis3820.h.
.SS "#define SIS3820_COUNTER_INHIBIT   0x200"
.PP
Definition at line 59 of file sis3820.h.
.PP
Referenced by sis3820_Status().
.SS "#define SIS3820_COUNTER_OVERFLOW   0x208"
.PP
Definition at line 61 of file sis3820.h.
.PP
Referenced by sis3820_Status().
.SS "#define SIS3820_COUNTER_SHADOW_CH1   0x800"
.PP
Definition at line 84 of file sis3820.h.
.PP
Referenced by sis3820_ScalerRead().
.SS "#define SIS3820_FIFO_BASE   0x800000"
.PP
Definition at line 87 of file sis3820.h.
.PP
Referenced by sis3820_FifoRead().
.SS "#define SIS3820_FIFO_MODE   0x0000"
.PP
Definition at line 182 of file sis3820.h.
.SS "#define SIS3820_FIFO_WORDCOUNT_THRESHOLD   0x3C"
.PP
Definition at line 47 of file sis3820.h.
.SS "#define SIS3820_FIFO_WORDCOUNTER   0x38"
.PP
Definition at line 46 of file sis3820.h.
.PP
Referenced by sis3820_DataReady().
.SS "#define SIS3820_FLAG_SOURCE0   0x10000"
.PP
Definition at line 131 of file sis3820.h.
.SS "#define SIS3820_FLAG_SOURCE1   0x20000"
.PP
Definition at line 132 of file sis3820.h.
.SS "#define SIS3820_FLAG_SOURCE2   0x40000"
.PP
Definition at line 133 of file sis3820.h.
.SS "#define SIS3820_FLAG_SOURCE3   0x80000"
.PP
Definition at line 134 of file sis3820.h.
.SS "#define SIS3820_FLAG_SOURCE4   0x100000"
.PP
Definition at line 135 of file sis3820.h.
.SS "#define SIS3820_FLAG_SOURCE5   0x200000"
.PP
Definition at line 136 of file sis3820.h.
.SS "#define SIS3820_FLAG_SOURCE6   0x400000"
.PP
Definition at line 137 of file sis3820.h.
.SS "#define SIS3820_FLAG_SOURCE7   0x800000"
.PP
Definition at line 138 of file sis3820.h.
.SS "#define SIS3820_HISCAL_COUNT   0x44"
.PP
Definition at line 50 of file sis3820.h.
.SS "#define SIS3820_HISCAL_LAST_ACQ_COUNT   0x48"
.PP
Definition at line 51 of file sis3820.h.
.SS "#define SIS3820_HISCAL_START_PRESET   0x40"
.PP
Definition at line 49 of file sis3820.h.
.SS "#define SIS3820_HISCAL_START_SOURCE_EXTERN   0x4000"
.PP
Definition at line 186 of file sis3820.h.
.SS "#define SIS3820_HISCAL_START_SOURCE_VME   0x0000"
.PP
Definition at line 185 of file sis3820.h.
.SS "#define SIS3820_IRQ_CONFIG   0x8"
.PP
Definition at line 32 of file sis3820.h.
.SS "#define SIS3820_IRQ_CONTROL   0xC"
.PP
Definition at line 33 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE0_CLEAR   0x10000"
.PP
Definition at line 113 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE0_DISABLE   0x100"
.PP
Definition at line 104 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE0_ENABLE   0x1"
.PP
Definition at line 95 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE0_FLAG   0x1000000"
.PP
Definition at line 122 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE1_CLEAR   0x20000"
.PP
Definition at line 114 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE1_DISABLE   0x200"
.PP
Definition at line 105 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE1_ENABLE   0x2"
.PP
Definition at line 96 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE1_FLAG   0x2000000"
.PP
Definition at line 123 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE2_CLEAR   0x40000"
.PP
Definition at line 115 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE2_DISABLE   0x400"
.PP
Definition at line 106 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE2_ENABLE   0x4"
.PP
Definition at line 97 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE2_FLAG   0x4000000"
.PP
Definition at line 124 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE3_CLEAR   0x80000"
.PP
Definition at line 116 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE3_DISABLE   0x800"
.PP
Definition at line 107 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE3_ENABLE   0x8"
.PP
Definition at line 98 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE3_FLAG   0x8000000"
.PP
Definition at line 125 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE4_CLEAR   0x100000"
.PP
Definition at line 117 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE4_DISABLE   0x1000"
.PP
Definition at line 108 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE4_ENABLE   0x10"
.PP
Definition at line 99 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE4_FLAG   0x10000000"
.PP
Definition at line 126 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE5_CLEAR   0x200000"
.PP
Definition at line 118 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE5_DISABLE   0x2000"
.PP
Definition at line 109 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE5_ENABLE   0x20"
.PP
Definition at line 100 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE5_FLAG   0x20000000"
.PP
Definition at line 127 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE6_CLEAR   0x400000"
.PP
Definition at line 119 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE6_DISABLE   0x4000"
.PP
Definition at line 110 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE6_ENABLE   0x40"
.PP
Definition at line 101 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE6_FLAG   0x40000000"
.PP
Definition at line 128 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE7_CLEAR   0x800000"
.PP
Definition at line 120 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE7_DISABLE   0x8000"
.PP
Definition at line 111 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE7_ENABLE   0x80"
.PP
Definition at line 102 of file sis3820.h.
.SS "#define SIS3820_IRQ_SOURCE7_FLAG   0x80000000"
.PP
Definition at line 129 of file sis3820.h.
.SS "#define SIS3820_JTAG_CONTROL   0x314"
.PP
Definition at line 66 of file sis3820.h.
.SS "#define SIS3820_JTAG_DATA_IN   0x310"
.PP
Definition at line 67 of file sis3820.h.
.SS "#define SIS3820_JTAG_TEST   0x310"
.PP
Definition at line 65 of file sis3820.h.
.SS "#define SIS3820_KEY_COUNTER_CLEAR   0x40C"
.PP
Definition at line 72 of file sis3820.h.
.SS "#define SIS3820_KEY_HISCAL_DISABLE   0x42C"
.PP
Definition at line 82 of file sis3820.h.
.SS "#define SIS3820_KEY_HISCAL_ENABLE_LNE_ARM   0x424"
.PP
Definition at line 80 of file sis3820.h.
.SS "#define SIS3820_KEY_HISCAL_ENABLE_LNE_ENABLE   0x428"
.PP
Definition at line 81 of file sis3820.h.
.SS "#define SIS3820_KEY_HISCAL_START_PULS   0x420"
.PP
Definition at line 79 of file sis3820.h.
.SS "#define SIS3820_KEY_LNE_PULS   0x410"
.PP
Definition at line 74 of file sis3820.h.
.SS "#define SIS3820_KEY_OPERATION_ARM   0x414"
.PP
Definition at line 75 of file sis3820.h.
.SS "#define SIS3820_KEY_OPERATION_DISABLE   0x41C"
.PP
Definition at line 77 of file sis3820.h.
.SS "#define SIS3820_KEY_OPERATION_ENABLE   0x418"
.PP
Definition at line 76 of file sis3820.h.
.SS "#define SIS3820_KEY_RESET   0x400"
.PP
Definition at line 69 of file sis3820.h.
.PP
Referenced by sis3820_Reset().
.SS "#define SIS3820_KEY_SDRAM_FIFO_RESET   0x404"
.PP
Definition at line 70 of file sis3820.h.
.SS "#define SIS3820_KEY_TEST_PULS   0x408"
.PP
Definition at line 71 of file sis3820.h.
.SS "#define SIS3820_LNE_CHANNEL_SELECT   0x108"
.PP
Definition at line 56 of file sis3820.h.
.SS "#define SIS3820_LNE_PRESCALE   0x18"
.PP
Definition at line 38 of file sis3820.h.
.SS "#define SIS3820_LNE_SOURCE_CHANNEL_N   0x30"
.PP
Definition at line 176 of file sis3820.h.
.SS "#define SIS3820_LNE_SOURCE_CONTROL_SIGNAL   0x10"
.PP
Definition at line 174 of file sis3820.h.
.SS "#define SIS3820_LNE_SOURCE_INTERNAL_10MHZ   0x20"
.PP
Definition at line 175 of file sis3820.h.
.SS "#define SIS3820_LNE_SOURCE_PRESET   0x40"
.PP
Definition at line 177 of file sis3820.h.
.SS "#define SIS3820_LNE_SOURCE_VME   0x0"
.PP
Definition at line 173 of file sis3820.h.
.SS "#define SIS3820_MCS_DATA_FORMAT_16BIT   0x8"
.PP
Definition at line 167 of file sis3820.h.
.SS "#define SIS3820_MCS_DATA_FORMAT_24BIT   0x4"
.PP
Definition at line 166 of file sis3820.h.
.SS "#define SIS3820_MCS_DATA_FORMAT_32BIT   0x0"
.PP
Definition at line 165 of file sis3820.h.
.SS "#define SIS3820_MCS_DATA_FORMAT_8BIT   0xC"
.PP
Definition at line 168 of file sis3820.h.
.SS "#define SIS3820_MODID   0x4"
.PP
Definition at line 31 of file sis3820.h.
.PP
Referenced by sis3820_Status().
.SS "#define SIS3820_NON_CLEARING_MODE   0x1"
.PP
Definition at line 163 of file sis3820.h.
.SS "#define SIS3820_OP_MODE_MULTI_CHANNEL_SCALER   0x20000000"
.PP
Definition at line 203 of file sis3820.h.
.SS "#define SIS3820_OP_MODE_SCALER   0x00000000"
.PP
Definition at line 202 of file sis3820.h.
.SS "#define SIS3820_OP_MODE_VME_FIFO_WRITE   0x70000000"
.PP
Definition at line 204 of file sis3820.h.
.SS "#define SIS3820_OPERATION_MODE   0x100"
.PP
Definition at line 54 of file sis3820.h.
.PP
Referenced by sis3820_Status().
.SS "#define SIS3820_PRESET_CHANNEL_SELECT   0x10C"
.PP
Definition at line 57 of file sis3820.h.
.SS "#define SIS3820_PRESET_ENABLE_HIT   0x28"
.PP
Definition at line 42 of file sis3820.h.
.SS "#define SIS3820_PRESET_GROUP1   0x20"
.PP
Definition at line 40 of file sis3820.h.
.SS "#define SIS3820_PRESET_GROUP2   0x24"
.PP
Definition at line 41 of file sis3820.h.
.SS "#define SIS3820_PRESET_LNELATCHED_REACHED_GROUP1   0x4"
.PP
Definition at line 210 of file sis3820.h.
.SS "#define SIS3820_PRESET_LNELATCHED_REACHED_GROUP2   0x40000"
.PP
Definition at line 213 of file sis3820.h.
.SS "#define SIS3820_PRESET_REACHED_GROUP1   0x2"
.PP
Definition at line 209 of file sis3820.h.
.SS "#define SIS3820_PRESET_REACHED_GROUP2   0x20000"
.PP
Definition at line 212 of file sis3820.h.
.SS "#define SIS3820_PRESET_STATUS_ENABLE_GROUP1   0x1"
.PP
Definition at line 208 of file sis3820.h.
.SS "#define SIS3820_PRESET_STATUS_ENABLE_GROUP2   0x10000"
.PP
Definition at line 211 of file sis3820.h.
.SS "#define SIS3820_SCALER_DATA_FORMAT_24BIT   0x4"
.PP
Definition at line 171 of file sis3820.h.
.SS "#define SIS3820_SCALER_DATA_FORMAT_32BIT   0x0"
.PP
Definition at line 170 of file sis3820.h.
.SS "#define SIS3820_SDRAM_ADD_MODE   0x2000"
.PP
Definition at line 184 of file sis3820.h.
.SS "#define SIS3820_SDRAM_BASE   0x800000"
.PP
Definition at line 88 of file sis3820.h.
.SS "#define SIS3820_SDRAM_EEPROM_CTRL_STAT   0x300"
.PP
Definition at line 63 of file sis3820.h.
.SS "#define SIS3820_SDRAM_EEPROM_SCL   0x1"
.PP
Definition at line 217 of file sis3820.h.
.SS "#define SIS3820_SDRAM_EEPROM_SDA_IN   0x100"
.PP
Definition at line 221 of file sis3820.h.
.SS "#define SIS3820_SDRAM_EEPROM_SDA_OE   0x4"
.PP
Definition at line 219 of file sis3820.h.
.SS "#define SIS3820_SDRAM_EEPROM_SDA_OUT   0x2"
.PP
Definition at line 218 of file sis3820.h.
.SS "#define SIS3820_SDRAM_MODE   0x1000"
.PP
Definition at line 183 of file sis3820.h.
.SS "#define SIS3820_SDRAM_PAGE   0x34"
.PP
Definition at line 45 of file sis3820.h.
.SS "#define STAT_OPERATION_MCS_ENABLED   0x40000"
.PP
Definition at line 158 of file sis3820.h.
.SS "#define STAT_OPERATION_SCALER_ENABLED   0x10000"
.PP
Definition at line 157 of file sis3820.h.
.SS "#define STAT_OPERATION_VME_WRITE_ENABLED   0x800000"
.PP
Definition at line 159 of file sis3820.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
