.TH "sis3320.h" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sis3320.h \- 
.SH SYNOPSIS
.br
.PP
.SH "Define Documentation"
.PP 
.SS "#define EVENT_CONF_ENABLE_SAMPLE_LENGTH_STOP   0x20"
.PP
Definition at line 172 of file sis3320.h.
.PP
Referenced by sis3320_Setup().
.SS "#define EVENT_CONF_ENABLE_WRAP_PAGE_MODE   0x10"
.PP
Definition at line 173 of file sis3320.h.
.SS "#define EVENT_CONF_PAGE_SIZE_128_WRAP   0xA"
.PP
Definition at line 187 of file sis3320.h.
.SS "#define EVENT_CONF_PAGE_SIZE_16K_WRAP   0x5"
.PP
Definition at line 181 of file sis3320.h.
.SS "#define EVENT_CONF_PAGE_SIZE_16M_WRAP   0x0"
.PP
Definition at line 175 of file sis3320.h.
.SS "#define EVENT_CONF_PAGE_SIZE_1K_WRAP   0x7"
.PP
Definition at line 183 of file sis3320.h.
.SS "#define EVENT_CONF_PAGE_SIZE_1M_WRAP   0x2"
.PP
Definition at line 177 of file sis3320.h.
.SS "#define EVENT_CONF_PAGE_SIZE_256_WRAP   0x9"
.PP
Definition at line 186 of file sis3320.h.
.SS "#define EVENT_CONF_PAGE_SIZE_256K_WRAP   0x3"
.PP
Definition at line 178 of file sis3320.h.
.SS "#define EVENT_CONF_PAGE_SIZE_4K_WRAP   0x6"
.PP
Definition at line 182 of file sis3320.h.
.SS "#define EVENT_CONF_PAGE_SIZE_4M_WRAP   0x1"
.PP
Definition at line 176 of file sis3320.h.
.SS "#define EVENT_CONF_PAGE_SIZE_512_WRAP   0x8"
.PP
Definition at line 185 of file sis3320.h.
.SS "#define EVENT_CONF_PAGE_SIZE_64_WRAP   0xB"
.PP
Definition at line 188 of file sis3320.h.
.SS "#define EVENT_CONF_PAGE_SIZE_64K_WRAP   0x4"
.PP
Definition at line 180 of file sis3320.h.
.SS "#define SIS3320_ACQ_DISABLE_AUTOSTART   0x00100000"
.PP
Definition at line 168 of file sis3320.h.
.SS "#define SIS3320_ACQ_DISABLE_INTERNAL_TRIGGER   0x00400000"
.PP
Definition at line 162 of file sis3320.h.
.SS "#define SIS3320_ACQ_DISABLE_LEMO_START_STOP   0x01000000"
.PP
Definition at line 159 of file sis3320.h.
.SS "#define SIS3320_ACQ_DISABLE_MULTIEVENT   0x00200000"
.PP
Definition at line 165 of file sis3320.h.
.SS "#define SIS3320_ACQ_ENABLE_AUTOSTART   0x00000010"
.PP
Definition at line 169 of file sis3320.h.
.SS "#define SIS3320_ACQ_ENABLE_INTERNAL_TRIGGER   0x00000040"
.PP
Definition at line 163 of file sis3320.h.
.SS "#define SIS3320_ACQ_ENABLE_LEMO_START_STOP   0x00000100"
.PP
Definition at line 160 of file sis3320.h.
.PP
Referenced by sis3320_Setup().
.SS "#define SIS3320_ACQ_ENABLE_MULTIEVENT   0x00000020"
.PP
Definition at line 166 of file sis3320.h.
.SS "#define SIS3320_ACQ_SET_CLOCK_TO_100MHZ   0x60001000"
.PP
Definition at line 153 of file sis3320.h.
.SS "#define SIS3320_ACQ_SET_CLOCK_TO_200MHZ   0x70000000"
.PP
Definition at line 152 of file sis3320.h.
.PP
Referenced by sis3320_Setup().
.SS "#define SIS3320_ACQ_SET_CLOCK_TO_50MHZ   0x50002000"
.PP
Definition at line 154 of file sis3320.h.
.PP
Referenced by sis3320_Setup().
.SS "#define SIS3320_ACQ_SET_CLOCK_TO_LEMO_CLOCK_IN   0x10006000"
.PP
Definition at line 155 of file sis3320.h.
.SS "#define SIS3320_ACQ_SET_CLOCK_TO_P2_CLOCK_IN   0x00007000"
.PP
Definition at line 156 of file sis3320.h.
.SS "#define SIS3320_ACQUISTION_CONTROL   0x10"
.PP
Definition at line 32 of file sis3320.h.
.PP
Referenced by sis3320_Setup().
.SS "#define SIS3320_ACTUAL_EVENT_COUNTER   0x24"
.PP
Definition at line 37 of file sis3320.h.
.SS "#define SIS3320_ACTUAL_SAMPLE_ADDRESS_ADC1   0x02000010"
.PP
Definition at line 68 of file sis3320.h.
.SS "#define SIS3320_ACTUAL_SAMPLE_ADDRESS_ADC2   0x02000014"
.PP
Definition at line 69 of file sis3320.h.
.SS "#define SIS3320_ACTUAL_SAMPLE_ADDRESS_ADC3   0x02800010"
.PP
Definition at line 90 of file sis3320.h.
.SS "#define SIS3320_ACTUAL_SAMPLE_ADDRESS_ADC4   0x02800014"
.PP
Definition at line 91 of file sis3320.h.
.SS "#define SIS3320_ACTUAL_SAMPLE_ADDRESS_ADC5   0x03000010"
.PP
Definition at line 107 of file sis3320.h.
.SS "#define SIS3320_ACTUAL_SAMPLE_ADDRESS_ADC6   0x03000014"
.PP
Definition at line 108 of file sis3320.h.
.SS "#define SIS3320_ACTUAL_SAMPLE_ADDRESS_ADC7   0x03800010"
.PP
Definition at line 125 of file sis3320.h.
.SS "#define SIS3320_ACTUAL_SAMPLE_ADDRESS_ADC8   0x03800014"
.PP
Definition at line 126 of file sis3320.h.
.SS "#define SIS3320_ACTUAL_SAMPLE_VALUE_ADC12   0x02000020"
.PP
Definition at line 73 of file sis3320.h.
.SS "#define SIS3320_ACTUAL_SAMPLE_VALUE_ADC12   0x02000020"
.PP
Definition at line 73 of file sis3320.h.
.SS "#define SIS3320_ACTUAL_SAMPLE_VALUE_ADC34   0x02800020"
.PP
Definition at line 93 of file sis3320.h.
.SS "#define SIS3320_ACTUAL_SAMPLE_VALUE_ADC56   0x03000020"
.PP
Definition at line 110 of file sis3320.h.
.SS "#define SIS3320_ACTUAL_SAMPLE_VALUE_ADC78   0x03800020"
.PP
Definition at line 128 of file sis3320.h.
.SS "#define SIS3320_ADC1_OFFSET   0x04000000"
.PP
Definition at line 140 of file sis3320.h.
.SS "#define SIS3320_ADC2_OFFSET   0x04800000"
.PP
Definition at line 141 of file sis3320.h.
.SS "#define SIS3320_ADC3_OFFSET   0x05000000"
.PP
Definition at line 142 of file sis3320.h.
.SS "#define SIS3320_ADC4_OFFSET   0x05800000"
.PP
Definition at line 143 of file sis3320.h.
.SS "#define SIS3320_ADC5_OFFSET   0x06000000"
.PP
Definition at line 144 of file sis3320.h.
.SS "#define SIS3320_ADC6_OFFSET   0x06800000"
.PP
Definition at line 145 of file sis3320.h.
.SS "#define SIS3320_ADC7_OFFSET   0x07000000"
.PP
Definition at line 146 of file sis3320.h.
.SS "#define SIS3320_ADC8_OFFSET   0x07800000"
.PP
Definition at line 147 of file sis3320.h.
.SS "#define SIS3320_ADC_GAIN_CONTROL   0x58"
.PP
Definition at line 45 of file sis3320.h.
.SS "#define SIS3320_ADC_INPUT_MODE_ADC12   0x0200000C"
.PP
Definition at line 66 of file sis3320.h.
.SS "#define SIS3320_ADC_INPUT_MODE_ADC34   0x0280000C"
.PP
Definition at line 88 of file sis3320.h.
.SS "#define SIS3320_ADC_INPUT_MODE_ADC56   0x0300000C"
.PP
Definition at line 105 of file sis3320.h.
.SS "#define SIS3320_ADC_INPUT_MODE_ADC78   0x0380000C"
.PP
Definition at line 123 of file sis3320.h.
.SS "#define SIS3320_ADC_INPUT_MODE_ALL_ADC   0x0100000C"
.PP
Definition at line 60 of file sis3320.h.
.PP
Referenced by sis3320_Setup().
.SS "#define SIS3320_ADC_MEMORY_PAGE_REGISTER   0x34"
.PP
Definition at line 41 of file sis3320.h.
.SS "#define SIS3320_CBLT_BROADCAST_SETUP   0x30"
.PP
Definition at line 40 of file sis3320.h.
.SS "#define SIS3320_CONTROL_STATUS   0x0"
.PP
Definition at line 27 of file sis3320.h.
.PP
Referenced by sis3320_Status().
.SS "#define SIS3320_DAC_CONTROL_STATUS   0x50"
.PP
Definition at line 43 of file sis3320.h.
.SS "#define SIS3320_DAC_DATA   0x54"
.PP
Definition at line 44 of file sis3320.h.
.SS "#define SIS3320_DDR2_TEST_REGISTER_ADC12   0x02000028"
.PP
Definition at line 74 of file sis3320.h.
.SS "#define SIS3320_DDR2_TEST_REGISTER_ADC34   0x02800028"
.PP
Definition at line 94 of file sis3320.h.
.SS "#define SIS3320_DDR2_TEST_REGISTER_ADC56   0x03000028"
.PP
Definition at line 111 of file sis3320.h.
.SS "#define SIS3320_DDR2_TEST_REGISTER_ADC78   0x03800028"
.PP
Definition at line 129 of file sis3320.h.
.SS "#define SIS3320_EVENT_CONFIG_ALL_ADC   0x01000000"
.PP
Definition at line 57 of file sis3320.h.
.PP
Referenced by sis3320_Setup().
.SS "#define SIS3320_EVENT_DIRECTORY_ADC1   0x02010000"
.PP
Definition at line 82 of file sis3320.h.
.SS "#define SIS3320_EVENT_DIRECTORY_ADC2   0x02018000"
.PP
Definition at line 83 of file sis3320.h.
.SS "#define SIS3320_EVENT_DIRECTORY_ADC3   0x02810000"
.PP
Definition at line 102 of file sis3320.h.
.SS "#define SIS3320_EVENT_DIRECTORY_ADC4   0x02818000"
.PP
Definition at line 103 of file sis3320.h.
.SS "#define SIS3320_EVENT_DIRECTORY_ADC5   0x03010000"
.PP
Definition at line 119 of file sis3320.h.
.SS "#define SIS3320_EVENT_DIRECTORY_ADC6   0x03018000"
.PP
Definition at line 120 of file sis3320.h.
.SS "#define SIS3320_EVENT_DIRECTORY_ADC7   0x03810000"
.PP
Definition at line 137 of file sis3320.h.
.SS "#define SIS3320_EVENT_DIRECTORY_ADC8   0x03818000"
.PP
Definition at line 138 of file sis3320.h.
.SS "#define SIS3320_IRQ_CONFIG   0x8"
.PP
Definition at line 29 of file sis3320.h.
.SS "#define SIS3320_IRQ_CONTROL   0xC"
.PP
Definition at line 30 of file sis3320.h.
.SS "#define SIS3320_KEY_ARM   0x410"
.PP
Definition at line 48 of file sis3320.h.
.SS "#define SIS3320_KEY_DISARM   0x414"
.PP
Definition at line 49 of file sis3320.h.
.SS "#define SIS3320_KEY_RESET   0x400"
.PP
Definition at line 47 of file sis3320.h.
.PP
Referenced by sis3320_Reset().
.SS "#define SIS3320_KEY_RESET_DDR2_LOGIC   0x428"
.PP
Definition at line 53 of file sis3320.h.
.SS "#define SIS3320_KEY_START   0x418"
.PP
Definition at line 50 of file sis3320.h.
.SS "#define SIS3320_KEY_STOP   0x41C"
.PP
Definition at line 51 of file sis3320.h.
.SS "#define SIS3320_MAX_NOF_EVENT   0x20"
.PP
Definition at line 36 of file sis3320.h.
.PP
Referenced by sis3320_Setup(), and sis3320_Status().
.SS "#define SIS3320_MODID   0x4"
.PP
Definition at line 28 of file sis3320.h.
.PP
Referenced by sis3320_Status().
.SS "#define SIS3320_NEXT_ADC_OFFSET   0x00800000"
.PP
Definition at line 149 of file sis3320.h.
.SS "#define SIS3320_SAMPLE_LENGTH_ALL_ADC   0x01000004"
.PP
Definition at line 58 of file sis3320.h.
.PP
Referenced by sis3320_Setup().
.SS "#define SIS3320_SAMPLE_START_ADDRESS_ALL_ADC   0x01000008"
.PP
Definition at line 59 of file sis3320.h.
.PP
Referenced by sis3320_Setup().
.SS "#define SIS3320_START_DELAY   0x14"
.PP
Definition at line 33 of file sis3320.h.
.SS "#define SIS3320_STOP_DELAY   0x18"
.PP
Definition at line 34 of file sis3320.h.
.SS "#define SIS3320_TRIGGER_FLAG_CLR_CNT_ADC12   0x0200002C"
.PP
Definition at line 75 of file sis3320.h.
.SS "#define SIS3320_TRIGGER_FLAG_CLR_CNT_ADC34   0x0280002C"
.PP
Definition at line 95 of file sis3320.h.
.SS "#define SIS3320_TRIGGER_FLAG_CLR_CNT_ADC56   0x0300002C"
.PP
Definition at line 112 of file sis3320.h.
.SS "#define SIS3320_TRIGGER_FLAG_CLR_CNT_ADC78   0x0380002C"
.PP
Definition at line 130 of file sis3320.h.
.SS "#define SIS3320_TRIGGER_FLAG_CLR_CNT_ALL_ADC   0x0100002C"
.PP
Definition at line 62 of file sis3320.h.
.SS "#define SIS3320_TRIGGER_SETUP_ADC1   0x02000030"
.PP
Definition at line 77 of file sis3320.h.
.SS "#define SIS3320_TRIGGER_SETUP_ADC2   0x02000038"
.PP
Definition at line 79 of file sis3320.h.
.SS "#define SIS3320_TRIGGER_SETUP_ADC3   0x02800030"
.PP
Definition at line 97 of file sis3320.h.
.SS "#define SIS3320_TRIGGER_SETUP_ADC4   0x02800038"
.PP
Definition at line 99 of file sis3320.h.
.SS "#define SIS3320_TRIGGER_SETUP_ADC5   0x03000030"
.PP
Definition at line 114 of file sis3320.h.
.SS "#define SIS3320_TRIGGER_SETUP_ADC6   0x03000038"
.PP
Definition at line 116 of file sis3320.h.
.SS "#define SIS3320_TRIGGER_SETUP_ADC7   0x03800030"
.PP
Definition at line 132 of file sis3320.h.
.SS "#define SIS3320_TRIGGER_SETUP_ADC8   0x03800038"
.PP
Definition at line 134 of file sis3320.h.
.SS "#define SIS3320_TRIGGER_THRESHOLD_ADC1   0x02000034"
.PP
Definition at line 78 of file sis3320.h.
.SS "#define SIS3320_TRIGGER_THRESHOLD_ADC2   0x0200003C"
.PP
Definition at line 80 of file sis3320.h.
.SS "#define SIS3320_TRIGGER_THRESHOLD_ADC3   0x02800034"
.PP
Definition at line 98 of file sis3320.h.
.SS "#define SIS3320_TRIGGER_THRESHOLD_ADC4   0x0280003C"
.PP
Definition at line 100 of file sis3320.h.
.SS "#define SIS3320_TRIGGER_THRESHOLD_ADC5   0x03000034"
.PP
Definition at line 115 of file sis3320.h.
.SS "#define SIS3320_TRIGGER_THRESHOLD_ADC6   0x0300003C"
.PP
Definition at line 117 of file sis3320.h.
.SS "#define SIS3320_TRIGGER_THRESHOLD_ADC7   0x03800034"
.PP
Definition at line 133 of file sis3320.h.
.SS "#define SIS3320_TRIGGER_THRESHOLD_ADC8   0x0380003C"
.PP
Definition at line 135 of file sis3320.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
