.TH "system.c" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
system.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBINT\fP \fBss_system\fP (char *command)"
.br
.ti -1c
.RI "midas_thread_t \fBss_thread_create\fP (\fBINT\fP(*thread_func)(void *), void *param)"
.br
.ti -1c
.RI "\fBINT\fP \fBss_thread_kill\fP (midas_thread_t thread_id)"
.br
.ti -1c
.RI "\fBDWORD\fP \fBss_millitime\fP ()"
.br
.ti -1c
.RI "\fBDWORD\fP \fBss_time\fP ()"
.br
.ti -1c
.RI "\fBINT\fP \fBss_sleep\fP (\fBINT\fP millisec)"
.br
.in -1c
.SH "Detailed Description"
.PP 
dox The Midas System file 
.PP
Definition in file \fBsystem.c\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
