.TH "todo" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
 
.IP "\fBPage \fBCustomizing the MIDAS data logging\fP \fP" 1c
More information needed about defining subruns
.PP
.PP
.PP
 
.IP "\fBPage \fBEvent Builder Functions\fP \fP" 1c
Event Builder tree - there are two versions that need combining !!
.PP
.PP
Is the tree /EB or /EBuilder as above ??
.PP
.PP
This eb example 1 is missing!!
.PP
.PP
This eb example 2 is missing!!
.PP
.PP
.PP
 
.IP "\fBPage \fBHistory Logging\fP \fP" 1c
The history section needs to be reviewed
.PP
.PP
Explanation needed  
.PP
.PP
Explanation needed
.PP
.PP
Explanation needed  
.PP
.PP
Explanation needed  
.PP
.PP
Explanation needed   
.PP
.PP
What is the co history?
.PP
 
.IP "\fBPage \fBMessaging\fP \fP" 1c
what is .MSG.SHM used for?
.PP
.PP
.PP
 
.IP "\fBPage \fBODB RPC access\fP \fP" 1c
Documentation and examples needed - ODBRpc
.PP
.PP
.PP
 
.IP "\fBPage \fBSECTION 8: Performance\fP \fP" 1c
May be changed to current use of the Midas package elsewhere
.PP
.PP
.PP
 
.IP "\fBPage \fBSlow Control System\fP \fP" 1c
more recent examples, description needed for slow control system
.PP
.PP
.PP
 
.IP "\fBPage \fBUsing odbedit\fP \fP" 1c
( MSG.SHM what for? )
.PP
.PP

