.TH "TR_CLIENT" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TR_CLIENT \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
dox 
.PP
Definition at line 3387 of file midas.c.
.SH "Field Documentation"
.PP 
.SS "char \fBTR_CLIENT::client_name\fP[NAME_LENGTH]"
.PP
Definition at line 3390 of file midas.c.
.SS "char \fBTR_CLIENT::host_name\fP[HOST_NAME_LENGTH]"
.PP
Definition at line 3389 of file midas.c.
.SS "int \fBTR_CLIENT::port\fP"
.PP
Definition at line 3391 of file midas.c.
.PP
Referenced by cm_transition1().
.SS "int \fBTR_CLIENT::sequence_number\fP"
.PP
Definition at line 3388 of file midas.c.
.PP
Referenced by cm_transition1().

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
