.TH "TRIGGER_COMMON" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TRIGGER_COMMON \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 122 of file experim.h.
.SH "Field Documentation"
.PP 
.SS "char \fBTRIGGER_COMMON::buffer\fP[32]"
.PP
Definition at line 125 of file experim.h.
.SS "\fBBOOL\fP \fBTRIGGER_COMMON::enabled\fP"
.PP
Definition at line 129 of file experim.h.
.SS "\fBWORD\fP \fBTRIGGER_COMMON::event_id\fP"
.PP
Definition at line 123 of file experim.h.
.SS "double \fBTRIGGER_COMMON::event_limit\fP"
.PP
Definition at line 132 of file experim.h.
.SS "char \fBTRIGGER_COMMON::format\fP[8]"
.PP
Definition at line 128 of file experim.h.
.SS "char \fBTRIGGER_COMMON::frontend_file_name\fP[256]"
.PP
Definition at line 137 of file experim.h.
.SS "char \fBTRIGGER_COMMON::frontend_host\fP[32]"
.PP
Definition at line 135 of file experim.h.
.SS "char \fBTRIGGER_COMMON::frontend_name\fP[32]"
.PP
Definition at line 136 of file experim.h.
.SS "\fBINT\fP \fBTRIGGER_COMMON::log_history\fP"
.PP
Definition at line 134 of file experim.h.
.SS "\fBDWORD\fP \fBTRIGGER_COMMON::num_subevents\fP"
.PP
Definition at line 133 of file experim.h.
.SS "\fBINT\fP \fBTRIGGER_COMMON::period\fP"
.PP
Definition at line 131 of file experim.h.
.SS "\fBINT\fP \fBTRIGGER_COMMON::read_on\fP"
.PP
Definition at line 130 of file experim.h.
.SS "\fBINT\fP \fBTRIGGER_COMMON::source\fP"
.PP
Definition at line 127 of file experim.h.
.SS "\fBWORD\fP \fBTRIGGER_COMMON::trigger_mask\fP"
.PP
Definition at line 124 of file experim.h.
.SS "\fBINT\fP \fBTRIGGER_COMMON::type\fP"
.PP
Definition at line 126 of file experim.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
