.TH "TRIGGER_SETTINGS" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TRIGGER_SETTINGS \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 162 of file experim.h.
.SH "Field Documentation"
.PP 
.SS "\fBBYTE\fP \fBTRIGGER_SETTINGS::io506\fP"
.PP
Definition at line 163 of file experim.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
