.TH "v1740drv.h" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
v1740drv.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBv1740_Setup\fP (\fBMVME_INTERFACE\fP *mvme, uint32_t a32base, int mode)"
.br
.ti -1c
.RI "uint32_t \fBv1740_DataBlockRead\fP (\fBMVME_INTERFACE\fP *mvme, uint32_t a32base, uint32_t *pdest, uint32_t *nentry)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void v1740_AcqCtl (\fBMVME_INTERFACE\fP * mvme, uint32_t a32base, uint32_t operation)"
.PP
Definition at line 98 of file v1740.c.
.SS "void v1740_Align64Set (\fBMVME_INTERFACE\fP * mvme, uint32_t base)"
.SS "uint32_t v1740_BufferFree (\fBMVME_INTERFACE\fP * mvme, uint32_t base, int nbuffer)"
.PP
Definition at line 191 of file v1740.c.
.SS "uint32_t v1740_BufferFreeRead (\fBMVME_INTERFACE\fP * mvme, uint32_t a32base)"
.PP
Definition at line 204 of file v1740.c.
.SS "uint32_t v1740_BufferOccupancy (\fBMVME_INTERFACE\fP * mvme, uint32_t a32base, uint32_t channel)"
.PP
Definition at line 182 of file v1740.c.
.SS "uint32_t v1740_DataBlockRead (\fBMVME_INTERFACE\fP * mvme, uint32_t base, uint32_t * pdest, uint32_t * nentry)"v1740_DataBlockRead Read N entries (32bit) 
.PP
\fBParameters:\fP
.RS 4
\fImvme\fP vme structure 
.br
\fIbase\fP base address 
.br
\fIpdest\fP Destination pointer 
.RE
.PP
\fBReturns:\fP
.RS 4
nentry 
.RE
.PP

.PP
Definition at line 235 of file v1740.c.
.SS "uint32_t v1740_DataRead (\fBMVME_INTERFACE\fP * mvme, uint32_t a32base, uint32_t * pdata, uint32_t n32w)"
.PP
Definition at line 210 of file v1740.c.
.SS "void v1740_GroupConfig (\fBMVME_INTERFACE\fP * mvme, uint32_t base, uint32_t operation)"
.PP
Definition at line 140 of file v1740.c.
.SS "void v1740_GroupCtl (\fBMVME_INTERFACE\fP * mvme, uint32_t a32base, uint32_t reg, uint32_t mask)"
.PP
Definition at line 67 of file v1740.c.
.SS "int v1740_GroupDACGet (\fBMVME_INTERFACE\fP * mvme, uint32_t base, uint32_t channel, uint32_t * dac)"
.SS "void v1740_GroupDACSet (\fBMVME_INTERFACE\fP * mvme, uint32_t base, uint32_t channel, uint32_t dac)"
.SS "uint32_t v1740_GroupGet (\fBMVME_INTERFACE\fP * mvme, uint32_t base, uint32_t channel, uint32_t what)"
.PP
Definition at line 87 of file v1740.c.
.SS "void v1740_GroupOUThresholdSet (\fBMVME_INTERFACE\fP * mvme, uint32_t base, uint32_t channel, uint32_t threshold)"
.SS "void v1740_GroupSet (\fBMVME_INTERFACE\fP * mvme, uint32_t base, uint32_t channel, uint32_t what, uint32_t that)"
.PP
Definition at line 73 of file v1740.c.
.SS "void v1740_GroupThresholdSet (\fBMVME_INTERFACE\fP * mvme, uint32_t base, uint32_t channel, uint32_t threshold)"
.SS "void v1740_info (\fBMVME_INTERFACE\fP * mvme, uint32_t a32base, int * nch, uint32_t * n32w)"
.PP
Definition at line 161 of file v1740.c.
.PP
Referenced by v1740_DataBlockRead().
.SS "uint32_t v1740_RegisterRead (\fBMVME_INTERFACE\fP * mvme, uint32_t a32base, int offset)"
.PP
Definition at line 43 of file v1740.c.
.SS "void v1740_RegisterWrite (\fBMVME_INTERFACE\fP * mvme, uint32_t a32base, int offset, uint32_t value)"
.PP
Definition at line 49 of file v1740.c.
.SS "void v1740_Reset (\fBMVME_INTERFACE\fP * mvme, uint32_t a32base)"
.PP
Definition at line 55 of file v1740.c.
.SS "int v1740_Setup (\fBMVME_INTERFACE\fP * mvme, uint32_t base, int mode)"Sets all the necessary paramters for a given configuration. The configuration is provided by the mode argument. Add your own configuration in the case statement. Let me know your setting if you want to include it in the distribution.
.IP "\(bu" 2
\fBMode 1\fP :
.PP
.PP
\fBParameters:\fP
.RS 4
\fI*mvme\fP VME structure 
.br
\fIbase\fP Module base address 
.br
\fImode\fP Configuration mode number 
.RE
.PP
\fBReturns:\fP
.RS 4
0: OK. -1: Bad 
.RE
.PP

.PP
Definition at line 292 of file v1740.c.
.SS "void v1740_Status (\fBMVME_INTERFACE\fP * mvme, uint32_t a32base)"
.PP
Definition at line 257 of file v1740.c.
.PP
Referenced by v1740_Setup().
.SS "void v1740_TrgCtl (\fBMVME_INTERFACE\fP * mvme, uint32_t a32base, uint32_t reg, uint32_t mask)"
.PP
Definition at line 61 of file v1740.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
