.TH "v1740.h" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
v1740.h \- 
.SH SYNOPSIS
.br
.PP
.SH "Define Documentation"
.PP 
.SS "#define V1740_ACQUISITION_CONTROL   0x8100"
.PP
Definition at line 22 of file v1740.h.
.PP
Referenced by ov1740_AcqCtl(), ov1740_Setup(), ov1740_Status(), v1740_AcqCtl(), v1740_Setup(), and v1740_Status().
.SS "#define V1740_ACQUISITION_STATUS   0x8104"
.PP
Definition at line 23 of file v1740.h.
.PP
Referenced by ov1740_Status(), and v1740_Status().
.SS "#define V1740_ALIGN64   0x20"
.PP
Definition at line 80 of file v1740.h.
.SS "#define V1740_BLT_EVENT_NB   0xEF1C"
.PP
Definition at line 45 of file v1740.h.
.SS "#define V1740_BOARD_ID   0xEF08"
.PP
Definition at line 40 of file v1740.h.
.PP
Referenced by ov1740_Status(), and v1740_Status().
.SS "#define V1740_BOARD_INFO   0x8140"
.PP
Definition at line 35 of file v1740.h.
.PP
Referenced by ov1740_Status(), and v1740_Status().
.SS "#define V1740_BUFFER_FREE   0x8010"
.PP
Definition at line 20 of file v1740.h.
.PP
Referenced by ov1740_BufferFree(), v1740_BufferFree(), and v1740_BufferFreeRead().
.SS "#define V1740_BUFFER_ORGANIZATION   0x800C"
.PP
Definition at line 19 of file v1740.h.
.PP
Referenced by ov1740_BufferFree(), ov1740_info(), ov1740_Setup(), v1740_BufferFree(), v1740_info(), and v1740_Setup().
.SS "#define V1740_CH_TRG_MASK   0x10A8"
.PP
Definition at line 60 of file v1740.h.
.PP
Referenced by v1740_Status().
.SS "#define V1740_CONFIG_RELOAD   0xEF34"
.PP
Definition at line 51 of file v1740.h.
.SS "#define V1740_CONFIG_ROM   0xF000"
.PP
Definition at line 52 of file v1740.h.
.SS "#define V1740_COUNT_ACCEPTED_TRIGGER   9"
.PP
Definition at line 71 of file v1740.h.
.PP
Referenced by ov1740_AcqCtl(), and v1740_AcqCtl().
.SS "#define V1740_COUNT_ALL_TRIGGER   10"
.PP
Definition at line 72 of file v1740.h.
.PP
Referenced by ov1740_AcqCtl(), and v1740_AcqCtl().
.SS "#define V1740_CUSTOM_SIZE   0x8020"
.PP
Definition at line 21 of file v1740.h.
.SS "#define V1740_DONE   0"
.PP
Definition at line 82 of file v1740.h.
.SS "#define V1740_DOWNSAMPLE_DISABLE   12"
.PP
Definition at line 74 of file v1740.h.
.PP
Referenced by v1740_AcqCtl().
.SS "#define V1740_DOWNSAMPLE_ENABLE   11"
.PP
Definition at line 73 of file v1740.h.
.PP
Referenced by v1740_AcqCtl().
.SS "#define V1740_DOWNSAMPLE_FAC   0x8128"
.PP
Definition at line 32 of file v1740.h.
.SS "#define V1740_EVENT_CONFIG_ALL_ADC   0x01000000"
.PP
Definition at line 77 of file v1740.h.
.SS "#define V1740_EVENT_READOUT_BUFFER   0x0000"
.PP
Definition at line 14 of file v1740.h.
.PP
Referenced by v1740_DataBlockRead(), and v1740_DataRead().
.SS "#define V1740_EVENT_SIZE   0x814C"
.PP
Definition at line 37 of file v1740.h.
.SS "#define V1740_EVENT_STORED   0x812C"
.PP
Definition at line 33 of file v1740.h.
.SS "#define V1740_EXTERNAL_TRIGGER   0x40000000"
.PP
Definition at line 79 of file v1740.h.
.SS "#define V1740_FLASH_DATA   0xEF30"
.PP
Definition at line 50 of file v1740.h.
.SS "#define V1740_FLASH_ENABLE   0xEF2C"
.PP
Definition at line 49 of file v1740.h.
.SS "#define V1740_FP_IO_CONTROL   0x811C"
.PP
Definition at line 29 of file v1740.h.
.PP
Referenced by v1740_Status().
.SS "#define V1740_FP_IO_DATA   0x8118"
.PP
Definition at line 28 of file v1740.h.
.SS "#define V1740_FP_TRIGGER_OUT_EN_MASK   0x8110"
.PP
Definition at line 26 of file v1740.h.
.PP
Referenced by v1740_Status().
.SS "#define V1740_GROUP_ADC_CONFIG   0x109C"
.PP
Definition at line 59 of file v1740.h.
.SS "#define V1740_GROUP_BUFFER_OCCUPANCY   0x1094"
.PP
Definition at line 57 of file v1740.h.
.PP
Referenced by ov1740_BufferOccupancy(), and v1740_BufferOccupancy().
.SS "#define V1740_GROUP_CFG_BIT_CLR   0x8008"
.PP
Definition at line 18 of file v1740.h.
.PP
Referenced by ov1740_GroupConfig().
.SS "#define V1740_GROUP_CFG_BIT_SET   0x8004"
.PP
Definition at line 17 of file v1740.h.
.PP
Referenced by ov1740_GroupConfig().
.SS "#define V1740_GROUP_CH_TRG_MASK   0x10B0"
.PP
Definition at line 61 of file v1740.h.
.SS "#define V1740_GROUP_CONFIG   0x8000"
.PP
Definition at line 16 of file v1740.h.
.PP
Referenced by ov1740_GroupConfig(), v1740_GroupConfig(), and v1740_Status().
.SS "#define V1740_GROUP_DAC   0x1098"
.PP
Definition at line 58 of file v1740.h.
.PP
Referenced by ov1740_GroupDACGet(), ov1740_GroupDACSet(), ov1740_GroupGet(), ov1740_GroupSet(), v1740_GroupGet(), v1740_GroupSet(), and v1740_Status().
.SS "#define V1740_GROUP_EN_MASK   0x8120"
.PP
Definition at line 30 of file v1740.h.
.PP
Referenced by ov1740_info(), ov1740_Setup(), v1740_info(), v1740_Setup(), and v1740_Status().
.SS "#define V1740_GROUP_FW_REV   0x108C"
.PP
Definition at line 56 of file v1740.h.
.SS "#define V1740_GROUP_STATUS   0x1088"
.PP
Definition at line 55 of file v1740.h.
.PP
Referenced by ov1740_GroupDACSet(), and v1740_GroupSet().
.SS "#define V1740_GROUP_THRESHOLD   0x1080"
.PP
Definition at line 54 of file v1740.h.
.PP
Referenced by ov1740_GroupGet(), ov1740_GroupSet(), ov1740_GroupThresholdSet(), v1740_GroupGet(), v1740_GroupSet(), and v1740_Status().
.SS "#define V1740_INTERRUPT_EVT_NB   0xEF18"
.PP
Definition at line 44 of file v1740.h.
.SS "#define V1740_INTERRUPT_STATUS_ID   0xEF14"
.PP
Definition at line 43 of file v1740.h.
.SS "#define V1740_MONITOR_MODE   0x8144"
.PP
Definition at line 36 of file v1740.h.
.SS "#define V1740_MULTI_BOARD_SYNC_MODE   8"
.PP
Definition at line 70 of file v1740.h.
.PP
Referenced by ov1740_AcqCtl(), and v1740_AcqCtl().
.SS "#define V1740_MULTICAST_BASE_ADDCTL   0xEF0C"
.PP
Definition at line 41 of file v1740.h.
.SS "#define V1740_NO_ZERO_SUPPRESSION   13"
.PP
Definition at line 75 of file v1740.h.
.SS "#define V1740_POST_TRIGGER_SETTING   0x8114"
.PP
Definition at line 27 of file v1740.h.
.PP
Referenced by ov1740_Setup(), and v1740_Setup().
.SS "#define V1740_REGISTER_RUN_MODE   3"
.PP
Definition at line 65 of file v1740.h.
.PP
Referenced by ov1740_AcqCtl(), and v1740_AcqCtl().
.SS "#define V1740_RELOC_ADDRESS   0xEF10"
.PP
Definition at line 42 of file v1740.h.
.SS "#define V1740_ROC_FPGA_FW_REV   0x8124"
.PP
Definition at line 31 of file v1740.h.
.PP
Referenced by v1740_Status().
.SS "#define V1740_RUN_START   1"
.PP
Definition at line 63 of file v1740.h.
.PP
Referenced by ov1740_AcqCtl(), and v1740_AcqCtl().
.SS "#define V1740_RUN_STOP   2"
.PP
Definition at line 64 of file v1740.h.
.PP
Referenced by ov1740_AcqCtl(), and v1740_AcqCtl().
.SS "#define V1740_SCRATCH   0xEF20"
.PP
Definition at line 46 of file v1740.h.
.SS "#define V1740_SET_MONITOR_DAC   0x8138"
.PP
Definition at line 34 of file v1740.h.
.SS "#define V1740_SIN_GATE_RUN_MODE   5"
.PP
Definition at line 67 of file v1740.h.
.PP
Referenced by ov1740_AcqCtl(), and v1740_AcqCtl().
.SS "#define V1740_SIN_RUN_MODE   4"
.PP
Definition at line 66 of file v1740.h.
.PP
Referenced by ov1740_AcqCtl(), and v1740_AcqCtl().
.SS "#define V1740_SOFT_TRIGGER   0x80000000"
.PP
Definition at line 78 of file v1740.h.
.SS "#define V1740_SOFTWARE_TRIGGER   0x8108"
.PP
Definition at line 24 of file v1740.h.
.SS "#define V1740_SW_CLEAR   0xEF28"
.PP
Definition at line 48 of file v1740.h.
.SS "#define V1740_SW_RESET   0xEF24"
.PP
Definition at line 47 of file v1740.h.
.PP
Referenced by v1740_Reset().
.SS "#define V1740_TRIG_SRCE_EN_MASK   0x810C"
.PP
Definition at line 25 of file v1740.h.
.PP
Referenced by ov1740_Setup(), v1740_Setup(), and v1740_Status().
.SS "#define V1740_TRIGGER_OVERTH   6"
.PP
Definition at line 68 of file v1740.h.
.PP
Referenced by ov1740_GroupConfig(), and v1740_GroupConfig().
.SS "#define V1740_TRIGGER_UNDERTH   7"
.PP
Definition at line 69 of file v1740.h.
.PP
Referenced by ov1740_GroupConfig(), and v1740_GroupConfig().
.SS "#define V1740_VME_CONTROL   0xEF00"
.PP
Definition at line 38 of file v1740.h.
.PP
Referenced by v1740_Status().
.SS "#define V1740_VME_STATUS   0xEF04"
.PP
Definition at line 39 of file v1740.h.
.PP
Referenced by v1740_Status().
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
