.TH "v560.c" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
v560.c \- 
.SH SYNOPSIS
.br
.PP
.SH "Function Documentation"
.PP 
.SS "static uint16_t regRead (\fBMVME_INTERFACE\fP * mvme, \fBDWORD\fP base, int offset)\fC [static]\fP"
.PP
Definition at line 20 of file v560.c.
.PP
Referenced by v560_RegisterRead(), v560_Reset(), and v560_Status().
.SS "static void regWrite (\fBMVME_INTERFACE\fP * mvme, \fBDWORD\fP base, int offset, uint16_t value)\fC [static]\fP"
.PP
Definition at line 31 of file v560.c.
.PP
Referenced by v560_RegisterWrite().
.SS "void v560_Read (\fBMVME_INTERFACE\fP * mvme, \fBDWORD\fP base, uint32_t data[16])"
.PP
Definition at line 48 of file v560.c.
.SS "uint16_t v560_RegisterRead (\fBMVME_INTERFACE\fP * mvme, \fBDWORD\fP base, int offset)"
.PP
Definition at line 38 of file v560.c.
.SS "void v560_RegisterWrite (\fBMVME_INTERFACE\fP * mvme, \fBDWORD\fP base, int offset, uint16_t value)"
.PP
Definition at line 43 of file v560.c.
.SS "void v560_Reset (\fBMVME_INTERFACE\fP * mvme, \fBDWORD\fP base)"
.PP
Definition at line 63 of file v560.c.
.SS "void v560_Status (\fBMVME_INTERFACE\fP * mvme, \fBDWORD\fP base)"
.PP
Definition at line 70 of file v560.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
