.TH "v792_StatusRegister1" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
v792_StatusRegister1 \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 128 of file v792.h.
.SH "Field Documentation"
.PP 
.SS "struct { ... } "
.SS "unsigned \fBv792_StatusRegister1::Amnesia\fP"
.PP
Definition at line 135 of file v792.h.
.SS "unsigned \fBv792_StatusRegister1::Busy\fP"
.PP
Definition at line 133 of file v792.h.
.SS "unsigned \fBv792_StatusRegister1::DataReady\fP"
.PP
Definition at line 131 of file v792.h.
.SS "unsigned \fBv792_StatusRegister1::EventReady\fP"
.PP
Definition at line 139 of file v792.h.
.SS "unsigned \fBv792_StatusRegister1::GlobalBusy\fP"
.PP
Definition at line 134 of file v792.h.
.SS "unsigned \fBv792_StatusRegister1::GlobalDataReady\fP"
.PP
Definition at line 132 of file v792.h.
.SS "unsigned \fBv792_StatusRegister1::Purge\fP"
.PP
Definition at line 136 of file v792.h.
.SS "\fBDWORD\fP \fBv792_StatusRegister1::raw\fP"
.PP
Definition at line 129 of file v792.h.
.SS "unsigned \fBv792_StatusRegister1::TermOff\fP"
.PP
Definition at line 138 of file v792.h.
.SS "unsigned \fBv792_StatusRegister1::TermOn\fP"
.PP
Definition at line 137 of file v792.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
