.TH "v792_Data" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
v792_Data \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBEntry\fP"
.br
.ti -1c
.RI "struct \fBFooter\fP"
.br
.ti -1c
.RI "struct \fBHeader\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 101 of file v792.h.
.SH "Field Documentation"
.PP 
.SS "struct \fBv792_Data::Entry\fP  \fBv792_Data::data\fP"
.PP
Referenced by v792_printEntry().
.SS "struct \fBv792_Data::Footer\fP  \fBv792_Data::footer\fP"
.PP
Referenced by v792_printEntry().
.SS "struct \fBv792_Data::Header\fP  \fBv792_Data::header\fP"
.PP
Referenced by v792_printEntry().
.SS "\fBDWORD\fP \fBv792_Data::raw\fP"
.PP
Definition at line 102 of file v792.h.
.PP
Referenced by v792_printEntry().

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
