.TH "v792_BitSet2Register" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
v792_BitSet2Register \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 167 of file v792.h.
.SH "Field Documentation"
.PP 
.SS "struct { ... } "
.SS "unsigned \fBv792_BitSet2Register::_pad_1\fP"
.PP
Definition at line 175 of file v792.h.
.SS "unsigned \fBv792_BitSet2Register::_pad_2\fP"
.PP
Definition at line 179 of file v792.h.
.SS "unsigned \fBv792_BitSet2Register::AllTrg\fP"
.PP
Definition at line 183 of file v792.h.
.SS "unsigned \fBv792_BitSet2Register::AutoIncr\fP"
.PP
Definition at line 180 of file v792.h.
.SS "unsigned \fBv792_BitSet2Register::ClearData\fP"
.PP
Definition at line 172 of file v792.h.
.SS "unsigned \fBv792_BitSet2Register::EmptyProg\fP"
.PP
Definition at line 181 of file v792.h.
.SS "unsigned \fBv792_BitSet2Register::LowThresh\fP"
.PP
Definition at line 174 of file v792.h.
.SS "unsigned \fBv792_BitSet2Register::MemTest\fP"
.PP
Definition at line 170 of file v792.h.
.SS "unsigned \fBv792_BitSet2Register::OffLine\fP"
.PP
Definition at line 171 of file v792.h.
.SS "unsigned \fBv792_BitSet2Register::OverRange\fP"
.PP
Definition at line 173 of file v792.h.
.SS "\fBDWORD\fP \fBv792_BitSet2Register::raw\fP"
.PP
Definition at line 168 of file v792.h.
.SS "unsigned \fBv792_BitSet2Register::SLDEnable\fP"
.PP
Definition at line 177 of file v792.h.
.SS "unsigned \fBv792_BitSet2Register::SlideSubEnable\fP"
.PP
Definition at line 182 of file v792.h.
.SS "unsigned \fBv792_BitSet2Register::StepTH\fP"
.PP
Definition at line 178 of file v792.h.
.SS "unsigned \fBv792_BitSet2Register::TestAcq\fP"
.PP
Definition at line 176 of file v792.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
