.TH "v792_Data::Footer" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
v792_Data::Footer \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 121 of file v792.h.
.SH "Field Documentation"
.PP 
.SS "unsigned \fBv792_Data::Footer::evtCnt\fP"
.PP
Definition at line 122 of file v792.h.
.PP
Referenced by v792_printEntry().
.SS "unsigned \fBv792_Data::Footer::geo\fP"
.PP
Definition at line 124 of file v792.h.
.PP
Referenced by v792_printEntry().
.SS "unsigned \fBv792_Data::Footer::type\fP"
.PP
Definition at line 123 of file v792.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
