.TH "v792_StatusRegister2" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
v792_StatusRegister2 \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 142 of file v792.h.
.SH "Field Documentation"
.PP 
.SS "struct { ... } "
.SS "unsigned \fBv792_StatusRegister2::_pad_1\fP"
.PP
Definition at line 145 of file v792.h.
.SS "unsigned \fBv792_StatusRegister2::_pad_2\fP"
.PP
Definition at line 148 of file v792.h.
.SS "unsigned \fBv792_StatusRegister2::BufferEmpty\fP"
.PP
Definition at line 146 of file v792.h.
.SS "unsigned \fBv792_StatusRegister2::BufferFull\fP"
.PP
Definition at line 147 of file v792.h.
.SS "unsigned \fBv792_StatusRegister2::PB\fP"
.PP
Definition at line 149 of file v792.h.
.SS "\fBDWORD\fP \fBv792_StatusRegister2::raw\fP"
.PP
Definition at line 143 of file v792.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
