.TH "v792_ControlRegister1" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
v792_ControlRegister1 \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 156 of file v792.h.
.SH "Field Documentation"
.PP 
.SS "struct { ... } "
.SS "unsigned \fBv792_ControlRegister1::_pad_1\fP"
.PP
Definition at line 159 of file v792.h.
.SS "unsigned \fBv792_ControlRegister1::_pad_2\fP"
.PP
Definition at line 161 of file v792.h.
.SS "unsigned \fBv792_ControlRegister1::Align64\fP"
.PP
Definition at line 164 of file v792.h.
.SS "unsigned \fBv792_ControlRegister1::BErr\fP"
.PP
Definition at line 163 of file v792.h.
.SS "unsigned \fBv792_ControlRegister1::BlkEnd\fP"
.PP
Definition at line 160 of file v792.h.
.SS "unsigned \fBv792_ControlRegister1::ProgReset\fP"
.PP
Definition at line 162 of file v792.h.
.SS "\fBDWORD\fP \fBv792_ControlRegister1::raw\fP"
.PP
Definition at line 157 of file v792.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
