.TH "v895.h" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
v895.h \- 
.SH SYNOPSIS
.br
.PP
.SH "Function Documentation"
.PP 
.SS "uint16_t v895_readReg16 (\fBMVME_INTERFACE\fP * mvme, int base, int ireg)"
.PP
Definition at line 35 of file v895.h.
.PP
Referenced by v895_Status().
.SS "uint8_t v895_readReg8 (\fBMVME_INTERFACE\fP * mvme, int base, int ireg)"
.PP
Definition at line 21 of file v895.h.
.SS "int v895_Status (\fBMVME_INTERFACE\fP * mvme, int base)"
.PP
Definition at line 49 of file v895.h.
.PP
Referenced by init_vme_modules().
.SS "void v895_TestPulse (\fBMVME_INTERFACE\fP * mvme, int base)"
.PP
Definition at line 59 of file v895.h.
.SS "void v895_writeReg16 (\fBMVME_INTERFACE\fP * mvme, int base, int ireg, uint16_t value)"
.PP
Definition at line 42 of file v895.h.
.PP
Referenced by init_vme_modules(), and v895_TestPulse().
.SS "void v895_writeReg8 (\fBMVME_INTERFACE\fP * mvme, int base, int ireg, uint8_t value)"
.PP
Definition at line 28 of file v895.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
