.TH "vpc6_Reg" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vpc6_Reg \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBEntry1\fP"
.br
.ti -1c
.RI "struct \fBEntry2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file vpc6.h.
.SH "Field Documentation"
.PP 
.SS "\fBDWORD\fP \fBvpc6_Reg::asdcfg\fP"
.PP
Definition at line 44 of file vpc6.h.
.PP
Referenced by vpc6_ASDRegSet().
.SS "struct \fBvpc6_Reg::Entry1\fP  \fBvpc6_Reg::asdx1\fP"
.PP
Referenced by vpc6_ASDDefaultLoad(), vpc6_ASDHysteresisSet(), vpc6_ASDModeSet(), and vpc6_EntryPrint().
.SS "struct \fBvpc6_Reg::Entry2\fP  \fBvpc6_Reg::asdx2\fP"
.PP
Referenced by vpc6_ASDDefaultLoad(), vpc6_ASDThresholdSet(), and vpc6_EntryPrint().

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
