.TH "vpc6_Reg::Entry2" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vpc6_Reg::Entry2 \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 54 of file vpc6.h.
.SH "Field Documentation"
.PP 
.SS "unsigned \fBvpc6_Reg::Entry2::calMaskReg\fP"
.PP
Definition at line 58 of file vpc6.h.
.PP
Referenced by vpc6_ASDDefaultLoad(), and vpc6_EntryPrint().
.SS "unsigned \fBvpc6_Reg::Entry2::capInjCapSel\fP"
.PP
Definition at line 57 of file vpc6.h.
.PP
Referenced by vpc6_ASDDefaultLoad(), and vpc6_EntryPrint().
.SS "unsigned \fBvpc6_Reg::Entry2::mainThresholdDAC\fP"
.PP
Definition at line 56 of file vpc6.h.
.PP
Referenced by vpc6_ASDDefaultLoad(), vpc6_ASDThresholdSet(), and vpc6_EntryPrint().
.SS "unsigned \fBvpc6_Reg::Entry2::notused\fP"
.PP
Definition at line 59 of file vpc6.h.
.PP
Referenced by vpc6_ASDDefaultLoad().
.SS "unsigned \fBvpc6_Reg::Entry2::wilkinsonADC\fP"
.PP
Definition at line 55 of file vpc6.h.
.PP
Referenced by vpc6_ASDDefaultLoad(), and vpc6_EntryPrint().

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
