.TH "vpc6_Reg::Entry1" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vpc6_Reg::Entry1 \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 45 of file vpc6.h.
.SH "Field Documentation"
.PP 
.SS "unsigned \fBvpc6_Reg::Entry1::channelmode\fP"
.PP
Definition at line 47 of file vpc6.h.
.PP
Referenced by vpc6_ASDDefaultLoad(), vpc6_ASDModeSet(), and vpc6_EntryPrint().
.SS "unsigned \fBvpc6_Reg::Entry1::chipmode\fP"
.PP
Definition at line 46 of file vpc6.h.
.PP
Referenced by vpc6_ASDDefaultLoad(), and vpc6_EntryPrint().
.SS "unsigned \fBvpc6_Reg::Entry1::deadtime\fP"
.PP
Definition at line 48 of file vpc6.h.
.PP
Referenced by vpc6_ASDDefaultLoad(), and vpc6_EntryPrint().
.SS "unsigned \fBvpc6_Reg::Entry1::hysteresisDAC\fP"
.PP
Definition at line 51 of file vpc6.h.
.PP
Referenced by vpc6_ASDDefaultLoad(), vpc6_ASDHysteresisSet(), and vpc6_EntryPrint().
.SS "unsigned \fBvpc6_Reg::Entry1::wilkinsonADC\fP"
.PP
Definition at line 52 of file vpc6.h.
.PP
Referenced by vpc6_ASDDefaultLoad(), and vpc6_EntryPrint().
.SS "unsigned \fBvpc6_Reg::Entry1::wilkinsonIGate\fP"
.PP
Definition at line 50 of file vpc6.h.
.PP
Referenced by vpc6_ASDDefaultLoad(), and vpc6_EntryPrint().
.SS "unsigned \fBvpc6_Reg::Entry1::wilkinsonRCurrent\fP"
.PP
Definition at line 49 of file vpc6.h.
.PP
Referenced by vpc6_ASDDefaultLoad(), and vpc6_EntryPrint().

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
