.TH "vt2.h" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vt2.h \- 
.SH SYNOPSIS
.br
.PP
.SH "Define Documentation"
.PP 
.SS "#define VT2_ALMOSTFULL_FLAG   (\fBDWORD\fP) (0x20000)"
.PP
Definition at line 48 of file vt2.h.
.SS "#define VT2_CSR_RO   (\fBDWORD\fP) (0x0)"
.PP
Definition at line 37 of file vt2.h.
.PP
Referenced by vt2_CSRRead().
.SS "#define VT2_CTL_WO   (\fBDWORD\fP) (0xc)"
.PP
Definition at line 40 of file vt2.h.
.PP
Referenced by vt2_CycleReset(), vt2_IntEnable(), vt2_KeepAlive(), and vt2_ManReset().
.SS "#define VT2_CYCLE_MASK   (\fBDWORD\fP) (0x03FF0000)"
.PP
Definition at line 56 of file vt2.h.
.SS "#define VT2_CYCLE_SHIFT   (\fBDWORD\fP) (16)"
.PP
Definition at line 57 of file vt2.h.
.SS "#define VT2_CYCLENUMBER_RO   (\fBDWORD\fP) (0x8)"
.PP
Definition at line 39 of file vt2.h.
.PP
Referenced by vt2_CycleNumberRead().
.SS "#define VT2_CYCLERESET   (\fBDWORD\fP) (0x2)"
.PP
Definition at line 44 of file vt2.h.
.PP
Referenced by vt2_CycleReset().
.SS "#define VT2_EMPTY_FLAG   (\fBDWORD\fP) (0x40000)"
.PP
Definition at line 49 of file vt2.h.
.SS "#define VT2_FIFO_RO   (\fBDWORD\fP) (0x14)"
.PP
Definition at line 42 of file vt2.h.
.PP
Referenced by vt2_FifoRead().
.SS "#define VT2_FIFOSTATUS_RO   (\fBDWORD\fP) (0x4)"
.PP
Definition at line 38 of file vt2.h.
.PP
Referenced by vt2_FifoLevelRead().
.SS "#define VT2_FULL_FLAG   (\fBDWORD\fP) (0x10000)"
.PP
Definition at line 47 of file vt2.h.
.PP
Referenced by vt2_FifoLevelRead().
.SS "#define VT2_HIT1   (\fBDWORD\fP) (1<<30)"
.PP
Definition at line 52 of file vt2.h.
.SS "#define VT2_HIT2   (\fBDWORD\fP) (1<<29)"
.PP
Definition at line 53 of file vt2.h.
.SS "#define VT2_HSTART   (\fBDWORD\fP) (1<<31)"
.PP
Definition at line 51 of file vt2.h.
.SS "#define VT2_HSTOP   (\fBDWORD\fP) (1<<28)"
.PP
Definition at line 54 of file vt2.h.
.SS "#define VT2_INTENABLE   (\fBDWORD\fP) (0x8)"
.PP
Definition at line 46 of file vt2.h.
.PP
Referenced by vt2_IntEnable().
.SS "#define VT2_INTREG   (\fBDWORD\fP) (0x10)"
.PP
Definition at line 41 of file vt2.h.
.SS "#define VT2_KEEPALIVE   (\fBDWORD\fP) (0x4)"
.PP
Definition at line 45 of file vt2.h.
.PP
Referenced by vt2_KeepAlive().
.SS "#define VT2_MANRESET   (\fBDWORD\fP) (0x1)"
.PP
Definition at line 43 of file vt2.h.
.PP
Referenced by vt2_ManReset().
.SS "#define VT2_MAX_CHANNELS   (\fBDWORD\fP) 2"
.PP
Definition at line 36 of file vt2.h.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBDWORD\fP \fBBOOL\fP"
.PP
Definition at line 30 of file vt2.h.
.SS "typedef unsigned char \fBBYTE\fP"
.PP
Definition at line 22 of file vt2.h.
.SS "typedef unsigned int \fBDWORD\fP"
.PP
Definition at line 25 of file vt2.h.
.SS "typedef unsigned short int \fBWORD\fP"
.PP
Definition at line 23 of file vt2.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
