.TH "vt48_Reg::Entry1" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vt48_Reg::Entry1 \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 88 of file vt48.h.
.SH "Field Documentation"
.PP 
.SS "unsigned \fBvt48_Reg::Entry1::id1\fP"
.PP
Definition at line 89 of file vt48.h.
.SS "unsigned \fBvt48_Reg::Entry1::id2\fP"
.PP
Definition at line 90 of file vt48.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
