.TH "vt48_Reg::csr0" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vt48_Reg::csr0 \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 92 of file vt48.h.
.SH "Field Documentation"
.PP 
.SS "unsigned \fBvt48_Reg::csr0::csr0\fP"
.PP
Definition at line 93 of file vt48.h.
.SS "unsigned \fBvt48_Reg::csr0::csr1\fP"
.PP
Definition at line 95 of file vt48.h.
.SS "unsigned \fBvt48_Reg::csr0::na1\fP"
.PP
Definition at line 94 of file vt48.h.
.SS "unsigned \fBvt48_Reg::csr0::na2\fP"
.PP
Definition at line 96 of file vt48.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
