.TH "vt48_Reg" 3 "31 May 2012" "Version 2.3.0-0" "Midas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vt48_Reg \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBcsr0\fP"
.br
.ti -1c
.RI "struct \fBEntry1\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 86 of file vt48.h.
.SH "Field Documentation"
.PP 
.SS "\fBDWORD\fP \fBvt48_Reg::id\fP"
.PP
Definition at line 87 of file vt48.h.
.SS "struct \fBvt48_Reg::Entry1\fP  \fBvt48_Reg::vtr0\fP"
.SS "struct \fBvt48_Reg::csr0\fP  \fBvt48_Reg::vtr1\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Midas from the source code.
