Midas: Midas RPC_LIST
Midas RPC_LIST
[The mrpc.h & mrpc.c]
Variables
static RPC_LIST rpc_list_library []
static RPC_LIST rpc_list_system []
Detailed Description
dox
Function Documentation
RPC_LIST* rpc_get_internal_list (INT flag)
Definition at line 1258 of file mrpc.c.
Referenced by cm_connect_experiment1(), rpc_register_client(), and rpc_register_functions().
Variable Documentation
RPC_LIST rpc_list_library[] [static]
dox dox rpc_list_library contains all MIDAS library functions and gets registerd whenever a connection to the MIDAS server is established
Definition at line 44 of file mrpc.c.
Referenced by rpc_get_internal_list().
RPC_LIST rpc_list_system[] [static]
Initial value:
 {
   {RPC_ID_WATCHDOG, "id_watchdog",
    {{0}}},
   {RPC_ID_SHUTDOWN, "id_shutdown",
    {{0}}},
   {RPC_ID_EXIT, "id_exit",
    {{0}}},
   {0}
}
dox rpc_list_system contains MIDAS system functions and gets registerd whenever a RPC server is registered
Definition at line 1242 of file mrpc.c.
Midas DOC Version 2.3.0 ---- PSI Stefan Ritt ----
Contributions: Pierre-Andre Amaudruz - Sergio Ballestrero - Suzannah Daviel - Doxygen - Peter Green - Qing Gu - Greg Hackman - Gertjan Hofman - Paul Knowles - Exaos Lee - Rudi Meier - Glenn Moloney - Dave Morris - John M O'Donnell - Konstantin Olchanski - Chris Pearson - Renee Poutissou - Tamsen Schurman - Andreas Suter - Jan M.Wouters - Piotr Adam Zolnierczuk