Midas: Equipment related
Equipment related
[Midas Structure Declaration]
Data Structures
struct BUS_DRIVER
struct DD_MT_CHANNEL
struct DD_MT_BUFFER
struct EQUIPMENT_INFO
struct DEVICE_DRIVER
struct EQUIPMENT_STATS
struct eqpmnt
Defines
#define DF_INPUT (1<<0)
#define DF_OUTPUT (1<<1)
#define DF_PRIO_DEVICE (1<<2)
#define DF_READ_ONLY (1<<3)
Detailed Description
dox dox
Define Documentation
#define DF_HW_RAMP (1<<5)
Definition at line 946 of file midas.h.
Referenced by hv_demand().
#define DF_INPUT (1<<0)
channel is input
Definition at line 941 of file midas.h.
#define DF_MULTITHREAD (1<<4)
Definition at line 945 of file midas.h.
Referenced by device_driver(), hv_idle(), hv_read(), hv_start(), hv_stop(), and main().
#define DF_OUTPUT (1<<1)
channel is output
Definition at line 942 of file midas.h.
#define DF_PRIO_DEVICE (1<<2)
get demand values from device instead of ODB
Definition at line 943 of file midas.h.
Referenced by hv_init().
#define DF_READ_ONLY (1<<3)
never write demand values to device
Definition at line 944 of file midas.h.
Typedef Documentation
typedef struct eqpmnt EQUIPMENT
typedef struct eqpmnt* PEQUIPMENT
Definition at line 1009 of file midas.h.
Function Documentation
INT device_driver (DEVICE_DRIVER * device_driver, INT cmd, ...)
Definition at line 404 of file mfe.c.
Referenced by hv_demand(), hv_exit(), hv_init(), hv_ramp(), hv_read(), hv_set_current_limit(), hv_set_rampdown(), hv_set_rampup(), hv_set_trip_time(), hv_set_voltage_limit(), hv_start(), hv_stop(), hv_update_label(), and validate_odb_array().
Midas DOC Version 2.3.0 ---- PSI Stefan Ritt ----
Contributions: Pierre-Andre Amaudruz - Sergio Ballestrero - Suzannah Daviel - Doxygen - Peter Green - Qing Gu - Greg Hackman - Gertjan Hofman - Paul Knowles - Exaos Lee - Rudi Meier - Glenn Moloney - Dave Morris - John M O'Donnell - Konstantin Olchanski - Chris Pearson - Renee Poutissou - Tamsen Schurman - Andreas Suter - Jan M.Wouters - Piotr Adam Zolnierczuk