Midas: The mdsupport.h & mdsupport.c
The mdsupport.h & mdsupport.c
Modules
Midas dump error code
Midas dump support Define
Midas dump support Macros
Functions
INT md_file_ropen (char *infile, INT data_fmt, INT openzip)
Detailed Description
dox
Function Documentation
INT md_all_info_display (INT what)
Definition at line 695 of file mdsupport.c.
void md_bank_display (void * pmbh, void * pbk, INT data_fmt, INT dsp_mode, INT dsp_fmt)
Definition at line 945 of file mdsupport.c.
void md_bank_event_display (void * pevent, INT data_fmt, INT dsp_fmt, INT dsp_mode, char * bn)
Definition at line 856 of file mdsupport.c.
Referenced by md_event_display().
INT md_dev_os_read (INT handle, INT type, void * prec, DWORD nbytes, DWORD * readn)
Definition at line 430 of file mdsupport.c.
Referenced by midas_physrec_get().
INT md_dev_os_write (INT handle, INT type, void * prec, DWORD nbytes, DWORD * written)
Definition at line 486 of file mdsupport.c.
Referenced by md_log_write().
void md_event_display (void * pevent, INT data_fmt, INT dsp_mode, INT dsp_fmt, char * bn)
Definition at line 791 of file mdsupport.c.
INT md_event_get (INT data_fmt, void ** pevent, DWORD * readn)
Definition at line 767 of file mdsupport.c.
INT md_event_swap (INT data_fmt, void * pevent)
Definition at line 735 of file mdsupport.c.
Referenced by eb_yfragment_add().
INT md_file_rclose (INT data_fmt)
Definition at line 263 of file mdsupport.c.
INT md_file_ropen (char * infile, INT data_fmt, INT openzip)
dox
Definition at line 174 of file mdsupport.c.
INT md_file_wclose (INT handle, INT type, INT data_fmt, char * destination)
Definition at line 360 of file mdsupport.c.
INT md_file_wopen (INT type, INT data_fmt, char * filename, INT * hDev)
Definition at line 305 of file mdsupport.c.
INT md_log_write (INT handle, INT data_fmt, INT type, void * prec, DWORD nbytes)
Definition at line 581 of file mdsupport.c.
INT md_physrec_display (INT data_fmt)
Definition at line 669 of file mdsupport.c.
INT md_physrec_get (INT data_fmt, void ** precord, DWORD * readn)
Definition at line 560 of file mdsupport.c.
INT md_physrec_skip (INT data_fmt, INT bl)
Definition at line 608 of file mdsupport.c.
void md_raw_bank_display (void * pbank, INT data_fmt, INT dsp_fmt)
Definition at line 975 of file mdsupport.c.
Referenced by md_bank_display().
void md_raw_event_display (void * pevent, INT data_fmt, INT dsp_fmt)
Definition at line 816 of file mdsupport.c.
Referenced by md_bank_event_display(), and md_event_display().
void midas_bank_display (BANK * pbk, INT dsp_fmt)
Definition at line 1152 of file mdsupport.c.
Referenced by md_bank_display(), and md_bank_event_display().
void midas_bank_display32 (BANK32 * pbk, INT dsp_fmt)
Definition at line 1373 of file mdsupport.c.
Referenced by md_bank_display(), and md_bank_event_display().
INT midas_event_get (void ** pevent, DWORD * readn)
Definition at line 1016 of file mdsupport.c.
Referenced by md_event_get(), and midas_event_skip().
INT midas_event_skip (INT evtn)
Definition at line 634 of file mdsupport.c.
Referenced by md_physrec_skip().
INT midas_physrec_get (void * prec, DWORD * readn)
Definition at line 1108 of file mdsupport.c.
Referenced by md_physrec_get(), and midas_event_get().
Midas DOC Version 2.3.0 ---- PSI Stefan Ritt ----
Contributions: Pierre-Andre Amaudruz - Sergio Ballestrero - Suzannah Daviel - Doxygen - Peter Green - Qing Gu - Greg Hackman - Gertjan Hofman - Paul Knowles - Exaos Lee - Rudi Meier - Glenn Moloney - Dave Morris - John M O'Donnell - Konstantin Olchanski - Chris Pearson - Renee Poutissou - Tamsen Schurman - Andreas Suter - Jan M.Wouters - Piotr Adam Zolnierczuk