Midas: hv.c File Reference
hv.c File Reference
Data Structures
struct HV_INFO
Define Documentation
#define abs (a) (((a) < 0) ? -(a) : (a))
Definition at line 59 of file hv.c.
Referenced by begin_of_run(), hs_dump(), and hv_read().
Function Documentation
INT cd_hv (INT cmd, PEQUIPMENT pequipment)
Definition at line 865 of file hv.c.
INT cd_hv_read (char * pevent, int offset)
Definition at line 780 of file hv.c.
static void free_mem (HV_INFO * hv_info) [static]
Definition at line 64 of file hv.c.
Referenced by hv_exit(), and hv_init().
void hv_demand (INT hDB, INT hKey, void * info)
Definition at line 289 of file hv.c.
Referenced by hv_init().
INT hv_exit (EQUIPMENT * pequipment)
Definition at line 724 of file hv.c.
Referenced by cd_hv().
INT hv_idle (EQUIPMENT * pequipment)
Definition at line 739 of file hv.c.
Referenced by cd_hv().
INT hv_init (EQUIPMENT * pequipment)
Definition at line 463 of file hv.c.
Referenced by cd_hv().
INT hv_ramp (HV_INFO * hv_info)
Definition at line 227 of file hv.c.
Referenced by hv_demand(), and hv_idle().
INT hv_read (EQUIPMENT * pequipment, int channel)
Definition at line 124 of file hv.c.
Referenced by hv_idle().
void hv_set_current_limit (INT hDB, INT hKey, void * info)
Definition at line 347 of file hv.c.
Referenced by hv_init().
void hv_set_rampdown (INT hDB, INT hKey, void * info)
Definition at line 385 of file hv.c.
Referenced by hv_init().
void hv_set_rampup (INT hDB, INT hKey, void * info)
Definition at line 366 of file hv.c.
Referenced by hv_init().
void hv_set_trip_time (INT hDB, INT hKey, void * info)
Definition at line 328 of file hv.c.
Referenced by hv_init().
void hv_set_voltage_limit (INT hDB, INT hKey, void * info)
Definition at line 404 of file hv.c.
Referenced by hv_init().
INT hv_start (EQUIPMENT * pequipment)
Definition at line 94 of file hv.c.
Referenced by cd_hv().
INT hv_stop (EQUIPMENT * pequipment)
Definition at line 110 of file hv.c.
Referenced by cd_hv().
void hv_update_label (INT hDB, INT hKey, void * info)
Definition at line 423 of file hv.c.
Referenced by hv_init().
void validate_odb_array (HNDLE hDB, HV_INFO * hv_info, char * path, double default_value, int cmd, float * array, void(*)(INT, INT, void *) callback, EQUIPMENT * pequipment)
Definition at line 441 of file hv.c.
Referenced by hv_init().
Midas DOC Version 2.3.0 ---- PSI Stefan Ritt ----
Contributions: Pierre-Andre Amaudruz - Sergio Ballestrero - Suzannah Daviel - Doxygen - Peter Green - Qing Gu - Greg Hackman - Gertjan Hofman - Paul Knowles - Exaos Lee - Rudi Meier - Glenn Moloney - Dave Morris - John M O'Donnell - Konstantin Olchanski - Chris Pearson - Renee Poutissou - Tamsen Schurman - Andreas Suter - Jan M.Wouters - Piotr Adam Zolnierczuk