Midas: isegvhs.c File Reference
isegvhs.c File Reference
Function Documentation
uint32_t isegvhs_RegisterRead (MVME_INTERFACE * mvme, DWORD base, int offset)
Definition at line 64 of file isegvhs.c.
float isegvhs_RegisterReadFloat (MVME_INTERFACE * mvme, DWORD base, int offset)
Definition at line 70 of file isegvhs.c.
Referenced by isegvhs_Status().
void isegvhs_RegisterWrite (MVME_INTERFACE * mvme, DWORD base, int offset, uint32_t value)
Definition at line 79 of file isegvhs.c.
void isegvhs_RegisterWriteFloat (MVME_INTERFACE * mvme, DWORD base, int offset, float value)
Definition at line 85 of file isegvhs.c.
void isegvhs_Status (MVME_INTERFACE * mvme, DWORD base)
Definition at line 91 of file isegvhs.c.
static uint32_t regRead (MVME_INTERFACE * mvme, DWORD base, int offset) [static]
Definition at line 20 of file isegvhs.c.
Referenced by isegvhs_RegisterRead(), and isegvhs_Status().
static float regReadFloat (MVME_INTERFACE * mvme, DWORD base, int offset) [static]
Definition at line 27 of file isegvhs.c.
Referenced by isegvhs_RegisterReadFloat(), and isegvhs_Status().
static void regWrite (MVME_INTERFACE * mvme, DWORD base, int offset, uint32_t value) [static]
Definition at line 46 of file isegvhs.c.
Referenced by isegvhs_RegisterWrite().
static void regWriteFloat (MVME_INTERFACE * mvme, DWORD base, int offset, float value) [static]
Definition at line 53 of file isegvhs.c.
Referenced by isegvhs_RegisterWriteFloat().
Midas DOC Version 2.3.0 ---- PSI Stefan Ritt ----
Contributions: Pierre-Andre Amaudruz - Sergio Ballestrero - Suzannah Daviel - Doxygen - Peter Green - Qing Gu - Greg Hackman - Gertjan Hofman - Paul Knowles - Exaos Lee - Rudi Meier - Glenn Moloney - Dave Morris - John M O'Donnell - Konstantin Olchanski - Chris Pearson - Renee Poutissou - Tamsen Schurman - Andreas Suter - Jan M.Wouters - Piotr Adam Zolnierczuk