Midas: mesadc32.c File Reference
mesadc32.c File Reference
Functions
int mesadc32_Setup (MVME_INTERFACE *mvme, uint32_t base, int mode)
Function Documentation
void mesadc32_AcqCtl (MVME_INTERFACE * mvme, uint32_t base, uint32_t operation)
Definition at line 119 of file mesadc32.c.
uint32_t mesadc32_MSCF16_GainGet (MVME_INTERFACE * mvme, uint32_t base, uint32_t modAdd, int subAdd, uint32_t * data)
Definition at line 224 of file mesadc32.c.
uint32_t mesadc32_MSCF16_GainSet (MVME_INTERFACE * mvme, uint32_t base, uint32_t modAdd, int subAdd, int data)
Definition at line 189 of file mesadc32.c.
uint32_t mesadc32_MSCF16_IDC (MVME_INTERFACE * mvme, uint32_t base, uint32_t modAdd)
Definition at line 162 of file mesadc32.c.
uint32_t mesadc32_MSCF16_RCon (MVME_INTERFACE * mvme, uint32_t base, uint32_t modAdd)
Definition at line 249 of file mesadc32.c.
int mesadc32_ReadData (MVME_INTERFACE * mvme, uint32_t base, uint32_t * pdata, int * nw32)
Definition at line 41 of file mesadc32.c.
uint32_t mesadc32_RegisterRead (MVME_INTERFACE * mvme, uint32_t base, int offset)
Definition at line 59 of file mesadc32.c.
void mesadc32_RegisterWrite (MVME_INTERFACE * mvme, uint32_t base, int offset, uint32_t value)
Definition at line 65 of file mesadc32.c.
void mesadc32_Reset (MVME_INTERFACE * mvme, uint32_t base)
Definition at line 71 of file mesadc32.c.
void mesadc32_ResolutionSet (MVME_INTERFACE * mvme, uint32_t base, uint32_t resolution)
Definition at line 77 of file mesadc32.c.
int mesadc32_Setup (MVME_INTERFACE * mvme, uint32_t base, int mode)
Sets all the necessary paramters for a given configuration. The configuration is provided by the mode argument. Add your own configuration in the case statement. Let me know your setting if you want to include it in the distribution.
Mode 1 :
Parameters:
*mvme VME structure
base Module base address
mode Configuration mode number
Returns:
0: OK. -1: Bad
Definition at line 295 of file mesadc32.c.
void mesadc32_Status (MVME_INTERFACE * mvme, uint32_t base)
Definition at line 266 of file mesadc32.c.
Referenced by mesadc32_Setup().
void mesadc32_ThresholdGet (MVME_INTERFACE * mvme, uint32_t base, uint32_t channel, uint32_t * thres)
Definition at line 105 of file mesadc32.c.
void mesadc32_ThresholdSet (MVME_INTERFACE * mvme, uint32_t base, uint32_t channel, uint32_t thres)
Definition at line 90 of file mesadc32.c.
int rcWait (MVME_INTERFACE * mvme, uint32_t base, uint32_t modAdd, int timeout)
Definition at line 141 of file mesadc32.c.
Referenced by mesadc32_MSCF16_GainGet(), mesadc32_MSCF16_GainSet(), and mesadc32_MSCF16_IDC().
static uint32_t regReadReg (MVME_INTERFACE * mvme, uint32_t base, int offset) [static]
Definition at line 19 of file mesadc32.c.
Referenced by mesadc32_MSCF16_GainGet(), mesadc32_MSCF16_GainSet(), mesadc32_MSCF16_IDC(), mesadc32_ReadData(), mesadc32_RegisterRead(), mesadc32_Setup(), mesadc32_Status(), mesadc32_ThresholdGet(), and rcWait().
static void regWriteReg (MVME_INTERFACE * mvme, uint32_t base, int offset, uint32_t value) [static]
Definition at line 30 of file mesadc32.c.
Referenced by mesadc32_MSCF16_GainGet(), mesadc32_MSCF16_GainSet(), mesadc32_MSCF16_IDC(), mesadc32_MSCF16_RCon(), mesadc32_RegisterWrite(), mesadc32_Reset(), mesadc32_ResolutionSet(), mesadc32_Setup(), mesadc32_ThresholdSet(), and rcWait().
Midas DOC Version 2.3.0 ---- PSI Stefan Ritt ----
Contributions: Pierre-Andre Amaudruz - Sergio Ballestrero - Suzannah Daviel - Doxygen - Peter Green - Qing Gu - Greg Hackman - Gertjan Hofman - Paul Knowles - Exaos Lee - Rudi Meier - Glenn Moloney - Dave Morris - John M O'Donnell - Konstantin Olchanski - Chris Pearson - Renee Poutissou - Tamsen Schurman - Andreas Suter - Jan M.Wouters - Piotr Adam Zolnierczuk