Midas: sis3320.c File Reference
sis3320.c File Reference
Functions
int sis3320_Setup (MVME_INTERFACE *mvme, uint32_t base, int mode)
Function Documentation
static uint32_t regRead (MVME_INTERFACE * mvme, uint32_t base, int offset) [static]
Definition at line 24 of file sis3320.c.
Referenced by sis3320_RegisterRead(), and sis3320_Status().
static void regWrite (MVME_INTERFACE * mvme, uint32_t base, int offset, uint32_t value) [static]
Definition at line 35 of file sis3320.c.
Referenced by sis3320_RegisterWrite(), sis3320_Reset(), and sis3320_Setup().
uint32_t sis3320_RegisterRead (MVME_INTERFACE * mvme, uint32_t base, int offset)
Definition at line 43 of file sis3320.c.
void sis3320_RegisterWrite (MVME_INTERFACE * mvme, uint32_t base, int offset, uint32_t value)
Definition at line 49 of file sis3320.c.
void sis3320_Reset (MVME_INTERFACE * mvme, uint32_t base)
Definition at line 55 of file sis3320.c.
int sis3320_Setup (MVME_INTERFACE * mvme, uint32_t base, int mode)
Sets all the necessary paramters for a given configuration. The configuration is provided by the mode argument. Add your own configuration in the case statement. Let me know your setting if you want to include it in the distribution.
Parameters:
*mvme VME structure
base Module base address
mode Configuration mode number
*nentry number of entries requested and returned.
Returns:
MVME_SUCCESS
Definition at line 83 of file sis3320.c.
void sis3320_Status (MVME_INTERFACE * mvme, uint32_t base)
Definition at line 61 of file sis3320.c.
Referenced by sis3320_Setup().
Midas DOC Version 2.3.0 ---- PSI Stefan Ritt ----
Contributions: Pierre-Andre Amaudruz - Sergio Ballestrero - Suzannah Daviel - Doxygen - Peter Green - Qing Gu - Greg Hackman - Gertjan Hofman - Paul Knowles - Exaos Lee - Rudi Meier - Glenn Moloney - Dave Morris - John M O'Donnell - Konstantin Olchanski - Chris Pearson - Renee Poutissou - Tamsen Schurman - Andreas Suter - Jan M.Wouters - Piotr Adam Zolnierczuk