Midas: sis3820.c File Reference
sis3820.c File Reference
Function Documentation
static uint32_t regRead (MVME_INTERFACE * mvme, DWORD base, int offset) [static]
Definition at line 25 of file sis3820.c.
Referenced by sis3820_DataReady(), sis3820_RegisterRead(), sis3820_ScalerRead(), and sis3820_Status().
static void regWrite (MVME_INTERFACE * mvme, DWORD base, int offset, uint32_t value) [static]
Definition at line 36 of file sis3820.c.
Referenced by sis3820_RegisterWrite(), and sis3820_Reset().
int sis3820_DataReady (MVME_INTERFACE * mvme, DWORD base)
Definition at line 93 of file sis3820.c.
int sis3820_FifoRead (MVME_INTERFACE * mvme, DWORD base, void * pdest, int wcount)
Definition at line 69 of file sis3820.c.
uint32_t sis3820_RegisterRead (MVME_INTERFACE * mvme, DWORD base, int offset)
Definition at line 44 of file sis3820.c.
void sis3820_RegisterWrite (MVME_INTERFACE * mvme, DWORD base, int offset, uint32_t value)
Definition at line 50 of file sis3820.c.
void sis3820_Reset (MVME_INTERFACE * mvme, DWORD base)
Definition at line 87 of file sis3820.c.
uint32_t sis3820_ScalerRead (MVME_INTERFACE * mvme, DWORD base, int ch)
Definition at line 56 of file sis3820.c.
void sis3820_Status (MVME_INTERFACE * mvme, DWORD base)
Definition at line 99 of file sis3820.c.
Midas DOC Version 2.3.0 ---- PSI Stefan Ritt ----
Contributions: Pierre-Andre Amaudruz - Sergio Ballestrero - Suzannah Daviel - Doxygen - Peter Green - Qing Gu - Greg Hackman - Gertjan Hofman - Paul Knowles - Exaos Lee - Rudi Meier - Glenn Moloney - Dave Morris - John M O'Donnell - Konstantin Olchanski - Chris Pearson - Renee Poutissou - Tamsen Schurman - Andreas Suter - Jan M.Wouters - Piotr Adam Zolnierczuk