Midas: v1190B.h File Reference
v1190B.h File Reference
Functions
int v1190_EventRead (MVME_INTERFACE *mvme, DWORD base, DWORD *pdest, int *nentry)
int v1190_DataRead (MVME_INTERFACE *mvme, DWORD base, DWORD *pdest, int nentry)
void v1190_WidthSet (MVME_INTERFACE *mvme, DWORD base, WORD width)
void v1190_OffsetSet (MVME_INTERFACE *mvme, DWORD base, WORD offset)
int v1190_Setup (MVME_INTERFACE *mvme, DWORD base, int mode)
int v1190_Status (MVME_INTERFACE *mvme, DWORD base)
Define Documentation
#define LE_RESOLUTION_100 (WORD) (0x10)
Definition at line 54 of file v1190B.h.
Referenced by begin_of_run(), and v1190_LEResolutionSet().
#define LE_RESOLUTION_200 (WORD) (0x01)
Definition at line 55 of file v1190B.h.
Referenced by begin_of_run(), and v1190_LEResolutionSet().
#define LE_RESOLUTION_800 (WORD) (0x00)
Definition at line 56 of file v1190B.h.
Referenced by begin_of_run(), and v1190_LEResolutionSet().
#define V1190_ACQ_MODE_RO (WORD) (0x0200)
Definition at line 52 of file v1190B.h.
Referenced by v1190_AcqModeRead().
#define V1190_ALMOST_FULL (DWORD) (0x0002)
Definition at line 26 of file v1190B.h.
#define V1190_CONTINUOUS_WO (WORD) (0x0100)
Definition at line 51 of file v1190B.h.
Referenced by v1190_ContinuousSet().
#define V1190_CR_RW (DWORD) (0x1000)
Definition at line 23 of file v1190B.h.
#define V1190_DATA_READY (DWORD) (0x0001)
Definition at line 25 of file v1190B.h.
Referenced by v1190_DataReady().
#define V1190_EDGE_DETECTION_WO (WORD) (0x2200)
Definition at line 46 of file v1190B.h.
Referenced by v1190_SetEdgeDetection().
#define V1190_EVT_CNT_RO (DWORD) (0x101C)
Definition at line 35 of file v1190B.h.
Referenced by v1190_EvtCounter().
#define V1190_EVT_STORED_RO (DWORD) (0x1020)
Definition at line 36 of file v1190B.h.
Referenced by v1190_EvtStored().
#define V1190_FIRM_REV_RO (DWORD) (0x1026)
Definition at line 37 of file v1190B.h.
Referenced by begin_of_run().
#define V1190_FULL (DWORD) (0x0004)
Definition at line 27 of file v1190B.h.
#define V1190_GEO_REG_RW (DWORD) (0x001E)
Definition at line 30 of file v1190B.h.
Referenced by v1190_GeoWrite().
#define V1190_HEADER_ENABLE (DWORD) (0x0010)
Definition at line 29 of file v1190B.h.
#define V1190_LE_RESOLUTION_WO (WORD) (0x2400)
Definition at line 47 of file v1190B.h.
Referenced by v1190_LEResolutionSet().
#define V1190_LEW_RESOLUTION_WO (WORD) (0x2500)
Definition at line 48 of file v1190B.h.
#define V1190_MAX_CHANNELS (DWORD) 64
Definition at line 21 of file v1190B.h.
#define V1190_MICRO_HAND_RO (DWORD) (0x1030)
Definition at line 38 of file v1190B.h.
Referenced by v1190_MicroRead(), and v1190_MicroWrite().
#define V1190_MICRO_RD_OK (WORD) (0x0002)
Definition at line 44 of file v1190B.h.
Referenced by v1190_MicroRead().
#define V1190_MICRO_RW (DWORD) (0x102E)
Definition at line 39 of file v1190B.h.
Referenced by v1190_MicroRead(), and v1190_MicroWrite().
#define V1190_MICRO_TDCID (WORD) (0x6000)
Definition at line 45 of file v1190B.h.
Referenced by v1190_TdcIdList().
#define V1190_MICRO_WR_OK (WORD) (0x0001)
Definition at line 43 of file v1190B.h.
Referenced by v1190_MicroWrite().
#define V1190_MODULE_RESET_WO (DWORD) (0x1014)
Definition at line 31 of file v1190B.h.
Referenced by v1190_SoftReset().
#define V1190_REG_BASE (DWORD) (0x1000)
Definition at line 22 of file v1190B.h.
#define V1190_RESOLUTION_RO (WORD) (0x2600)
Definition at line 49 of file v1190B.h.
Referenced by v1190_ResolutionRead().
#define V1190_SOFT_CLEAR_WO (DWORD) (0x1016)
Definition at line 32 of file v1190B.h.
Referenced by v1190_SoftClear().
#define V1190_SOFT_EVT_RESET_WO (DWORD) (0x1018)
Definition at line 33 of file v1190B.h.
#define V1190_SOFT_TRIGGER_WO (DWORD) (0x101A)
Definition at line 34 of file v1190B.h.
Referenced by v1190_SoftTrigger().
#define V1190_SR_RO (DWORD) (0x1002)
Definition at line 24 of file v1190B.h.
Referenced by v1190_DataReady().
#define V1190_TRIGGER_MATCH (DWORD) (0x0008)
Definition at line 28 of file v1190B.h.
#define V1190_TRIGGER_MATCH_WO (WORD) (0x0000)
Definition at line 50 of file v1190B.h.
Referenced by v1190_TriggerMatchingSet().
#define V1190_WINDOW_OFFSET_WO (WORD) (0x1100)
Definition at line 42 of file v1190B.h.
Referenced by v1190_OffsetSet().
#define V1190_WINDOW_WIDTH_WO (WORD) (0x1000)
Definition at line 41 of file v1190B.h.
Referenced by v1190_WidthSet().
Function Documentation
int udelay (int usec)
Definition at line 623 of file v1190B.c.
Referenced by v1190_MicroRead(), and v1190_MicroWrite().
void v1190_AcqModeRead (MVME_INTERFACE * mvme, DWORD base)
Definition at line 273 of file v1190B.c.
void v1190_ContinuousSet (MVME_INTERFACE * mvme, DWORD base)
Definition at line 301 of file v1190B.c.
int v1190_DataRead (MVME_INTERFACE * mvme, DWORD base, DWORD * pdest, int nentry)
Read data buffer for nentry data.
Parameters:
*mvme VME structure
base Module base address
*pdest destination pointer address
*nentry number of entries requested and returned.
Returns:
Definition at line 99 of file v1190B.c.
Referenced by read_tdc().
int v1190_DataReady (MVME_INTERFACE * mvme, DWORD base)
Definition at line 171 of file v1190B.c.
Referenced by v1190_EventRead().
void v1190_DataReset (MVME_INTERFACE * mvme, DWORD base)
int v1190_EventRead (MVME_INTERFACE * mvme, DWORD base, DWORD * pdest, int * nentry)
Read Data buffer for single event (check delimiters) 0x4... and 0xC...
Parameters:
*mvme VME structure
base Module base address
*pdest destination pointer address
*nentry number of entries requested and returned.
Returns:
Definition at line 45 of file v1190B.c.
Referenced by read_trigger_event().
int v1190_EvtCounter (MVME_INTERFACE * mvme, DWORD base)
Definition at line 195 of file v1190B.c.
int v1190_EvtStored (MVME_INTERFACE * mvme, DWORD base)
Definition at line 183 of file v1190B.c.
int v1190_GeoWrite (MVME_INTERFACE * mvme, DWORD base, int geo)
Definition at line 124 of file v1190B.c.
void v1190_LEResolutionSet (MVME_INTERFACE * mvme, DWORD base, WORD le)
Definition at line 245 of file v1190B.c.
Referenced by begin_of_run().
void v1190_LEWResolutionSet (MVME_INTERFACE * mvme, DWORD base, WORD le, WORD width)
Definition at line 267 of file v1190B.c.
int v1190_MicroCheck (MVME_INTERFACE * mvme, const DWORD base, int what)
int v1190_MicroFlush (MVME_INTERFACE * mvme, const DWORD base)
Definition at line 430 of file v1190B.c.
int v1190_MicroRead (MVME_INTERFACE * mvme, const DWORD base)
Definition at line 408 of file v1190B.c.
Referenced by v1190_AcqModeRead(), v1190_MicroFlush(), v1190_ResolutionRead(), v1190_Status(), and v1190_TdcIdList().
int v1190_MicroWrite (MVME_INTERFACE * mvme, DWORD base, WORD data)
Definition at line 384 of file v1190B.c.
Referenced by v1190_AcqModeRead(), v1190_ContinuousSet(), v1190_LEResolutionSet(), v1190_OffsetSet(), v1190_ResolutionRead(), v1190_SetEdgeDetection(), v1190_Setup(), v1190_Status(), v1190_TdcIdList(), v1190_TriggerMatchingSet(), and v1190_WidthSet().
void v1190_OffsetSet (MVME_INTERFACE * mvme, DWORD base, WORD offset)
Set the offset of the matching window with respect to the trigger. The offset parameter should be in 25ns units. The range is from -2048(0x800) to +40(0x28). Example 0xFE8 == 600ns.
Parameters:
*mvme VME structure
base Module base address
offset offset in ns units
Definition at line 347 of file v1190B.c.
Referenced by begin_of_run().
WORD v1190_Read16 (MVME_INTERFACE * mvme, DWORD base, int offset)
Definition at line 15 of file v1190B.c.
DWORD v1190_Read32 (MVME_INTERFACE * mvme, DWORD base, int offset)
Definition at line 22 of file v1190B.c.
int v1190_ResolutionRead (MVME_INTERFACE * mvme, DWORD base)
Definition at line 226 of file v1190B.c.
void v1190_SetEdgeDetection (MVME_INTERFACE * mvme, DWORD base, int eLeading, int eTrailing)
Definition at line 363 of file v1190B.c.
int v1190_Setup (MVME_INTERFACE * mvme, DWORD base, int mode)
Sets all the necessary paramters for a given configuration. The configuration is provided by the mode argument. Add your own configuration in the case statement. Let me know your setting if you want to include it in the distribution.
Parameters:
*mvme VME structure
base Module base address
mode Configuration mode number
*nentry number of entries requested and returned.
Returns:
MVME_SUCCESS
Definition at line 461 of file v1190B.c.
Referenced by begin_of_run().
void v1190_SoftClear (MVME_INTERFACE * mvme, DWORD base)
Definition at line 149 of file v1190B.c.
Referenced by init_vme_modules(), and read_tdc().
void v1190_SoftReset (MVME_INTERFACE * mvme, DWORD base)
Definition at line 138 of file v1190B.c.
void v1190_SoftTrigger (MVME_INTERFACE * mvme, DWORD base)
Definition at line 160 of file v1190B.c.
int v1190_Status (MVME_INTERFACE * mvme, DWORD base)
Read and display the curent status of the TDC.
Parameters:
*mvme VME structure
base Module base address
Returns:
MVME_SUCCESS, MicroCode error
Definition at line 510 of file v1190B.c.
Referenced by begin_of_run(), init_vme_modules(), and v1190_Setup().
void v1190_TdcIdList (MVME_INTERFACE * mvme, DWORD base)
Definition at line 207 of file v1190B.c.
void v1190_TriggerMatchingSet (MVME_INTERFACE * mvme, DWORD base)
Definition at line 287 of file v1190B.c.
void v1190_WidthSet (MVME_INTERFACE * mvme, DWORD base, WORD width)
Set the width of the matching Window. The width parameter should be in the range of 1 to 4095 (0xFFF). Example 0x14 == 500ns.
Parameters:
*mvme VME structure
base Module base address
width window width in ns units
Returns:
Definition at line 323 of file v1190B.c.
Referenced by begin_of_run().
void v1190_Write16 (MVME_INTERFACE * mvme, DWORD base, int offset, WORD value)
Definition at line 29 of file v1190B.c.
Midas DOC Version 2.3.0 ---- PSI Stefan Ritt ----
Contributions: Pierre-Andre Amaudruz - Sergio Ballestrero - Suzannah Daviel - Doxygen - Peter Green - Qing Gu - Greg Hackman - Gertjan Hofman - Paul Knowles - Exaos Lee - Rudi Meier - Glenn Moloney - Dave Morris - John M O'Donnell - Konstantin Olchanski - Chris Pearson - Renee Poutissou - Tamsen Schurman - Andreas Suter - Jan M.Wouters - Piotr Adam Zolnierczuk