Midas: v1190B.c File Reference
v1190B.c File Reference
Functions
int v1190_EventRead (MVME_INTERFACE *mvme, DWORD base, DWORD *pdest, int *nentry)
int v1190_DataRead (MVME_INTERFACE *mvme, DWORD base, DWORD *pdest, int nentry)
void v1190_WidthSet (MVME_INTERFACE *mvme, DWORD base, WORD width)
void v1190_OffsetSet (MVME_INTERFACE *mvme, DWORD base, WORD offset)
int v1190_Setup (MVME_INTERFACE *mvme, DWORD base, int mode)
int v1190_Status (MVME_INTERFACE *mvme, DWORD base)
Function Documentation
int udelay (int usec)
Definition at line 623 of file v1190B.c.
Referenced by v1190_MicroRead(), and v1190_MicroWrite().
void v1190_AcqModeRead (MVME_INTERFACE * mvme, DWORD base)
Definition at line 273 of file v1190B.c.
void v1190_ContinuousSet (MVME_INTERFACE * mvme, DWORD base)
Definition at line 301 of file v1190B.c.
int v1190_DataRead (MVME_INTERFACE * mvme, DWORD base, DWORD * pdest, int nentry)
Read data buffer for nentry data.
Parameters:
*mvme VME structure
base Module base address
*pdest destination pointer address
*nentry number of entries requested and returned.
Returns:
Definition at line 99 of file v1190B.c.
Referenced by read_tdc().
int v1190_DataReady (MVME_INTERFACE * mvme, DWORD base)
Definition at line 171 of file v1190B.c.
Referenced by v1190_EventRead().
int v1190_EventRead (MVME_INTERFACE * mvme, DWORD base, DWORD * pdest, int * nentry)
Read Data buffer for single event (check delimiters) 0x4... and 0xC...
Parameters:
*mvme VME structure
base Module base address
*pdest destination pointer address
*nentry number of entries requested and returned.
Returns:
Definition at line 45 of file v1190B.c.
Referenced by read_trigger_event().
int v1190_EvtCounter (MVME_INTERFACE * mvme, DWORD base)
Definition at line 195 of file v1190B.c.
int v1190_EvtStored (MVME_INTERFACE * mvme, DWORD base)
Definition at line 183 of file v1190B.c.
int v1190_GeoWrite (MVME_INTERFACE * mvme, DWORD base, int geo)
Definition at line 124 of file v1190B.c.
void v1190_LEResolutionSet (MVME_INTERFACE * mvme, DWORD base, WORD le)
Definition at line 245 of file v1190B.c.
Referenced by begin_of_run().
void v1190_LEWResolutionSet (MVME_INTERFACE * mvme, DWORD base, WORD le, WORD width)
Definition at line 267 of file v1190B.c.
int v1190_MicroFlush (MVME_INTERFACE * mvme, const DWORD base)
Definition at line 430 of file v1190B.c.
int v1190_MicroRead (MVME_INTERFACE * mvme, const DWORD base)
Definition at line 408 of file v1190B.c.
Referenced by v1190_AcqModeRead(), v1190_MicroFlush(), v1190_ResolutionRead(), v1190_Status(), and v1190_TdcIdList().
int v1190_MicroWrite (MVME_INTERFACE * mvme, DWORD base, WORD data)
Definition at line 384 of file v1190B.c.
Referenced by v1190_AcqModeRead(), v1190_ContinuousSet(), v1190_LEResolutionSet(), v1190_OffsetSet(), v1190_ResolutionRead(), v1190_SetEdgeDetection(), v1190_Setup(), v1190_Status(), v1190_TdcIdList(), v1190_TriggerMatchingSet(), and v1190_WidthSet().
void v1190_OffsetSet (MVME_INTERFACE * mvme, DWORD base, WORD offset)
Set the offset of the matching window with respect to the trigger. The offset parameter should be in 25ns units. The range is from -2048(0x800) to +40(0x28). Example 0xFE8 == 600ns.
Parameters:
*mvme VME structure
base Module base address
offset offset in ns units
Definition at line 347 of file v1190B.c.
Referenced by begin_of_run().
WORD v1190_Read16 (MVME_INTERFACE * mvme, DWORD base, int offset)
Definition at line 15 of file v1190B.c.
DWORD v1190_Read32 (MVME_INTERFACE * mvme, DWORD base, int offset)
Definition at line 22 of file v1190B.c.
int v1190_ResolutionRead (MVME_INTERFACE * mvme, DWORD base)
Definition at line 226 of file v1190B.c.
void v1190_SetEdgeDetection (MVME_INTERFACE * mvme, DWORD base, int eLeading, int eTrailing)
Definition at line 363 of file v1190B.c.
int v1190_Setup (MVME_INTERFACE * mvme, DWORD base, int mode)
Sets all the necessary paramters for a given configuration. The configuration is provided by the mode argument. Add your own configuration in the case statement. Let me know your setting if you want to include it in the distribution.
Parameters:
*mvme VME structure
base Module base address
mode Configuration mode number
*nentry number of entries requested and returned.
Returns:
MVME_SUCCESS
Definition at line 461 of file v1190B.c.
Referenced by begin_of_run().
void v1190_SoftClear (MVME_INTERFACE * mvme, DWORD base)
Definition at line 149 of file v1190B.c.
Referenced by init_vme_modules(), and read_tdc().
void v1190_SoftReset (MVME_INTERFACE * mvme, DWORD base)
Definition at line 138 of file v1190B.c.
void v1190_SoftTrigger (MVME_INTERFACE * mvme, DWORD base)
Definition at line 160 of file v1190B.c.
int v1190_Status (MVME_INTERFACE * mvme, DWORD base)
Read and display the curent status of the TDC.
Parameters:
*mvme VME structure
base Module base address
Returns:
MVME_SUCCESS, MicroCode error
Definition at line 510 of file v1190B.c.
Referenced by begin_of_run(), init_vme_modules(), and v1190_Setup().
void v1190_TdcIdList (MVME_INTERFACE * mvme, DWORD base)
Definition at line 207 of file v1190B.c.
void v1190_TriggerMatchingSet (MVME_INTERFACE * mvme, DWORD base)
Definition at line 287 of file v1190B.c.
void v1190_WidthSet (MVME_INTERFACE * mvme, DWORD base, WORD width)
Set the width of the matching Window. The width parameter should be in the range of 1 to 4095 (0xFFF). Example 0x14 == 500ns.
Parameters:
*mvme VME structure
base Module base address
width window width in ns units
Returns:
Definition at line 323 of file v1190B.c.
Referenced by begin_of_run().
void v1190_Write16 (MVME_INTERFACE * mvme, DWORD base, int offset, WORD value)
Definition at line 29 of file v1190B.c.
Midas DOC Version 2.3.0 ---- PSI Stefan Ritt ----
Contributions: Pierre-Andre Amaudruz - Sergio Ballestrero - Suzannah Daviel - Doxygen - Peter Green - Qing Gu - Greg Hackman - Gertjan Hofman - Paul Knowles - Exaos Lee - Rudi Meier - Glenn Moloney - Dave Morris - John M O'Donnell - Konstantin Olchanski - Chris Pearson - Renee Poutissou - Tamsen Schurman - Andreas Suter - Jan M.Wouters - Piotr Adam Zolnierczuk