Midas: v1729.h File Reference
v1729.h File Reference
Functions
int v1729_Setup (MVME_INTERFACE *mvme, DWORD base, int mode)
int v1729_TimeCalibrationRun (MVME_INTERFACE *mvme, DWORD base, int flag)
int v1729_PedestalRun (MVME_INTERFACE *mvme, DWORD base, int loop, int flag)
int v1729_OrderData (MVME_INTERFACE *mvme, DWORD base, WORD *psrce, int *pdest, int nch, int ch, int npt)
Define Documentation
#define V1729_1GSPS (DWORD) 2
Definition at line 60 of file v1729.h.
Referenced by v1729_Setup().
#define V1729_2GSPS (DWORD) 1
Definition at line 61 of file v1729.h.
Referenced by v1729_Setup().
#define V1729_ACQ_START_W (DWORD) (0x1700)
Definition at line 50 of file v1729.h.
Referenced by v1729_AcqStart().
#define V1729_ALL_FOUR (DWORD) (0xF)
Definition at line 48 of file v1729.h.
Referenced by v1729_Setup().
#define V1729_AUTHORIZE_RANDOM (DWORD) (0x8)
Definition at line 38 of file v1729.h.
Referenced by v1729_Setup().
#define V1729_CHANMASK (DWORD) (0x2300)
Definition at line 56 of file v1729.h.
Referenced by v1729_Status().
#define V1729_DATA_FIFO_R (DWORD) (0x0D00)
Definition at line 52 of file v1729.h.
Referenced by v1729_DataRead(), and v1729_TimeCalibrationRun().
#define V1729_DISABLE_ALL (DWORD) (0x0)
Definition at line 43 of file v1729.h.
#define V1729_ENABLE_CH1 (DWORD) (0x1)
Definition at line 44 of file v1729.h.
#define V1729_ENABLE_CH2 (DWORD) (0x2)
Definition at line 45 of file v1729.h.
#define V1729_ENABLE_CH3 (DWORD) (0x4)
Definition at line 46 of file v1729.h.
#define V1729_ENABLE_CH4 (DWORD) (0x8)
Definition at line 47 of file v1729.h.
#define V1729_ERROR -1
Definition at line 19 of file v1729.h.
#define V1729_EXT_TRIGG_NO_MASK (DWORD) (0x10)
Definition at line 40 of file v1729.h.
#define V1729_EXTERNAL_TRIGGER (DWORD) (0x2)
Definition at line 33 of file v1729.h.
Referenced by v1729_Setup().
#define V1729_FALLING_EDGE (DWORD) (0x4)
Definition at line 36 of file v1729.h.
#define V1729_FAST_READ_MODES (DWORD) (0x2100)
Definition at line 54 of file v1729.h.
Referenced by v1729_Status().
#define V1729_FRQ_SAMPLING (DWORD) (0x8100)
Definition at line 58 of file v1729.h.
Referenced by v1729_FrqSamplingSet(), and v1729_Status().
#define V1729_INHIBIT_RANDOM (DWORD) (0x0)
Definition at line 37 of file v1729.h.
Referenced by v1729_Setup().
#define V1729_INTERRUPT_ENABLE (DWORD) (0x8300)
Definition at line 64 of file v1729.h.
Referenced by v1729_Setup().
#define V1729_INTERRUPT_REG (DWORD) (0x8000)
Definition at line 57 of file v1729.h.
Referenced by v1729_AcqStart(), and v1729_isTrigger().
#define V1729_MAX_CHANNEL_SIZE (DWORD) 2560
Definition at line 22 of file v1729.h.
Referenced by v1729_DataRead(), v1729_OrderData(), and v1729_PedestalRun().
#define V1729_MAX_CHANNELS (DWORD) 4
Definition at line 21 of file v1729.h.
Referenced by v1729_DataRead(), and v1729_OrderData().
#define V1729_N_COL (DWORD) (0x2200)
Definition at line 55 of file v1729.h.
Referenced by v1729_NColsGet(), v1729_NColsSet(), and v1729_Status().
#define V1729_NORMAL_TRIGGER (DWORD) (0x0)
Definition at line 39 of file v1729.h.
Referenced by v1729_Setup().
#define V1729_POSTTRIG_LSB (DWORD) (0x1A00)
Definition at line 27 of file v1729.h.
Referenced by v1729_OrderData(), v1729_PedestalRun(), v1729_PostTrigSet(), and v1729_Status().
#define V1729_POSTTRIG_MSB (DWORD) (0x1B00)
Definition at line 28 of file v1729.h.
Referenced by v1729_OrderData(), v1729_PedestalRun(), v1729_PostTrigSet(), and v1729_Status().
#define V1729_PRETRIG_LSB (DWORD) (0x1800)
Definition at line 25 of file v1729.h.
Referenced by v1729_PreTrigSet(), and v1729_Status().
#define V1729_PRETRIG_MSB (DWORD) (0x1900)
Definition at line 26 of file v1729.h.
Referenced by v1729_PreTrigSet(), and v1729_Status().
#define V1729_RAM_SIZE (DWORD) (4*2563)
Definition at line 23 of file v1729.h.
Referenced by v1729_PedestalRun().
#define V1729_RESET_W (DWORD) (0x0800)
Definition at line 24 of file v1729.h.
Referenced by v1729_Reset().
#define V1729_RISING_EDGE (DWORD) (0x0)
Definition at line 35 of file v1729.h.
Referenced by v1729_Setup().
#define V1729_SOFT_OR_DISCR (DWORD) (0x3)
Definition at line 34 of file v1729.h.
#define V1729_SOFT_TRIGGER (DWORD) (0x0)
Definition at line 31 of file v1729.h.
Referenced by v1729_Setup().
#define V1729_SOFT_TRIGGER_W (DWORD) (0x1C00)
Definition at line 51 of file v1729.h.
Referenced by v1729_SoftTrigger().
#define V1729_SUCCESS 1
Definition at line 18 of file v1729.h.
Referenced by v1729_Status().
#define V1729_TRIG_ON_DISCR (DWORD) (0x1)
Definition at line 32 of file v1729.h.
#define V1729_TRIGCHAN (DWORD) (0x1E00)
Definition at line 42 of file v1729.h.
Referenced by v1729_ChannelSelect(), and v1729_Status().
#define V1729_TRIGREC_R (DWORD) (0x2000)
Definition at line 53 of file v1729.h.
Referenced by v1729_OrderData(), and v1729_PedestalRun().
#define V1729_TRIGTYPE (DWORD) (0x1D00)
Definition at line 30 of file v1729.h.
Referenced by v1729_Status(), and v1729_TriggerTypeSet().
#define V1729_VERSION_R (DWORD) (0x8200)
Definition at line 63 of file v1729.h.
Referenced by v1729_Status().
Function Documentation
void v1729_AcqStart (MVME_INTERFACE * mvme, DWORD base)
Definition at line 29 of file v1729.c.
Referenced by begin_of_run(), read_trigger_event(), v1729_PedestalRun(), and v1729_TimeCalibrationRun().
void v1729_ChannelSelect (MVME_INTERFACE * mvme, DWORD base, int value)
Definition at line 276 of file v1729.c.
Referenced by v1729_Setup().
void v1729_DataRead (MVME_INTERFACE * mvme, DWORD base, WORD * pdest, int nch, int npt)
Definition at line 183 of file v1729.c.
Referenced by read_trigger_event(), and v1729_PedestalRun().
void v1729_FrqSamplingSet (MVME_INTERFACE * mvme, DWORD base, int value)
Definition at line 298 of file v1729.c.
Referenced by v1729_Setup().
int v1729_isTrigger (MVME_INTERFACE * mvme, DWORD base)
Definition at line 206 of file v1729.c.
Referenced by read_trigger_event(), v1729_PedestalRun(), and v1729_TimeCalibrationRun().
int v1729_NColsGet (MVME_INTERFACE * mvme, DWORD base)
Definition at line 264 of file v1729.c.
Referenced by v1729_OrderData(), and v1729_Status().
void v1729_NColsSet (MVME_INTERFACE * mvme, DWORD base, int value)
Definition at line 253 of file v1729.c.
Referenced by v1729_Setup().
int v1729_OrderData (MVME_INTERFACE * mvme, DWORD base, WORD * srce, int * dest, int nch, int chan, int npt)
Re-order given channel from srce to dest len is for now frozen to V1729_MAX_CHANNEL_SIZE Does pedestal subtraction if enabled (ped_ok) Doesn't correct for timing.
NOTE: destination cell index[k] computed as 2560+j+end_cell instead of manual formula [2] page 13 (2560+j-end_cell).
Definition at line 595 of file v1729.c.
Referenced by read_trigger_event().
int v1729_PedestalRun (MVME_INTERFACE * mvme, DWORD base, int loop, int flag)
Pedestal extraction. Requires to module to be in setup mode 7 (soft trigger). Show major improvment in the WF reconstruction, but still has 20 bin periodic spikes.
Code not yet guarantee to be fully correct...
Definition at line 426 of file v1729.c.
Referenced by frontend_init().
void v1729_PostTrigSet (MVME_INTERFACE * mvme, DWORD base, int value)
Definition at line 230 of file v1729.c.
Referenced by begin_of_run(), and v1729_Setup().
void v1729_PreTrigSet (MVME_INTERFACE * mvme, DWORD base, int value)
Definition at line 218 of file v1729.c.
Referenced by v1729_Setup().
void v1729_Reset (MVME_INTERFACE * mvme, DWORD base)
Definition at line 41 of file v1729.c.
int v1729_Setup (MVME_INTERFACE * mvme, DWORD base, int mode)
Sets all the necessary paramters for a given configuration. The configuration is provided by the mode argument. Add your own configuration in the case statement. Let me know your setting if you want to include it in the distribution.
Parameters:
*mvme VME structure
base Module base address
mode Configuration mode number
*nentry number of entries requested and returned.
Returns:
MVME_SUCCESS
Definition at line 63 of file v1729.c.
Referenced by begin_of_run(), v1729_PedestalRun(), and v1729_TimeCalibrationRun().
void v1729_SoftTrigger (MVME_INTERFACE * mvme, DWORD base)
Definition at line 287 of file v1729.c.
Referenced by v1729_PedestalRun().
int v1729_Status (MVME_INTERFACE * mvme, DWORD base)
Definition at line 139 of file v1729.c.
Referenced by begin_of_run().
int v1729_TimeCalibrationRun (MVME_INTERFACE * mvme, DWORD base, int flag)
Does Time calibration of all 4 channels. Requires the module to be in random Vernier mode (setup 8). Trigger internally generated for the whole memory.
! Code not yet guarantee to be correct.
Definition at line 318 of file v1729.c.
Referenced by frontend_init().
void v1729_TriggerTypeSet (MVME_INTERFACE * mvme, DWORD base, int value)
Definition at line 242 of file v1729.c.
Referenced by v1729_Setup().
Midas DOC Version 2.3.0 ---- PSI Stefan Ritt ----
Contributions: Pierre-Andre Amaudruz - Sergio Ballestrero - Suzannah Daviel - Doxygen - Peter Green - Qing Gu - Greg Hackman - Gertjan Hofman - Paul Knowles - Exaos Lee - Rudi Meier - Glenn Moloney - Dave Morris - John M O'Donnell - Konstantin Olchanski - Chris Pearson - Renee Poutissou - Tamsen Schurman - Andreas Suter - Jan M.Wouters - Piotr Adam Zolnierczuk