Midas: v1720.c File Reference
v1720.c File Reference
Functions
uint32_t v1720_DataBlockRead (MVME_INTERFACE *mvme, uint32_t base, uint32_t *pdest, uint32_t *nentry)
int v1720_Setup (MVME_INTERFACE *mvme, uint32_t base, int mode)
Function Documentation
static uint32_t regRead (MVME_INTERFACE * mvme, uint32_t base, int offset) [static]
Definition at line 24 of file v1720.c.
Referenced by v1720_AcqCtl(), v1720_BufferFree(), v1720_BufferFreeRead(), v1720_BufferOccupancy(), v1720_ChannelConfig(), v1720_ChannelDACGet(), v1720_ChannelGet(), v1720_DataRead(), v1720_info(), v1720_RegisterRead(), and v1720_Status().
static void regWrite (MVME_INTERFACE * mvme, uint32_t base, int offset, uint32_t value) [static]
Definition at line 35 of file v1720.c.
Referenced by v1720_AcqCtl(), v1720_Align64Set(), v1720_BufferFree(), v1720_ChannelConfig(), v1720_ChannelCtl(), v1720_ChannelDACSet(), v1720_ChannelOUThresholdSet(), v1720_ChannelSet(), v1720_ChannelThresholdSet(), v1720_RegisterWrite(), v1720_Reset(), v1720_Setup(), and v1720_TrgCtl().
void v1720_AcqCtl (MVME_INTERFACE * mvme, uint32_t base, uint32_t operation)
Definition at line 145 of file v1720.c.
void v1720_Align64Set (MVME_INTERFACE * mvme, uint32_t base)
Definition at line 139 of file v1720.c.
uint32_t v1720_BufferFree (MVME_INTERFACE * mvme, uint32_t base, int nbuffer)
Definition at line 233 of file v1720.c.
uint32_t v1720_BufferFreeRead (MVME_INTERFACE * mvme, uint32_t base)
Definition at line 246 of file v1720.c.
uint32_t v1720_BufferOccupancy (MVME_INTERFACE * mvme, uint32_t base, uint32_t channel)
Definition at line 224 of file v1720.c.
void v1720_ChannelConfig (MVME_INTERFACE * mvme, uint32_t base, uint32_t operation)
Definition at line 181 of file v1720.c.
void v1720_ChannelCtl (MVME_INTERFACE * mvme, uint32_t base, uint32_t reg, uint32_t mask)
Definition at line 67 of file v1720.c.
int v1720_ChannelDACGet (MVME_INTERFACE * mvme, uint32_t base, uint32_t channel, uint32_t * dac)
Definition at line 126 of file v1720.c.
void v1720_ChannelDACSet (MVME_INTERFACE * mvme, uint32_t base, uint32_t channel, uint32_t dac)
Definition at line 116 of file v1720.c.
uint32_t v1720_ChannelGet (MVME_INTERFACE * mvme, uint32_t base, uint32_t channel, uint32_t what)
Definition at line 86 of file v1720.c.
void v1720_ChannelOUThresholdSet (MVME_INTERFACE * mvme, uint32_t base, uint32_t channel, uint32_t threshold)
Definition at line 107 of file v1720.c.
void v1720_ChannelSet (MVME_INTERFACE * mvme, uint32_t base, uint32_t channel, uint32_t what, uint32_t that)
Definition at line 73 of file v1720.c.
void v1720_ChannelThresholdSet (MVME_INTERFACE * mvme, uint32_t base, uint32_t channel, uint32_t threshold)
Definition at line 98 of file v1720.c.
uint32_t v1720_DataBlockRead (MVME_INTERFACE * mvme, uint32_t base, uint32_t * pdest, uint32_t * nentry)
v1720_DataBlockRead Read N entries (32bit)
Parameters:
mvme vme structure
base base address
pdest Destination pointer
Returns:
nentry
Definition at line 275 of file v1720.c.
uint32_t v1720_DataRead (MVME_INTERFACE * mvme, uint32_t base, uint32_t * pdata, uint32_t n32w)
Definition at line 252 of file v1720.c.
void v1720_info (MVME_INTERFACE * mvme, uint32_t base, int * nchannels, uint32_t * n32word)
Definition at line 202 of file v1720.c.
uint32_t v1720_RegisterRead (MVME_INTERFACE * mvme, uint32_t base, int offset)
Definition at line 43 of file v1720.c.
void v1720_RegisterWrite (MVME_INTERFACE * mvme, uint32_t base, int offset, uint32_t value)
Definition at line 49 of file v1720.c.
void v1720_Reset (MVME_INTERFACE * mvme, uint32_t base)
Definition at line 55 of file v1720.c.
int v1720_Setup (MVME_INTERFACE * mvme, uint32_t base, int mode)
Sets all the necessary paramters for a given configuration. The configuration is provided by the mode argument. Add your own configuration in the case statement. Let me know your setting if you want to include it in the distribution.
Mode 1 :
Parameters:
*mvme VME structure
base Module base address
mode Configuration mode number
Returns:
0: OK. -1: Bad
Definition at line 319 of file v1720.c.
void v1720_Status (MVME_INTERFACE * mvme, uint32_t base)
Definition at line 296 of file v1720.c.
Referenced by v1720_Setup().
void v1720_TrgCtl (MVME_INTERFACE * mvme, uint32_t base, uint32_t reg, uint32_t mask)
Definition at line 61 of file v1720.c.
Variable Documentation
uint32_t V1720_NSAMPLES_MODE[11]
Initial value:
 { (1<<20), (1<<19), (1<<18), (1<<17), (1<<16), (1<<15)
                               ,(1<<14), (1<<13), (1<<12), (1<<11), (1<<10)}
Definition at line 17 of file v1720.c.
Midas DOC Version 2.3.0 ---- PSI Stefan Ritt ----
Contributions: Pierre-Andre Amaudruz - Sergio Ballestrero - Suzannah Daviel - Doxygen - Peter Green - Qing Gu - Greg Hackman - Gertjan Hofman - Paul Knowles - Exaos Lee - Rudi Meier - Glenn Moloney - Dave Morris - John M O'Donnell - Konstantin Olchanski - Chris Pearson - Renee Poutissou - Tamsen Schurman - Andreas Suter - Jan M.Wouters - Piotr Adam Zolnierczuk