Midas: v1729.c File Reference
v1729.c File Reference
Functions
int v1729_Setup (MVME_INTERFACE *mvme, DWORD base, int mode)
int v1729_TimeCalibrationRun (MVME_INTERFACE *mvme, DWORD base, int flag)
int v1729_PedestalRun (MVME_INTERFACE *mvme, DWORD base, int loop, int flag)
int v1729_OrderData (MVME_INTERFACE *mvme, DWORD base, WORD *srce, int *dest, int nch, int chan, int npt)
Function Documentation
void v1729_AcqStart (MVME_INTERFACE * mvme, DWORD base)
Definition at line 29 of file v1729.c.
Referenced by begin_of_run(), read_trigger_event(), v1729_PedestalRun(), and v1729_TimeCalibrationRun().
void v1729_ChannelSelect (MVME_INTERFACE * mvme, DWORD base, int value)
Definition at line 276 of file v1729.c.
Referenced by v1729_Setup().
void v1729_DataRead (MVME_INTERFACE * mvme, DWORD base, WORD * pdest, int nch, int npt)
Definition at line 183 of file v1729.c.
Referenced by read_trigger_event(), and v1729_PedestalRun().
void v1729_FrqSamplingSet (MVME_INTERFACE * mvme, DWORD base, int value)
Definition at line 298 of file v1729.c.
Referenced by v1729_Setup().
int v1729_isTrigger (MVME_INTERFACE * mvme, DWORD base)
Definition at line 206 of file v1729.c.
Referenced by read_trigger_event(), v1729_PedestalRun(), and v1729_TimeCalibrationRun().
int v1729_NColsGet (MVME_INTERFACE * mvme, DWORD base)
Definition at line 264 of file v1729.c.
Referenced by v1729_OrderData(), and v1729_Status().
void v1729_NColsSet (MVME_INTERFACE * mvme, DWORD base, int value)
Definition at line 253 of file v1729.c.
Referenced by v1729_Setup().
int v1729_OrderData (MVME_INTERFACE * mvme, DWORD base, WORD * srce, int * dest, int nch, int chan, int npt)
Re-order given channel from srce to dest len is for now frozen to V1729_MAX_CHANNEL_SIZE Does pedestal subtraction if enabled (ped_ok) Doesn't correct for timing.
NOTE: destination cell index[k] computed as 2560+j+end_cell instead of manual formula [2] page 13 (2560+j-end_cell).
Definition at line 595 of file v1729.c.
Referenced by read_trigger_event().
int v1729_PedestalRun (MVME_INTERFACE * mvme, DWORD base, int loop, int flag)
Pedestal extraction. Requires to module to be in setup mode 7 (soft trigger). Show major improvment in the WF reconstruction, but still has 20 bin periodic spikes.
Code not yet guarantee to be fully correct...
Definition at line 426 of file v1729.c.
Referenced by frontend_init().
void v1729_PostTrigSet (MVME_INTERFACE * mvme, DWORD base, int value)
Definition at line 230 of file v1729.c.
Referenced by begin_of_run(), and v1729_Setup().
void v1729_PreTrigSet (MVME_INTERFACE * mvme, DWORD base, int value)
Definition at line 218 of file v1729.c.
Referenced by v1729_Setup().
void v1729_Reset (MVME_INTERFACE * mvme, DWORD base)
Definition at line 41 of file v1729.c.
int v1729_Setup (MVME_INTERFACE * mvme, DWORD base, int mode)
Sets all the necessary paramters for a given configuration. The configuration is provided by the mode argument. Add your own configuration in the case statement. Let me know your setting if you want to include it in the distribution.
Parameters:
*mvme VME structure
base Module base address
mode Configuration mode number
*nentry number of entries requested and returned.
Returns:
MVME_SUCCESS
Definition at line 63 of file v1729.c.
Referenced by begin_of_run(), v1729_PedestalRun(), and v1729_TimeCalibrationRun().
void v1729_SoftTrigger (MVME_INTERFACE * mvme, DWORD base)
Definition at line 287 of file v1729.c.
Referenced by v1729_PedestalRun().
int v1729_Status (MVME_INTERFACE * mvme, DWORD base)
Definition at line 139 of file v1729.c.
Referenced by begin_of_run().
int v1729_TimeCalibrationRun (MVME_INTERFACE * mvme, DWORD base, int flag)
Does Time calibration of all 4 channels. Requires the module to be in random Vernier mode (setup 8). Trigger internally generated for the whole memory.
! Code not yet guarantee to be correct.
Definition at line 318 of file v1729.c.
Referenced by frontend_init().
void v1729_TriggerTypeSet (MVME_INTERFACE * mvme, DWORD base, int value)
Definition at line 242 of file v1729.c.
Referenced by v1729_Setup().
Variable Documentation
float Corr_vernier[4] [static]
Definition at line 18 of file v1729.c.
Referenced by v1729_OrderData().
int debug = 1
Definition at line 17 of file v1729.c.
int end_cell [static]
Definition at line 19 of file v1729.c.
Referenced by v1729_OrderData(), and v1729_PedestalRun().
int get_ref = 1 [static]
Definition at line 19 of file v1729.c.
Referenced by v1729_DataRead(), and v1729_OrderData().
int lMAXVER [static]
Definition at line 24 of file v1729.c.
Referenced by v1729_OrderData(), and v1729_TimeCalibrationRun().
int lMINVER [static]
Definition at line 24 of file v1729.c.
Referenced by v1729_OrderData(), and v1729_TimeCalibrationRun().
int ncol [static]
Definition at line 19 of file v1729.c.
Referenced by v1729_OrderData(), and v1729_Status().
float ped[4][V1729_MAX_CHANNEL_SIZE+3] [static]
Definition at line 21 of file v1729.c.
Referenced by v1729_PedestalRun().
int ped_ok = 0 [static]
Definition at line 23 of file v1729.c.
Referenced by v1729_PedestalRun().
float pedestals[V1729_RAM_SIZE] [static]
Definition at line 21 of file v1729.c.
Referenced by v1729_OrderData(), and v1729_PedestalRun().
float pedestalsRms[V1729_RAM_SIZE] [static]
Definition at line 22 of file v1729.c.
Referenced by v1729_PedestalRun().
WORD post_trig [static]
Definition at line 20 of file v1729.c.
Referenced by v1729_OrderData(), and v1729_PedestalRun().
int trig_rec [static]
Definition at line 19 of file v1729.c.
Referenced by v1729_OrderData(), and v1729_PedestalRun().
int vernier_ok = 0 [static]
Definition at line 25 of file v1729.c.
Referenced by v1729_TimeCalibrationRun().
Midas DOC Version 2.3.0 ---- PSI Stefan Ritt ----
Contributions: Pierre-Andre Amaudruz - Sergio Ballestrero - Suzannah Daviel - Doxygen - Peter Green - Qing Gu - Greg Hackman - Gertjan Hofman - Paul Knowles - Exaos Lee - Rudi Meier - Glenn Moloney - Dave Morris - John M O'Donnell - Konstantin Olchanski - Chris Pearson - Renee Poutissou - Tamsen Schurman - Andreas Suter - Jan M.Wouters - Piotr Adam Zolnierczuk