Midas: v1740.c File Reference
v1740.c File Reference
Functions
uint32_t v1740_DataBlockRead (MVME_INTERFACE *mvme, uint32_t base, uint32_t *pdest, uint32_t *nentry)
int v1740_Setup (MVME_INTERFACE *mvme, uint32_t base, int mode)
Function Documentation
static uint32_t regRead (MVME_INTERFACE * mvme, uint32_t base, int offset) [static]
Definition at line 24 of file v1740.c.
Referenced by v1740_AcqCtl(), v1740_BufferFree(), v1740_BufferFreeRead(), v1740_BufferOccupancy(), v1740_DataRead(), v1740_GroupConfig(), v1740_GroupGet(), v1740_GroupSet(), v1740_info(), v1740_RegisterRead(), and v1740_Status().
static void regWrite (MVME_INTERFACE * mvme, uint32_t base, int offset, uint32_t value) [static]
Definition at line 35 of file v1740.c.
Referenced by v1740_AcqCtl(), v1740_BufferFree(), v1740_GroupConfig(), v1740_GroupCtl(), v1740_GroupSet(), v1740_RegisterWrite(), v1740_Reset(), v1740_Setup(), and v1740_TrgCtl().
void v1740_AcqCtl (MVME_INTERFACE * mvme, uint32_t base, uint32_t operation)
Definition at line 98 of file v1740.c.
uint32_t v1740_BufferFree (MVME_INTERFACE * mvme, uint32_t base, int nbuffer)
Definition at line 191 of file v1740.c.
uint32_t v1740_BufferFreeRead (MVME_INTERFACE * mvme, uint32_t base)
Definition at line 204 of file v1740.c.
uint32_t v1740_BufferOccupancy (MVME_INTERFACE * mvme, uint32_t base, uint32_t group)
Definition at line 182 of file v1740.c.
uint32_t v1740_DataBlockRead (MVME_INTERFACE * mvme, uint32_t base, uint32_t * pdest, uint32_t * nentry)
v1740_DataBlockRead Read N entries (32bit)
Parameters:
mvme vme structure
base base address
pdest Destination pointer
Returns:
nentry
Definition at line 235 of file v1740.c.
uint32_t v1740_DataRead (MVME_INTERFACE * mvme, uint32_t base, uint32_t * pdata, uint32_t n32w)
Definition at line 210 of file v1740.c.
void v1740_GroupConfig (MVME_INTERFACE * mvme, uint32_t base, uint32_t operation)
Definition at line 140 of file v1740.c.
void v1740_GroupCtl (MVME_INTERFACE * mvme, uint32_t base, uint32_t reg, uint32_t mask)
Definition at line 67 of file v1740.c.
uint32_t v1740_GroupGet (MVME_INTERFACE * mvme, uint32_t base, uint32_t channel, uint32_t what)
Definition at line 87 of file v1740.c.
void v1740_GroupSet (MVME_INTERFACE * mvme, uint32_t base, uint32_t channel, uint32_t what, uint32_t that)
Definition at line 73 of file v1740.c.
void v1740_info (MVME_INTERFACE * mvme, uint32_t base, int * ngroups, uint32_t * n32word)
Definition at line 161 of file v1740.c.
Referenced by v1740_DataBlockRead().
uint32_t v1740_RegisterRead (MVME_INTERFACE * mvme, uint32_t base, int offset)
Definition at line 43 of file v1740.c.
void v1740_RegisterWrite (MVME_INTERFACE * mvme, uint32_t base, int offset, uint32_t value)
Definition at line 49 of file v1740.c.
void v1740_Reset (MVME_INTERFACE * mvme, uint32_t base)
Definition at line 55 of file v1740.c.
int v1740_Setup (MVME_INTERFACE * mvme, uint32_t base, int mode)
Sets all the necessary paramters for a given configuration. The configuration is provided by the mode argument. Add your own configuration in the case statement. Let me know your setting if you want to include it in the distribution.
Mode 1 :
Parameters:
*mvme VME structure
base Module base address
mode Configuration mode number
Returns:
0: OK. -1: Bad
Definition at line 292 of file v1740.c.
void v1740_Status (MVME_INTERFACE * mvme, uint32_t base)
Definition at line 257 of file v1740.c.
Referenced by v1740_Setup().
void v1740_TrgCtl (MVME_INTERFACE * mvme, uint32_t base, uint32_t reg, uint32_t mask)
Definition at line 61 of file v1740.c.
Variable Documentation
uint32_t V1740_NSAMPLES_MODE[11]
Initial value:
 { (1024*192), (512*192), (256*192), (128*192), (64*192), (32*192)
                               ,(16*192), (8*192), (4*192), (2*192), (192)}
Definition at line 17 of file v1740.c.
Midas DOC Version 2.3.0 ---- PSI Stefan Ritt ----
Contributions: Pierre-Andre Amaudruz - Sergio Ballestrero - Suzannah Daviel - Doxygen - Peter Green - Qing Gu - Greg Hackman - Gertjan Hofman - Paul Knowles - Exaos Lee - Rudi Meier - Glenn Moloney - Dave Morris - John M O'Donnell - Konstantin Olchanski - Chris Pearson - Renee Poutissou - Tamsen Schurman - Andreas Suter - Jan M.Wouters - Piotr Adam Zolnierczuk