Midas: v513.c File Reference
v513.c File Reference
Function Documentation
static uint16_t regRead (MVME_INTERFACE * mvme, DWORD base, int offset) [static]
Definition at line 20 of file v513.c.
Referenced by v513_GetChannelMode(), v513_Read(), v513_RegisterRead(), v513_Reset(), and v513_Status().
static void regWrite (MVME_INTERFACE * mvme, DWORD base, int offset, uint16_t value) [static]
Definition at line 31 of file v513.c.
Referenced by v513_RegisterWrite(), v513_Reset(), v513_SetChannelMode(), and v513_Write().
int v513_GetChannelMode (MVME_INTERFACE * mvme, DWORD base, int channel)
Definition at line 78 of file v513.c.
uint16_t v513_Read (MVME_INTERFACE * mvme, DWORD base)
Definition at line 48 of file v513.c.
uint16_t v513_RegisterRead (MVME_INTERFACE * mvme, DWORD base, int offset)
Definition at line 38 of file v513.c.
void v513_RegisterWrite (MVME_INTERFACE * mvme, DWORD base, int offset, uint16_t value)
Definition at line 43 of file v513.c.
void v513_Reset (MVME_INTERFACE * mvme, DWORD base)
Definition at line 59 of file v513.c.
void v513_SetChannelMode (MVME_INTERFACE * mvme, DWORD base, int channel, int mode)
Definition at line 73 of file v513.c.
void v513_Status (MVME_INTERFACE * mvme, DWORD base)
Definition at line 68 of file v513.c.
void v513_Write (MVME_INTERFACE * mvme, DWORD base, uint16_t data)
Definition at line 53 of file v513.c.
Midas DOC Version 2.3.0 ---- PSI Stefan Ritt ----
Contributions: Pierre-Andre Amaudruz - Sergio Ballestrero - Suzannah Daviel - Doxygen - Peter Green - Qing Gu - Greg Hackman - Gertjan Hofman - Paul Knowles - Exaos Lee - Rudi Meier - Glenn Moloney - Dave Morris - John M O'Donnell - Konstantin Olchanski - Chris Pearson - Renee Poutissou - Tamsen Schurman - Andreas Suter - Jan M.Wouters - Piotr Adam Zolnierczuk