Midas: v792.h File Reference
v792.h File Reference
Data Structures
union v792_Data
struct v792_Data::Entry
struct v792_Data::Header
struct v792_Data::Footer
union v792_StatusRegister1
union v792_StatusRegister2
union v792_ControlRegister1
union v792_BitSet2Register
Functions
int v792_ThresholdWrite (MVME_INTERFACE *mvme, DWORD base, WORD *threshold)
int v792_ThresholdRead (MVME_INTERFACE *mvme, DWORD base, WORD *threshold)
int v792_Setup (MVME_INTERFACE *mvme, DWORD base, int mode)
void v792_ControlRegister1Write (MVME_INTERFACE *mvme, DWORD base, WORD pat)
WORD v792_ControlRegister1Read (MVME_INTERFACE *mvme, DWORD base)
void v792_Trigger (MVME_INTERFACE *mvme, DWORD base)
void v792_printEntry (const v792_Data *v)
Define Documentation
#define V785_SLIDECONST_RW (DWORD) (0x106A)
Definition at line 52 of file v792.h.
#define V792_BIT_CLEAR1_WO (DWORD) (0x1008)
Definition at line 32 of file v792.h.
Referenced by v792_BitSet2Clear(), v792_BitSet2Set(), and v792_SoftReset().
#define V792_BIT_CLEAR2_WO (DWORD) (0x1034)
Definition at line 47 of file v792.h.
Referenced by v792_DataClear(), v792_LowThEnable(), and v792_OnlineSet().
#define V792_BIT_SET1_RW (DWORD) (0x1006)
Definition at line 31 of file v792.h.
Referenced by v792_BitSet2Clear(), v792_BitSet2Set(), and v792_SoftReset().
#define V792_BIT_SET2_RW (DWORD) (0x1032)
Definition at line 46 of file v792.h.
Referenced by v792_BitSet2Read(), v792_DataClear(), v792_EmptyEnable(), and v792_LowThDisable().
#define V792_CR1_RW (DWORD) (0x1010)
Definition at line 37 of file v792.h.
Referenced by v792_ControlRegister1Read(), and v792_ControlRegister1Write().
#define V792_CSR1_RO (DWORD) (0x100E)
Definition at line 36 of file v792.h.
Referenced by v792_CSR1Read(), v792_DataReady(), and v792_isBusy().
#define V792_CSR2_RO (DWORD) (0x1022)
Definition at line 40 of file v792.h.
Referenced by v792_CSR2Read().
#define V792_DELAY_CLEAR_RW (DWORD) (0x102E)
Definition at line 45 of file v792.h.
#define V792_EVT_CNT_H_RO (DWORD) (0x1026)
Definition at line 42 of file v792.h.
Referenced by v792_EvtCntRead().
#define V792_EVT_CNT_L_RO (DWORD) (0x1024)
Definition at line 41 of file v792.h.
Referenced by v792_EvtCntRead().
#define V792_EVT_CNT_RST_WO (DWORD) (0x1040)
Definition at line 49 of file v792.h.
Referenced by v792_EvtCntReset().
#define V792_EVTRIG_REG_RW (DWORD) (0x1020)
Definition at line 39 of file v792.h.
Referenced by v792_EvtTriggerSet(), v792_IntDisable(), and v792_IntEnable().
#define V792_FIRM_REV (DWORD) (0x1000)
Definition at line 29 of file v792.h.
Referenced by v792_isPresent(), and v792_Status().
#define V792_GEO_ADDR_RW (DWORD) (0x1002)
Definition at line 30 of file v792.h.
#define V792_INCR_EVT_WO (DWORD) (0x1028)
Definition at line 43 of file v792.h.
#define V792_INCR_OFFSET_WO (DWORD) (0x102A)
Definition at line 44 of file v792.h.
#define V792_INT_LEVEL_WO (DWORD) (0x100A)
Definition at line 34 of file v792.h.
Referenced by v792_IntSet().
#define V792_INT_VECTOR_WO (DWORD) (0x100C)
Definition at line 35 of file v792.h.
Referenced by v792_IntSet().
#define V792_IPED_RW (DWORD) (0x1060)
Definition at line 50 of file v792.h.
Referenced by v792_Status().
#define V792_MAX_CHANNELS (DWORD) 32
Definition at line 27 of file v792.h.
Referenced by begin_of_run(), v792_Status(), v792_ThresholdRead(), and v792_ThresholdWrite().
#define V792_REG_BASE (DWORD) (0x1000)
Definition at line 28 of file v792.h.
#define V792_SINGLE_RST_WO (DWORD) (0x1016)
Definition at line 38 of file v792.h.
Referenced by v792_SingleShotReset().
#define V792_SOFT_RESET (DWORD) (0x1<<7)
Definition at line 33 of file v792.h.
#define V792_SWCOMM_WO (DWORD) (0x1068)
Definition at line 51 of file v792.h.
Referenced by v792_Trigger().
#define V792_TEST_EVENT_WO (DWORD) (0x103E)
Definition at line 48 of file v792.h.
#define V792_THRES_BASE (DWORD) (0x1080)
Definition at line 53 of file v792.h.
Referenced by v792_ThresholdRead(), and v792_ThresholdWrite().
Enumeration Type Documentation
enum v792_DataType
Enumerator:
v792_typeMeasurement
v792_typeHeader
v792_typeFooter
v792_typeFiller
Definition at line 94 of file v792.h.
Function Documentation
void v792_BitSet2Clear (MVME_INTERFACE * mvme, DWORD base, WORD pat)
Definition at line 215 of file v792.c.
int v792_BitSet2Read (MVME_INTERFACE * mvme, DWORD base)
Definition at line 192 of file v792.c.
Referenced by v792_Status().
void v792_BitSet2Set (MVME_INTERFACE * mvme, DWORD base, WORD pat)
Definition at line 204 of file v792.c.
WORD v792_ControlRegister1Read (MVME_INTERFACE * mvme, DWORD base)
read Control Register 1 (0x1010,16 bit)
Definition at line 369 of file v792.c.
void v792_ControlRegister1Write (MVME_INTERFACE * mvme, DWORD base, WORD pat)
write Control Register 1 (0x1010,16 bit)
Definition at line 383 of file v792.c.
void v792_CrateSet (MVME_INTERFACE * mvme, DWORD base, DWORD * evtcnt)
int v792_CSR1Read (MVME_INTERFACE * mvme, DWORD base)
Definition at line 151 of file v792.c.
Referenced by begin_of_run(), v792_isEvtReady(), and v792_Status().
int v792_CSR2Read (MVME_INTERFACE * mvme, DWORD base)
Definition at line 180 of file v792.c.
Referenced by v792_Status().
void v792_DataClear (MVME_INTERFACE * mvme, DWORD base)
Definition at line 226 of file v792.c.
Referenced by begin_of_run(), and read_trigger_event().
int v792_DataRead (MVME_INTERFACE * mvme, DWORD base, DWORD * pdest, int * nentry)
Definition at line 73 of file v792.c.
int v792_DataReady (MVME_INTERFACE * mvme, DWORD base)
Definition at line 308 of file v792.c.
Referenced by poll_event(), v792_DataRead(), and v792_EventRead().
void v792_DelayClearSet (MVME_INTERFACE * mvme, DWORD base, int delay)
void v792_EmptyEnable (MVME_INTERFACE * mvme, DWORD base)
Definition at line 278 of file v792.c.
Referenced by v792_Setup().
int v792_EventRead (MVME_INTERFACE * mvme, DWORD base, DWORD * pdest, int * nentry)
Definition at line 41 of file v792.c.
Referenced by read_trigger_event(), and read_v792().
void v792_EvtCntRead (MVME_INTERFACE * mvme, DWORD base, DWORD * evtcnt)
Definition at line 139 of file v792.c.
Referenced by read_trigger_event(), read_v792(), and v792_Status().
void v792_EvtCntReset (MVME_INTERFACE * mvme, DWORD base)
Definition at line 288 of file v792.c.
void v792_EvtTriggerSet (MVME_INTERFACE * mvme, DWORD base, int count)
Definition at line 128 of file v792.c.
void v792_IntDisable (MVME_INTERFACE * mvme, DWORD base)
Definition at line 352 of file v792.c.
void v792_IntEnable (MVME_INTERFACE * mvme, DWORD base, int level)
Definition at line 339 of file v792.c.
void v792_IntSet (MVME_INTERFACE * mvme, DWORD base, int level, int vector)
Definition at line 328 of file v792.c.
int v792_isEvtReady (MVME_INTERFACE * mvme, DWORD base)
Definition at line 320 of file v792.c.
int v792_isPresent (MVME_INTERFACE * mvme, DWORD base)
Definition at line 543 of file v792.c.
void v792_LowThDisable (MVME_INTERFACE * mvme, DWORD base)
Definition at line 268 of file v792.c.
void v792_LowThEnable (MVME_INTERFACE * mvme, DWORD base)
Definition at line 258 of file v792.c.
Referenced by v792_Setup().
void v792_OnlineSet (MVME_INTERFACE * mvme, DWORD base)
Definition at line 248 of file v792.c.
Referenced by v792_Setup().
void v792_printEntry (const v792_Data * v)
decoded printout of readout entry Not to be trusted for data decoding but acceptable for display purpose as its implementation is strongly compiler dependent and not flawless.
Parameters:
v
Definition at line 519 of file v792.c.
WORD v792_Read16 (MVME_INTERFACE * mvme, DWORD base, int offset)
Definition at line 24 of file v792.c.
Referenced by v792_Status().
int v792_Setup (MVME_INTERFACE * mvme, DWORD base, int mode)
Sets all the necessary paramters for a given configuration. The configuration is provided by the mode argument. Add your own configuration in the case statement. Let me know your setting if you want to include it in the distribution.
Parameters:
*mvme VME structure
base Module base address
mode Configuration mode number
*nentry number of entries requested and returned.
Returns:
MVME_SUCCESS
Definition at line 415 of file v792.c.
Referenced by begin_of_run().
void v792_SingleShotReset (MVME_INTERFACE * mvme, DWORD base)
Definition at line 298 of file v792.c.
Referenced by init_vme_modules().
void v792_SoftReset (MVME_INTERFACE * mvme, DWORD base)
Definition at line 237 of file v792.c.
void v792_Status (MVME_INTERFACE * mvme, DWORD base)
Definition at line 444 of file v792.c.
Referenced by init_vme_modules().
int v792_ThresholdRead (MVME_INTERFACE * mvme, DWORD base, WORD * threshold)
Read Thresholds
Definition at line 113 of file v792.c.
Referenced by v792_Status().
int v792_ThresholdWrite (MVME_INTERFACE * mvme, DWORD base, WORD * threshold)
Write Thresholds and read them back
Definition at line 91 of file v792.c.
Referenced by begin_of_run().
void v792_Trigger (MVME_INTERFACE * mvme, DWORD base)
cause a software trigger
Definition at line 395 of file v792.c.
void v792_Write16 (MVME_INTERFACE * mvme, DWORD base, int offset, WORD value)
Definition at line 30 of file v792.c.
Midas DOC Version 2.3.0 ---- PSI Stefan Ritt ----
Contributions: Pierre-Andre Amaudruz - Sergio Ballestrero - Suzannah Daviel - Doxygen - Peter Green - Qing Gu - Greg Hackman - Gertjan Hofman - Paul Knowles - Exaos Lee - Rudi Meier - Glenn Moloney - Dave Morris - John M O'Donnell - Konstantin Olchanski - Chris Pearson - Renee Poutissou - Tamsen Schurman - Andreas Suter - Jan M.Wouters - Piotr Adam Zolnierczuk