Midas: v895.h File Reference
v895.h File Reference
Function Documentation
uint16_t v895_readReg16 (MVME_INTERFACE * mvme, int base, int ireg)
Definition at line 35 of file v895.h.
Referenced by v895_Status().
uint8_t v895_readReg8 (MVME_INTERFACE * mvme, int base, int ireg)
Definition at line 21 of file v895.h.
int v895_Status (MVME_INTERFACE * mvme, int base)
Definition at line 49 of file v895.h.
Referenced by init_vme_modules().
void v895_TestPulse (MVME_INTERFACE * mvme, int base)
Definition at line 59 of file v895.h.
void v895_writeReg16 (MVME_INTERFACE * mvme, int base, int ireg, uint16_t value)
Definition at line 42 of file v895.h.
Referenced by init_vme_modules(), and v895_TestPulse().
void v895_writeReg8 (MVME_INTERFACE * mvme, int base, int ireg, uint8_t value)
Definition at line 28 of file v895.h.
Midas DOC Version 2.3.0 ---- PSI Stefan Ritt ----
Contributions: Pierre-Andre Amaudruz - Sergio Ballestrero - Suzannah Daviel - Doxygen - Peter Green - Qing Gu - Greg Hackman - Gertjan Hofman - Paul Knowles - Exaos Lee - Rudi Meier - Glenn Moloney - Dave Morris - John M O'Donnell - Konstantin Olchanski - Chris Pearson - Renee Poutissou - Tamsen Schurman - Andreas Suter - Jan M.Wouters - Piotr Adam Zolnierczuk