Midas: vmeio.h File Reference
vmeio.h File Reference
Functions
void vmeio_SyncWrite (MVME_INTERFACE *mvme, DWORD base, DWORD data)
void vmeio_AsyncWrite (MVME_INTERFACE *mvme, DWORD base, DWORD data)
void vmeio_OutputSet (MVME_INTERFACE *mvme, DWORD base, DWORD data)
int vmeio_CsrRead (MVME_INTERFACE *mvme, DWORD base)
int vmeio_AsyncRead (MVME_INTERFACE *myvme, DWORD base)
int vmeio_SyncRead (MVME_INTERFACE *myvme, DWORD base)
void vmeio_StrobeClear (MVME_INTERFACE *mvme, DWORD base)
void vmeio_IntEnable (MVME_INTERFACE *myvme, DWORD base, int input)
void vmeio_IntRearm (MVME_INTERFACE *myvme, DWORD base, int input)
Define Documentation
#define VMEIO_CLSTB (0x1c)
Definition at line 23 of file vmeio.h.
#define VMEIO_INTSRC (0x04)
Definition at line 16 of file vmeio.h.
Referenced by vmeio_IntRearm().
#define VMEIO_IRQENBL (0x00)
Definition at line 15 of file vmeio.h.
Referenced by vmeio_IntEnable().
#define VMEIO_OUTLATCH (0x10)
Definition at line 19 of file vmeio.h.
Referenced by vmeio_AsyncWrite().
#define VMEIO_OUTPULSE (0x0c)
Definition at line 18 of file vmeio.h.
Referenced by vmeio_SyncWrite().
#define VMEIO_OUTSET (0x08)
Definition at line 17 of file vmeio.h.
Referenced by vmeio_OutputSet().
#define VMEIO_RDASYNC (0x18)
Definition at line 21 of file vmeio.h.
Referenced by vmeio_AsyncRead().
#define VMEIO_RDCNTL (0x1c)
Definition at line 22 of file vmeio.h.
Referenced by vmeio_CsrRead(), and vmeio_StrobeClear().
#define VMEIO_RDSYNC (0x14)
Definition at line 20 of file vmeio.h.
Referenced by vmeio_SyncRead().
Function Documentation
int vmeio_AsyncRead (MVME_INTERFACE * myvme, DWORD base)
Read from the Async register
Parameters:
myvme vme structure
base VMEIO base address
Returns:
Async_Reg
Definition at line 84 of file vmeio.c.
void vmeio_AsyncWrite (MVME_INTERFACE * myvme, DWORD base, DWORD data)
Writee to the Async output (latch mode)
Parameters:
myvme vme structure
base VMEIO base address
data data to be written
Returns:
void
Definition at line 54 of file vmeio.c.
Referenced by end_of_run(), pause_run(), and resume_run().
int vmeio_CsrRead (MVME_INTERFACE * myvme, DWORD base)
Read the CSR register
Parameters:
myvme vme structure
base VMEIO base address
Returns:
CSR status
Definition at line 68 of file vmeio.c.
Referenced by init_vme_modules(), and poll_event().
void vmeio_IntEnable (MVME_INTERFACE * myvme, DWORD base, int input)
Enable Interrupt source. Only any of the first 8 inputs can generate interrupt.
Parameters:
myvme vme structure
base VMEIO base address
input inputs 0..7 (LSB)
Returns:
void
Definition at line 132 of file vmeio.c.
void vmeio_IntRearm (MVME_INTERFACE * myvme, DWORD base, int input)
Select Interrupt source and arm interrupt The CSR should be reset before this operation. In Sync mode the strobe and the input have to be in coincidence. In Async mode a logical level on the input will trigger the interrupt.
Parameters:
myvme vme structure
base VMEIO base address
input inputs 0..7 if 1=> Sync, 0=> Async
Returns:
void
Definition at line 150 of file vmeio.c.
void vmeio_OutputSet (MVME_INTERFACE * myvme, DWORD base, DWORD data)
Set output in pulse mode
Parameters:
myvme vme structure
base VMEIO base address
data data to be written
Returns:
void
Definition at line 24 of file vmeio.c.
Referenced by begin_of_run(), disable_trigger(), enable_trigger(), and init_vme_modules().
void vmeio_StrobeClear (MVME_INTERFACE * myvme, DWORD base)
Clear Strobe input
Parameters:
myvme vme structure
base VMEIO base address
Returns:
void
Definition at line 116 of file vmeio.c.
Referenced by init_vme_modules().
int vmeio_SyncRead (MVME_INTERFACE * myvme, DWORD base)
Read from the Sync register
Parameters:
myvme vme structure
base VMEIO base address
Returns:
Sync_Reg
Definition at line 100 of file vmeio.c.
void vmeio_SyncWrite (MVME_INTERFACE * myvme, DWORD base, DWORD data)
Write to the sync output (pulse mode)
Parameters:
myvme vme structure
base VMEIO base address
data data to be written
Returns:
void
Definition at line 39 of file vmeio.c.
Referenced by resume_run().
Midas DOC Version 2.3.0 ---- PSI Stefan Ritt ----
Contributions: Pierre-Andre Amaudruz - Sergio Ballestrero - Suzannah Daviel - Doxygen - Peter Green - Qing Gu - Greg Hackman - Gertjan Hofman - Paul Knowles - Exaos Lee - Rudi Meier - Glenn Moloney - Dave Morris - John M O'Donnell - Konstantin Olchanski - Chris Pearson - Renee Poutissou - Tamsen Schurman - Andreas Suter - Jan M.Wouters - Piotr Adam Zolnierczuk