Midas: vpc6.h File Reference
vpc6.h File Reference
Data Structures
union vpc6_Reg
struct vpc6_Reg::Entry1
struct vpc6_Reg::Entry2
Functions
void vpc6_PATypeWrite (MVME_INTERFACE *mvme, DWORD base, WORD data)
int vpc6_PortTypeRead (MVME_INTERFACE *mvme, DWORD base, WORD port)
int vpc6_PATypeRead (MVME_INTERFACE *mvme, DWORD base)
int vpc6_CfgRetrieve (MVME_INTERFACE *mvme, DWORD base, WORD port)
int vpc6_PortRegRBRead (MVME_INTERFACE *mvme, DWORD base, WORD port)
int vpc6_PortRegRead (MVME_INTERFACE *mvme, DWORD base, WORD port)
void vpc6_PortDisplay (WORD type, WORD port, DWORD *reg)
void vpc6_EntryPrint (WORD type, WORD chip, const vpc6_Reg *v)
Define Documentation
#define ALL_CHANNELS -1
Definition at line 34 of file vpc6.h.
Referenced by vpc6_ASDModeSet().
#define VPC6_3ASD_3BUCK 0x444
Definition at line 32 of file vpc6.h.
Referenced by vpc6_Setup().
#define VPC6_3BUCK_3ASD 0x111
Definition at line 33 of file vpc6.h.
Referenced by vpc6_Setup().
#define VPC6_ALL_ASD 0x000
Definition at line 31 of file vpc6.h.
Referenced by vpc6_Setup().
#define VPC6_ALL_BUCKEYE 0x555
Definition at line 30 of file vpc6.h.
Referenced by vpc6_Setup().
#define VPC6_ASD01 0
Definition at line 29 of file vpc6.h.
Referenced by vpc6_EntryPrint(), and vpc6_PortDisplay().
#define VPC6_BUCKEYE 1
Definition at line 64 of file vpc6.h.
Referenced by vpc6_EntryPrint().
#define VPC6_CFG_RW (WORD) (0x0010)
Definition at line 26 of file vpc6.h.
Referenced by vpc6_ASDHysteresisSet(), vpc6_ASDModeSet(), vpc6_ASDRegSet(), vpc6_ASDThresholdSet(), and vpc6_PortRegRead().
#define VPC6_CMD_WO (WORD) (0x000C)
Definition at line 25 of file vpc6.h.
Referenced by vpc6_CfgRetrieve(), and vpc6_PortCfgLoad().
#define VPC6_CR_RW (WORD) (0x0004)
Definition at line 24 of file vpc6.h.
Referenced by vpc6_PATypeRead(), vpc6_PATypeWrite(), vpc6_PortRegRBRead(), vpc6_PortRegRead(), and vpc6_PortTypeRead().
#define VPC6_EXTERNALCAP 0x4
Definition at line 69 of file vpc6.h.
#define VPC6_KILL 0x7
Definition at line 70 of file vpc6.h.
#define VPC6_LARGECAP 0x3
Definition at line 68 of file vpc6.h.
#define VPC6_MEDIUMCAP 0x2
Definition at line 67 of file vpc6.h.
#define VPC6_NORMAL 0x0
Definition at line 65 of file vpc6.h.
#define VPC6_PARAM_ERROR 100
Definition at line 22 of file vpc6.h.
Referenced by vpc6_PortCfgLoad().
#define VPC6_RBCK_RO (WORD) (0x0110)
Definition at line 27 of file vpc6.h.
Referenced by vpc6_PortRegRBRead().
#define VPC6_SMALLCAP 0x1
Definition at line 66 of file vpc6.h.
#define VPC6_SR_RO (WORD) (0x0000)
Definition at line 23 of file vpc6.h.
Referenced by vpc6_isPortBusy().
#define VPC6_SUCCESS 1
Definition at line 21 of file vpc6.h.
Referenced by vpc6_CfgRetrieve(), vpc6_PortCfgLoad(), vpc6_PortRegRBRead(), and vpc6_PortRegRead().
Enumeration Type Documentation
enum vpc6_ASDDataType
Enumerator:
vpc6_asd_ch1_8
vpc6_asd_ch9_16
Definition at line 38 of file vpc6.h.
Function Documentation
void vpc6_ASDDefaultLoad (MVME_INTERFACE * mvme, DWORD base, WORD port)
Definition at line 344 of file vpc6.c.
int vpc6_ASDHysteresisSet (MVME_INTERFACE * mvme, DWORD base, WORD port, float hysteresis)
Definition at line 488 of file vpc6.c.
int vpc6_ASDModeSet (MVME_INTERFACE * mvme, DWORD base, WORD port, int channel, int mode)
Definition at line 397 of file vpc6.c.
void vpc6_ASDRegSet (MVME_INTERFACE * mvme, DWORD base, WORD port, WORD reg, vpc6_Reg * Reg)
Definition at line 382 of file vpc6.c.
Referenced by vpc6_ASDDefaultLoad(), vpc6_ASDHysteresisSet(), vpc6_ASDModeSet(), and vpc6_ASDThresholdSet().
int vpc6_ASDThresholdSet (MVME_INTERFACE * mvme, DWORD base, WORD port, int threshold)
Definition at line 452 of file vpc6.c.
int vpc6_BuckeyeModeSet (MVME_INTERFACE * mvme, DWORD base, WORD port, int channel, int mode)
Definition at line 524 of file vpc6.c.
int vpc6_CfgLoad (MVME_INTERFACE * mvme, DWORD base, WORD port)
int vpc6_CfgRetrieve (MVME_INTERFACE * mvme, DWORD base, WORD port)
Retrieve bit string full configuration from a given port. Loads bit string into Readback registers that can then be read. the port is either ASD01 or Buckeye for now.
Definition at line 121 of file vpc6.c.
Referenced by vpc6_ASDHysteresisSet(), vpc6_ASDModeSet(), and vpc6_ASDThresholdSet().
void vpc6_EntryPrint (WORD type, WORD chip, const vpc6_Reg * v)
decoded printout of readout entry for ASD type preamp Not to be trusted for data decoding but acceptable for display purpose as its implementation is strongly compiler dependent and not flawless.
Parameters:
v
Definition at line 238 of file vpc6.c.
Referenced by vpc6_PortDisplay().
int vpc6_isPortBusy (MVME_INTERFACE * mvme, DWORD base, WORD port)
Definition at line 19 of file vpc6.c.
Referenced by vpc6_CfgRetrieve(), vpc6_PortCfgLoad(), vpc6_PortRegRBRead(), and vpc6_Status().
int vpc6_PATypeRead (MVME_INTERFACE * mvme, DWORD base)
Read the 6 AP type of the board (either ASD01 or Buckeye for now.
Definition at line 51 of file vpc6.c.
void vpc6_PATypeWrite (MVME_INTERFACE * mvme, DWORD base, WORD data)
Setup Preamp type of the board (2 bit per PA) 00 : ASD, 01 : Buckeye
Definition at line 35 of file vpc6.c.
Referenced by vpc6_Setup().
void vpc6_PortDisplay (WORD type, WORD port, DWORD * reg)
decoded printout of readout entry
Definition at line 220 of file vpc6.c.
Referenced by vpc6_PortRegRBRead(), and vpc6_PortRegRead().
int vpc6_PortRegRBRead (MVME_INTERFACE * mvme, DWORD base, WORD port)
Read the Readback and Display in a readable form the Port setting No action to the PA board
Definition at line 155 of file vpc6.c.
int vpc6_PortRegRead (MVME_INTERFACE * mvme, DWORD base, WORD port)
Read the Register and Display in a readable form the Port setting No action to the PA board
Definition at line 192 of file vpc6.c.
int vpc6_PortTypeRead (MVME_INTERFACE * mvme, DWORD base, WORD port)
Read Port type of the board (either ASD01 or Buckeye for now) return the type of the requested port
Definition at line 67 of file vpc6.c.
Referenced by vpc6_Status().
Midas DOC Version 2.3.0 ---- PSI Stefan Ritt ----
Contributions: Pierre-Andre Amaudruz - Sergio Ballestrero - Suzannah Daviel - Doxygen - Peter Green - Qing Gu - Greg Hackman - Gertjan Hofman - Paul Knowles - Exaos Lee - Rudi Meier - Glenn Moloney - Dave Morris - John M O'Donnell - Konstantin Olchanski - Chris Pearson - Renee Poutissou - Tamsen Schurman - Andreas Suter - Jan M.Wouters - Piotr Adam Zolnierczuk