Midas: vpc6.c File Reference
vpc6.c File Reference
Functions
void vpc6_PATypeWrite (MVME_INTERFACE *mvme, DWORD base, WORD data)
int vpc6_PATypeRead (MVME_INTERFACE *mvme, DWORD base)
int vpc6_PortTypeRead (MVME_INTERFACE *mvme, DWORD base, WORD port)
int vpc6_PortCfgLoad (MVME_INTERFACE *mvme, DWORD base, WORD port)
int vpc6_CfgRetrieve (MVME_INTERFACE *mvme, DWORD base, WORD port)
int vpc6_PortRegRBRead (MVME_INTERFACE *mvme, DWORD base, WORD port)
int vpc6_PortRegRead (MVME_INTERFACE *mvme, DWORD base, WORD port)
void vpc6_PortDisplay (WORD type, WORD port, DWORD *reg)
void vpc6_EntryPrint (WORD type, WORD chip, const vpc6_Reg *v)
int vpc6_Setup (MVME_INTERFACE *mvme, DWORD base, int mode)
Function Documentation
void vpc6_ASDDefaultLoad (MVME_INTERFACE * mvme, DWORD base, WORD port)
Definition at line 344 of file vpc6.c.
int vpc6_ASDHysteresisSet (MVME_INTERFACE * mvme, DWORD base, WORD port, float value)
Definition at line 488 of file vpc6.c.
int vpc6_ASDModeSet (MVME_INTERFACE * mvme, DWORD base, WORD port, int channel, int mode)
Definition at line 397 of file vpc6.c.
void vpc6_ASDRegSet (MVME_INTERFACE * mvme, DWORD base, WORD port, WORD reg, vpc6_Reg * Reg)
Definition at line 382 of file vpc6.c.
Referenced by vpc6_ASDDefaultLoad(), vpc6_ASDHysteresisSet(), vpc6_ASDModeSet(), and vpc6_ASDThresholdSet().
int vpc6_ASDThresholdSet (MVME_INTERFACE * mvme, DWORD base, WORD port, int value)
Definition at line 452 of file vpc6.c.
int vpc6_BuckeyeModeSet (MVME_INTERFACE * mvme, DWORD base, WORD port, int channel, int mode)
Definition at line 524 of file vpc6.c.
int vpc6_CfgRetrieve (MVME_INTERFACE * mvme, DWORD base, WORD port)
Retrieve bit string full configuration from a given port. Loads bit string into Readback registers that can then be read. the port is either ASD01 or Buckeye for now.
Definition at line 121 of file vpc6.c.
Referenced by vpc6_ASDHysteresisSet(), vpc6_ASDModeSet(), and vpc6_ASDThresholdSet().
void vpc6_EntryPrint (WORD type, WORD chip, const vpc6_Reg * v)
decoded printout of readout entry for ASD type preamp Not to be trusted for data decoding but acceptable for display purpose as its implementation is strongly compiler dependent and not flawless.
Parameters:
v
Definition at line 238 of file vpc6.c.
Referenced by vpc6_PortDisplay().
int vpc6_isPortBusy (MVME_INTERFACE * mvme, DWORD base, WORD port)
Definition at line 19 of file vpc6.c.
Referenced by vpc6_CfgRetrieve(), vpc6_PortCfgLoad(), vpc6_PortRegRBRead(), and vpc6_Status().
int vpc6_PATypeRead (MVME_INTERFACE * mvme, DWORD base)
Read the 6 AP type of the board (either ASD01 or Buckeye for now.
Definition at line 51 of file vpc6.c.
void vpc6_PATypeWrite (MVME_INTERFACE * mvme, DWORD base, WORD data)
Setup Preamp type of the board (2 bit per PA) 00 : ASD, 01 : Buckeye
Definition at line 35 of file vpc6.c.
Referenced by vpc6_Setup().
int vpc6_PortCfgLoad (MVME_INTERFACE * mvme, DWORD base, WORD port)
Load full configuration for a given port. the port is either ASD01 or Buckeye for now.
Definition at line 84 of file vpc6.c.
Referenced by vpc6_ASDHysteresisSet(), vpc6_ASDModeSet(), and vpc6_ASDThresholdSet().
void vpc6_PortDisplay (WORD type, WORD port, DWORD * reg)
decoded printout of readout entry
Definition at line 220 of file vpc6.c.
Referenced by vpc6_PortRegRBRead(), and vpc6_PortRegRead().
int vpc6_PortRegRBRead (MVME_INTERFACE * mvme, DWORD base, WORD port)
Read the Readback and Display in a readable form the Port setting No action to the PA board
Definition at line 155 of file vpc6.c.
int vpc6_PortRegRead (MVME_INTERFACE * mvme, DWORD base, WORD port)
Read the Register and Display in a readable form the Port setting No action to the PA board
Definition at line 192 of file vpc6.c.
int vpc6_PortTypeRead (MVME_INTERFACE * mvme, DWORD base, WORD port)
Read Port type of the board (either ASD01 or Buckeye for now) return the type of the requested port
Definition at line 67 of file vpc6.c.
Referenced by vpc6_Status().
int vpc6_Setup (MVME_INTERFACE * mvme, DWORD base, int mode)
Sets all the necessary paramters for a given configuration. The configuration is provided by the mode argument. Add your own configuration in the case statement. Let me know your setting if you want to include it in the distribution.
Parameters:
*mvme VME structure
base Module base address
mode Configuration mode number
*nentry number of entries requested and returned.
Returns:
MVME_SUCCESS
Definition at line 291 of file vpc6.c.
void vpc6_Status (MVME_INTERFACE * mvme, DWORD base, WORD port)
Definition at line 329 of file vpc6.c.
Midas DOC Version 2.3.0 ---- PSI Stefan Ritt ----
Contributions: Pierre-Andre Amaudruz - Sergio Ballestrero - Suzannah Daviel - Doxygen - Peter Green - Qing Gu - Greg Hackman - Gertjan Hofman - Paul Knowles - Exaos Lee - Rudi Meier - Glenn Moloney - Dave Morris - John M O'Donnell - Konstantin Olchanski - Chris Pearson - Renee Poutissou - Tamsen Schurman - Andreas Suter - Jan M.Wouters - Piotr Adam Zolnierczuk