Midas: vt48.c File Reference
vt48.c File Reference
Functions
int vt48_EventRead (MVME_INTERFACE *myvme, DWORD base, DWORD *pdest, int *nentry)
int vt48_Setup (MVME_INTERFACE *mvme, DWORD base, int mode)
Function Documentation
int vt48_EventRead (MVME_INTERFACE * myvme, DWORD base, DWORD * pdest, int * nentry)
Read one Event
Parameters:
myvme vme structure
base TF48 base address
pdest Destination pointer
entry return number of entry
Returns:
void
Definition at line 28 of file vt48.c.
void vt48_RegPrint (MVME_INTERFACE * mvme, DWORD base)
Definition at line 150 of file vt48.c.
DWORD vt48_RegRead (MVME_INTERFACE * mvme, DWORD base, WORD reg)
Definition at line 135 of file vt48.c.
Referenced by vt48_RegPrint(), and vt48_Status().
void vt48_RegWrite (MVME_INTERFACE * mvme, DWORD base, DWORD reg, DWORD data)
Definition at line 95 of file vt48.c.
Referenced by vt48_RegPrint(), vt48_Setup(), and vt48_Status().
int vt48_Setup (MVME_INTERFACE * mvme, DWORD base, int mode)
Sets all the necessary paramters for a given configuration. The configuration is provided by the mode argument. Add your own configuration in the case statement. Let me know your setting if you want to include it in the distribution.
Parameters:
*mvme VME structure
base Module base address
mode Configuration mode number
*nentry number of entries requested and returned.
Returns:
MVME_SUCCESS
Definition at line 180 of file vt48.c.
void vt48_Status (MVME_INTERFACE * mvme, DWORD base)
Definition at line 273 of file vt48.c.
void vt48_WindowOffsetSet (MVME_INTERFACE * mvme, DWORD base, float offset)
Definition at line 121 of file vt48.c.
void vt48_WindowSet (MVME_INTERFACE * mvme, DWORD base, float window)
Definition at line 108 of file vt48.c.
Midas DOC Version 2.3.0 ---- PSI Stefan Ritt ----
Contributions: Pierre-Andre Amaudruz - Sergio Ballestrero - Suzannah Daviel - Doxygen - Peter Green - Qing Gu - Greg Hackman - Gertjan Hofman - Paul Knowles - Exaos Lee - Rudi Meier - Glenn Moloney - Dave Morris - John M O'Donnell - Konstantin Olchanski - Chris Pearson - Renee Poutissou - Tamsen Schurman - Andreas Suter - Jan M.Wouters - Piotr Adam Zolnierczuk