ROOT Analyzer: XmlServer Class Reference
XmlServer Class Reference
#include <xmlServer.h>
Public Member Functions
void Start (int port)
void SetVerbose (bool verbose)
void Export (TDirectory *dir, const char *exportName)
void Export (TFolder *folder, const char *exportName)
void Export (TCollection *collection, const char *exportName)
void Start (int port)
void SetVerbose (bool verbose)
void Export (TDirectory *dir, const char *exportName)
void Export (TFolder *folder, const char *exportName)
void Export (TCollection *collection, const char *exportName)
Detailed Description
Definition at line 11 of file xmlServer.h.
Member Function Documentation
void XmlServer::Export (TCollection * collection, const char * exportName)
void XmlServer::Export (TFolder * folder, const char * exportName)
void XmlServer::Export (TDirectory * dir, const char * exportName)
void XmlServer::Export (TCollection * collection, const char * exportName)
Definition at line 990 of file xmlServer.cxx.
References gExportNames, gExports, and gVerbose.
{
  if (gVerbose)
    printf("Export TCollection %p named [%s] of type [%s] as [%s]\n", collection, collection->GetName(), collection->IsA()->GetName(), exportName);
  bool found = false;
  for (unsigned int i=0; i<gExports.size(); i++)
    {
      const char* ename = gExports[i].c_str();
      if (strcmp(ename, exportName) == 0)
        found = true;
    }
  if (!found)
    gExports.push_back(exportName);
  gExportNames[exportName] = collection->GetName();
}
void XmlServer::Export (TFolder * folder, const char * exportName)
Definition at line 972 of file xmlServer.cxx.
References gExportNames, gExports, and gVerbose.
{
  if (gVerbose)
    printf("Export TFolder %p named [%s] of type [%s] as [%s]\n", folder, folder->GetName(), folder->IsA()->GetName(), exportName);
  bool found = false;
  for (unsigned int i=0; i<gExports.size(); i++)
    {
      const char* ename = gExports[i].c_str();
      if (strcmp(ename, exportName) == 0)
        found = true;
    }
  if (!found)
    gExports.push_back(exportName);
  gExportNames[exportName] = folder->GetName();
}
void XmlServer::Export (TDirectory * dir, const char * exportName)
Definition at line 954 of file xmlServer.cxx.
References gExportNames, gExports, and gVerbose.
Referenced by main().
{
  if (gVerbose)
    printf("Export TDirectory %p named [%s] of type [%s] as [%s]\n", dir, dir->GetName(), dir->IsA()->GetName(), exportName);
  bool found = false;
  for (unsigned int i=0; i<gExports.size(); i++)
    {
      const char* ename = gExports[i].c_str();
      if (strcmp(ename, exportName) == 0)
        found = true;
    }
  if (!found)
    gExports.push_back(exportName);
  gExportNames[exportName] = dir->GetName();
}
void XmlServer::SetVerbose (bool verbose)
void XmlServer::SetVerbose (bool verbose)
Definition at line 947 of file xmlServer.cxx.
References gVerbose.
Referenced by main().
{
  gVerbose = verbose;
}
void XmlServer::Start (int port)
void XmlServer::Start (int port)
Definition at line 1008 of file xmlServer.cxx.
References xsocket_listener().
Referenced by main().
{
  if (port==0)
    return;
  //printf("Here!\n");
  static int pport = port;
#if 1
  TThread *thread = new TThread("XmlServer", xsocket_listener, &pport);
  thread->Run();
#else
  LPDWORD lpThreadId = 0;
  CloseHandle(CreateThread(NULL, 1024, &xroot_socket_server, &pport, 0, lpThreadId));
#endif
}
The documentation for this class was generated from the following files:
include/xmlServer.h
libXmlServer/xmlServer.h
libXmlServer/xmlServer.cxx