ROOT Analyzer: TDirectory::TContext Class Reference
TDirectory::TContext Class Reference
#include <TDirectory-example.h>
Public Member Functions
TContext (TDirectory *previous, TDirectory *newCurrent)
TContext (TDirectory *newCurrent)
~TContext ()
TContext (TDirectory *previous, TDirectory *newCurrent)
TContext (TDirectory *newCurrent)
~TContext ()
Private Member Functions
TContext (TContext &)
TContext & operator= (TContext &)
void CdNull ()
TContext (TContext &)
TContext & operator= (TContext &)
void CdNull ()
Private Attributes
TDirectory * fPrevious
Detailed Description
Definition at line 81 of file TDirectory-example.h.
Constructor & Destructor Documentation
TDirectory::TContext::TContext (TContext &) [private]
TDirectory::TContext::TContext (TDirectory * previous, TDirectory * newCurrent) [inline]
Definition at line 88 of file TDirectory-example.h.
References TDirectory::cd().
         : fPrevious(previous)
      {
         // Store the current directory so we can restore it
         // later and cd to the new directory.
         if ( newCurrent ) newCurrent->cd();
      }
TDirectory::TContext::TContext (TDirectory * newCurrent) [inline]
Definition at line 95 of file TDirectory-example.h.
References TDirectory::cd().
                                       : fPrevious(gDirectory)
      {
         // Store the current directory so we can restore it
         // later and cd to the new directory.
         if ( newCurrent ) newCurrent->cd();
      }
TDirectory::TContext::~TContext () [inline]
Definition at line 101 of file TDirectory-example.h.
References TDirectory::cd(), CdNull(), and fPrevious.
      {
         // Destructor.   Reset the current directory to its
         // previous state.
         if ( fPrevious ) fPrevious->cd();
         else CdNull();
      }
TDirectory::TContext::TContext (TContext &) [private]
TDirectory::TContext::TContext (TDirectory * previous, TDirectory * newCurrent) [inline]
Definition at line 88 of file TDirectory-example.h.
References TDirectory::cd().
         : fPrevious(previous)
      {
         // Store the current directory so we can restore it
         // later and cd to the new directory.
         if ( newCurrent ) newCurrent->cd();
      }
TDirectory::TContext::TContext (TDirectory * newCurrent) [inline]
Definition at line 95 of file TDirectory-example.h.
References TDirectory::cd().
                                       : fPrevious(gDirectory)
      {
         // Store the current directory so we can restore it
         // later and cd to the new directory.
         if ( newCurrent ) newCurrent->cd();
      }
TDirectory::TContext::~TContext () [inline]
Definition at line 101 of file TDirectory-example.h.
References TDirectory::cd(), CdNull(), and fPrevious.
      {
         // Destructor.   Reset the current directory to its
         // previous state.
         if ( fPrevious ) fPrevious->cd();
         else CdNull();
      }
Member Function Documentation
void TDirectory::TContext::CdNull () [private]
void TDirectory::TContext::CdNull () [private]
Referenced by ~TContext().
TContext& TDirectory::TContext::operator= (TContext &) [private]
TContext& TDirectory::TContext::operator= (TContext &) [private]
Member Data Documentation
TDirectory * TDirectory::TContext::fPrevious [private]
Definition at line 83 of file TDirectory-example.h.
Referenced by ~TContext().
The documentation for this class was generated from the following files:
include/TDirectory-example.h
libNetDirectory/TDirectory-example.h