ROOT Analyzer: TRootanaDisplay Class Reference
TRootanaDisplay Class Reference
#include <TRootanaDisplay.hxx>
Public Member Functions
TRootanaDisplay ()
virtual ~TRootanaDisplay ()
virtual void AddAllCanvases ()=0
User must.
void AddSingleCanvas (std::string name)
Add a new canvas; user will interactively fill it.
void AddSingleCanvas (TCanvasHandleBase *handleClass)
TMainDisplayWindow * GetDisplayWindow ()
virtual void UpdateHistograms (TDataContainer &dataContainer)
This method can be implemented by users to update user histograms.
virtual void PlotCanvas (TDataContainer &dataContainer)
This method can be implemented by users to plotting of current canvas.
virtual void ResetHistograms ()
This method can be implemented by users to plotting of current canvas.
void NextButtonPushed ()
Method for when next button is pushed (offline mode).
void EventSkipButtonPushed ()
Method for when skip event button is pushed (online mode).
void Reset ()
void UpdatePlotsAction ()
void SetNumberSkipEvent (int number)
std::string GetDisplayName ()
Get Display name.
void SetDisplayName (std::string name)
Set Display name.
void Initialize ()
TRootanaDisplay ()
virtual ~TRootanaDisplay ()
virtual void AddAllCanvases ()=0
User must.
void AddSingleCanvas (std::string name)
Add a new canvas; user will interactively fill it.
void AddSingleCanvas (TCanvasHandleBase *handleClass)
TMainDisplayWindow * GetDisplayWindow ()
virtual void UpdateHistograms (TDataContainer &dataContainer)
This method can be implemented by users to update user histograms.
virtual void PlotCanvas (TDataContainer &dataContainer)
This method can be implemented by users to plotting of current canvas.
virtual void ResetHistograms ()
This method can be implemented by users to plotting of current canvas.
void NextButtonPushed ()
Method for when next button is pushed (offline mode).
void EventSkipButtonPushed ()
Method for when skip event button is pushed (online mode).
void Reset ()
void UpdatePlotsAction ()
void SetNumberSkipEvent (int number)
std::string GetDisplayName ()
Get Display name.
void SetDisplayName (std::string name)
Set Display name.
void Initialize ()
TDataContainer * GetDataContainer ()
Method to get the data container that event loop owns.
TDataContainer * GetDataContainer ()
Method to get the data container that event loop owns.
virtual void Finalize ()
virtual void Finalize ()
virtual void Usage (void)
virtual void Usage (void)
virtual bool CheckOption (std::string option)
virtual bool CheckOption (std::string option)
bool IsOnline () const
Are we processing online data?
bool IsOnline () const
Are we processing online data?
bool IsOffline () const
Are we processing offline data?
bool IsOffline () const
Are we processing offline data?
int GetCurrentRunNumber () const
Current Run Number.
int GetCurrentRunNumber () const
Current Run Number.
void SetCurrentRunNumber (int run)
Current Run Number.
void SetCurrentRunNumber (int run)
Current Run Number.
int ExecuteLoop (int argc, char *argv[])
Method to actually process the Midas information, either as file or online.
int ExecuteLoop (int argc, char *argv[])
Method to actually process the Midas information, either as file or online.
int ProcessMidasFile (TApplication *app, const char *fname)
int ProcessMidasFile (TApplication *app, const char *fname)
void DisableAutoMainWindow ()
Disable automatic creation of MainWindow.
void DisableAutoMainWindow ()
Disable automatic creation of MainWindow.
VirtualOdb * GetODB ()
Get pointer to ODB variables.
VirtualOdb * GetODB ()
Get pointer to ODB variables.
void OpenRootFile (int run)
Open output ROOT file.
void OpenRootFile (int run)
Open output ROOT file.
void CloseRootFile ()
Cloe output ROOT file.
void CloseRootFile ()
Cloe output ROOT file.
void DisableRootOutput (bool disable=true)
void DisableRootOutput (bool disable=true)
Static Public Member Functions
static TRootanaEventLoop & Get (void)
static TRootanaEventLoop & Get (void)
template<typename T >
static void CreateSingleton ()
template<typename T >
static void CreateSingleton ()
Protected Member Functions
bool CreateOutputFile (std::string name, std::string options="RECREATE")
bool CreateOutputFile (std::string name, std::string options="RECREATE")
Protected Attributes
TDirectory * fOnlineHistDir
TDirectory for online histograms.
Static Protected Attributes
static TRootanaEventLoop * fTRootanaEventLoop = NULL
The static pointer to the singleton instance.
Private Member Functions
void InitializeMainWindow ()
Method to initialize the Main display window.
bool ProcessMidasEvent (TDataContainer &dataContainer)
Process each midas event.
void BeginRun (int transition, int run, int time)
void EndRun (int transition, int run, int time)
void SetCachedDataContainer (TDataContainer &dataContainer)
void InitializeMainWindow ()
Method to initialize the Main display window.
bool ProcessMidasEvent (TDataContainer &dataContainer)
Process each midas event.
void BeginRun (int transition, int run, int time)
void EndRun (int transition, int run, int time)
void SetCachedDataContainer (TDataContainer &dataContainer)
Private Attributes
bool waitingForNextButton
int fNumberSkipEventsOnline
int fNumberProcessed
TMainDisplayWindow * fMainWindow
The pointer to our display window.
TDataContainer * fCachedDataContainer
We keep a cached copy of the midas event (so that it can used for callback).
std::string fDisplayName
Display name.
std::vector< std::pair< int,
TCanvasHandleBase * > > fCanvasHandlers
Detailed Description
This is an abstract base class for event displays. Users need to define a class that derives from this class in order to make an event display. The only method that users must implement is the method AddAllCanvas(), where the user defines which tabs to use.
The user then needs to define how they what to update and plot histograms. The updating of histograms happens for each event. In online mode, the plotting of histograms only happens for each XX events; for offline mode the plotting happens for each event.
There are two ways that users can decide to update and plot histograms:
1) They can create histograms in their event display class and then fill the methods UpdateHistograms(TDataContainer) and PlotCanvas(TDataContainer). This histograms can then file in the canvases that are added using AddSingleCanvas(std::string name).
2) They can create classes that are derived from TCanvasHandleBase. The derived classes are then added using the method AddSingleCanvas(TCanvasHandleBase* handleClass).
There is no substantial difference between the two methods. The second method is mainly meant to allow the user to separate the methods into separate files for code cleaniness.
Examples of both these methods are available in examples/display_example.cxx
The actual ROOT GUI is encapsulated in a separate class TMainDisplayWindow. The TRootanaDisplay has an instance of this TMainDisplayWindow class. Users will be need to access the TMainDisplayWindow by calling
TRootanaDisplay::GetDisplayWindow()
in order to grab the particular canvas that we want plot on.
Definition at line 51 of file TRootanaDisplay.hxx.
Constructor & Destructor Documentation
TRootanaDisplay::TRootanaDisplay ()
TRootanaDisplay::~TRootanaDisplay () [virtual]
Definition at line 24 of file TRootanaDisplay.cxx.
References fCanvasHandlers.
{
  for(unsigned int i = 0; i < fCanvasHandlers.size(); i++)
    delete fCanvasHandlers[i].second;
};
TRootanaDisplay::TRootanaDisplay ()
virtual TRootanaDisplay::~TRootanaDisplay () [virtual]
Member Function Documentation
virtual void TRootanaDisplay::AddAllCanvases () [pure virtual]
User must.
Implemented in MyTestLoop.
virtual void TRootanaDisplay::AddAllCanvases () [pure virtual]
User must.
Implemented in MyTestLoop.
Referenced by InitializeMainWindow().
void TRootanaDisplay::AddSingleCanvas (TCanvasHandleBase * handleClass)
Add a new canvas, using a TCanvasHandleBase class. TRootanaDisplay will take ownership of pointer and delete memory it points to.
void TRootanaDisplay::AddSingleCanvas (std::string name) [inline]
Add a new canvas; user will interactively fill it.
Definition at line 64 of file TRootanaDisplay.hxx.
References TMainDisplayWindow::AddCanvas(), and fMainWindow.
{
    fMainWindow->AddCanvas(name);
  }
void TRootanaDisplay::AddSingleCanvas (TCanvasHandleBase * handleClass)
Add a new canvas, using a TCanvasHandleBase class. TRootanaDisplay will take ownership of pointer and delete memory it points to.
Definition at line 66 of file TRootanaDisplay.cxx.
References TMainDisplayWindow::AddCanvas(), fCanvasHandlers, GetDisplayWindow(), TMainDisplayWindow::GetTab(), TCanvasHandleBase::GetTabName(), and TCanvasHandleBase::SetUpCompositeFrame().
{
  GetDisplayWindow()->AddCanvas(handleClass->GetTabName());
  int tab_index = GetDisplayWindow()->GetTab()->GetNumberOfTabs() - 1;
  fCanvasHandlers.push_back(std::pair<int,TCanvasHandleBase*>(tab_index,handleClass));
  // Now set up the embedded canvas, if user so desires.
  TGCompositeFrame* embed = GetDisplayWindow()->GetTab()->GetTabContainer(tab_index);
  handleClass->SetUpCompositeFrame(embed,this);
}
void TRootanaDisplay::AddSingleCanvas (std::string name) [inline]
Add a new canvas; user will interactively fill it.
Definition at line 64 of file TRootanaDisplay.hxx.
References TMainDisplayWindow::AddCanvas(), and fMainWindow.
Referenced by MyTestLoop::AddAllCanvases().
{
    fMainWindow->AddCanvas(name);
  }
void TRootanaDisplay::BeginRun (int transition, int run, int time) [private, virtual]
Called before the first event of a file is read, but you should prefer Initialize() for general initialization. This method will be called once for each input file.
Reimplemented from TRootanaEventLoop.
Reimplemented in MyTestLoop.
void TRootanaDisplay::BeginRun (int transition, int run, int time) [private, virtual]
Called before the first event of a file is read, but you should prefer Initialize() for general initialization. This method will be called once for each input file.
Reimplemented from TRootanaEventLoop.
Reimplemented in MyTestLoop.
Definition at line 144 of file TRootanaDisplay.cxx.
References fCanvasHandlers, and UpdatePlotsAction().
{
  std::cout << "Begin of run " << run << " at time " << time << std::endl;
  for(unsigned int i = 0; i < fCanvasHandlers.size(); i++)
    fCanvasHandlers[i].second->BeginRun(transition,run,time);
  UpdatePlotsAction();
}
virtual bool TRootanaEventLoop::CheckOption (std::string option) [virtual, inherited]
Check an option and return true if it is valid. The return value is used to flag errors during option handling. If the options are valid, then CheckOption should return true to indicate success. If there is a problem processing the options, then CheckOption should return false. If this returns false, then the event loop will print the Usage message and exit with a non zero value (i.e. indicate failure).
Reimplemented in MyTestLoop.
bool TRootanaEventLoop::CheckOption (std::string option) [virtual, inherited]
Check an option and return true if it is valid. The return value is used to flag errors during option handling. If the options are valid, then CheckOption should return true to indicate success. If there is a problem processing the options, then CheckOption should return false. If this returns false, then the event loop will print the Usage message and exit with a non zero value (i.e. indicate failure).
Reimplemented in MyTestLoop.
Definition at line 79 of file TRootanaEventLoop.cxx.
Referenced by TRootanaEventLoop::ExecuteLoop().
{return false;}
void TRootanaEventLoop::CloseRootFile () [inherited]
Cloe output ROOT file.
void TRootanaEventLoop::CloseRootFile () [inherited]
Cloe output ROOT file.
Definition at line 342 of file TRootanaEventLoop.cxx.
References TRootanaEventLoop::fOutputFile.
Referenced by TRootanaEventLoop::ProcessMidasFile(), and TRootanaEventLoop::~TRootanaEventLoop().
{
  std::cout << "Closing ROOT file " << std::endl;
  if(fOutputFile) {
    fOutputFile->Write();
    fOutputFile->Close();
    fOutputFile=0;
  }
}
bool TRootanaEventLoop::CreateOutputFile (std::string name, std::string options = "RECREATE") [inline, protected, inherited]
Definition at line 140 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fOutputFile.
{
    fOutputFile = new TFile(name.c_str(),options.c_str());
    return true;
  }
bool TRootanaEventLoop::CreateOutputFile (std::string name, std::string options = "RECREATE") [inline, protected, inherited]
Definition at line 140 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fOutputFile.
{
    fOutputFile = new TFile(name.c_str(),options.c_str());
    return true;
  }
template<typename T > static void TRootanaEventLoop::CreateSingleton () [inline, static, inherited]
This static templated function will make it a little easier for users to create the singleton instance.
Definition at line 114 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fTRootanaEventLoop.
  {
    if(fTRootanaEventLoop)
      std::cout << "Singleton has already been created" << std::endl;
    else
      fTRootanaEventLoop = new T();
  }
template<typename T > static void TRootanaEventLoop::CreateSingleton () [inline, static, inherited]
This static templated function will make it a little easier for users to create the singleton instance.
Definition at line 114 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fTRootanaEventLoop.
  {
    if(fTRootanaEventLoop)
      std::cout << "Singleton has already been created" << std::endl;
    else
      fTRootanaEventLoop = new T();
  }
void TRootanaEventLoop::DisableAutoMainWindow () [inline, inherited]
Disable automatic creation of MainWindow.
Definition at line 124 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fCreateMainWindow.
{  fCreateMainWindow = false;}
void TRootanaEventLoop::DisableAutoMainWindow () [inline, inherited]
Disable automatic creation of MainWindow.
Definition at line 124 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fCreateMainWindow.
{  fCreateMainWindow = false;}
void TRootanaEventLoop::DisableRootOutput (bool disable = true) [inline, inherited]
Definition at line 136 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fDisableRootOutput.
{fDisableRootOutput = disable;};
void TRootanaEventLoop::DisableRootOutput (bool disable = true) [inline, inherited]
Definition at line 136 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fDisableRootOutput.
{fDisableRootOutput = disable;};
void TRootanaDisplay::EndRun (int transition, int run, int time) [private, virtual]
Called after the last event of a file is read, but you should prefer Finalize() for general finalization. This method will be called once for each input file.
Reimplemented from TRootanaEventLoop.
Reimplemented in MyTestLoop.
void TRootanaDisplay::EndRun (int transition, int run, int time) [private, virtual]
Called after the last event of a file is read, but you should prefer Finalize() for general finalization. This method will be called once for each input file.
Reimplemented from TRootanaEventLoop.
Reimplemented in MyTestLoop.
Definition at line 152 of file TRootanaDisplay.cxx.
References fCanvasHandlers, and UpdatePlotsAction().
{
  std::cout << "End of run " << run << " at time " << time << std::endl;
  for(unsigned int i = 0; i < fCanvasHandlers.size(); i++)
    fCanvasHandlers[i].second->EndRun(transition,run,time);
  UpdatePlotsAction();
}
void TRootanaDisplay::EventSkipButtonPushed () [inline]
Method for when skip event button is pushed (online mode).
Definition at line 92 of file TRootanaDisplay.hxx.
References fMainWindow, fNumberSkipEventsOnline, and TMainDisplayWindow::GetSkipEventButton().
{
    fNumberSkipEventsOnline = fMainWindow->GetSkipEventButton()->GetNumberEntry()->GetIntNumber();
  }
void TRootanaDisplay::EventSkipButtonPushed () [inline]
Method for when skip event button is pushed (online mode).
Definition at line 92 of file TRootanaDisplay.hxx.
References fMainWindow, fNumberSkipEventsOnline, and TMainDisplayWindow::GetSkipEventButton().
{
    fNumberSkipEventsOnline = fMainWindow->GetSkipEventButton()->GetNumberEntry()->GetIntNumber();
  }
int TRootanaEventLoop::ExecuteLoop (int argc, char * argv[]) [inherited]
Method to actually process the Midas information, either as file or online.
int TRootanaEventLoop::ExecuteLoop (int argc, char * argv[]) [inherited]
Method to actually process the Midas information, either as file or online.
Definition at line 105 of file TRootanaEventLoop.cxx.
References TDirectory::cd(), TRootanaEventLoop::CheckOption(), TRootanaEventLoop::fApp, TRootanaEventLoop::fCreateMainWindow, TRootanaEventLoop::Finalize(), TRootanaEventLoop::fIsOffline, TRootanaEventLoop::fMaxEvents, TRootanaEventLoop::fOnlineHistDir, TRootanaEventLoop::Initialize(), TRootanaEventLoop::PrintHelp(), TRootanaEventLoop::ProcessMidasFile(), and StartNetDirectoryServer().
Referenced by main().
{
  setbuf(stdout,NULL);
  setbuf(stderr,NULL);
  signal(SIGILL,  SIG_DFL);
  signal(SIGBUS,  SIG_DFL);
  signal(SIGSEGV, SIG_DFL);
  std::vector<std::string> args;
  for (int i=0; i<argc; i++)
    {
      if (strcmp(argv[i],"-h")==0)
        PrintHelp(); // does not return
      args.push_back(argv[i]);
    }
  if(gROOT->IsBatch()) {
    printf("Cannot run in batch mode\n");
    return 1;
  }
  bool forceEnableGraphics = false;
  bool testMode = false;
  int  tcpPort = 0;
  const char* hostname = NULL;
  const char* exptname = NULL;
  for (unsigned int i=1; i<args.size(); i++) // loop over the commandline options
    {
      const char* arg = args[i].c_str();
      //printf("argv[%d] is %s\n",i,arg);
      if (strncmp(arg,"-e",2)==0)  // Event cutoff flag (only applicable in offline mode)
        fMaxEvents = atoi(arg+2);
      else if (strncmp(arg,"-m",2)==0) // Enable memory debugging
        ;//      gEnableShowMem = true;
      else if (strncmp(arg,"-P",2)==0) // Set the histogram server port
        tcpPort = atoi(arg+2);
      else if (strcmp(arg,"-T")==0)
        testMode = true;
      else if (strcmp(arg,"-g")==0)
        forceEnableGraphics = true;
      else if (strncmp(arg,"-H",2)==0)
        hostname = strdup(arg+2);
      else if (strncmp(arg,"-E",2)==0)
        exptname = strdup(arg+2);
      else if (strcmp(arg,"-h")==0)
        PrintHelp(); // does not return
      else if(arg[0] == '-' && !CheckOption(args[i])) // Chec if a user-defined option
        PrintHelp(); // does not return
    }
  // Do quick check if we are processing online or offline.
  // Want to know before we initialize.
  fIsOffline = false;
  for (unsigned int i=1; i<args.size(); i++){
    const char* arg = args[i].c_str();
    if (arg[0] != '-')
      {
        fIsOffline = true;
      }
  }
  MainWindow *mainWindow=0;
  if(fCreateMainWindow){
    mainWindow = new MainWindow(gClient->GetRoot(), 200, 300);
  }
   gROOT->cd();
   fOnlineHistDir = new TDirectory("rootana", "rootana online plots");
#ifdef HAVE_LIBNETDIRECTORY
   if (tcpPort)
     StartNetDirectoryServer(tcpPort, fOnlineHistDir);
#else
   if (tcpPort)
     fprintf(stderr,"ERROR: No support for the TNetDirectory server!\n");
#endif
   // Initialize the event loop with user initialization.
   Initialize();
   for (unsigned int i=1; i<args.size(); i++){
     const char* arg = args[i].c_str();
     if (arg[0] != '-')
       {
           ProcessMidasFile(fApp,arg);
       }
   }
   if (testMode){
     std::cout << "Entering test mode." << std::endl;
     fOnlineHistDir->cd();
     TH1D* hh = new TH1D("test", "test", 100, 0, 100);
     hh->Fill(1);
     hh->Fill(10);
     hh->Fill(50);
     fApp->Run(kTRUE);
     if(fCreateMainWindow) delete mainWindow;
     return 0;
   }
   // if we processed some data files,
   // do not go into online mode.
   if (fIsOffline){
     if(fCreateMainWindow) delete mainWindow;
     return 0;
   }
#ifdef HAVE_MIDAS
   ProcessMidasOnline(fApp, hostname, exptname);;
#endif
   if(fCreateMainWindow) delete mainWindow;
   Finalize();
   return 0;
}
virtual void TRootanaEventLoop::Finalize () [virtual, inherited]
Called after the last event has been processed, but before any open output files are closed.
void TRootanaEventLoop::Finalize () [virtual, inherited]
Called after the last event has been processed, but before any open output files are closed.
Definition at line 74 of file TRootanaEventLoop.cxx.
Referenced by TRootanaEventLoop::ExecuteLoop().
{};
static TRootanaEventLoop& TRootanaEventLoop::Get (void) [static, inherited]
TRootanaEventLoop & TRootanaEventLoop::Get (void) [static, inherited]
Definition at line 29 of file TRootanaEventLoop.cxx.
References TRootanaEventLoop::fTRootanaEventLoop.
Referenced by main().
{
  if(!fTRootanaEventLoop){
    std::cerr << "Singleton Not Instantiated! "
              << " Need to call something like SomeClass::CreateSingleton<SomeClass>(); Exiting!"
              <<std::endl; exit(0);
  }
  return *fTRootanaEventLoop;
}
int TRootanaEventLoop::GetCurrentRunNumber () const [inline, inherited]
Current Run Number.
Definition at line 96 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fCurrentRunNumber.
{return fCurrentRunNumber;};
int TRootanaEventLoop::GetCurrentRunNumber () const [inline, inherited]
Current Run Number.
Definition at line 96 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fCurrentRunNumber.
Referenced by MyTestLoop::ProcessMidasEvent(), and UpdatePlotsAction().
{return fCurrentRunNumber;};
TDataContainer* TRootanaEventLoop::GetDataContainer () [inline, inherited]
Method to get the data container that event loop owns.
Definition at line 49 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fDataContainer.
{return fDataContainer;};
TDataContainer* TRootanaEventLoop::GetDataContainer () [inline, inherited]
Method to get the data container that event loop owns.
Definition at line 49 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fDataContainer.
{return fDataContainer;};
std::string TRootanaDisplay::GetDisplayName () [inline]
Get Display name.
Definition at line 114 of file TRootanaDisplay.hxx.
References fDisplayName.
{return fDisplayName;}
std::string TRootanaDisplay::GetDisplayName () [inline]
Get Display name.
Definition at line 114 of file TRootanaDisplay.hxx.
References fDisplayName.
Referenced by UpdatePlotsAction().
{return fDisplayName;}
TMainDisplayWindow* TRootanaDisplay::GetDisplayWindow () [inline]
Retrieve the main display window, so that users can do things like grab the canvases and update them.
Definition at line 76 of file TRootanaDisplay.hxx.
References fMainWindow.
{ return fMainWindow;}
TMainDisplayWindow* TRootanaDisplay::GetDisplayWindow () [inline]
Retrieve the main display window, so that users can do things like grab the canvases and update them.
Definition at line 76 of file TRootanaDisplay.hxx.
References fMainWindow.
Referenced by AddSingleCanvas(), InitializeMainWindow(), MyTestLoop::PlotCanvas(), and UpdatePlotsAction().
{ return fMainWindow;}
VirtualOdb* TRootanaEventLoop::GetODB () [inline, inherited]
Get pointer to ODB variables.
Definition at line 127 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fODB.
{return fODB;}
VirtualOdb* TRootanaEventLoop::GetODB () [inline, inherited]
Get pointer to ODB variables.
Definition at line 127 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fODB.
{return fODB;}
void TRootanaDisplay::Initialize (void) [inline, virtual]
Called after the arguments are processes but before reading the first event is read
Reimplemented from TRootanaEventLoop.
Definition at line 118 of file TRootanaDisplay.hxx.
References InitializeMainWindow().
                   {
    InitializeMainWindow();
  }
void TRootanaDisplay::Initialize (void) [inline, virtual]
Called after the arguments are processes but before reading the first event is read
Reimplemented from TRootanaEventLoop.
Definition at line 118 of file TRootanaDisplay.hxx.
References InitializeMainWindow().
                   {
    InitializeMainWindow();
  }
void TRootanaDisplay::InitializeMainWindow () [private]
Method to initialize the Main display window.
void TRootanaDisplay::InitializeMainWindow () [private]
Method to initialize the Main display window.
Definition at line 31 of file TRootanaDisplay.cxx.
References AddAllCanvases(), TMainDisplayWindow::BuildWindow(), fMainWindow, fNumberSkipEventsOnline, GetDisplayWindow(), TMainDisplayWindow::GetNextButton(), TMainDisplayWindow::GetResetButton(), TMainDisplayWindow::GetSkipEventButton(), TMainDisplayWindow::GetTab(), TRootanaEventLoop::IsOffline(), and TRootanaEventLoop::IsOnline().
Referenced by Initialize().
{
  fMainWindow = new TMainDisplayWindow(gClient->GetRoot(),1200,800,IsOffline());
  // Link the a bunch of buttons in TMainWindowDisplay to functions in TRootanaDisplay.
  // This bit of ROOT magic requires that the TRootanaDisplay class get rootcint-ed.
  // It also requires that TRootanaDisplay methods be public (protected doesn't work).
  // The reset button
  fMainWindow->GetResetButton()->Connect("Clicked()", "TRootanaDisplay", this, "Reset()");
  // The tab buttons
  fMainWindow->GetTab()->Connect("Selected(Int_t)", "TRootanaDisplay", this, "UpdatePlotsAction()");
  // The next button
  if(IsOffline())
    fMainWindow->GetNextButton()->Connect("Clicked()", "TRootanaDisplay", this, "NextButtonPushed()");
  // The event skip counter
  if(IsOnline()){
    TGNumberEntry *skipButton = fMainWindow->GetSkipEventButton();
    skipButton->Connect("ValueSet(Long_t)", "TRootanaDisplay",this, "EventSkipButtonPushed()");
    skipButton->GetNumberEntry()->Connect("ReturnPressed()", "TRootanaDisplay", this, "EventSkipButtonPushed()");
    fNumberSkipEventsOnline = skipButton->GetNumberEntry()->GetIntNumber();
  }
  // Let the user add all the canvases they want.
  AddAllCanvases();
  // Now map out window.
  GetDisplayWindow()->BuildWindow();
}
bool TRootanaEventLoop::IsOffline () const [inline, inherited]
Are we processing offline data?
Definition at line 93 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fIsOffline.
{return fIsOffline;};
bool TRootanaEventLoop::IsOffline () const [inline, inherited]
Are we processing offline data?
Definition at line 93 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fIsOffline.
Referenced by InitializeMainWindow().
{return fIsOffline;};
bool TRootanaEventLoop::IsOnline () const [inline, inherited]
Are we processing online data?
Definition at line 90 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fIsOffline.
{return !fIsOffline;};
bool TRootanaEventLoop::IsOnline () const [inline, inherited]
Are we processing online data?
Definition at line 90 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fIsOffline.
Referenced by InitializeMainWindow(), ProcessMidasEvent(), and UpdatePlotsAction().
{return !fIsOffline;};
void TRootanaDisplay::NextButtonPushed () [inline]
Method for when next button is pushed (offline mode).
Definition at line 88 of file TRootanaDisplay.hxx.
References waitingForNextButton.
{
    waitingForNextButton = false;
  }
void TRootanaDisplay::NextButtonPushed () [inline]
Method for when next button is pushed (offline mode).
Definition at line 88 of file TRootanaDisplay.hxx.
References waitingForNextButton.
{
    waitingForNextButton = false;
  }
void TRootanaEventLoop::OpenRootFile (int run) [inherited]
Open output ROOT file.
void TRootanaEventLoop::OpenRootFile (int run) [inherited]
Open output ROOT file.
Definition at line 319 of file TRootanaEventLoop.cxx.
References TRootanaEventLoop::fDisableRootOutput, TRootanaEventLoop::fOutputFile, and NetDirectoryExport().
Referenced by TRootanaEventLoop::ProcessMidasFile().
{
  if(fDisableRootOutput) return;
  if(fOutputFile) {
    fOutputFile->Write();
    fOutputFile->Close();
    fOutputFile=0;
  }
  char filename[1024];
  sprintf(filename, "output%05d.root", run);
  fOutputFile = new TFile(filename,"RECREATE");
  std::cout << "Opened output file with name : " << filename << std::endl;
#ifdef HAVE_LIBNETDIRECTORY
  NetDirectoryExport(fOutputFile, "outputFile");
#endif
}
virtual void TRootanaDisplay::PlotCanvas (TDataContainer & dataContainer) [inline, virtual]
This method can be implemented by users to plotting of current canvas.
Reimplemented in MyTestLoop.
Definition at line 82 of file TRootanaDisplay.hxx.
{};
virtual void TRootanaDisplay::PlotCanvas (TDataContainer & dataContainer) [inline, virtual]
This method can be implemented by users to plotting of current canvas.
Reimplemented in MyTestLoop.
Definition at line 82 of file TRootanaDisplay.hxx.
Referenced by UpdatePlotsAction().
{};
bool TRootanaDisplay::ProcessMidasEvent (TDataContainer & dataContainer) [private, virtual]
Process each midas event.
Implements TRootanaEventLoop.
Reimplemented in MyTestLoop.
bool TRootanaDisplay::ProcessMidasEvent (TDataContainer & dataContainer) [private, virtual]
Process each midas event.
Implements TRootanaEventLoop.
Reimplemented in MyTestLoop.
Definition at line 80 of file TRootanaDisplay.cxx.
References fCachedDataContainer, fCanvasHandlers, fMainWindow, fNumberProcessed, fNumberSkipEventsOnline, TMainDisplayWindow::IsDisplayPaused(), TRootanaEventLoop::IsOnline(), TMainDisplayWindow::ResetSize(), SetCachedDataContainer(), UpdateHistograms(), UpdatePlotsAction(), and waitingForNextButton.
{
  fNumberProcessed++;
  // Only update histograms if we are "offline" or "online and but paused".
  // This ensures that we don't update if the user pressed 'pause' since the
  // last event.
  if(!IsOnline() || (IsOnline() && !fMainWindow->IsDisplayPaused())){
    SetCachedDataContainer(dataContainer);
    // Perform any histogram updating from user code.
    UpdateHistograms(*fCachedDataContainer);
    for(unsigned int i = 0; i < fCanvasHandlers.size(); i++)
      fCanvasHandlers[i].second->UpdateCanvasHistograms(*fCachedDataContainer);
  }
  // If processing online and if processing is not paused, then just plot and return
  if(IsOnline() && !fMainWindow->IsDisplayPaused() ){
    // Do canvas plotting from user code;
    // only do plot if we have processed enough events
    if(fNumberSkipEventsOnline == 1 || fNumberProcessed % fNumberSkipEventsOnline  == 1){
      UpdatePlotsAction();
    }
    return true;
  }
  UpdatePlotsAction();
  // If offline, then keep looping till the next event button is pushed.
  // If online, then keep looping till the resume button is pushed.
  waitingForNextButton = true;
  while(1){
    // This is crude! Need to add some sort of wait function, otherwise
    // this will use 99% of CPU time, for no good reason...
    // usleep(1000); this seems to work fine, but need to test a bit more first...
    // ROOT signal/slot trick; this variable will magically
    // get changed to false once the next button is pushed.
    if(!waitingForNextButton){
      break;
    }
    // Alternately, break out if in online mode and
    // no longer in paused state.  Again, the state of variable
    // will be changed by ROOT signal/slot callback.
    if(IsOnline() && !fMainWindow->IsDisplayPaused()){
      break;
    }
    // Resize windows, if needed.
    fMainWindow->ResetSize();
    // handle GUI events
    bool result = gSystem->ProcessEvents();
  }
  return true;
}
int TRootanaEventLoop::ProcessMidasFile (TApplication * app, const char * fname) [inherited]
int TRootanaEventLoop::ProcessMidasFile (TApplication * app, const char * fname) [inherited]
Treat the begin run and end run events differently.
Definition at line 232 of file TRootanaEventLoop.cxx.
References TRootanaEventLoop::BeginRun(), TDataContainer::CleanupEvent(), TMidasFile::Close(), TRootanaEventLoop::CloseRootFile(), TRootanaEventLoop::EndRun(), TRootanaEventLoop::fCurrentRunNumber, TRootanaEventLoop::fDataContainer, TRootanaEventLoop::fMaxEvents, TRootanaEventLoop::fODB, TMidasEvent::GetData(), TMidasEvent::GetSerialNumber(), TMidasFile::Open(), TRootanaEventLoop::OpenRootFile(), TRootanaEventLoop::ProcessMidasEvent(), TMidasFile::Read(), and TDataContainer::SetMidasEventPointer().
Referenced by TRootanaEventLoop::ExecuteLoop().
{
  TMidasFile f;
  bool tryOpen = f.Open(fname);
  if (!tryOpen){
    printf("Cannot open input file \"%s\"\n",fname);
    return -1;
  }
  int i=0;
  while (1)
    {
      TMidasEvent event;
      if (!f.Read(&event))
        break;
      /// Treat the begin run and end run events differently.
      int eventId = event.GetEventId();
      if ((eventId & 0xFFFF) == 0x8000){// begin run event
        event.Print();
        // Load ODB contents from the ODB XML file
        if (fODB) delete fODB;
        fODB = new XmlOdb(event.GetData(),event.GetDataSize());
        fCurrentRunNumber = event.GetSerialNumber();
        OpenRootFile(fCurrentRunNumber);
        BeginRun(0,event.GetSerialNumber(),0);
      } else if ((eventId & 0xFFFF) == 0x8001){// end run event
        event.Print();
        //EndRun(0,fCurrentRunNumber,0);
      } else if ((eventId & 0xFFFF) == 0x8002){
        event.Print();
        printf("Log message: %s\n", event.GetData());
      }else { // all other events
        // Set the bank list for midas event.
        event.SetBankList();
        // Set the midas event pointer in the physics event.
        fDataContainer->SetMidasEventPointer(event);
        //ProcessEvent(event);
        ProcessMidasEvent(*fDataContainer);
        // Cleanup the information for this event.
        fDataContainer->CleanupEvent();
      }
      if((i%500)==0){
        printf("Processing event %d\n",i);
      }
      // Check if we have processed desired number of events.
      i++;
      if ((fMaxEvents!=0)&&(i>=fMaxEvents)){
        printf("Reached event %d, exiting loop.\n",i);
        break;
      }
    }
  f.Close();
  EndRun(0,fCurrentRunNumber,0);
  CloseRootFile();
  // start the ROOT GUI event loop
  //  app->Run(kTRUE);
  return 0;
}
void TRootanaDisplay::Reset ()
This method calls a couple other methods for resets the histograms. This method is attached using the ROOT signal/input system to the reset button on the canvas.
void TRootanaDisplay::Reset ()
This method calls a couple other methods for resets the histograms. This method is attached using the ROOT signal/input system to the reset button on the canvas.
Definition at line 204 of file TRootanaDisplay.cxx.
References fCanvasHandlers, ResetHistograms(), and UpdatePlotsAction().
{
  // Call the reset functions defined in user event loop.
  ResetHistograms();
  // Call the user defined canvas classes.
  for(unsigned int i = 0; i < fCanvasHandlers.size(); i++)
      fCanvasHandlers[i].second->ResetCanvasHistograms();
  UpdatePlotsAction();
}
virtual void TRootanaDisplay::ResetHistograms () [inline, virtual]
This method can be implemented by users to plotting of current canvas.
Reimplemented in MyTestLoop.
Definition at line 85 of file TRootanaDisplay.hxx.
{};
virtual void TRootanaDisplay::ResetHistograms () [inline, virtual]
This method can be implemented by users to plotting of current canvas.
Reimplemented in MyTestLoop.
Definition at line 85 of file TRootanaDisplay.hxx.
Referenced by Reset().
{};
void TRootanaDisplay::SetCachedDataContainer (TDataContainer & dataContainer) [inline, private]
Set the cached copy of midas dataContainer. !!! This is very questionable! Caching each dataContainer might add a considerable overhead to the processing!
Definition at line 161 of file TRootanaDisplay.hxx.
References fCachedDataContainer.
{
    if(fCachedDataContainer) delete fCachedDataContainer;
    fCachedDataContainer = new TDataContainer(dataContainer);
  }
void TRootanaDisplay::SetCachedDataContainer (TDataContainer & dataContainer) [inline, private]
Set the cached copy of midas dataContainer. !!! This is very questionable! Caching each dataContainer might add a considerable overhead to the processing!
Definition at line 161 of file TRootanaDisplay.hxx.
References fCachedDataContainer.
Referenced by ProcessMidasEvent().
{
    if(fCachedDataContainer) delete fCachedDataContainer;
    fCachedDataContainer = new TDataContainer(dataContainer);
  }
void TRootanaEventLoop::SetCurrentRunNumber (int run) [inline, inherited]
Current Run Number.
Definition at line 99 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fCurrentRunNumber.
{fCurrentRunNumber = run;};
void TRootanaEventLoop::SetCurrentRunNumber (int run) [inline, inherited]
Current Run Number.
Definition at line 99 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fCurrentRunNumber.
{fCurrentRunNumber = run;};
void TRootanaDisplay::SetDisplayName (std::string name) [inline]
Set Display name.
Definition at line 116 of file TRootanaDisplay.hxx.
References fDisplayName.
{fDisplayName = name;}
void TRootanaDisplay::SetDisplayName (std::string name) [inline]
Set Display name.
Definition at line 116 of file TRootanaDisplay.hxx.
References fDisplayName.
Referenced by MyTestLoop::AddAllCanvases().
{fDisplayName = name;}
void TRootanaDisplay::SetNumberSkipEvent (int number) [inline]
Function so that user can specify at outset how many events to skip before refreshing display (in online mode).
Definition at line 107 of file TRootanaDisplay.hxx.
References fMainWindow, fNumberSkipEventsOnline, and TMainDisplayWindow::GetSkipEventButton().
{
    fNumberSkipEventsOnline = number;
    if(fMainWindow->GetSkipEventButton())
      fMainWindow->GetSkipEventButton()->GetNumberEntry()->SetIntNumber(number);
  }
void TRootanaDisplay::SetNumberSkipEvent (int number) [inline]
Function so that user can specify at outset how many events to skip before refreshing display (in online mode).
Definition at line 107 of file TRootanaDisplay.hxx.
References fMainWindow, fNumberSkipEventsOnline, and TMainDisplayWindow::GetSkipEventButton().
Referenced by MyTestLoop::AddAllCanvases().
{
    fNumberSkipEventsOnline = number;
    if(fMainWindow->GetSkipEventButton())
      fMainWindow->GetSkipEventButton()->GetNumberEntry()->SetIntNumber(number);
  }
virtual void TRootanaDisplay::UpdateHistograms (TDataContainer & dataContainer) [inline, virtual]
This method can be implemented by users to update user histograms.
Reimplemented in MyTestLoop.
Definition at line 79 of file TRootanaDisplay.hxx.
{};
virtual void TRootanaDisplay::UpdateHistograms (TDataContainer & dataContainer) [inline, virtual]
This method can be implemented by users to update user histograms.
Reimplemented in MyTestLoop.
Definition at line 79 of file TRootanaDisplay.hxx.
Referenced by ProcessMidasEvent().
{};
void TRootanaDisplay::UpdatePlotsAction ()
void TRootanaDisplay::UpdatePlotsAction ()
Definition at line 163 of file TRootanaDisplay.cxx.
References fCachedDataContainer, fCanvasHandlers, fMainWindow, TRootanaEventLoop::GetCurrentRunNumber(), TMainDisplayWindow::GetCurrentTabNumber(), GetDisplayName(), GetDisplayWindow(), TMainDisplayWindow::GetEmbeddedCanvas(), TMainDisplayWindow::GetMain(), TDataContainer::GetMidasData(), TMidasEvent::GetSerialNumber(), TRootanaEventLoop::IsOnline(), PlotCanvas(), and TMainDisplayWindow::ResetSize().
Referenced by BeginRun(), EndRun(), ProcessMidasEvent(), and Reset().
{
  if(!fCachedDataContainer){
    char displayTitle[200];
    sprintf(displayTitle,"%s (): run %i (no events yet)",
            GetDisplayName().c_str(),GetCurrentRunNumber());
    GetDisplayWindow()->GetMain()->SetWindowName(displayTitle);
    return;
  }
  // Execute the plotting actions from user event loop.
  PlotCanvas(*fCachedDataContainer);
  // See if we find a user class that describes this tab.
  int currentTab = GetDisplayWindow()->GetCurrentTabNumber();
  for(unsigned int i = 0; i < fCanvasHandlers.size(); i++){
    if(currentTab == fCanvasHandlers[i].first){
      TRootEmbeddedCanvas* embed = GetDisplayWindow()->GetEmbeddedCanvas(currentTab);
      fCanvasHandlers[i].second->PlotCanvas(*fCachedDataContainer,embed);
    }
  }
  // Set the display title
  char displayTitle[200];
  if(IsOnline())
    sprintf(displayTitle,"%s (online): run %i event %i",
            GetDisplayName().c_str(),GetCurrentRunNumber(),
            fCachedDataContainer->GetMidasData().GetSerialNumber());
  else
    sprintf(displayTitle,"%s (offline): run %i event %i",
            GetDisplayName().c_str(),GetCurrentRunNumber(),
            fCachedDataContainer->GetMidasData().GetSerialNumber());
  GetDisplayWindow()->GetMain()->SetWindowName(displayTitle);
  // Update canvas and window sizes
  fMainWindow->ResetSize();
}
virtual void TRootanaEventLoop::Usage (void) [virtual, inherited]
Called when there is a usage error. This code should print a usage message and then return.
Reimplemented in MyTestLoop.
void TRootanaEventLoop::Usage (void) [virtual, inherited]
Called when there is a usage error. This code should print a usage message and then return.
Reimplemented in MyTestLoop.
Definition at line 76 of file TRootanaEventLoop.cxx.
Referenced by TRootanaEventLoop::PrintHelp().
{};
Member Data Documentation
TDataContainer * TRootanaDisplay::fCachedDataContainer [private]
We keep a cached copy of the midas event (so that it can used for callback).
Definition at line 156 of file TRootanaDisplay.hxx.
Referenced by ProcessMidasEvent(), SetCachedDataContainer(), and UpdatePlotsAction().
std::vector< std::pair< int, TCanvasHandleBase * > > TRootanaDisplay::fCanvasHandlers [private]
This is a vector of user-defined canvas handler classes. The first part of pair is the tab number.
Definition at line 171 of file TRootanaDisplay.hxx.
Referenced by AddSingleCanvas(), BeginRun(), EndRun(), ProcessMidasEvent(), Reset(), UpdatePlotsAction(), and ~TRootanaDisplay().
std::string TRootanaDisplay::fDisplayName [private]
Display name.
Definition at line 167 of file TRootanaDisplay.hxx.
Referenced by GetDisplayName(), and SetDisplayName().
TMainDisplayWindow * TRootanaDisplay::fMainWindow [private]
The pointer to our display window.
Definition at line 139 of file TRootanaDisplay.hxx.
Referenced by AddSingleCanvas(), EventSkipButtonPushed(), GetDisplayWindow(), InitializeMainWindow(), ProcessMidasEvent(), SetNumberSkipEvent(), and UpdatePlotsAction().
int TRootanaDisplay::fNumberProcessed [private]
Definition at line 136 of file TRootanaDisplay.hxx.
Referenced by ProcessMidasEvent().
int TRootanaDisplay::fNumberSkipEventsOnline [private]
Variable to keep track of how many events to skip before updating display; we have separate variable for online and offline modes.
Definition at line 133 of file TRootanaDisplay.hxx.
Referenced by EventSkipButtonPushed(), InitializeMainWindow(), ProcessMidasEvent(), and SetNumberSkipEvent().
TDirectory * TRootanaEventLoop::fOnlineHistDir [protected, inherited]
TDirectory for online histograms.
Definition at line 154 of file TRootanaEventLoop.hxx.
Referenced by TRootanaEventLoop::ExecuteLoop(), MyTestLoop::ProcessMidasEvent(), and TRootanaEventLoop::TRootanaEventLoop().
static TRootanaEventLoop * TRootanaEventLoop::fTRootanaEventLoop = NULL [static, protected, inherited]
The static pointer to the singleton instance.
Definition at line 151 of file TRootanaEventLoop.hxx.
Referenced by TRootanaEventLoop::CreateSingleton(), and TRootanaEventLoop::Get().
bool TRootanaDisplay::waitingForNextButton [private]
Definition at line 129 of file TRootanaDisplay.hxx.
Referenced by NextButtonPushed(), and ProcessMidasEvent().
The documentation for this class was generated from the following files:
include/TRootanaDisplay.hxx
libAnalyzerDisplay/TRootanaDisplay.hxx
libAnalyzerDisplay/TRootanaDisplay.cxx