ROOT Analyzer: TNetDirectoryConnection Class Reference
TNetDirectoryConnection Class Reference
Public Member Functions
TNetDirectoryConnection (const char *host, int port)
int Reconnect ()
void Request (const char *req)
TObject * ReadObject (TClass *type)
Private Attributes
TSocket * fSocket
Detailed Description
Definition at line 18 of file TNetDirectory.cxx.
Constructor & Destructor Documentation
TNetDirectoryConnection::TNetDirectoryConnection (const char * host, int port) [inline]
Definition at line 24 of file TNetDirectory.cxx.
References fSocket.
  {
    fSocket = new TSocket(host, port);
    printf("Connected to %s:%d\n", host, port);
  }
Member Function Documentation
TObject* TNetDirectoryConnection::ReadObject (TClass * type) [inline]
Definition at line 49 of file TNetDirectory.cxx.
References fSocket.
Referenced by TNetDirectory::FindObject(), TNetDirectory::Get(), TNetDirectory::GetListOfKeys(), and TNetDirectory::ResetTH1().
  {
    TMessage *mr = 0;
    int r = fSocket->Recv(mr);
    //printf("ReadObject recv %d\n", r);
    if (r <= 0) {
      printf("Error reading from socket!\n");
      return NULL;
    }
    TObject *obj = NULL;
    if (mr) {
      //mr->Print();
      obj = (TObject*)mr->ReadObjectAny(mr->GetClass());
    }
    //printf("mr %p, obj %p, class %p, %s\n", mr, obj, mr->GetClass(), mr->GetClass()->GetName());
    if (obj) {
      //obj->Print();
      if (!obj->InheritsFrom(type)) {
        if (obj->IsA() == TObjString::Class()) {
            TObjString *ostr = (TObjString*)obj;
            printf("Instead of a %s, received a %s reading \'%s\'\n", type->GetName(), obj->IsA()->GetName(), ostr->GetName());
            return NULL;
        }
        printf("Object type mismatch, received %s, expected %s\n", obj->IsA()->GetName(), type->GetName());
        return NULL;
      }
    }
    if (mr)
      delete mr;
    return obj;
  }
int TNetDirectoryConnection::Reconnect () [inline]
Definition at line 30 of file TNetDirectory.cxx.
References fSocket.
Referenced by TNetDirectory::Reconnect().
  {
    std::string host = fSocket->GetName();
    int         port = fSocket->GetPort();
    fSocket->Close();
    delete fSocket;
    fSocket = new TSocket(host.c_str(), port);
    printf("Connected to %s:%d\n", host.c_str(), port);
    return 0;
  }
void TNetDirectoryConnection::Request (const char * req) [inline]
Definition at line 41 of file TNetDirectory.cxx.
References fSocket, and gVerbose.
Referenced by TNetDirectory::FindObject(), TNetDirectory::Get(), TNetDirectory::GetListOfKeys(), and TNetDirectory::ResetTH1().
  {
    if (gVerbose)
      printf("Request [%s]\n", req);
    int s = fSocket->Send(req);
    //printf("Request sent %d\n", s);
  }
Member Data Documentation
TSocket* TNetDirectoryConnection::fSocket [private]
Definition at line 20 of file TNetDirectory.cxx.
Referenced by ReadObject(), Reconnect(), Request(), and TNetDirectoryConnection().
The documentation for this class was generated from the following file:
libNetDirectory/TNetDirectory.cxx