ROOT Analyzer: TV792Data Class Reference
TV792Data Class Reference
Class for storing data from CAEN V792 module.
#include <TV792Data.hxx>
Public Member Functions
TV792Data (int bklen, int bktype, const char *name, void *pdata)
Constructor.
void Print ()
Print the bank contents in a structured way.
uint32_t GetGeoAddress () const
Get GEO address.
uint32_t GetCrate () const
Get the crate number.
uint32_t GetNumberChannels () const
Get the number of converted channels.
uint32_t GetEventCounter () const
Get the event counter.
std::vector< VADCMeasurement > & GetMeasurements ()
Get the Vector of TDC Measurements.
TV792Data (int bklen, int bktype, const char *name, void *pdata)
Constructor.
void Print ()
Print the bank contents in a structured way.
uint32_t GetGeoAddress () const
Get GEO address.
uint32_t GetCrate () const
Get the crate number.
uint32_t GetNumberChannels () const
Get the number of converted channels.
uint32_t GetEventCounter () const
Get the event counter.
std::vector< VADCMeasurement > & GetMeasurements ()
Get the Vector of TDC Measurements.
const uint16_t * GetData16 () const
const uint16_t * GetData16 () const
const uint32_t * GetData32 () const
const uint32_t * GetData32 () const
const uint64_t * GetData64 () const
const uint64_t * GetData64 () const
int GetSize () const
int GetSize () const
int GetType () const
int GetType () const
std::string GetName () const
std::string GetName () const
void Dump ()
Dump the bank contents in an unstructured way.
void Dump ()
Dump the bank contents in an unstructured way.
Private Attributes
std::vector< VADCMeasurement > fMeasurements
Vector of TDC Measurements.
uint32_t fAdc_header_word
Fields to hold the header, measurement, trailer and error words.
uint32_t fAdc_trailer_word
Detailed Description
Class for storing data from CAEN V792 module.
Definition at line 53 of file TV792Data.hxx.
Constructor & Destructor Documentation
TV792Data::TV792Data (int bklen, int bktype, const char * name, void * pdata)
Constructor.
Definition at line 5 of file TV792Data.cxx.
References fAdc_header_word, fAdc_trailer_word, fMeasurements, TGenericData::GetData32(), and TGenericData::GetSize().
                                                                        :
  TGenericData(bklen, bktype, name, pdata)
{
  fAdc_header_word = 0;
  fAdc_trailer_word = 0;
  for(int i = 0; i < GetSize(); i++){
    uint32_t word = GetData32()[i];
    if((word & 0x07000000) == 0x02000000){ // header
      fAdc_header_word = word;
    }
    if((word & 0x07000000) == 0x00000000) // measurement
      fMeasurements.push_back(VADCMeasurement(fAdc_header_word,word));
    if((word & 0x07000000) == 0x04000000) // trailer
      fAdc_trailer_word = word;
  }
}
TV792Data::TV792Data (int bklen, int bktype, const char * name, void * pdata)
Constructor.
Member Function Documentation
void TGenericData::Dump () [inline, inherited]
Dump the bank contents in an unstructured way.
Definition at line 38 of file TGenericData.hxx.
References TGenericData::GetData32(), TGenericData::GetName(), and TGenericData::GetSize().
             {
    std::cout << "Generic decoder for bank named " <<  GetName().c_str() << std::endl;
    for(int i = 0; i < GetSize(); i++){
      std::cout << std::hex << "0x" << GetData32()[i] << std::dec << std::endl;
    }
  }
void TGenericData::Dump () [inline, inherited]
Dump the bank contents in an unstructured way.
Definition at line 38 of file TGenericData.hxx.
References TGenericData::GetData32(), TGenericData::GetName(), and TGenericData::GetSize().
Referenced by TGenericData::Print().
             {
    std::cout << "Generic decoder for bank named " <<  GetName().c_str() << std::endl;
    for(int i = 0; i < GetSize(); i++){
      std::cout << std::hex << "0x" << GetData32()[i] << std::dec << std::endl;
    }
  }
uint32_t TV792Data::GetCrate () const [inline]
Get the crate number.
Definition at line 68 of file TV792Data.hxx.
References fAdc_header_word.
{return ((fAdc_header_word & 0xff0000) >> 16);}
uint32_t TV792Data::GetCrate () const [inline]
Get the crate number.
Definition at line 68 of file TV792Data.hxx.
References fAdc_header_word.
Referenced by Print().
{return ((fAdc_header_word & 0xff0000) >> 16);}
const uint16_t* TGenericData::GetData16 () const [inline, inherited]
Definition at line 23 of file TGenericData.hxx.
References TGenericData::fData.
{ return reinterpret_cast<const uint16_t*>(fData); }
const uint16_t* TGenericData::GetData16 () const [inline, inherited]
Definition at line 23 of file TGenericData.hxx.
References TGenericData::fData.
{ return reinterpret_cast<const uint16_t*>(fData); }
const uint32_t* TGenericData::GetData32 () const [inline, inherited]
Definition at line 26 of file TGenericData.hxx.
References TGenericData::fData.
{ return reinterpret_cast<const uint32_t*>(fData); }
const uint32_t* TGenericData::GetData32 () const [inline, inherited]
Definition at line 26 of file TGenericData.hxx.
References TGenericData::fData.
Referenced by TGenericData::Dump(), TMesytecData::TMesytecData(), TV1190Data::TV1190Data(), and TV792Data().
{ return reinterpret_cast<const uint32_t*>(fData); }
const uint64_t* TGenericData::GetData64 () const [inline, inherited]
Definition at line 29 of file TGenericData.hxx.
References TGenericData::fData.
{ return reinterpret_cast<const uint64_t*>(fData); }
const uint64_t* TGenericData::GetData64 () const [inline, inherited]
Definition at line 29 of file TGenericData.hxx.
References TGenericData::fData.
{ return reinterpret_cast<const uint64_t*>(fData); }
uint32_t TV792Data::GetEventCounter () const [inline]
Get the event counter.
Definition at line 74 of file TV792Data.hxx.
References fAdc_trailer_word.
{return (fAdc_trailer_word & 0xffffff); };
uint32_t TV792Data::GetEventCounter () const [inline]
Get the event counter.
Definition at line 74 of file TV792Data.hxx.
References fAdc_trailer_word.
Referenced by Print().
{return (fAdc_trailer_word & 0xffffff); };
uint32_t TV792Data::GetGeoAddress () const [inline]
Get GEO address.
Definition at line 65 of file TV792Data.hxx.
References fAdc_header_word.
{return ((fAdc_header_word & 0xf8000000) >> 27);}
uint32_t TV792Data::GetGeoAddress () const [inline]
Get GEO address.
Definition at line 65 of file TV792Data.hxx.
References fAdc_header_word.
Referenced by Print().
{return ((fAdc_header_word & 0xf8000000) >> 27);}
std::vector<VADCMeasurement>& TV792Data::GetMeasurements () [inline]
Get the Vector of TDC Measurements.
Definition at line 77 of file TV792Data.hxx.
References fMeasurements.
{return fMeasurements;}
std::vector<VADCMeasurement>& TV792Data::GetMeasurements () [inline]
Get the Vector of TDC Measurements.
Definition at line 77 of file TV792Data.hxx.
References fMeasurements.
Referenced by TComplicatedExampleCanvas::UpdateCanvasHistograms().
{return fMeasurements;}
std::string TGenericData::GetName () const [inline, inherited]
Definition at line 35 of file TGenericData.hxx.
References TGenericData::fBankName.
{return fBankName;}
std::string TGenericData::GetName () const [inline, inherited]
Definition at line 35 of file TGenericData.hxx.
References TGenericData::fBankName.
Referenced by TGenericData::Dump(), Print(), TV1190Data::Print(), and TMesytecData::Print().
{return fBankName;}
uint32_t TV792Data::GetNumberChannels () const [inline]
Get the number of converted channels.
Definition at line 71 of file TV792Data.hxx.
References fAdc_header_word.
{return ((fAdc_header_word & 0x3f00) >> 8); };
uint32_t TV792Data::GetNumberChannels () const [inline]
Get the number of converted channels.
Definition at line 71 of file TV792Data.hxx.
References fAdc_header_word.
Referenced by Print().
{return ((fAdc_header_word & 0x3f00) >> 8); };
int TGenericData::GetSize () const [inline, inherited]
Definition at line 31 of file TGenericData.hxx.
References TGenericData::fSize.
{return fSize;}
int TGenericData::GetSize () const [inline, inherited]
Definition at line 31 of file TGenericData.hxx.
References TGenericData::fSize.
Referenced by TGenericData::Dump(), TMesytecData::TMesytecData(), TV1190Data::TV1190Data(), and TV792Data().
{return fSize;}
int TGenericData::GetType () const [inline, inherited]
Definition at line 33 of file TGenericData.hxx.
References TGenericData::fBankType.
{return fBankType;}
int TGenericData::GetType () const [inline, inherited]
Definition at line 33 of file TGenericData.hxx.
References TGenericData::fBankType.
{return fBankType;}
void TV792Data::Print () [virtual]
Print the bank contents in a structured way.
Reimplemented from TGenericData.
void TV792Data::Print () [virtual]
Print the bank contents in a structured way.
Reimplemented from TGenericData.
Definition at line 31 of file TV792Data.cxx.
References fMeasurements, GetCrate(), GetEventCounter(), GetGeoAddress(), TGenericData::GetName(), and GetNumberChannels().
Referenced by MyTestLoop::ProcessMidasEvent().
                     {
  std::cout << "V792 decoder for bank " << GetName().c_str() << std::endl;
  std::cout << "Geo-Add = " << GetGeoAddress() << ", crate number =  " << GetCrate()
            << ", Number of channels= " << GetNumberChannels() << ", event counter = "
            << GetEventCounter() << std::endl;
  for(int i = 0; i < fMeasurements.size(); i++){
    std::cout << "chan " << fMeasurements[i].GetChannel()
              << " meas = " << fMeasurements[i].GetMeasurement() << " " ;
    std::cout << " [UN/OV=" << fMeasurements[i].IsUnderThreshold() << "/" << fMeasurements[i].IsOverFlow() << "],  ";
    if((i-2)%3 == 0) std::cout << std::endl;
  }
  std::cout << std::endl;
}
Member Data Documentation
uint32_t TV792Data::fAdc_header_word [private]
Fields to hold the header, measurement, trailer and error words.
Definition at line 87 of file TV792Data.hxx.
Referenced by GetCrate(), GetGeoAddress(), GetNumberChannels(), and TV792Data().
uint32_t TV792Data::fAdc_trailer_word [private]
Definition at line 88 of file TV792Data.hxx.
Referenced by GetEventCounter(), and TV792Data().
std::vector< VADCMeasurement > TV792Data::fMeasurements [private]
Vector of TDC Measurements.
Definition at line 83 of file TV792Data.hxx.
Referenced by GetMeasurements(), Print(), and TV792Data().
The documentation for this class was generated from the following files:
include/TV792Data.hxx
libAnalyzer/TV792Data.hxx
libAnalyzer/TV792Data.cxx