ROOT Analyzer: LockRootGuard Struct Reference
LockRootGuard Struct Reference
#include <RootLock.h>
Public Member Functions
LockRootGuard ()
~LockRootGuard ()
void Unlock ()
LockRootGuard ()
~LockRootGuard ()
void Unlock ()
Public Attributes
bool fLocked
Detailed Description
Definition at line 17 of file RootLock.h.
Constructor & Destructor Documentation
LockRootGuard::LockRootGuard ()
Definition at line 40 of file RootLock.cxx.
References fLocked, and LockRoot().
{
  fLocked = true;
  LockRoot();
}
LockRootGuard::~LockRootGuard ()
Definition at line 46 of file RootLock.cxx.
References fLocked, and Unlock().
{
  if (fLocked)
    Unlock();
}
LockRootGuard::LockRootGuard ()
LockRootGuard::~LockRootGuard ()
Member Function Documentation
void LockRootGuard::Unlock ()
void LockRootGuard::Unlock ()
Definition at line 52 of file RootLock.cxx.
References fLocked, and UnlockRoot().
Referenced by root_server_thread(), and ~LockRootGuard().
{
  UnlockRoot();
  fLocked = false;
}
Member Data Documentation
bool LockRootGuard::fLocked
Definition at line 19 of file RootLock.h.
Referenced by LockRootGuard(), Unlock(), and ~LockRootGuard().
The documentation for this struct was generated from the following files:
include/RootLock.h
libNetDirectory/RootLock.h
libNetDirectory/RootLock.cxx