ROOT Analyzer: TComplicatedExampleCanvas Class Reference
TComplicatedExampleCanvas Class Reference
A complicated canvas example, using the values from V792 module.
#include <TComplicatedExampleCanvas.hxx>
Public Member Functions
TComplicatedExampleCanvas ()
void ResetCanvasHistograms ()
Reset the histograms for this canvas.
void UpdateCanvasHistograms (TDataContainer &dataContainer)
Update the histograms for this canvas.
void PlotCanvas (TDataContainer &dataContainer, TRootEmbeddedCanvas *embedCanvas)
Plot the histograms for this canvas.
void SetUpCompositeFrame (TGCompositeFrame *compFrame, TRootanaDisplay *display)
void BeginRun (int transition, int run, int time)
Take actions at begin run.
TComplicatedExampleCanvas ()
void ResetCanvasHistograms ()
Reset the histograms for this canvas.
void UpdateCanvasHistograms (TDataContainer &dataContainer)
Update the histograms for this canvas.
void PlotCanvas (TDataContainer &dataContainer, TRootEmbeddedCanvas *embedCanvas)
Plot the histograms for this canvas.
void SetUpCompositeFrame (TGCompositeFrame *compFrame, TRootanaDisplay *display)
void BeginRun (int transition, int run, int time)
Take actions at begin run.
virtual void EndRun (int transition, int run, int time)
Take actions at end run.
virtual void EndRun (int transition, int run, int time)
Take actions at end run.
std::string GetTabName ()
std::string GetTabName ()
TRootEmbeddedCanvas * GetEmbeddedCanvas ()
This method is only.
TRootEmbeddedCanvas * GetEmbeddedCanvas ()
This method is only.
Private Attributes
TH1F * adcValue [32]
TGNumberEntry * fBankCounterButton
Detailed Description
A complicated canvas example, using the values from V792 module.
Definition at line 13 of file TComplicatedExampleCanvas.hxx.
Constructor & Destructor Documentation
TComplicatedExampleCanvas::TComplicatedExampleCanvas ()
Definition at line 9 of file TComplicatedExampleCanvas.cxx.
References adcValue.
                                                    : TCanvasHandleBase("V792 ADC Values"){
  for(int i = 0; i < 32; i++){
    char name[100];
    char title[100];
    sprintf(name,"adcValue%i",i+10);
    sprintf(title,"ADC values for channel %i",i);
    adcValue[i] = new TH1F(name,title,2000,0,4000);
  }
}
TComplicatedExampleCanvas::TComplicatedExampleCanvas ()
Member Function Documentation
void TComplicatedExampleCanvas::BeginRun (int transition, int run, int time) [inline, virtual]
Take actions at begin run.
Reimplemented from TCanvasHandleBase.
Definition at line 29 of file TComplicatedExampleCanvas.hxx.
{
    std::cout << "BOR: User can do something here... " << std::endl;
  }
void TComplicatedExampleCanvas::BeginRun (int transition, int run, int time) [inline, virtual]
Take actions at begin run.
Reimplemented from TCanvasHandleBase.
Definition at line 29 of file TComplicatedExampleCanvas.hxx.
{
    std::cout << "BOR: User can do something here... " << std::endl;
  }
virtual void TCanvasHandleBase::EndRun (int transition, int run, int time) [inline, virtual, inherited]
Take actions at end run.
Reimplemented in TFancyHistogramCanvas, and TFancyHistogramCanvas.
Definition at line 36 of file TCanvasHandleBase.hxx.
{};
virtual void TCanvasHandleBase::EndRun (int transition, int run, int time) [inline, virtual, inherited]
Take actions at end run.
Reimplemented in TFancyHistogramCanvas, and TFancyHistogramCanvas.
Definition at line 36 of file TCanvasHandleBase.hxx.
{};
TRootEmbeddedCanvas* TCanvasHandleBase::GetEmbeddedCanvas () [inline, inherited]
This method is only.
Definition at line 41 of file TCanvasHandleBase.hxx.
{
    std::cerr<< "Not implemented for base class; exiting." << std::endl;
    exit(0);
    return 0;
  }
TRootEmbeddedCanvas* TCanvasHandleBase::GetEmbeddedCanvas () [inline, inherited]
This method is only.
Definition at line 41 of file TCanvasHandleBase.hxx.
{
    std::cerr<< "Not implemented for base class; exiting." << std::endl;
    exit(0);
    return 0;
  }
std::string TCanvasHandleBase::GetTabName () [inline, inherited]
Definition at line 38 of file TCanvasHandleBase.hxx.
References TCanvasHandleBase::fTabName.
{return fTabName;}
std::string TCanvasHandleBase::GetTabName () [inline, inherited]
Definition at line 38 of file TCanvasHandleBase.hxx.
References TCanvasHandleBase::fTabName.
Referenced by TRootanaDisplay::AddSingleCanvas().
{return fTabName;}
void TComplicatedExampleCanvas::PlotCanvas (TDataContainer & dataContainer, TRootEmbeddedCanvas * embedCanvas) [virtual]
Plot the histograms for this canvas.
Implements TCanvasHandleBase.
void TComplicatedExampleCanvas::PlotCanvas (TDataContainer & dataContainer, TRootEmbeddedCanvas * embedCanvas) [virtual]
Plot the histograms for this canvas.
Implements TCanvasHandleBase.
Definition at line 74 of file TComplicatedExampleCanvas.cxx.
References adcValue, and fBankCounterButton.
{
  TCanvas* c1 = embedCanvas->GetCanvas();
  c1->Clear();
  int whichbank = fBankCounterButton->GetNumberEntry()->GetIntNumber();
  if(whichbank >=0 && whichbank <32)
    adcValue[whichbank]->Draw();
  c1->Modified();
  c1->Update();
}
void TComplicatedExampleCanvas::ResetCanvasHistograms () [virtual]
Reset the histograms for this canvas.
Implements TCanvasHandleBase.
void TComplicatedExampleCanvas::ResetCanvasHistograms () [virtual]
Reset the histograms for this canvas.
Implements TCanvasHandleBase.
Definition at line 46 of file TComplicatedExampleCanvas.cxx.
References adcValue.
{
  for(int i = 0; i < 32; i++)
    adcValue[i]->Reset();
}
void TComplicatedExampleCanvas::SetUpCompositeFrame (TGCompositeFrame * compFrame, TRootanaDisplay * display) [virtual]
Reimplemented from TCanvasHandleBase.
void TComplicatedExampleCanvas::SetUpCompositeFrame (TGCompositeFrame * compFrame, TRootanaDisplay * display) [virtual]
Reimplemented from TCanvasHandleBase.
Definition at line 20 of file TComplicatedExampleCanvas.cxx.
References fBankCounterButton.
{
  // Now create my embedded canvas, along with the various buttons for this canvas.
  TGHorizontalFrame *labelframe = new TGHorizontalFrame(compFrame,200,40);
  fBankCounterButton = new TGNumberEntry(labelframe, 0, 9,999, TGNumberFormat::kNESInteger,
                                              TGNumberFormat::kNEANonNegative,
                                              TGNumberFormat::kNELLimitMinMax,
                                              0, 31);
  fBankCounterButton->Connect("ValueSet(Long_t)", "TRootanaDisplay", display, "UpdatePlotsAction()");
  fBankCounterButton->GetNumberEntry()->Connect("ReturnPressed()", "TRootanaDisplay", display, "UpdatePlotsAction()");
  labelframe->AddFrame(fBankCounterButton, new TGLayoutHints(kLHintsTop | kLHintsLeft, 5, 5, 5, 5));
  TGLabel *labelMinicrate = new TGLabel(labelframe, "ADC Channel (0-31)");
  labelframe->AddFrame(labelMinicrate, new TGLayoutHints(kLHintsTop | kLHintsLeft, 5, 5, 5, 5));
  compFrame->AddFrame(labelframe, new TGLayoutHints(kLHintsCenterX,2,2,2,2));
}
void TComplicatedExampleCanvas::UpdateCanvasHistograms (TDataContainer & dataContainer) [virtual]
Update the histograms for this canvas.
Implements TCanvasHandleBase.
void TComplicatedExampleCanvas::UpdateCanvasHistograms (TDataContainer & dataContainer) [virtual]
Update the histograms for this canvas.
Implements TCanvasHandleBase.
Definition at line 53 of file TComplicatedExampleCanvas.cxx.
References adcValue, VADCMeasurement::GetChannel(), TDataContainer::GetEventData(), VADCMeasurement::GetMeasurement(), and TV792Data::GetMeasurements().
{
  // Get the V792 data
  TV792Data *v792 = dataContainer.GetEventData<TV792Data>("ADC0");
  if(v792 ){
    // Loop over ADC measurements
    std::vector<VADCMeasurement>& measurements = v792->GetMeasurements();
    for(unsigned int i = 0; i < measurements.size(); i++){
      VADCMeasurement adcmeas = measurements[i];
      // For each measurement, update histogram
      int chan = adcmeas.GetChannel();
      if(chan >= 0 && chan < 32){
        adcValue[chan]->Fill(adcmeas.GetMeasurement());
      }
    }
  }
}
Member Data Documentation
TH1F * TComplicatedExampleCanvas::adcValue [private]
Definition at line 34 of file TComplicatedExampleCanvas.hxx.
Referenced by PlotCanvas(), ResetCanvasHistograms(), TComplicatedExampleCanvas(), and UpdateCanvasHistograms().
TGNumberEntry * TComplicatedExampleCanvas::fBankCounterButton [private]
Definition at line 35 of file TComplicatedExampleCanvas.hxx.
Referenced by PlotCanvas(), and SetUpCompositeFrame().
The documentation for this class was generated from the following files:
include/TComplicatedExampleCanvas.hxx
libAnalyzerDisplay/TComplicatedExampleCanvas.hxx
libAnalyzerDisplay/TComplicatedExampleCanvas.cxx