ROOT Analyzer: include/RootLock.h File Reference
RootLock.h File Reference
Classes
struct LockRootGuard
Functions
void LockRoot ()
void UnlockRoot ()
void StartLockRootTimer (int period_msec=100)
Variables
bool gDebugLockRoot
Function Documentation
void LockRoot ()
Definition at line 23 of file RootLock.cxx.
Referenced by LockRootGuard::LockRootGuard().
{
  if (gDebugLockRoot)
    printf("Try Lock ROOT!\n");
  gWaitSema.Post();
  gRootSema.Wait();
  if (gDebugLockRoot)
    printf("Lock ROOT!\n");
}
void StartLockRootTimer (int period_msec = 100)
Definition at line 114 of file RootLock.cxx.
Referenced by StartMidasServer(), and StartNetDirectoryServer().
{
  ServerTimer::StartServerTimer(period_msec);
}
void UnlockRoot ()
Definition at line 33 of file RootLock.cxx.
Referenced by LockRootGuard::Unlock().
{
  if (gDebugLockRoot)
    printf("Unlock ROOT!\n");
  gDoneSema.Post();
}
Variable Documentation
bool gDebugLockRoot
Definition at line 21 of file RootLock.cxx.
Referenced by LockRoot(), ServerTimer::Notify(), and UnlockRoot().