ROOT Analyzer: TDCMeasurement Class Reference
TDCMeasurement Class Reference
#include <TV1190Data.hxx>
Public Member Functions
bool IsLeading () const
Is this the leading edge measurement?
bool IsTrailing () const
Is this the trailing edge measurement?
uint32_t GetMeasurement () const
Get the TDC measurement.
uint32_t GetTDCNumber () const
Get the TDC number.
uint32_t GetChannel () const
Get the channel number.
uint32_t GetEventID () const
Get Event ID.
uint32_t GetBunchID () const
Get Bunch ID.
bool HasTDCHeader () const
Check if measurement has a TDC header.
bool HasTDCTrailer () const
Check if measurement has a TDC trailer.
bool HasTDCErrorWord () const
Check if measurement has a TDC error word.
uint32_t GetErrors () const
Get Errors.
bool IsLeading () const
Is this the leading edge measurement?
bool IsTrailing () const
Is this the trailing edge measurement?
uint32_t GetMeasurement () const
Get the TDC measurement.
uint32_t GetTDCNumber () const
Get the TDC number.
uint32_t GetChannel () const
Get the channel number.
uint32_t GetEventID () const
Get Event ID.
uint32_t GetBunchID () const
Get Bunch ID.
bool HasTDCHeader () const
Check if measurement has a TDC header.
bool HasTDCTrailer () const
Check if measurement has a TDC trailer.
bool HasTDCErrorWord () const
Check if measurement has a TDC error word.
uint32_t GetErrors () const
Get Errors.
Private Member Functions
TDCMeasurement (uint32_t header, uint32_t measurement)
Constructor; need to pass in header and measurement.
void SetTrailer (uint32_t trailer)
Set the trailer word.
void SetErrors (uint32_t error)
Set the error word.
TDCMeasurement ()
TDCMeasurement (uint32_t header, uint32_t measurement)
Constructor; need to pass in header and measurement.
void SetTrailer (uint32_t trailer)
Set the trailer word.
void SetErrors (uint32_t error)
Set the error word.
TDCMeasurement ()
Private Attributes
uint32_t tdc_header_word
Found fields to hold the header, measurement, trailer and error words.
uint32_t tdc_measurement_word
uint32_t tdc_trailer_word
uint32_t tdc_error_error
Friends
class TV1190Data
Detailed Description
Class for each TDC measurement For the definition of obscure variables see the CAEN V1190 manual.
Definition at line 10 of file TV1190Data.hxx.
Constructor & Destructor Documentation
TDCMeasurement::TDCMeasurement (uint32_t header, uint32_t measurement) [inline, private]
Constructor; need to pass in header and measurement.
Definition at line 53 of file TV1190Data.hxx.
                                                       :
    tdc_header_word(header),
    tdc_measurement_word(measurement),
    tdc_trailer_word(0),tdc_error_error(0){};
TDCMeasurement::TDCMeasurement () [private]
TDCMeasurement::TDCMeasurement (uint32_t header, uint32_t measurement) [inline, private]
Constructor; need to pass in header and measurement.
Definition at line 53 of file TV1190Data.hxx.
                                                       :
    tdc_header_word(header),
    tdc_measurement_word(measurement),
    tdc_trailer_word(0),tdc_error_error(0){};
TDCMeasurement::TDCMeasurement () [private]
Member Function Documentation
uint32_t TDCMeasurement::GetBunchID () const
Get Bunch ID.
uint32_t TDCMeasurement::GetBunchID () const
Get Bunch ID.
Definition at line 30 of file TV1190Data.cxx.
References HasTDCHeader(), and tdc_header_word.
{
  if(HasTDCHeader())
    return ((tdc_header_word & 0xfff));
  return 0xdeadbeef;
}
uint32_t TDCMeasurement::GetChannel () const [inline]
Get the channel number.
Definition at line 26 of file TV1190Data.hxx.
References tdc_measurement_word.
{return ((tdc_measurement_word & 0x3f80000) >> 19);}
uint32_t TDCMeasurement::GetChannel () const [inline]
Get the channel number.
Definition at line 26 of file TV1190Data.hxx.
References tdc_measurement_word.
Referenced by MyTestLoop::ProcessMidasEvent().
{return ((tdc_measurement_word & 0x3f80000) >> 19);}
uint32_t TDCMeasurement::GetErrors () const
Get Errors.
uint32_t TDCMeasurement::GetErrors () const
Get Errors.
Definition at line 37 of file TV1190Data.cxx.
References HasTDCErrorWord(), and tdc_error_error.
{
  if(HasTDCErrorWord())
    return ((tdc_error_error & 0x7fff));
  return 0xdeadbeef;
}
uint32_t TDCMeasurement::GetEventID () const
Get Event ID.
uint32_t TDCMeasurement::GetEventID () const
Get Event ID.
Definition at line 21 of file TV1190Data.cxx.
References HasTDCHeader(), HasTDCTrailer(), tdc_header_word, and tdc_trailer_word.
{
  if(HasTDCHeader())
    return ((tdc_header_word & 0xfff000) >> 12 );
  if(HasTDCTrailer())
    return ((tdc_trailer_word & 0xfff000) >> 12 );
  return 0xdeadbeef;
}
uint32_t TDCMeasurement::GetMeasurement () const [inline]
Get the TDC measurement.
Definition at line 21 of file TV1190Data.hxx.
References tdc_measurement_word.
{return (tdc_measurement_word & 0x7ffff);}
uint32_t TDCMeasurement::GetMeasurement () const [inline]
Get the TDC measurement.
Definition at line 21 of file TV1190Data.hxx.
References tdc_measurement_word.
Referenced by MyTestLoop::ProcessMidasEvent(), and TSimpleExampleCanvas::UpdateCanvasHistograms().
{return (tdc_measurement_word & 0x7ffff);}
uint32_t TDCMeasurement::GetTDCNumber () const
Get the TDC number.
uint32_t TDCMeasurement::GetTDCNumber () const
Get the TDC number.
Definition at line 12 of file TV1190Data.cxx.
References HasTDCHeader(), HasTDCTrailer(), tdc_header_word, and tdc_trailer_word.
Referenced by MyTestLoop::ProcessMidasEvent().
{
  if(HasTDCHeader())
    return ((tdc_header_word & 0x3000000) >> 24 );
  if(HasTDCTrailer())
    return ((tdc_trailer_word & 0x3000000) >> 24 );
  return 0xdeadbeef;
}
bool TDCMeasurement::HasTDCErrorWord () const [inline]
Check if measurement has a TDC error word.
Definition at line 39 of file TV1190Data.hxx.
References tdc_error_error.
{return (tdc_error_error != 0);}
bool TDCMeasurement::HasTDCErrorWord () const [inline]
Check if measurement has a TDC error word.
Definition at line 39 of file TV1190Data.hxx.
References tdc_error_error.
Referenced by GetErrors().
{return (tdc_error_error != 0);}
bool TDCMeasurement::HasTDCHeader () const [inline]
Check if measurement has a TDC header.
Definition at line 35 of file TV1190Data.hxx.
References tdc_header_word.
{return (tdc_header_word != 0);}
bool TDCMeasurement::HasTDCHeader () const [inline]
Check if measurement has a TDC header.
Definition at line 35 of file TV1190Data.hxx.
References tdc_header_word.
Referenced by GetBunchID(), GetEventID(), and GetTDCNumber().
{return (tdc_header_word != 0);}
bool TDCMeasurement::HasTDCTrailer () const [inline]
Check if measurement has a TDC trailer.
Definition at line 37 of file TV1190Data.hxx.
References tdc_trailer_word.
{return (tdc_trailer_word != 0);}
bool TDCMeasurement::HasTDCTrailer () const [inline]
Check if measurement has a TDC trailer.
Definition at line 37 of file TV1190Data.hxx.
References tdc_trailer_word.
Referenced by GetEventID(), and GetTDCNumber().
{return (tdc_trailer_word != 0);}
bool TDCMeasurement::IsLeading () const [inline]
Is this the leading edge measurement?
Definition at line 17 of file TV1190Data.hxx.
References tdc_measurement_word.
{return ((tdc_measurement_word & 0x4000000) == 0x0000000);}
bool TDCMeasurement::IsLeading () const [inline]
Is this the leading edge measurement?
Definition at line 17 of file TV1190Data.hxx.
References tdc_measurement_word.
{return ((tdc_measurement_word & 0x4000000) == 0x0000000);}
bool TDCMeasurement::IsTrailing () const [inline]
Is this the trailing edge measurement?
Definition at line 19 of file TV1190Data.hxx.
References tdc_measurement_word.
{return ((tdc_measurement_word & 0x4000000) == 0x4000000);}
bool TDCMeasurement::IsTrailing () const [inline]
Is this the trailing edge measurement?
Definition at line 19 of file TV1190Data.hxx.
References tdc_measurement_word.
{return ((tdc_measurement_word & 0x4000000) == 0x4000000);}
void TDCMeasurement::SetErrors (uint32_t error) [inline, private]
Set the error word.
Definition at line 62 of file TV1190Data.hxx.
References tdc_error_error.
{tdc_error_error = error;}
void TDCMeasurement::SetErrors (uint32_t error) [inline, private]
Set the error word.
Definition at line 62 of file TV1190Data.hxx.
References tdc_error_error.
{tdc_error_error = error;}
void TDCMeasurement::SetTrailer (uint32_t trailer) [private]
Set the trailer word.
void TDCMeasurement::SetTrailer (uint32_t trailer) [private]
Set the trailer word.
Definition at line 6 of file TV1190Data.cxx.
References tdc_trailer_word.
{
  tdc_trailer_word = trailer;
}
Friends And Related Function Documentation
TV1190Data [friend]
Definition at line 12 of file TV1190Data.hxx.
Member Data Documentation
uint32_t TDCMeasurement::tdc_error_error [private]
Definition at line 50 of file TV1190Data.hxx.
Referenced by GetErrors(), HasTDCErrorWord(), and SetErrors().
uint32_t TDCMeasurement::tdc_header_word [private]
Found fields to hold the header, measurement, trailer and error words.
Definition at line 47 of file TV1190Data.hxx.
Referenced by GetBunchID(), GetEventID(), GetTDCNumber(), and HasTDCHeader().
uint32_t TDCMeasurement::tdc_measurement_word [private]
Definition at line 48 of file TV1190Data.hxx.
Referenced by GetChannel(), GetMeasurement(), IsLeading(), and IsTrailing().
uint32_t TDCMeasurement::tdc_trailer_word [private]
Definition at line 49 of file TV1190Data.hxx.
Referenced by GetEventID(), GetTDCNumber(), HasTDCTrailer(), and SetTrailer().
The documentation for this class was generated from the following files:
include/TV1190Data.hxx
libAnalyzer/TV1190Data.hxx
libAnalyzer/TV1190Data.cxx