ROOT Analyzer: XmlOdb Struct Reference
XmlOdb Struct Reference
Access to ODB saved in XML format inside midas .mid files.
#include <XmlOdb.h>
Public Member Functions
XmlOdb (const char *buf, int bufLength)
Contructor from a string.
XmlOdb (const char *filename)
Contructor from a file.
virtual ~XmlOdb ()
Destructor.
TXMLNode * FindNode (TXMLNode *node, const char *name)
Find node with given name anywhere inside the given ODB tree.
void DumpTree (TXMLNode *node=NULL, int level=0)
Print out the contents of the ODB tree.
void DumpDirTree (TXMLNode *node=NULL, int level=0)
Print out the directory structure of the ODB tree.
const char * GetAttrValue (TXMLNode *node, const char *attrName)
Return the value of the named attribute.
TXMLNode * FindPath (TXMLNode *node, const char *path)
Follow the ODB path through the XML DOM tree.
TXMLNode * FindArrayPath (TXMLNode *node, const char *path, const char *type, int index)
Same as FindPath(), but also index into an array.
int odbReadAny (const char *name, int index, int tid, void *buf, int bufsize=0)
Read value of arbitrary type.
int odbReadInt (const char *name, int index, int defaultValue)
Read an integer value, midas type TID_INT.
uint32_t odbReadUint32 (const char *name, int index, uint32_t defaultValue)
Read an unsigned 32-bit integer value, midas type TID_DWORD.
bool odbReadBool (const char *name, int index, bool defaultValue)
Read a boolean value, midas type TID_BOOL.
double odbReadDouble (const char *name, int index, double defaultValue)
Read an 64-bit floating point value, midas type TID_DOUBLET.
float odbReadFloat (const char *name, int index, float defaultValue)
Read an 32-bit floating point value, midas type TID_FLOAT.
const char * odbReadString (const char *name, int index, const char *defaultValue)
Read a string value, midas type TID_STRING.
int odbReadArraySize (const char *name)
Read size of an array.
XmlOdb (const char *buf, int bufLength)
Contructor from a string.
XmlOdb (const char *filename)
Contructor from a file.
virtual ~XmlOdb ()
Destructor.
TXMLNode * FindNode (TXMLNode *node, const char *name)
Find node with given name anywhere inside the given ODB tree.
void DumpTree (TXMLNode *node=NULL, int level=0)
Print out the contents of the ODB tree.
void DumpDirTree (TXMLNode *node=NULL, int level=0)
Print out the directory structure of the ODB tree.
const char * GetAttrValue (TXMLNode *node, const char *attrName)
Return the value of the named attribute.
TXMLNode * FindPath (TXMLNode *node, const char *path)
Follow the ODB path through the XML DOM tree.
TXMLNode * FindArrayPath (TXMLNode *node, const char *path, const char *type, int index)
Same as FindPath(), but also index into an array.
int odbReadAny (const char *name, int index, int tid, void *buf, int bufsize=0)
Read value of arbitrary type.
int odbReadInt (const char *name, int index, int defaultValue)
Read an integer value, midas type TID_INT.
uint32_t odbReadUint32 (const char *name, int index, uint32_t defaultValue)
Read an unsigned 32-bit integer value, midas type TID_DWORD.
bool odbReadBool (const char *name, int index, bool defaultValue)
Read a boolean value, midas type TID_BOOL.
double odbReadDouble (const char *name, int index, double defaultValue)
Read an 64-bit floating point value, midas type TID_DOUBLET.
float odbReadFloat (const char *name, int index, float defaultValue)
Read an 32-bit floating point value, midas type TID_FLOAT.
const char * odbReadString (const char *name, int index, const char *defaultValue)
Read a string value, midas type TID_STRING.
int odbReadArraySize (const char *name)
Read size of an array.
Public Attributes
TDOMParser * fParser
XML parser for the XML-encoded ODB data.
TXMLNode * fOdb
Pointer to the root of the ODB tree.
Detailed Description
Access to ODB saved in XML format inside midas .mid files.
Definition at line 23 of file XmlOdb.h.
Constructor & Destructor Documentation
XmlOdb::XmlOdb (const char * buf, int bufLength)
Contructor from a string.
Definition at line 23 of file XmlOdb.cxx.
References FindNode(), fOdb, and fParser.
{
  fOdb = NULL;
  fParser = new TDOMParser();
  fParser->SetValidate(false);
  char*buf = (char*)malloc(bufLength);
  memcpy(buf, xbuf, bufLength);
  for (int i=0; i<bufLength; i++)
    if (!isascii(buf[i]))
      buf[i] = 'X';
    else if (buf[i]=='\n')
      0;
    else if (buf[i]=='\r')
      0;
    else if (!isprint(buf[i]))
      buf[i] = 'X';
    else if (buf[i] == 0x1D)
      buf[i] = 'X';
  char* xend = strstr(buf,"odb>");
  if (xend)
    xend[4] = 0;
  //printf("end: %s\n", buf+bufLength-5);
  fParser->ParseBuffer(buf,bufLength);
  TXMLDocument* doc = fParser->GetXMLDocument();
  if (!doc)
    {
      fprintf(stderr,"XmlOdb::XmlOdb: Malformed ODB dump: cannot get XML document\n");
      return;
    }
  fOdb = FindNode(doc->GetRootNode(),"odb");
  if (!fOdb)
    {
      fprintf(stderr,"XmlOdb::XmlOdb: Malformed ODB dump: cannot find <odb> tag\n");
      return;
    }
}
XmlOdb::XmlOdb (const char * filename)
Contructor from a file.
Definition at line 66 of file XmlOdb.cxx.
References FindNode(), fOdb, and fParser.
{
  fOdb = NULL;
  fParser = new TDOMParser();
  fParser->SetValidate(false);
  int status = fParser->ParseFile(filename);
  if (status != 0)
    {
      fprintf(stderr,"XmlOdb::XmlOdb: Failed to parse XML file \'%s\', ParseFile() returned %d\n", filename, status);
      return;
    }
  TXMLDocument* doc = fParser->GetXMLDocument();
  if (!doc)
    {
      fprintf(stderr,"XmlOdb::XmlOdb: Malformed ODB dump: cannot get XML document\n");
      return;
    }
  fOdb = FindNode(doc->GetRootNode(),"odb");
  if (!fOdb)
    {
      fprintf(stderr,"XmlOdb::XmlOdb: Malformed ODB dump: cannot find <odb> tag\n");
      return;
    }
}
XmlOdb::~XmlOdb () [virtual]
Destructor.
Definition at line 94 of file XmlOdb.cxx.
References fParser.
{
  delete fParser;
  fParser = NULL;
}
XmlOdb::XmlOdb (const char * buf, int bufLength)
Contructor from a string.
XmlOdb::XmlOdb (const char * filename)
Contructor from a file.
virtual XmlOdb::~XmlOdb () [virtual]
Destructor.
Member Function Documentation
void XmlOdb::DumpDirTree (TXMLNode * node = NULL, int level = 0)
Print out the directory structure of the ODB tree.
void XmlOdb::DumpDirTree (TXMLNode * node = NULL, int level = 0)
Print out the directory structure of the ODB tree.
Definition at line 157 of file XmlOdb.cxx.
References fOdb.
{
  if (!node)
    node = fOdb;
  if (!node)
    {
      fprintf(stderr,"XmlOdb::DumpDirTree: node is NULL!\n");
      return;
    }
  for (; node != NULL; node = node->GetNextNode())
    {
      const char* name = node->GetNodeName();
      if (strcmp(name,"dir") != 0)
        continue;
      for (int i=0; i<level; i++)
        printf(" ");
      printf("node name: \"%s\"\n",node->GetNodeName());
      TList* attrs = node->GetAttributes();
      TIter next(attrs);
      while (TXMLAttr *attr = (TXMLAttr*)next())
        {
          for (int i=0; i<level; i++)
            printf(" ");
          printf("attribute name: \"%s\", value: \"%s\"\n",attr->GetName(),attr->GetValue());
        }
      if (node->HasChildren())
        DumpDirTree(node->GetChildren(),level + 1);
    }
  //printf("no more next nodes...\n");
}
void XmlOdb::DumpTree (TXMLNode * node = NULL, int level = 0)
Print out the contents of the ODB tree.
void XmlOdb::DumpTree (TXMLNode * node = NULL, int level = 0)
Print out the contents of the ODB tree.
Definition at line 119 of file XmlOdb.cxx.
References fOdb.
{
  if (!node)
    node = fOdb;
  if (!node)
    {
      fprintf(stderr,"XmlOdb::DumpTree: node is NULL!\n");
      return;
    }
  while (node)
    {
      for (int i=0; i<level; i++)
        printf(" ");
      printf("node name: \"%s\"\n",node->GetNodeName());
      TList* attrs = node->GetAttributes();
      TIter next(attrs);
      while (TXMLAttr *attr = (TXMLAttr*)next())
        {
          for (int i=0; i<level; i++)
            printf(" ");
          printf("attribute name: \"%s\", value: \"%s\"\n",attr->GetName(),attr->GetValue());
        }
      const char*text = node->GetText();
      if (text)
        {
          for (int i=0; i<level; i++)
            printf(" ");
          printf("node text: \"%s\"\n",node->GetText());
        }
      if (node->HasChildren())
        DumpTree(node->GetChildren(),level + 1);
      node = node->GetNextNode();
    }
  //printf("no more next nodes...\n");
}
TXMLNode* XmlOdb::FindArrayPath (TXMLNode * node, const char * path, const char * type, int index)
Same as FindPath(), but also index into an array.
TXMLNode * XmlOdb::FindArrayPath (TXMLNode * node, const char * path, const char * type, int index)
Same as FindPath(), but also index into an array.
Definition at line 282 of file XmlOdb.cxx.
References FindPath(), fOdb, and GetAttrValue().
Referenced by odbReadBool(), odbReadDouble(), odbReadFloat(), odbReadInt(), odbReadString(), and odbReadUint32().
{
  if (!fOdb)
    return NULL;
  if (!node)
    node = fOdb->GetChildren();
  node = FindPath(node, path);
  if (!node)
    return NULL;
  const char* nodename = node->GetNodeName();
  const char* num_values = GetAttrValue(node,"num_values");
  const char* typevalue = GetAttrValue(node,"type");
  if (!typevalue || (strcasecmp(typevalue,type) != 0))
    {
      fprintf(stderr,"XmlOdb::FindArrayPath: Type mismatch: \'%s\' has type \'%s\', we expected \'%s\'\n", path, typevalue, type);
      return NULL;
    }
  bool isKeyArray = (num_values!=NULL) && (strcmp(nodename,"keyarray")==0);
  if (!isKeyArray)
    {
      if (index != 0)
        {
          fprintf(stderr,"XmlOdb::FindArrayPath: Attempt to access array element %d, but \'%s\' is not an array\n", index, path);
          return NULL;
        }
      return node;
    }
  int max_index = atoi(num_values);
  if (index < 0 || index >= max_index)
    {
      fprintf(stderr,"XmlOdb::FindArrayPath: Attempt to access array element %d, but size of array \'%s\' is %d\n", index, path, max_index);
      return NULL;
    }
  //printf("nodename [%s]\n", nodename);
  TXMLNode* elem = node->GetChildren();
  for (int i=0; elem!=NULL; )
    {
      const char* name = elem->GetNodeName();
      const char* text = elem->GetText();
      //printf("index %d, name [%s] text [%s]\n", i, name, text);
      if (strcmp(name,"value") == 0)
        {
          if (i == index)
            return elem;
          i++;
        }
      elem = elem->GetNextNode();
    }
  return node;
}
TXMLNode* XmlOdb::FindNode (TXMLNode * node, const char * name)
Find node with given name anywhere inside the given ODB tree.
TXMLNode * XmlOdb::FindNode (TXMLNode * node, const char * name)
Find node with given name anywhere inside the given ODB tree.
Definition at line 100 of file XmlOdb.cxx.
Referenced by XmlOdb().
{
  for (; node != NULL; node = node->GetNextNode())
    {
      //printf("node name: \"%s\"\n",node->GetNodeName());
      if (strcmp(node->GetNodeName(),name) == 0)
        return node;
      if (node->HasChildren())
        {
          TXMLNode* found = FindNode(node->GetChildren(),name);
          if (found)
            return found;
        }
    }
  return NULL;
}
TXMLNode* XmlOdb::FindPath (TXMLNode * node, const char * path)
Follow the ODB path through the XML DOM tree.
TXMLNode * XmlOdb::FindPath (TXMLNode * node, const char * path)
Follow the ODB path through the XML DOM tree.
Definition at line 212 of file XmlOdb.cxx.
References fOdb, and GetAttrValue().
Referenced by FindArrayPath(), and odbReadArraySize().
{
  if (!fOdb)
    return NULL;
  if (!node)
    node = fOdb->GetChildren();
  while (1)
    {
      // skip leading slashes
      while (*path == '/')
        path++;
      if (*path == 0)
        return node;
      const int kElemSize = 256;
      char elem[kElemSize+1];
      memset(elem,0,kElemSize+1);
      // copy the next path element into "elem"-
      // copy "path" until we hit "/" or end of string
      for (int i=0; i<kElemSize; i++)
        {
          if (*path==0 || *path=='/')
            break;
          elem[i] = *path++;
        }
      //printf("looking for \"%s\" more \"%s\"\n",elem,path);
      for (; node != NULL; node = node->GetNextNode())
        {
          const char* nodename = node->GetNodeName();
          const char* namevalue = GetAttrValue(node,"name");
          //printf("node name: \"%s\", \"name\" value: \"%s\"\n",node->GetNodeName(),namevalue);
          bool isDir = strcmp(nodename,"dir") == 0;
          bool isKey = strcmp(nodename,"key") == 0;
          bool isKeyArray = strcmp(nodename,"keyarray") == 0;
          if (!isKey && !isDir && !isKeyArray)
            continue;
          //
          // compare directory names
          //
          if (strcasecmp(elem,namevalue) == 0)
            {
              if (isDir)
                {
                  // found the right subdirectory, descend into it
                  node = node->GetChildren();
                  break;
                }
              else if (isKey || isKeyArray)
                {
                  return node;
                }
            }
        }
    }
}
const char* XmlOdb::GetAttrValue (TXMLNode * node, const char * attrName)
Return the value of the named attribute.
const char * XmlOdb::GetAttrValue (TXMLNode * node, const char * attrName)
Return the value of the named attribute.
Definition at line 195 of file XmlOdb.cxx.
Referenced by FindArrayPath(), FindPath(), and odbReadArraySize().
{
  TList* attrs = node->GetAttributes();
  TIter next(attrs);
  while (TXMLAttr *attr = (TXMLAttr*)next())
    {
      //printf("attribute name: \"%s\", value: \"%s\"\n",attr->GetName(),attr->GetValue());
      if (strcmp(attr->GetName(),attrName)==0)
        return attr->GetValue();
    }
  return NULL;
}
int XmlOdb::odbReadAny (const char * name, int index, int tid, void * buf, int bufsize = 0) [virtual]
Read value of arbitrary type.
Implements VirtualOdb.
int XmlOdb::odbReadAny (const char * name, int index, int tid, void * buf, int bufsize = 0) [virtual]
Read value of arbitrary type.
Implements VirtualOdb.
Definition at line 351 of file XmlOdb.cxx.
{ assert(!"Not implemented!"); }
int XmlOdb::odbReadArraySize (const char * name) [virtual]
Read size of an array.
Implements VirtualOdb.
int XmlOdb::odbReadArraySize (const char * name) [virtual]
Read size of an array.
Implements VirtualOdb.
Definition at line 425 of file XmlOdb.cxx.
References FindPath(), and GetAttrValue().
{
  TXMLNode *node = FindPath(NULL,name);
  if (!node)
    return 0;
  const char* num_values = GetAttrValue(node,"num_values");
  if (!num_values)
    return 1;
  return atoi(num_values);
}
bool XmlOdb::odbReadBool (const char * name, int index, bool defaultValue) [virtual]
Read a boolean value, midas type TID_BOOL.
Implements VirtualOdb.
bool XmlOdb::odbReadBool (const char * name, int index, bool defaultValue) [virtual]
Read a boolean value, midas type TID_BOOL.
Implements VirtualOdb.
Definition at line 401 of file XmlOdb.cxx.
References FindArrayPath().
{
  TXMLNode *node = FindArrayPath(NULL,name,"BOOL",index);
  if (!node)
    return defaultValue;
  const char* text = node->GetText();
  if (!text)
    return defaultValue;
  if (*text == 'n')
    return false;
  return true;
}
double XmlOdb::odbReadDouble (const char * name, int index, double defaultValue) [virtual]
Read an 64-bit floating point value, midas type TID_DOUBLET.
Implements VirtualOdb.
double XmlOdb::odbReadDouble (const char * name, int index, double defaultValue) [virtual]
Read an 64-bit floating point value, midas type TID_DOUBLET.
Implements VirtualOdb.
Definition at line 364 of file XmlOdb.cxx.
References FindArrayPath().
{
  TXMLNode *node = FindArrayPath(NULL,name,"DOUBLE",index);
  if (!node)
    return defaultValue;
  const char* text = node->GetText();
  if (!text)
    return defaultValue;
  return atof(text);
}
float XmlOdb::odbReadFloat (const char * name, int index, float defaultValue) [virtual]
Read an 32-bit floating point value, midas type TID_FLOAT.
Implements VirtualOdb.
float XmlOdb::odbReadFloat (const char * name, int index, float defaultValue) [virtual]
Read an 32-bit floating point value, midas type TID_FLOAT.
Implements VirtualOdb.
Definition at line 375 of file XmlOdb.cxx.
References FindArrayPath().
{
  TXMLNode *node = FindArrayPath(NULL,name,"FLOAT",index);
  if (!node)
    return defaultValue;
  const char* text = node->GetText();
  if (!text)
    return defaultValue;
  return atof(text);
}
int XmlOdb::odbReadInt (const char * name, int index, int defaultValue) [virtual]
Read an integer value, midas type TID_INT.
Implements VirtualOdb.
int XmlOdb::odbReadInt (const char * name, int index, int defaultValue) [virtual]
Read an integer value, midas type TID_INT.
Implements VirtualOdb.
Definition at line 386 of file XmlOdb.cxx.
References FindArrayPath().
{
  TXMLNode *node = FindArrayPath(NULL,name,"INT",index);
  if (!node)
    return defaultValue;
  const char* text = node->GetText();
  if (!text)
    return defaultValue;
  return atoi(text);
  //printf("for \'%s\', type is \'%s\', text is \'%s\'\n", name, typevalue, text);
  //DumpTree(node);
  //exit(1);
  return 0;
}
const char* XmlOdb::odbReadString (const char * name, int index, const char * defaultValue) [virtual]
Read a string value, midas type TID_STRING.
Implements VirtualOdb.
const char * XmlOdb::odbReadString (const char * name, int index, const char * defaultValue) [virtual]
Read a string value, midas type TID_STRING.
Implements VirtualOdb.
Definition at line 414 of file XmlOdb.cxx.
References FindArrayPath().
{
  TXMLNode *node = FindArrayPath(NULL, name, "STRING", index);
  if (!node)
    return defaultValue;
  const char* text = node->GetText();
  if (!text)
    return defaultValue;
  return text;
}
uint32_t XmlOdb::odbReadUint32 (const char * name, int index, uint32_t defaultValue) [virtual]
Read an unsigned 32-bit integer value, midas type TID_DWORD.
Implements VirtualOdb.
uint32_t XmlOdb::odbReadUint32 (const char * name, int index, uint32_t defaultValue) [virtual]
Read an unsigned 32-bit integer value, midas type TID_DWORD.
Implements VirtualOdb.
Definition at line 353 of file XmlOdb.cxx.
References FindArrayPath().
{
  TXMLNode *node = FindArrayPath(NULL,name,"DWORD",index);
  if (!node)
    return defaultValue;
  const char* text = node->GetText();
  if (!text)
    return defaultValue;
  return strtoul(text,NULL,0);
}
Member Data Documentation
TXMLNode * XmlOdb::fOdb
Pointer to the root of the ODB tree.
Definition at line 26 of file XmlOdb.h.
Referenced by DumpDirTree(), DumpTree(), FindArrayPath(), FindPath(), and XmlOdb().
TDOMParser * XmlOdb::fParser
XML parser for the XML-encoded ODB data.
Definition at line 25 of file XmlOdb.h.
Referenced by XmlOdb(), and ~XmlOdb().
The documentation for this struct was generated from the following files:
include/XmlOdb.h
libMidasInterface/XmlOdb.h
libMidasInterface/XmlOdb.cxx