ROOT Analyzer: HttpOdb Class Reference
HttpOdb Class Reference
Access to ODB through the MIDAS HTTP server mhttpd.
#include <HttpOdb.h>
Public Member Functions
HttpOdb (const char *url)
Contructor from a base URL.
virtual ~HttpOdb ()
Destructor.
int odbReadAny (const char *name, int index, int tid, void *buf, int bufsize=0)
Read value of arbitrary type.
int odbReadInt (const char *name, int index, int defaultValue)
Read an integer value, midas type TID_INT.
uint32_t odbReadUint32 (const char *name, int index, uint32_t defaultValue)
Read an unsigned 32-bit integer value, midas type TID_DWORD.
bool odbReadBool (const char *name, int index, bool defaultValue)
Read a boolean value, midas type TID_BOOL.
double odbReadDouble (const char *name, int index, double defaultValue)
Read an 64-bit floating point value, midas type TID_DOUBLET.
float odbReadFloat (const char *name, int index, float defaultValue)
Read an 32-bit floating point value, midas type TID_FLOAT.
const char * odbReadString (const char *name, int index, const char *defaultValue)
Read a string value, midas type TID_STRING.
int odbReadArraySize (const char *name)
Read size of an array.
HttpOdb (const char *url)
Contructor from a base URL.
virtual ~HttpOdb ()
Destructor.
int odbReadAny (const char *name, int index, int tid, void *buf, int bufsize=0)
Read value of arbitrary type.
int odbReadInt (const char *name, int index, int defaultValue)
Read an integer value, midas type TID_INT.
uint32_t odbReadUint32 (const char *name, int index, uint32_t defaultValue)
Read an unsigned 32-bit integer value, midas type TID_DWORD.
bool odbReadBool (const char *name, int index, bool defaultValue)
Read a boolean value, midas type TID_BOOL.
double odbReadDouble (const char *name, int index, double defaultValue)
Read an 64-bit floating point value, midas type TID_DOUBLET.
float odbReadFloat (const char *name, int index, float defaultValue)
Read an 32-bit floating point value, midas type TID_FLOAT.
const char * odbReadString (const char *name, int index, const char *defaultValue)
Read a string value, midas type TID_STRING.
int odbReadArraySize (const char *name)
Read size of an array.
Protected Member Functions
const char * jkey (const char *path)
const char * jget (const char *path, int index)
const char * jkey (const char *path)
const char * jget (const char *path, int index)
Protected Attributes
const char * fUrl
int fDebug
char fRequestBuf [1024]
char fReplyBuf [1024]
Detailed Description
Access to ODB through the MIDAS HTTP server mhttpd.
To enable ODB access in mhttpd, create an ODB string entry "/Custom/secret.html!" with blank value.
Then create an HttpOdb class with URL "http://hostname:port/CS/secret.html" and use the odb access functions as required.
Note that HTTP access is not optimized for speed. It can be slow, can result in high CPU utilization by mhttpd and is subject to lengthy delays if mhttpd is busy with something else (i.e. starting a run or generating history plots).
In this usage, the string "secret.html" functions as an access password.
Definition at line 27 of file HttpOdb.h.
Constructor & Destructor Documentation
HttpOdb::HttpOdb (const char * url)
Contructor from a base URL.
Definition at line 17 of file HttpOdb.cxx.
References fDebug, and fUrl.
{
  fDebug = 0;
  fUrl = strdup(url);
}
HttpOdb::~HttpOdb () [virtual]
Destructor.
Definition at line 23 of file HttpOdb.cxx.
References fUrl.
{
  if (fUrl)
    free((void*)fUrl);
  fUrl = NULL;
}
HttpOdb::HttpOdb (const char * url)
Contructor from a base URL.
virtual HttpOdb::~HttpOdb () [virtual]
Destructor.
Member Function Documentation
const char* HttpOdb::jget (const char * path, int index) [protected]
const char * HttpOdb::jget (const char * path, int index) [protected]
Definition at line 35 of file HttpOdb.cxx.
References fDebug, fReplyBuf, fRequestBuf, and fUrl.
Referenced by odbReadBool(), odbReadDouble(), odbReadFloat(), odbReadInt(), odbReadString(), and odbReadUint32().
{
  // index "-1" is special for "return whole array"
  if (index < 0)
    return NULL;
  TUrl xurl(fUrl);
  TSocket s(xurl.GetHost(), xurl.GetPort());
  //char *req = "GET /CS/F000.html?cmd=jset&odb=/equipment/mscb/settings/FGD/Feb_demand/power[0]&value=y HTTP/1.1\r\n\r\n";
  //char *req = "GET /CS/F000.html?cmd=jget&odb=/runinfo/run number HTTP/1.1\r\n\r\n";
  sprintf(fRequestBuf,"GET /%s?cmd=jget&odb=%s[%d] HTTP/1.1\r\n\r\n", xurl.GetFileAndOptions(), path, index);
  if (fDebug)
    printf("Sending [%s]\n", fRequestBuf);
  s.SendRaw(fRequestBuf, strlen(fRequestBuf));
  int rd = s.RecvRaw(fReplyBuf, sizeof(fReplyBuf));
  if (fDebug)
    printf("Received %d [%s]\n", rd, fReplyBuf);
  if (rd < 10)
    return NULL;
  if (strstr(fReplyBuf, "200 Document follows") == NULL)
    return NULL;
  fReplyBuf[rd] = 0;
  const char* p = strstr(fReplyBuf,"\r\n\r\n");
  if (!p)
    return NULL;
  p += 4;
  if (strcmp(p, "<DB_NO_KEY>") == 0)
    return NULL;
  if (strcmp(p, "<DB_OUT_OF_RANGE>") == 0)
    return NULL;
  if (strcmp(p, "<unknown>") == 0)
    return NULL;
  if (strstr(p, "<html>") != NULL)
    {
      fprintf(stderr, "HttpOdb::jget: Bad mhttpd response: %s\n", p);
      return NULL;
    }
  if (fDebug)
    printf("----> mhttpd %s[%d] return [%s]\n", path, index, p);
  return p;
}
const char* HttpOdb::jkey (const char * path) [protected]
const char * HttpOdb::jkey (const char * path) [protected]
Definition at line 94 of file HttpOdb.cxx.
References fDebug, fReplyBuf, fRequestBuf, and fUrl.
Referenced by odbReadArraySize().
{
  TUrl xurl(fUrl);
  TSocket s(xurl.GetHost(), xurl.GetPort());
  //char *req = "GET /CS/F000.html?cmd=jset&odb=/equipment/mscb/settings/FGD/Feb_demand/power[0]&value=y HTTP/1.1\r\n\r\n";
  //char *req = "GET /CS/F000.html?cmd=jget&odb=/runinfo/run number HTTP/1.1\r\n\r\n";
  sprintf(fRequestBuf,"GET /%s?cmd=jkey&odb=%s HTTP/1.1\r\n\r\n", xurl.GetFileAndOptions(), path);
  if (fDebug)
    printf("Sending [%s]\n", fRequestBuf);
  s.SendRaw(fRequestBuf, strlen(fRequestBuf));
  int rd = s.RecvRaw(fReplyBuf, sizeof(fReplyBuf));
  if (fDebug)
    printf("Received %d [%s]\n", rd, fReplyBuf);
  if (rd < 10)
    return NULL;
  if (strstr(fReplyBuf, "200 Document follows") == NULL)
    return NULL;
  fReplyBuf[rd] = 0;
  const char* p = strstr(fReplyBuf,"\r\n\r\n");
  if (!p)
    return NULL;
  p += 4;
  if (strcmp(p, "<DB_NO_KEY>") == 0)
    return NULL;
  if (strcmp(p, "<DB_OUT_OF_RANGE>") == 0)
    return NULL;
  if (strcmp(p, "<unknown>") == 0)
    return NULL;
  if (strstr(p, "<html>") != NULL)
    {
      fprintf(stderr, "HttpOdb::jget: Bad mhttpd response: %s\n", p);
      return NULL;
    }
  if (fDebug)
    printf("----> mhttpd %s return [%s]\n", path, p);
  return p;
}
int HttpOdb::odbReadAny (const char * name, int index, int tid, void * buf, int bufsize = 0) [virtual]
Read value of arbitrary type.
Implements VirtualOdb.
int HttpOdb::odbReadAny (const char * name, int index, int tid, void * buf, int bufsize = 0) [virtual]
Read value of arbitrary type.
Implements VirtualOdb.
Definition at line 149 of file HttpOdb.cxx.
{ assert(!"Not implemented!"); }
int HttpOdb::odbReadArraySize (const char * name) [virtual]
Read size of an array.
Implements VirtualOdb.
int HttpOdb::odbReadArraySize (const char * name) [virtual]
Read size of an array.
Implements VirtualOdb.
Definition at line 201 of file HttpOdb.cxx.
References jkey().
{
  const char* reply = jkey(name);
  if (!reply)
    return 0;
  const char* p = strstr(reply, "\n");
  if (p)
    p = strstr(p+1, "\n");
  if (p)
    return atoi(p);
  return 1;
}
bool HttpOdb::odbReadBool (const char * name, int index, bool defaultValue) [virtual]
Read a boolean value, midas type TID_BOOL.
Implements VirtualOdb.
bool HttpOdb::odbReadBool (const char * name, int index, bool defaultValue) [virtual]
Read a boolean value, midas type TID_BOOL.
Implements VirtualOdb.
Definition at line 183 of file HttpOdb.cxx.
References jget().
{
  const char* reply = jget(name, index);
  if (!reply)
    return defaultValue;
  if (*reply == 'n')
    return false;
  return true;
}
double HttpOdb::odbReadDouble (const char * name, int index, double defaultValue) [virtual]
Read an 64-bit floating point value, midas type TID_DOUBLET.
Implements VirtualOdb.
double HttpOdb::odbReadDouble (const char * name, int index, double defaultValue) [virtual]
Read an 64-bit floating point value, midas type TID_DOUBLET.
Implements VirtualOdb.
Definition at line 167 of file HttpOdb.cxx.
References jget().
{
  const char* reply = jget(name, index);
  if (!reply)
    return defaultValue;
  return atof(reply);
}
float HttpOdb::odbReadFloat (const char * name, int index, float defaultValue) [virtual]
Read an 32-bit floating point value, midas type TID_FLOAT.
Implements VirtualOdb.
float HttpOdb::odbReadFloat (const char * name, int index, float defaultValue) [virtual]
Read an 32-bit floating point value, midas type TID_FLOAT.
Implements VirtualOdb.
Definition at line 159 of file HttpOdb.cxx.
References jget().
{
  const char* reply = jget(name, index);
  if (!reply)
    return defaultValue;
  return atof(reply);
}
int HttpOdb::odbReadInt (const char * name, int index, int defaultValue) [virtual]
Read an integer value, midas type TID_INT.
Implements VirtualOdb.
int HttpOdb::odbReadInt (const char * name, int index, int defaultValue) [virtual]
Read an integer value, midas type TID_INT.
Implements VirtualOdb.
Definition at line 175 of file HttpOdb.cxx.
References jget().
{
  const char* reply = jget(name, index);
  if (!reply)
    return defaultValue;
  return atoi(reply);
}
const char* HttpOdb::odbReadString (const char * name, int index, const char * defaultValue) [virtual]
Read a string value, midas type TID_STRING.
Implements VirtualOdb.
const char * HttpOdb::odbReadString (const char * name, int index, const char * defaultValue) [virtual]
Read a string value, midas type TID_STRING.
Implements VirtualOdb.
Definition at line 193 of file HttpOdb.cxx.
References jget().
{
  const char* reply = jget(name, index);
  if (!reply)
    return defaultValue;
  return reply;
}
uint32_t HttpOdb::odbReadUint32 (const char * name, int index, uint32_t defaultValue) [virtual]
Read an unsigned 32-bit integer value, midas type TID_DWORD.
Implements VirtualOdb.
uint32_t HttpOdb::odbReadUint32 (const char * name, int index, uint32_t defaultValue) [virtual]
Read an unsigned 32-bit integer value, midas type TID_DWORD.
Implements VirtualOdb.
Definition at line 151 of file HttpOdb.cxx.
References jget().
{
  const char* reply = jget(name, index);
  if (!reply)
    return defaultValue;
  return strtoul(reply, NULL, 0);
}
Member Data Documentation
int HttpOdb::fDebug [protected]
Definition at line 31 of file HttpOdb.h.
Referenced by HttpOdb(), jget(), and jkey().
char HttpOdb::fReplyBuf [protected]
Definition at line 55 of file HttpOdb.h.
Referenced by jget(), and jkey().
char HttpOdb::fRequestBuf [protected]
Definition at line 54 of file HttpOdb.h.
Referenced by jget(), and jkey().
const char * HttpOdb::fUrl [protected]
Definition at line 30 of file HttpOdb.h.
Referenced by HttpOdb(), jget(), jkey(), and ~HttpOdb().
The documentation for this class was generated from the following files:
include/HttpOdb.h
libMidasInterface/HttpOdb.h
libMidasInterface/HttpOdb.cxx