ROOT Analyzer: TSimpleExampleCanvas Class Reference
TSimpleExampleCanvas Class Reference
#include <TSimpleExampleCanvas.hxx>
Public Member Functions
TSimpleExampleCanvas ()
void ResetCanvasHistograms ()
Reset the histograms for this canvas.
void UpdateCanvasHistograms (TDataContainer &dataContainer)
Update the histograms for this canvas.
void PlotCanvas (TDataContainer &dataContainer, TRootEmbeddedCanvas *embedCanvas)
Plot the histograms for this canvas.
TSimpleExampleCanvas ()
void ResetCanvasHistograms ()
Reset the histograms for this canvas.
void UpdateCanvasHistograms (TDataContainer &dataContainer)
Update the histograms for this canvas.
void PlotCanvas (TDataContainer &dataContainer, TRootEmbeddedCanvas *embedCanvas)
Plot the histograms for this canvas.
virtual void BeginRun (int transition, int run, int time)
Take actions at begin run.
virtual void BeginRun (int transition, int run, int time)
Take actions at begin run.
virtual void EndRun (int transition, int run, int time)
Take actions at end run.
virtual void EndRun (int transition, int run, int time)
Take actions at end run.
std::string GetTabName ()
std::string GetTabName ()
TRootEmbeddedCanvas * GetEmbeddedCanvas ()
This method is only.
TRootEmbeddedCanvas * GetEmbeddedCanvas ()
This method is only.
virtual void SetUpCompositeFrame (TGCompositeFrame *, TRootanaDisplay *display)
virtual void SetUpCompositeFrame (TGCompositeFrame *, TRootanaDisplay *display)
Private Attributes
TH1F * tdcHistogram
Detailed Description
A simple example, using V1190 data
Definition at line 15 of file TSimpleExampleCanvas.hxx.
Constructor & Destructor Documentation
TSimpleExampleCanvas::TSimpleExampleCanvas ()
Definition at line 6 of file TSimpleExampleCanvas.cxx.
References tdcHistogram.
                                          : TCanvasHandleBase("V1190 TDC Values"){
  tdcHistogram = new TH1F("tdcHistogram","Histogram of all V1190 TDC value",2000,0,100000);
}
TSimpleExampleCanvas::TSimpleExampleCanvas ()
Member Function Documentation
virtual void TCanvasHandleBase::BeginRun (int transition, int run, int time) [inline, virtual, inherited]
Take actions at begin run.
Reimplemented in TComplicatedExampleCanvas, TFancyHistogramCanvas, TComplicatedExampleCanvas, and TFancyHistogramCanvas.
Definition at line 33 of file TCanvasHandleBase.hxx.
{};
virtual void TCanvasHandleBase::BeginRun (int transition, int run, int time) [inline, virtual, inherited]
Take actions at begin run.
Reimplemented in TComplicatedExampleCanvas, TFancyHistogramCanvas, TComplicatedExampleCanvas, and TFancyHistogramCanvas.
Definition at line 33 of file TCanvasHandleBase.hxx.
{};
virtual void TCanvasHandleBase::EndRun (int transition, int run, int time) [inline, virtual, inherited]
Take actions at end run.
Reimplemented in TFancyHistogramCanvas, and TFancyHistogramCanvas.
Definition at line 36 of file TCanvasHandleBase.hxx.
{};
virtual void TCanvasHandleBase::EndRun (int transition, int run, int time) [inline, virtual, inherited]
Take actions at end run.
Reimplemented in TFancyHistogramCanvas, and TFancyHistogramCanvas.
Definition at line 36 of file TCanvasHandleBase.hxx.
{};
TRootEmbeddedCanvas* TCanvasHandleBase::GetEmbeddedCanvas () [inline, inherited]
This method is only.
Definition at line 41 of file TCanvasHandleBase.hxx.
{
    std::cerr<< "Not implemented for base class; exiting." << std::endl;
    exit(0);
    return 0;
  }
TRootEmbeddedCanvas* TCanvasHandleBase::GetEmbeddedCanvas () [inline, inherited]
This method is only.
Definition at line 41 of file TCanvasHandleBase.hxx.
{
    std::cerr<< "Not implemented for base class; exiting." << std::endl;
    exit(0);
    return 0;
  }
std::string TCanvasHandleBase::GetTabName () [inline, inherited]
Definition at line 38 of file TCanvasHandleBase.hxx.
References TCanvasHandleBase::fTabName.
{return fTabName;}
std::string TCanvasHandleBase::GetTabName () [inline, inherited]
Definition at line 38 of file TCanvasHandleBase.hxx.
References TCanvasHandleBase::fTabName.
Referenced by TRootanaDisplay::AddSingleCanvas().
{return fTabName;}
void TSimpleExampleCanvas::PlotCanvas (TDataContainer & dataContainer, TRootEmbeddedCanvas * embedCanvas) [virtual]
Plot the histograms for this canvas.
Implements TCanvasHandleBase.
void TSimpleExampleCanvas::PlotCanvas (TDataContainer & dataContainer, TRootEmbeddedCanvas * embedCanvas) [virtual]
Plot the histograms for this canvas.
Implements TCanvasHandleBase.
Definition at line 38 of file TSimpleExampleCanvas.cxx.
References tdcHistogram.
{
  TCanvas* c1 = embedCanvas->GetCanvas();
  c1->Clear();
  tdcHistogram->Draw();
  c1->Modified();
  c1->Update();
}
void TSimpleExampleCanvas::ResetCanvasHistograms () [virtual]
Reset the histograms for this canvas.
Implements TCanvasHandleBase.
void TSimpleExampleCanvas::ResetCanvasHistograms () [virtual]
Reset the histograms for this canvas.
Implements TCanvasHandleBase.
Definition at line 15 of file TSimpleExampleCanvas.cxx.
References tdcHistogram.
{
  tdcHistogram->Reset();
}
virtual void TCanvasHandleBase::SetUpCompositeFrame (TGCompositeFrame * , TRootanaDisplay * display) [inline, virtual, inherited]
Reimplemented in TComplicatedExampleCanvas, TFancyHistogramCanvas, TComplicatedExampleCanvas, and TFancyHistogramCanvas.
Definition at line 48 of file TCanvasHandleBase.hxx.
{}
virtual void TCanvasHandleBase::SetUpCompositeFrame (TGCompositeFrame * , TRootanaDisplay * display) [inline, virtual, inherited]
Reimplemented in TComplicatedExampleCanvas, TFancyHistogramCanvas, TComplicatedExampleCanvas, and TFancyHistogramCanvas.
Definition at line 48 of file TCanvasHandleBase.hxx.
Referenced by TRootanaDisplay::AddSingleCanvas().
{}
void TSimpleExampleCanvas::UpdateCanvasHistograms (TDataContainer & dataContainer) [virtual]
Update the histograms for this canvas.
Implements TCanvasHandleBase.
void TSimpleExampleCanvas::UpdateCanvasHistograms (TDataContainer & dataContainer) [virtual]
Update the histograms for this canvas.
Implements TCanvasHandleBase.
Definition at line 21 of file TSimpleExampleCanvas.cxx.
References TDataContainer::GetEventData(), TDCMeasurement::GetMeasurement(), TV1190Data::GetMeasurements(), and tdcHistogram.
{
  TV1190Data *v1190 = dataContainer.GetEventData<TV1190Data>("TDC0");
  if(v1190){
    std::vector<TDCMeasurement>& measurements = v1190->GetMeasurements();
    for(unsigned int i = 0; i < measurements.size(); i++){
      TDCMeasurement tdcmeas = measurements[i];
      tdcHistogram->Fill(tdcmeas.GetMeasurement());
    }
  }
}
Member Data Documentation
TH1F * TSimpleExampleCanvas::tdcHistogram [private]
Definition at line 30 of file TSimpleExampleCanvas.hxx.
Referenced by PlotCanvas(), ResetCanvasHistograms(), TSimpleExampleCanvas(), and UpdateCanvasHistograms().
The documentation for this class was generated from the following files:
include/TSimpleExampleCanvas.hxx
libAnalyzerDisplay/TSimpleExampleCanvas.hxx
libAnalyzerDisplay/TSimpleExampleCanvas.cxx