ROOT Analyzer: include/netDirectoryServer.h File Reference
netDirectoryServer.h File Reference
Functions
void VerboseNetDirectoryServer (bool verbose)
void StartNetDirectoryServer (int port, TDirectory *dir)
void NetDirectoryExport (TDirectory *dir, const char *exportName)
void NetDirectoryExport (TFolder *folder, const char *exportName)
void NetDirectoryExport (TCollection *collection, const char *exportName)
Function Documentation
void NetDirectoryExport (TCollection * collection, const char * exportName)
Definition at line 654 of file netDirectoryServer.cxx.
{
  if (gVerbose)
    printf("Export TCollection %p named [%s] of type [%s] as [%s]\n", collection, collection->GetName(), collection->IsA()->GetName(), exportName);
  bool found = false;
  for (unsigned int i=0; i<gExports.size(); i++)
    {
      const char* ename = gExports[i].c_str();
      if (strcmp(ename, exportName) == 0)
        found = true;
    }
  if (!found)
    gExports.push_back(exportName);
  gExportNames[exportName] = collection->GetName();
}
void NetDirectoryExport (TFolder * folder, const char * exportName)
Definition at line 636 of file netDirectoryServer.cxx.
{
  if (gVerbose)
    printf("Export TFolder %p named [%s] of type [%s] as [%s]\n", folder, folder->GetName(), folder->IsA()->GetName(), exportName);
  bool found = false;
  for (unsigned int i=0; i<gExports.size(); i++)
    {
      const char* ename = gExports[i].c_str();
      if (strcmp(ename, exportName) == 0)
        found = true;
    }
  if (!found)
    gExports.push_back(exportName);
  gExportNames[exportName] = folder->GetName();
}
void NetDirectoryExport (TDirectory * dir, const char * exportName)
Definition at line 618 of file netDirectoryServer.cxx.
Referenced by main(), TRootanaEventLoop::OpenRootFile(), StartNetDirectoryServer(), and startRun().
{
  if (gVerbose)
    printf("Export TDirectory %p named [%s] of type [%s] as [%s]\n", dir, dir->GetName(), dir->IsA()->GetName(), exportName);
  bool found = false;
  for (unsigned int i=0; i<gExports.size(); i++)
    {
      const char* ename = gExports[i].c_str();
      if (strcmp(ename, exportName) == 0)
        found = true;
    }
  if (!found)
    gExports.push_back(exportName);
  gExportNames[exportName] = dir->GetName();
}
void StartNetDirectoryServer (int port, TDirectory * dir)
Definition at line 672 of file netDirectoryServer.cxx.
Referenced by TRootanaEventLoop::ExecuteLoop(), and main().
{
  if (dir)
    NetDirectoryExport(dir, dir->GetName());
  if (gAlreadyRunning)
    return;
  if (port==0)
    return;
  gAlreadyRunning = true;
  StartLockRootTimer();
  static int pport = port;
#if 1
  TThread *thread = new TThread("NetDirectoryServer", socket_listener, &pport);
  thread->Run();
#else
  LPDWORD lpThreadId = 0;
  CloseHandle(CreateThread(NULL, 1024, &root_socket_server, &pport, 0, lpThreadId));
#endif
}
void VerboseNetDirectoryServer (bool verbose)
Definition at line 608 of file netDirectoryServer.cxx.
{
  gVerbose = verbose;
  //gDebugLockRoot = verbose;
}