ROOT Analyzer: XLockRootGuard Class Reference
XLockRootGuard Class Reference
Public Member Functions
XLockRootGuard ()
~XLockRootGuard ()
void Unlock ()
Public Attributes
bool fIsLocked
Detailed Description
Definition at line 50 of file xmlServer.cxx.
Constructor & Destructor Documentation
XLockRootGuard::XLockRootGuard () [inline]
Definition at line 55 of file xmlServer.cxx.
References fIsLocked.
   {
      TThread::Lock();
      fIsLocked = true;
   }
XLockRootGuard::~XLockRootGuard () [inline]
Definition at line 61 of file xmlServer.cxx.
References fIsLocked, and Unlock().
   {
      if (fIsLocked)
         Unlock();
   }
Member Function Documentation
void XLockRootGuard::Unlock () [inline]
Definition at line 67 of file xmlServer.cxx.
References fIsLocked.
Referenced by xroot_server_thread(), and ~XLockRootGuard().
   {
      fIsLocked = false;
      TThread::UnLock();
   };
Member Data Documentation
bool XLockRootGuard::fIsLocked
Definition at line 53 of file xmlServer.cxx.
Referenced by Unlock(), XLockRootGuard(), and ~XLockRootGuard().
The documentation for this class was generated from the following file:
libXmlServer/xmlServer.cxx