ROOT Analyzer: TV1190Data Class Reference
TV1190Data Class Reference
#include <TV1190Data.hxx>
Public Member Functions
TV1190Data (int bklen, int bktype, const char *name, void *pdata)
Constructor.
uint32_t GetEventCounter () const
Get Event Counter.
uint32_t GetGeoAddress () const
Get Geographical Address.
int GetExtendedTriggerTimeTag () const
Get the extended trigger time tag.
int GetWordCount () const
Get the word count.
bool IsTriggerLost () const
bool HasBufferOverflow () const
bool HasTDCError () const
void Print ()
Print the bank contents in a structured way.
std::vector< TDCMeasurement > & GetMeasurements ()
Get the Vector of TDC Measurements.
TV1190Data (int bklen, int bktype, const char *name, void *pdata)
Constructor.
uint32_t GetEventCounter () const
Get Event Counter.
uint32_t GetGeoAddress () const
Get Geographical Address.
int GetExtendedTriggerTimeTag () const
Get the extended trigger time tag.
int GetWordCount () const
Get the word count.
bool IsTriggerLost () const
bool HasBufferOverflow () const
bool HasTDCError () const
void Print ()
Print the bank contents in a structured way.
std::vector< TDCMeasurement > & GetMeasurements ()
Get the Vector of TDC Measurements.
const uint16_t * GetData16 () const
const uint16_t * GetData16 () const
const uint32_t * GetData32 () const
const uint32_t * GetData32 () const
const uint64_t * GetData64 () const
const uint64_t * GetData64 () const
int GetSize () const
int GetSize () const
int GetType () const
int GetType () const
std::string GetName () const
std::string GetName () const
void Dump ()
Dump the bank contents in an unstructured way.
void Dump ()
Dump the bank contents in an unstructured way.
Private Attributes
uint32_t fGlobalHeader
The overall global header.
uint32_t fGlobalTrailer
The overall global trailer.
int fExtendedTriggerTimeTag
int fWordCount
uint32_t fStatus
std::vector< TDCMeasurement > fMeasurements
Vector of TDC Measurements.
Detailed Description
Class to store data from CAEN V1190. We store the information as a vector of TDCMeasurement's Question: do we need a way of retrieving information about TDCs that have no measurements? Currently this information is not exposed. For the definition of obscure variables see the CAEN V1190 manual.
Definition at line 74 of file TV1190Data.hxx.
Constructor & Destructor Documentation
TV1190Data::TV1190Data (int bklen, int bktype, const char * name, void * pdata)
Constructor.
Definition at line 46 of file TV1190Data.cxx.
References fExtendedTriggerTimeTag, fGlobalHeader, fMeasurements, fStatus, fWordCount, TGenericData::GetData32(), and TGenericData::GetSize().
                                                                          :
    TGenericData(bklen, bktype, name, pdata)
{
  // Do some sanity checking.
  // Make sure first word has right identifier
  if( (GetData32()[0] & 0xf8000000) != 0x40000000)
    std::cerr << "First word has wrong identifier; first word = 0x"
              << std::hex << GetData32()[0] << std::dec << std::endl;
  fGlobalHeader = GetData32()[0];
  // Scan through the data, saving information as we go.
  int found_trailer_word = -1;
  fExtendedTriggerTimeTag = -1;
  uint32_t current_tdc_header =0;
  int index_for_trailer = 0;
  int index_for_error = 0;
  for(int i = 0; i < GetSize(); i++){
    uint32_t word = GetData32()[i];
    // TDC header
    if( (word & 0xf8000000) == 0x08000000){
      current_tdc_header = word;
    }
    // TDC measurement
    if( (word & 0xf8000000) == 0x00000000){
      fMeasurements.push_back(TDCMeasurement(current_tdc_header,word));
    }
    // TDC trailer
    if( (word & 0xf8000000) == 0x18000000){
      // Set the TDC trailer word for all the measurements since the last
      // TDC trailer.
      for(unsigned int i = index_for_trailer; i < fMeasurements.size(); i++){
        fMeasurements[i].SetTrailer(word);
      }
      index_for_trailer = fMeasurements.size();
    }
    // TDC error
    if( (word & 0xf8000000) == 0x20000000){
      // Set the TDC error word for all the measurements since the last
      // TDC error.
      std::cout << "Error word: " << std::hex << "0x"<<word<< std::dec << std::endl;
      for(unsigned int i = index_for_trailer; i < fMeasurements.size(); i++){
        fMeasurements[i].SetErrors(word);
      }
      index_for_error = fMeasurements.size();
    }
    // Extended Trigger Time Tag
    if( (word & 0xf8000000) == 0x88000000) fExtendedTriggerTimeTag = (word & 0x07ffffff);
    // Found global trailer
    if( (word & 0xf8000000) == 0x80000000){ // Found trailer
      found_trailer_word = i;
      fWordCount = (word & 0x0001fffe0) >> 5;
      if(fWordCount != GetSize())
        std::cerr << "Error in decoding V1190 data; word count in trailer ("<<fWordCount
                  << ") doesn't match bank size ("<< GetSize() << ")." << std::endl;
      fStatus = (word & 0x07000000) >> 24;
    }
  }
  if(found_trailer_word == -1)
    std::cerr << "Error in decoding V1190 data; didn't find trailer." << std::endl;
  if(found_trailer_word != GetSize()-1)
    std::cerr << "Error; did not find trailer on last word of bank. trailer word = " << found_trailer_word
              << " last word = " << GetSize()-1 << std::endl;
}
TV1190Data::TV1190Data (int bklen, int bktype, const char * name, void * pdata)
Constructor.
Member Function Documentation
void TGenericData::Dump () [inline, inherited]
Dump the bank contents in an unstructured way.
Definition at line 38 of file TGenericData.hxx.
References TGenericData::GetData32(), TGenericData::GetName(), and TGenericData::GetSize().
             {
    std::cout << "Generic decoder for bank named " <<  GetName().c_str() << std::endl;
    for(int i = 0; i < GetSize(); i++){
      std::cout << std::hex << "0x" << GetData32()[i] << std::dec << std::endl;
    }
  }
void TGenericData::Dump () [inline, inherited]
Dump the bank contents in an unstructured way.
Definition at line 38 of file TGenericData.hxx.
References TGenericData::GetData32(), TGenericData::GetName(), and TGenericData::GetSize().
Referenced by TGenericData::Print().
             {
    std::cout << "Generic decoder for bank named " <<  GetName().c_str() << std::endl;
    for(int i = 0; i < GetSize(); i++){
      std::cout << std::hex << "0x" << GetData32()[i] << std::dec << std::endl;
    }
  }
const uint16_t* TGenericData::GetData16 () const [inline, inherited]
Definition at line 23 of file TGenericData.hxx.
References TGenericData::fData.
{ return reinterpret_cast<const uint16_t*>(fData); }
const uint16_t* TGenericData::GetData16 () const [inline, inherited]
Definition at line 23 of file TGenericData.hxx.
References TGenericData::fData.
{ return reinterpret_cast<const uint16_t*>(fData); }
const uint32_t* TGenericData::GetData32 () const [inline, inherited]
Definition at line 26 of file TGenericData.hxx.
References TGenericData::fData.
{ return reinterpret_cast<const uint32_t*>(fData); }
const uint32_t* TGenericData::GetData32 () const [inline, inherited]
Definition at line 26 of file TGenericData.hxx.
References TGenericData::fData.
Referenced by TGenericData::Dump(), TMesytecData::TMesytecData(), TV1190Data(), and TV792Data::TV792Data().
{ return reinterpret_cast<const uint32_t*>(fData); }
const uint64_t* TGenericData::GetData64 () const [inline, inherited]
Definition at line 29 of file TGenericData.hxx.
References TGenericData::fData.
{ return reinterpret_cast<const uint64_t*>(fData); }
const uint64_t* TGenericData::GetData64 () const [inline, inherited]
Definition at line 29 of file TGenericData.hxx.
References TGenericData::fData.
{ return reinterpret_cast<const uint64_t*>(fData); }
uint32_t TV1190Data::GetEventCounter () const [inline]
Get Event Counter.
Definition at line 83 of file TV1190Data.hxx.
References fGlobalHeader.
{return (fGlobalHeader & 0x07ffffe0) >> 5;};
uint32_t TV1190Data::GetEventCounter () const [inline]
Get Event Counter.
Definition at line 83 of file TV1190Data.hxx.
References fGlobalHeader.
Referenced by Print().
{return (fGlobalHeader & 0x07ffffe0) >> 5;};
int TV1190Data::GetExtendedTriggerTimeTag () const [inline]
Get the extended trigger time tag.
Definition at line 89 of file TV1190Data.hxx.
References fExtendedTriggerTimeTag.
{return fExtendedTriggerTimeTag;};
int TV1190Data::GetExtendedTriggerTimeTag () const [inline]
Get the extended trigger time tag.
Definition at line 89 of file TV1190Data.hxx.
References fExtendedTriggerTimeTag.
{return fExtendedTriggerTimeTag;};
uint32_t TV1190Data::GetGeoAddress () const [inline]
Get Geographical Address.
Definition at line 86 of file TV1190Data.hxx.
References fGlobalHeader.
{return (fGlobalHeader & 0x1f) ;};
uint32_t TV1190Data::GetGeoAddress () const [inline]
Get Geographical Address.
Definition at line 86 of file TV1190Data.hxx.
References fGlobalHeader.
Referenced by Print().
{return (fGlobalHeader & 0x1f) ;};
std::vector<TDCMeasurement>& TV1190Data::GetMeasurements () [inline]
Get the Vector of TDC Measurements.
Definition at line 118 of file TV1190Data.hxx.
References fMeasurements.
{return fMeasurements;}
std::vector<TDCMeasurement>& TV1190Data::GetMeasurements () [inline]
Get the Vector of TDC Measurements.
Definition at line 118 of file TV1190Data.hxx.
References fMeasurements.
Referenced by MyTestLoop::ProcessMidasEvent(), and TSimpleExampleCanvas::UpdateCanvasHistograms().
{return fMeasurements;}
std::string TGenericData::GetName () const [inline, inherited]
Definition at line 35 of file TGenericData.hxx.
References TGenericData::fBankName.
{return fBankName;}
std::string TGenericData::GetName () const [inline, inherited]
Definition at line 35 of file TGenericData.hxx.
References TGenericData::fBankName.
Referenced by TGenericData::Dump(), TV792Data::Print(), Print(), and TMesytecData::Print().
{return fBankName;}
int TGenericData::GetSize () const [inline, inherited]
Definition at line 31 of file TGenericData.hxx.
References TGenericData::fSize.
{return fSize;}
int TGenericData::GetSize () const [inline, inherited]
Definition at line 31 of file TGenericData.hxx.
References TGenericData::fSize.
Referenced by TGenericData::Dump(), TMesytecData::TMesytecData(), TV1190Data(), and TV792Data::TV792Data().
{return fSize;}
int TGenericData::GetType () const [inline, inherited]
Definition at line 33 of file TGenericData.hxx.
References TGenericData::fBankType.
{return fBankType;}
int TGenericData::GetType () const [inline, inherited]
Definition at line 33 of file TGenericData.hxx.
References TGenericData::fBankType.
{return fBankType;}
int TV1190Data::GetWordCount () const [inline]
Get the word count.
Definition at line 92 of file TV1190Data.hxx.
References fWordCount.
{return fWordCount;};
int TV1190Data::GetWordCount () const [inline]
Get the word count.
Definition at line 92 of file TV1190Data.hxx.
References fWordCount.
{return fWordCount;};
bool TV1190Data::HasBufferOverflow () const [inline]
Definition at line 101 of file TV1190Data.hxx.
References fStatus.
{
    if(fStatus & 0x2)
      return true;
    else
      return false;
  }
bool TV1190Data::HasBufferOverflow () const [inline]
Definition at line 101 of file TV1190Data.hxx.
References fStatus.
{
    if(fStatus & 0x2)
      return true;
    else
      return false;
  }
bool TV1190Data::HasTDCError () const [inline]
Definition at line 107 of file TV1190Data.hxx.
References fStatus.
{
    if(fStatus & 0x1)
      return true;
    else
      return false;
  }
bool TV1190Data::HasTDCError () const [inline]
Definition at line 107 of file TV1190Data.hxx.
References fStatus.
{
    if(fStatus & 0x1)
      return true;
    else
      return false;
  }
bool TV1190Data::IsTriggerLost () const [inline]
Definition at line 95 of file TV1190Data.hxx.
References fStatus.
{
    if(fStatus & 0x4)
      return true;
    else
      return false;
  }
bool TV1190Data::IsTriggerLost () const [inline]
Definition at line 95 of file TV1190Data.hxx.
References fStatus.
{
    if(fStatus & 0x4)
      return true;
    else
      return false;
  }
void TV1190Data::Print () [virtual]
Print the bank contents in a structured way.
Reimplemented from TGenericData.
void TV1190Data::Print () [virtual]
Print the bank contents in a structured way.
Reimplemented from TGenericData.
Definition at line 122 of file TV1190Data.cxx.
References fMeasurements, GetEventCounter(), GetGeoAddress(), and TGenericData::GetName().
                      {
  std::cout << "V1190 decoder for bank " << GetName().c_str() << std::endl;
  std::cout << "event counter = " << GetEventCounter() << ", geographic address: " <<  GetGeoAddress() << std::endl;
  for(unsigned int i = 0; i < fMeasurements.size(); i++){
    std::cout << "Measurement: " <<    fMeasurements[i].GetMeasurement() << " for tdc/chan "  <<
      fMeasurements[i].GetTDCNumber() << "/"<< fMeasurements[i].GetChannel();
    if(fMeasurements[i].IsLeading())
      std::cout << " (leading edge meas)";
    if(fMeasurements[i].IsTrailing())
      std::cout << " (trailing edge meas)";
    std::cout << "[event_id = " << fMeasurements[i].GetEventID() << ",bunch_id="
              << fMeasurements[i].GetBunchID()<< "]";
    if(fMeasurements[i].HasTDCErrorWord())
      std::cout << "[errors=0x"<< std::hex << fMeasurements[i].GetErrors() << std::dec << "]";
    std::cout << std::endl;
  }
}
Member Data Documentation
int TV1190Data::fExtendedTriggerTimeTag [private]
Definition at line 129 of file TV1190Data.hxx.
Referenced by GetExtendedTriggerTimeTag(), and TV1190Data().
uint32_t TV1190Data::fGlobalHeader [private]
The overall global header.
Definition at line 124 of file TV1190Data.hxx.
Referenced by GetEventCounter(), GetGeoAddress(), and TV1190Data().
uint32_t TV1190Data::fGlobalTrailer [private]
The overall global trailer.
Definition at line 127 of file TV1190Data.hxx.
std::vector< TDCMeasurement > TV1190Data::fMeasurements [private]
Vector of TDC Measurements.
Definition at line 136 of file TV1190Data.hxx.
Referenced by GetMeasurements(), Print(), and TV1190Data().
uint32_t TV1190Data::fStatus [private]
Definition at line 132 of file TV1190Data.hxx.
Referenced by HasBufferOverflow(), HasTDCError(), IsTriggerLost(), and TV1190Data().
int TV1190Data::fWordCount [private]
Definition at line 130 of file TV1190Data.hxx.
Referenced by GetWordCount(), and TV1190Data().
The documentation for this class was generated from the following files:
include/TV1190Data.hxx
libAnalyzer/TV1190Data.hxx
libAnalyzer/TV1190Data.cxx