ROOT Analyzer: libAnalyzer/TPeriodicClass.hxx File Reference
TPeriodicClass.hxx File Reference
#include "TMidasOnline.h"
#include <TTimer.h>
#include <stdio.h>
Classes
class TPeriodicClass
Functions
double GetTimeSec ()
Function Documentation
double GetTimeSec ()
Definition at line 54 of file analyzer.cxx.
Referenced by MyPeriodic::MyPeriodic(), TPeriodicClass::Notify(), MyPeriodic::Notify(), and TPeriodicClass::TPeriodicClass().
{
  struct timeval tv;
  gettimeofday(&tv,NULL);
  return tv.tv_sec + 0.000001*tv.tv_usec;
}