ROOT Analyzer: event_dump.cxx File Reference
event_dump.cxx File Reference
#include <stdio.h>
#include <sys/time.h>
#include <assert.h>
#include <signal.h>
#include <errno.h>
#include "TMidasOnline.h"
#include "TMidasEvent.h"
#include "TMidasFile.h"
#include "VirtualOdb.h"
#include <vector>
Functions
void HandleMidasEvent (TMidasEvent &event)
int ProcessMidasFile (const char *fname)
void help ()
int main (int argc, char *argv[])
Variables
VirtualOdb * gOdb = NULL
int gEventCutoff = 0
bool gSaveOdb = false
bool gPrintBank = false
Function Documentation
void HandleMidasEvent (TMidasEvent & event)
Definition at line 33 of file event_dump.cxx.
References gPrintBank.
{
  int eventId = event.GetEventId();
  if (gPrintBank)
    event.Print("a");
  else
    event.Print();
}
void help ()
Definition at line 215 of file event_dump.cxx.
{
  printf("\nUsage:\n");
  printf("\n./event_dump.exe [-h] [-Hhostname] [-Eexptname] [-p] [-O] [-eMaxEvents] [file1 file2 ...]\n");
  printf("\n");
  printf("\t-h: print this help message\n");
  printf("\t-Hhostname: connect to MIDAS experiment on given host\n");
  printf("\t-Eexptname: connect to this MIDAS experiment\n");
  printf("\t-O: save ODB from midas data file into odbNNNN.xml or .odb file\n");
  printf("\t-e: Number of events to read from input data files\n");
  printf("\t-p: Print bank contents\n");
  printf("\n");
  printf("Example1: print online events: ./event_dump.exe\n");
  printf("Example2: print events from file: ./event_dump.exe /data/alpha/current/run00500.mid.gz\n");
  exit(1);
}
int main (int argc, char * argv[])
Definition at line 234 of file event_dump.cxx.
References gEventCutoff, gPrintBank, gSaveOdb, help(), and ProcessMidasFile().
{
   setbuf(stdout,NULL);
   setbuf(stderr,NULL);
   signal(SIGILL,  SIG_DFL);
   signal(SIGBUS,  SIG_DFL);
   signal(SIGSEGV, SIG_DFL);
   signal(SIGPIPE, SIG_DFL);
   std::vector<std::string> args;
   for (int i=0; i<argc; i++)
     {
       if (strcmp(argv[i],"-h")==0)
         help(); // does not return
       args.push_back(argv[i]);
     }
   const char* hostname = NULL;
   const char* exptname = NULL;
   for (unsigned int i=1; i<args.size(); i++) // loop over the commandline options
     {
       const char* arg = args[i].c_str();
       //printf("argv[%d] is %s\n",i,arg);
       if (strncmp(arg,"-e",2)==0)  // Event cutoff flag (only applicable in offline mode)
         gEventCutoff = atoi(arg+2);
       else if (strncmp(arg,"-H",2)==0)
         hostname = strdup(arg+2);
       else if (strncmp(arg,"-E",2)==0)
         exptname = strdup(arg+2);
       else if (strncmp(arg,"-O",2)==0)
         gSaveOdb = true;
       else if (strncmp(arg,"-p",2)==0)
         gPrintBank = true;
       else if (strcmp(arg,"-h")==0)
         help(); // does not return
       else if (arg[0] == '-')
         help(); // does not return
    }
   bool flag = false;
   for (unsigned int i=1; i<args.size(); i++)
     {
       const char* arg = args[i].c_str();
       if (arg[0] != '-')
         {
           flag = true;
           ProcessMidasFile(arg);
         }
     }
   // if we processed some data files,
   // do not go into online mode.
   if (flag)
     return 0;
#ifdef HAVE_MIDAS
   ProcessMidasOnline(hostname, exptname);
#endif
   return 0;
}
int ProcessMidasFile (const char * fname)
Definition at line 42 of file event_dump.cxx.
References TMidasFile::Close(), TMidasEvent::GetData(), TMidasEvent::GetSerialNumber(), gEventCutoff, gSaveOdb, HandleMidasEvent(), TMidasFile::Open(), and TMidasFile::Read().
{
  TMidasFile f;
  bool tryOpen = f.Open(fname);
  if (!tryOpen)
    {
      printf("Cannot open input file \"%s\"\n",fname);
      return -1;
    }
  int i=0;
  while (1)
    {
      TMidasEvent event;
      if (!f.Read(&event))
        break;
      int eventId = event.GetEventId();
      //printf("Have an event of type %d\n",eventId);
      if ((eventId & 0xFFFF) == 0x8000)
        {
          // begin run
          event.Print();
          if (gSaveOdb)
            {
              char fname[256];
              char* ptr = event.GetData();
              int size = event.GetDataSize();
              if (strncmp(ptr, "<?xml", 5) == 0)
                sprintf(fname,"odb%05d.xml", event.GetSerialNumber());
              else
                sprintf(fname,"odb%05d.odb", event.GetSerialNumber());
              FILE* fp = fopen(fname,"w");
              if (!fp)
                {
                  fprintf(stderr,"Error: Cannot write ODB to \'%s\', errno %d (%s)\n", fname, errno, strerror(errno));
                  exit(1);
                }
              fwrite(ptr, size, 1, fp);
              fclose(fp);
              fprintf(stderr,"Wrote ODB to \'%s\'\n", fname);
              exit(0);
            }
          //
          // Load ODB contents from the ODB XML file
          //
          if (gOdb)
            delete gOdb;
          gOdb = NULL;
#ifdef HAVE_ROOT
          gOdb = new XmlOdb(event.GetData(),event.GetDataSize());
#endif
        }
      else if ((eventId & 0xFFFF) == 0x8001)
        {
          // end run
          event.Print();
        }
      else if ((eventId & 0xFFFF) == 0x8002)
        {
          // log message
          event.Print();
          printf("Log message: %s\n", event.GetData());
        }
      else
        {
          event.SetBankList();
          //event.Print();
          HandleMidasEvent(event);
        }
      if((i%500)==0)
        {
          printf("Processing event %d\n",i);
        }
      i++;
      if ((gEventCutoff!=0)&&(i>=gEventCutoff))
        {
          printf("Reached event %d, exiting loop.\n", i);
          break;
        }
    }
  f.Close();
  return 0;
}
Variable Documentation
int gEventCutoff = 0
Definition at line 29 of file event_dump.cxx.
VirtualOdb* gOdb = NULL
Definition at line 27 of file event_dump.cxx.
bool gPrintBank = false
Definition at line 31 of file event_dump.cxx.
Referenced by HandleMidasEvent(), and main().
bool gSaveOdb = false
Definition at line 30 of file event_dump.cxx.
Referenced by main(), and ProcessMidasFile().