ROOT Analyzer: MyTestLoop Class Reference
MyTestLoop Class Reference
Public Member Functions
MyTestLoop ()
virtual ~MyTestLoop ()
void BeginRun (int transition, int run, int time)
void EndRun (int transition, int run, int time)
bool ProcessMidasEvent (TDataContainer &dataContainer)
Process each midas event.
void Usage (void)
bool CheckOption (std::string option)
MyTestLoop ()
void AddAllCanvases ()
User must.
virtual ~MyTestLoop ()
void ResetHistograms ()
This method can be implemented by users to plotting of current canvas.
void UpdateHistograms (TDataContainer &dataContainer)
This method can be implemented by users to update user histograms.
void PlotCanvas (TDataContainer &dataContainer)
This method can be implemented by users to plotting of current canvas.
void AddSingleCanvas (std::string name)
Add a new canvas; user will interactively fill it.
void AddSingleCanvas (TCanvasHandleBase *handleClass)
void AddSingleCanvas (std::string name)
Add a new canvas; user will interactively fill it.
void AddSingleCanvas (TCanvasHandleBase *handleClass)
TMainDisplayWindow * GetDisplayWindow ()
TMainDisplayWindow * GetDisplayWindow ()
void NextButtonPushed ()
Method for when next button is pushed (offline mode).
void NextButtonPushed ()
Method for when next button is pushed (offline mode).
void EventSkipButtonPushed ()
Method for when skip event button is pushed (online mode).
void EventSkipButtonPushed ()
Method for when skip event button is pushed (online mode).
void Reset ()
void Reset ()
void UpdatePlotsAction ()
void UpdatePlotsAction ()
void SetNumberSkipEvent (int number)
void SetNumberSkipEvent (int number)
std::string GetDisplayName ()
Get Display name.
std::string GetDisplayName ()
Get Display name.
void SetDisplayName (std::string name)
Set Display name.
void SetDisplayName (std::string name)
Set Display name.
void Initialize ()
void Initialize ()
TDataContainer * GetDataContainer ()
Method to get the data container that event loop owns.
TDataContainer * GetDataContainer ()
Method to get the data container that event loop owns.
virtual void Finalize ()
virtual void Finalize ()
bool IsOnline () const
Are we processing online data?
bool IsOnline () const
Are we processing online data?
bool IsOffline () const
Are we processing offline data?
bool IsOffline () const
Are we processing offline data?
int GetCurrentRunNumber () const
Current Run Number.
int GetCurrentRunNumber () const
Current Run Number.
void SetCurrentRunNumber (int run)
Current Run Number.
void SetCurrentRunNumber (int run)
Current Run Number.
int ExecuteLoop (int argc, char *argv[])
Method to actually process the Midas information, either as file or online.
int ExecuteLoop (int argc, char *argv[])
Method to actually process the Midas information, either as file or online.
int ProcessMidasFile (TApplication *app, const char *fname)
int ProcessMidasFile (TApplication *app, const char *fname)
void DisableAutoMainWindow ()
Disable automatic creation of MainWindow.
void DisableAutoMainWindow ()
Disable automatic creation of MainWindow.
VirtualOdb * GetODB ()
Get pointer to ODB variables.
VirtualOdb * GetODB ()
Get pointer to ODB variables.
void OpenRootFile (int run)
Open output ROOT file.
void OpenRootFile (int run)
Open output ROOT file.
void CloseRootFile ()
Cloe output ROOT file.
void CloseRootFile ()
Cloe output ROOT file.
void DisableRootOutput (bool disable=true)
void DisableRootOutput (bool disable=true)
Static Public Member Functions
static TRootanaEventLoop & Get (void)
static TRootanaEventLoop & Get (void)
template<typename T >
static void CreateSingleton ()
template<typename T >
static void CreateSingleton ()
Protected Member Functions
bool CreateOutputFile (std::string name, std::string options="RECREATE")
bool CreateOutputFile (std::string name, std::string options="RECREATE")
Protected Attributes
TDirectory * fOnlineHistDir
TDirectory for online histograms.
TDirectory * fOnlineHistDir
TDirectory for online histograms.
Static Protected Attributes
static TRootanaEventLoop * fTRootanaEventLoop = NULL
The static pointer to the singleton instance.
static TRootanaEventLoop * fTRootanaEventLoop = NULL
The static pointer to the singleton instance.
Private Attributes
int nnn
TH1F * sizeBankFR10
Detailed Description
This is an example of the a user defined event display. The user then needs to define how they what to update and plot histograms. The updating of histograms happens for each event. In online mode, the plotting of histograms only happens for each XX events; for offline mode the plotting happens for each event.
There are two ways that users can decide to update and plot histograms:
1) They can create histograms in their event display class and then fill the methods UpdateHistograms(TMidasEvent*) and PlotCanvas(TMidasEvent*). This histograms can then file in the canvases that are added using AddSingleCanvas(std::string name).
In this example this method is used for the histogram sizeBankFR10, which is just a histogram of the size of the bank called "FR10".
2) They can create classes that are derived from TCanvasHandleBase. The derived classes are then added using the method AddSingleCanvas(TCanvasHandleBase* handleClass). In this example there are two classes derived from TCanvasHandleBase: a) TSimpleExampleCanvas: this class just creates a tab/canvas with a histogram of the size of the bank called "FR11". a) TComplicatedExampleCanvas: this class creates a set of four different canvases/histograms which the user can select using a ROOT number widget.
The actual ROOT GUI is encapsulated in a separate class TMainDisplayWindow. The TRootanaDisplay has an instance of this TMainDisplayWindow class. Users will be need to access the TMainDisplayWindow by calling
TRootanaDisplay::GetDisplayWindow()
in order to grab the particular canvas that we want plot on.
Definition at line 13 of file analyzer_example.cxx.
Constructor & Destructor Documentation
MyTestLoop::MyTestLoop () [inline]
Definition at line 19 of file analyzer_example.cxx.
References nnn.
               {
    nnn = 0;
  };
virtual MyTestLoop::~MyTestLoop () [inline, virtual]
Definition at line 23 of file analyzer_example.cxx.
{};
MyTestLoop::MyTestLoop () [inline]
Definition at line 48 of file display_example.cxx.
References sizeBankFR10.
               {
    // Initialize histograms.
    sizeBankFR10 = new TH1F("sizeBankFR10","Size of FR10 bank",2000,0,10000);
  }
virtual MyTestLoop::~MyTestLoop () [inline, virtual]
Definition at line 63 of file display_example.cxx.
{};
Member Function Documentation
void MyTestLoop::AddAllCanvases () [inline, virtual]
User must.
Implements TRootanaDisplay.
Definition at line 54 of file display_example.cxx.
References TRootanaDisplay::AddSingleCanvas(), TRootanaDisplay::SetDisplayName(), and TRootanaDisplay::SetNumberSkipEvent().
                       {
    // Set up tabbed canvases
    AddSingleCanvas(new TSimpleExampleCanvas());
    AddSingleCanvas(new TComplicatedExampleCanvas());
    AddSingleCanvas("FR10");
    SetNumberSkipEvent(20);
    SetDisplayName("Example Display");
  };
void TRootanaDisplay::AddSingleCanvas (TCanvasHandleBase * handleClass) [inherited]
Add a new canvas, using a TCanvasHandleBase class. TRootanaDisplay will take ownership of pointer and delete memory it points to.
void TRootanaDisplay::AddSingleCanvas (std::string name) [inline, inherited]
Add a new canvas; user will interactively fill it.
Definition at line 64 of file TRootanaDisplay.hxx.
References TMainDisplayWindow::AddCanvas(), and TRootanaDisplay::fMainWindow.
{
    fMainWindow->AddCanvas(name);
  }
void TRootanaDisplay::AddSingleCanvas (TCanvasHandleBase * handleClass) [inherited]
Add a new canvas, using a TCanvasHandleBase class. TRootanaDisplay will take ownership of pointer and delete memory it points to.
Definition at line 66 of file TRootanaDisplay.cxx.
References TMainDisplayWindow::AddCanvas(), TRootanaDisplay::fCanvasHandlers, TRootanaDisplay::GetDisplayWindow(), TMainDisplayWindow::GetTab(), TCanvasHandleBase::GetTabName(), and TCanvasHandleBase::SetUpCompositeFrame().
{
  GetDisplayWindow()->AddCanvas(handleClass->GetTabName());
  int tab_index = GetDisplayWindow()->GetTab()->GetNumberOfTabs() - 1;
  fCanvasHandlers.push_back(std::pair<int,TCanvasHandleBase*>(tab_index,handleClass));
  // Now set up the embedded canvas, if user so desires.
  TGCompositeFrame* embed = GetDisplayWindow()->GetTab()->GetTabContainer(tab_index);
  handleClass->SetUpCompositeFrame(embed,this);
}
void TRootanaDisplay::AddSingleCanvas (std::string name) [inline, inherited]
Add a new canvas; user will interactively fill it.
Definition at line 64 of file TRootanaDisplay.hxx.
References TMainDisplayWindow::AddCanvas(), and TRootanaDisplay::fMainWindow.
Referenced by AddAllCanvases().
{
    fMainWindow->AddCanvas(name);
  }
void MyTestLoop::BeginRun (int transition, int run, int time) [inline, virtual]
Called before the first event of a file is read, but you should prefer Initialize() for general initialization. This method will be called once for each input file.
Reimplemented from TRootanaDisplay.
Definition at line 25 of file analyzer_example.cxx.
{
    std::cout << "Custom: begin run " << run << std::endl;
  }
bool MyTestLoop::CheckOption (std::string option) [inline, virtual]
Check an option and return true if it is valid. The return value is used to flag errors during option handling. If the options are valid, then CheckOption should return true to indicate success. If there is a problem processing the options, then CheckOption should return false. If this returns false, then the event loop will print the Usage message and exit with a non zero value (i.e. indicate failure).
Reimplemented from TRootanaEventLoop.
Definition at line 89 of file analyzer_example.cxx.
{
    const char* arg = option.c_str();
    if (strncmp(arg,"-D",2)==0){
      std::cout << arg+2 << std::endl;
      std::cout << "I'm happy with this flag!" << std::endl;
      return true;
    }
    return false;
  }
void TRootanaEventLoop::CloseRootFile () [inherited]
Cloe output ROOT file.
void TRootanaEventLoop::CloseRootFile () [inherited]
Cloe output ROOT file.
Definition at line 342 of file TRootanaEventLoop.cxx.
References TRootanaEventLoop::fOutputFile.
Referenced by TRootanaEventLoop::ProcessMidasFile(), and TRootanaEventLoop::~TRootanaEventLoop().
{
  std::cout << "Closing ROOT file " << std::endl;
  if(fOutputFile) {
    fOutputFile->Write();
    fOutputFile->Close();
    fOutputFile=0;
  }
}
bool TRootanaEventLoop::CreateOutputFile (std::string name, std::string options = "RECREATE") [inline, protected, inherited]
Definition at line 140 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fOutputFile.
{
    fOutputFile = new TFile(name.c_str(),options.c_str());
    return true;
  }
bool TRootanaEventLoop::CreateOutputFile (std::string name, std::string options = "RECREATE") [inline, protected, inherited]
Definition at line 140 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fOutputFile.
{
    fOutputFile = new TFile(name.c_str(),options.c_str());
    return true;
  }
template<typename T > static void TRootanaEventLoop::CreateSingleton () [inline, static, inherited]
This static templated function will make it a little easier for users to create the singleton instance.
Definition at line 114 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fTRootanaEventLoop.
  {
    if(fTRootanaEventLoop)
      std::cout << "Singleton has already been created" << std::endl;
    else
      fTRootanaEventLoop = new T();
  }
template<typename T > static void TRootanaEventLoop::CreateSingleton () [inline, static, inherited]
This static templated function will make it a little easier for users to create the singleton instance.
Definition at line 114 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fTRootanaEventLoop.
  {
    if(fTRootanaEventLoop)
      std::cout << "Singleton has already been created" << std::endl;
    else
      fTRootanaEventLoop = new T();
  }
void TRootanaEventLoop::DisableAutoMainWindow () [inline, inherited]
Disable automatic creation of MainWindow.
Definition at line 124 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fCreateMainWindow.
{  fCreateMainWindow = false;}
void TRootanaEventLoop::DisableAutoMainWindow () [inline, inherited]
Disable automatic creation of MainWindow.
Definition at line 124 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fCreateMainWindow.
{  fCreateMainWindow = false;}
void TRootanaEventLoop::DisableRootOutput (bool disable = true) [inline, inherited]
Definition at line 136 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fDisableRootOutput.
{fDisableRootOutput = disable;};
void TRootanaEventLoop::DisableRootOutput (bool disable = true) [inline, inherited]
Definition at line 136 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fDisableRootOutput.
{fDisableRootOutput = disable;};
void MyTestLoop::EndRun (int transition, int run, int time) [inline, virtual]
Called after the last event of a file is read, but you should prefer Finalize() for general finalization. This method will be called once for each input file.
Reimplemented from TRootanaDisplay.
Definition at line 29 of file analyzer_example.cxx.
{
    std::cout << "Custom end run " << run <<std::endl;
  }
void TRootanaDisplay::EventSkipButtonPushed () [inline, inherited]
Method for when skip event button is pushed (online mode).
Definition at line 92 of file TRootanaDisplay.hxx.
References TRootanaDisplay::fMainWindow, TRootanaDisplay::fNumberSkipEventsOnline, and TMainDisplayWindow::GetSkipEventButton().
{
    fNumberSkipEventsOnline = fMainWindow->GetSkipEventButton()->GetNumberEntry()->GetIntNumber();
  }
void TRootanaDisplay::EventSkipButtonPushed () [inline, inherited]
Method for when skip event button is pushed (online mode).
Definition at line 92 of file TRootanaDisplay.hxx.
References TRootanaDisplay::fMainWindow, TRootanaDisplay::fNumberSkipEventsOnline, and TMainDisplayWindow::GetSkipEventButton().
{
    fNumberSkipEventsOnline = fMainWindow->GetSkipEventButton()->GetNumberEntry()->GetIntNumber();
  }
int TRootanaEventLoop::ExecuteLoop (int argc, char * argv[]) [inherited]
Method to actually process the Midas information, either as file or online.
int TRootanaEventLoop::ExecuteLoop (int argc, char * argv[]) [inherited]
Method to actually process the Midas information, either as file or online.
Definition at line 105 of file TRootanaEventLoop.cxx.
References TDirectory::cd(), TRootanaEventLoop::CheckOption(), TRootanaEventLoop::fApp, TRootanaEventLoop::fCreateMainWindow, TRootanaEventLoop::Finalize(), TRootanaEventLoop::fIsOffline, TRootanaEventLoop::fMaxEvents, TRootanaEventLoop::fOnlineHistDir, TRootanaEventLoop::Initialize(), TRootanaEventLoop::PrintHelp(), TRootanaEventLoop::ProcessMidasFile(), and StartNetDirectoryServer().
Referenced by main().
{
  setbuf(stdout,NULL);
  setbuf(stderr,NULL);
  signal(SIGILL,  SIG_DFL);
  signal(SIGBUS,  SIG_DFL);
  signal(SIGSEGV, SIG_DFL);
  std::vector<std::string> args;
  for (int i=0; i<argc; i++)
    {
      if (strcmp(argv[i],"-h")==0)
        PrintHelp(); // does not return
      args.push_back(argv[i]);
    }
  if(gROOT->IsBatch()) {
    printf("Cannot run in batch mode\n");
    return 1;
  }
  bool forceEnableGraphics = false;
  bool testMode = false;
  int  tcpPort = 0;
  const char* hostname = NULL;
  const char* exptname = NULL;
  for (unsigned int i=1; i<args.size(); i++) // loop over the commandline options
    {
      const char* arg = args[i].c_str();
      //printf("argv[%d] is %s\n",i,arg);
      if (strncmp(arg,"-e",2)==0)  // Event cutoff flag (only applicable in offline mode)
        fMaxEvents = atoi(arg+2);
      else if (strncmp(arg,"-m",2)==0) // Enable memory debugging
        ;//      gEnableShowMem = true;
      else if (strncmp(arg,"-P",2)==0) // Set the histogram server port
        tcpPort = atoi(arg+2);
      else if (strcmp(arg,"-T")==0)
        testMode = true;
      else if (strcmp(arg,"-g")==0)
        forceEnableGraphics = true;
      else if (strncmp(arg,"-H",2)==0)
        hostname = strdup(arg+2);
      else if (strncmp(arg,"-E",2)==0)
        exptname = strdup(arg+2);
      else if (strcmp(arg,"-h")==0)
        PrintHelp(); // does not return
      else if(arg[0] == '-' && !CheckOption(args[i])) // Chec if a user-defined option
        PrintHelp(); // does not return
    }
  // Do quick check if we are processing online or offline.
  // Want to know before we initialize.
  fIsOffline = false;
  for (unsigned int i=1; i<args.size(); i++){
    const char* arg = args[i].c_str();
    if (arg[0] != '-')
      {
        fIsOffline = true;
      }
  }
  MainWindow *mainWindow=0;
  if(fCreateMainWindow){
    mainWindow = new MainWindow(gClient->GetRoot(), 200, 300);
  }
   gROOT->cd();
   fOnlineHistDir = new TDirectory("rootana", "rootana online plots");
#ifdef HAVE_LIBNETDIRECTORY
   if (tcpPort)
     StartNetDirectoryServer(tcpPort, fOnlineHistDir);
#else
   if (tcpPort)
     fprintf(stderr,"ERROR: No support for the TNetDirectory server!\n");
#endif
   // Initialize the event loop with user initialization.
   Initialize();
   for (unsigned int i=1; i<args.size(); i++){
     const char* arg = args[i].c_str();
     if (arg[0] != '-')
       {
           ProcessMidasFile(fApp,arg);
       }
   }
   if (testMode){
     std::cout << "Entering test mode." << std::endl;
     fOnlineHistDir->cd();
     TH1D* hh = new TH1D("test", "test", 100, 0, 100);
     hh->Fill(1);
     hh->Fill(10);
     hh->Fill(50);
     fApp->Run(kTRUE);
     if(fCreateMainWindow) delete mainWindow;
     return 0;
   }
   // if we processed some data files,
   // do not go into online mode.
   if (fIsOffline){
     if(fCreateMainWindow) delete mainWindow;
     return 0;
   }
#ifdef HAVE_MIDAS
   ProcessMidasOnline(fApp, hostname, exptname);;
#endif
   if(fCreateMainWindow) delete mainWindow;
   Finalize();
   return 0;
}
virtual void TRootanaEventLoop::Finalize () [virtual, inherited]
Called after the last event has been processed, but before any open output files are closed.
void TRootanaEventLoop::Finalize () [virtual, inherited]
Called after the last event has been processed, but before any open output files are closed.
Definition at line 74 of file TRootanaEventLoop.cxx.
Referenced by TRootanaEventLoop::ExecuteLoop().
{};
static TRootanaEventLoop& TRootanaEventLoop::Get (void) [static, inherited]
TRootanaEventLoop & TRootanaEventLoop::Get (void) [static, inherited]
Definition at line 29 of file TRootanaEventLoop.cxx.
References TRootanaEventLoop::fTRootanaEventLoop.
Referenced by main().
{
  if(!fTRootanaEventLoop){
    std::cerr << "Singleton Not Instantiated! "
              << " Need to call something like SomeClass::CreateSingleton<SomeClass>(); Exiting!"
              <<std::endl; exit(0);
  }
  return *fTRootanaEventLoop;
}
int TRootanaEventLoop::GetCurrentRunNumber () const [inline, inherited]
Current Run Number.
Definition at line 96 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fCurrentRunNumber.
{return fCurrentRunNumber;};
int TRootanaEventLoop::GetCurrentRunNumber () const [inline, inherited]
Current Run Number.
Definition at line 96 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fCurrentRunNumber.
Referenced by ProcessMidasEvent(), and TRootanaDisplay::UpdatePlotsAction().
{return fCurrentRunNumber;};
TDataContainer* TRootanaEventLoop::GetDataContainer () [inline, inherited]
Method to get the data container that event loop owns.
Definition at line 49 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fDataContainer.
{return fDataContainer;};
TDataContainer* TRootanaEventLoop::GetDataContainer () [inline, inherited]
Method to get the data container that event loop owns.
Definition at line 49 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fDataContainer.
{return fDataContainer;};
std::string TRootanaDisplay::GetDisplayName () [inline, inherited]
Get Display name.
Definition at line 114 of file TRootanaDisplay.hxx.
References TRootanaDisplay::fDisplayName.
{return fDisplayName;}
std::string TRootanaDisplay::GetDisplayName () [inline, inherited]
Get Display name.
Definition at line 114 of file TRootanaDisplay.hxx.
References TRootanaDisplay::fDisplayName.
Referenced by TRootanaDisplay::UpdatePlotsAction().
{return fDisplayName;}
TMainDisplayWindow* TRootanaDisplay::GetDisplayWindow () [inline, inherited]
Retrieve the main display window, so that users can do things like grab the canvases and update them.
Definition at line 76 of file TRootanaDisplay.hxx.
References TRootanaDisplay::fMainWindow.
{ return fMainWindow;}
TMainDisplayWindow* TRootanaDisplay::GetDisplayWindow () [inline, inherited]
Retrieve the main display window, so that users can do things like grab the canvases and update them.
Definition at line 76 of file TRootanaDisplay.hxx.
References TRootanaDisplay::fMainWindow.
Referenced by TRootanaDisplay::AddSingleCanvas(), TRootanaDisplay::InitializeMainWindow(), PlotCanvas(), and TRootanaDisplay::UpdatePlotsAction().
{ return fMainWindow;}
VirtualOdb* TRootanaEventLoop::GetODB () [inline, inherited]
Get pointer to ODB variables.
Definition at line 127 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fODB.
{return fODB;}
VirtualOdb* TRootanaEventLoop::GetODB () [inline, inherited]
Get pointer to ODB variables.
Definition at line 127 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fODB.
{return fODB;}
void TRootanaDisplay::Initialize (void) [inline, virtual, inherited]
Called after the arguments are processes but before reading the first event is read
Reimplemented from TRootanaEventLoop.
Definition at line 118 of file TRootanaDisplay.hxx.
References TRootanaDisplay::InitializeMainWindow().
                   {
    InitializeMainWindow();
  }
void TRootanaDisplay::Initialize (void) [inline, virtual, inherited]
Called after the arguments are processes but before reading the first event is read
Reimplemented from TRootanaEventLoop.
Definition at line 118 of file TRootanaDisplay.hxx.
References TRootanaDisplay::InitializeMainWindow().
                   {
    InitializeMainWindow();
  }
bool TRootanaEventLoop::IsOffline () const [inline, inherited]
Are we processing offline data?
Definition at line 93 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fIsOffline.
{return fIsOffline;};
bool TRootanaEventLoop::IsOffline () const [inline, inherited]
Are we processing offline data?
Definition at line 93 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fIsOffline.
Referenced by TRootanaDisplay::InitializeMainWindow().
{return fIsOffline;};
bool TRootanaEventLoop::IsOnline () const [inline, inherited]
Are we processing online data?
Definition at line 90 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fIsOffline.
{return !fIsOffline;};
bool TRootanaEventLoop::IsOnline () const [inline, inherited]
Are we processing online data?
Definition at line 90 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fIsOffline.
Referenced by TRootanaDisplay::InitializeMainWindow(), TRootanaDisplay::ProcessMidasEvent(), and TRootanaDisplay::UpdatePlotsAction().
{return !fIsOffline;};
void TRootanaDisplay::NextButtonPushed () [inline, inherited]
Method for when next button is pushed (offline mode).
Definition at line 88 of file TRootanaDisplay.hxx.
References TRootanaDisplay::waitingForNextButton.
{
    waitingForNextButton = false;
  }
void TRootanaDisplay::NextButtonPushed () [inline, inherited]
Method for when next button is pushed (offline mode).
Definition at line 88 of file TRootanaDisplay.hxx.
References TRootanaDisplay::waitingForNextButton.
{
    waitingForNextButton = false;
  }
void TRootanaEventLoop::OpenRootFile (int run) [inherited]
Open output ROOT file.
void TRootanaEventLoop::OpenRootFile (int run) [inherited]
Open output ROOT file.
Definition at line 319 of file TRootanaEventLoop.cxx.
References TRootanaEventLoop::fDisableRootOutput, TRootanaEventLoop::fOutputFile, and NetDirectoryExport().
Referenced by TRootanaEventLoop::ProcessMidasFile().
{
  if(fDisableRootOutput) return;
  if(fOutputFile) {
    fOutputFile->Write();
    fOutputFile->Close();
    fOutputFile=0;
  }
  char filename[1024];
  sprintf(filename, "output%05d.root", run);
  fOutputFile = new TFile(filename,"RECREATE");
  std::cout << "Opened output file with name : " << filename << std::endl;
#ifdef HAVE_LIBNETDIRECTORY
  NetDirectoryExport(fOutputFile, "outputFile");
#endif
}
void MyTestLoop::PlotCanvas (TDataContainer & dataContainer) [inline, virtual]
This method can be implemented by users to plotting of current canvas.
Reimplemented from TRootanaDisplay.
Definition at line 78 of file display_example.cxx.
References TMainDisplayWindow::GetCanvas(), TRootanaDisplay::GetDisplayWindow(), and sizeBankFR10.
{
    if(GetDisplayWindow()->GetCurrentTabName().compare("FR10") == 0){
      TCanvas* c1 = GetDisplayWindow()->GetCanvas("FR10");
      c1->Clear();
      sizeBankFR10->Draw();
      c1->Modified();
      c1->Update();
    }
  }
bool MyTestLoop::ProcessMidasEvent (TDataContainer & dataContainer) [inline, virtual]
Process each midas event.
Reimplemented from TRootanaDisplay.
Definition at line 33 of file analyzer_example.cxx.
References TDirectory::cd(), TRootanaEventLoop::fOnlineHistDir, TDirectory::Get(), TDCMeasurement::GetChannel(), TRootanaEventLoop::GetCurrentRunNumber(), TDataContainer::GetEventData(), TDCMeasurement::GetMeasurement(), TV1190Data::GetMeasurements(), TDataContainer::GetMidasData(), TDCMeasurement::GetTDCNumber(), TMidasEvent::LocateBank(), nnn, and TV792Data::Print().
{
    void *ptr;
    int size = dataContainer.GetMidasData().LocateBank(NULL, "FR10", &ptr);
    if (ptr){
      nnn++;
      if(nnn%100 == 0){
        std::cout << "Current run :  " << GetCurrentRunNumber() << std::endl;
        std::cout << "Trying to handle this event... " << size << " " << nnn << std::endl;
      }
      fOnlineHistDir->cd();
      char sname[256];
      sprintf(sname, "size%d", 0);
      TH1D* hsize = (TH1D*)fOnlineHistDir->Get(sname);
      if (!hsize){
        printf("Create [%s]\n", sname);
        hsize = new TH1D(sname, sname, 600, 0, 6000);
      }
      hsize->Fill(size);
    }
    TV1190Data *v1190 = dataContainer.GetEventData<TV1190Data>("TDC0");
    if(v1190){
      std::cout << "TDC measurements for V1190" << std::endl;
      std::vector<TDCMeasurement>& measurements = v1190->GetMeasurements();
      for(unsigned int i = 0; i < measurements.size(); i++){
        TDCMeasurement tdcmeas = measurements[i];
        std::cout << "Measurement: " <<    tdcmeas.GetMeasurement() << " for tdc/chan "  <<
          tdcmeas.GetTDCNumber() << "/"<< tdcmeas.GetChannel() << std::endl;
      }
    }
    TV792Data *v792 = dataContainer.GetEventData<TV792Data>("ADC0");
    if(v792 ){
      v792->Print();
    }
    return true;
  }
int TRootanaEventLoop::ProcessMidasFile (TApplication * app, const char * fname) [inherited]
int TRootanaEventLoop::ProcessMidasFile (TApplication * app, const char * fname) [inherited]
Treat the begin run and end run events differently.
Definition at line 232 of file TRootanaEventLoop.cxx.
References TRootanaEventLoop::BeginRun(), TDataContainer::CleanupEvent(), TMidasFile::Close(), TRootanaEventLoop::CloseRootFile(), TRootanaEventLoop::EndRun(), TRootanaEventLoop::fCurrentRunNumber, TRootanaEventLoop::fDataContainer, TRootanaEventLoop::fMaxEvents, TRootanaEventLoop::fODB, TMidasEvent::GetData(), TMidasEvent::GetSerialNumber(), TMidasFile::Open(), TRootanaEventLoop::OpenRootFile(), TRootanaEventLoop::ProcessMidasEvent(), TMidasFile::Read(), and TDataContainer::SetMidasEventPointer().
Referenced by TRootanaEventLoop::ExecuteLoop().
{
  TMidasFile f;
  bool tryOpen = f.Open(fname);
  if (!tryOpen){
    printf("Cannot open input file \"%s\"\n",fname);
    return -1;
  }
  int i=0;
  while (1)
    {
      TMidasEvent event;
      if (!f.Read(&event))
        break;
      /// Treat the begin run and end run events differently.
      int eventId = event.GetEventId();
      if ((eventId & 0xFFFF) == 0x8000){// begin run event
        event.Print();
        // Load ODB contents from the ODB XML file
        if (fODB) delete fODB;
        fODB = new XmlOdb(event.GetData(),event.GetDataSize());
        fCurrentRunNumber = event.GetSerialNumber();
        OpenRootFile(fCurrentRunNumber);
        BeginRun(0,event.GetSerialNumber(),0);
      } else if ((eventId & 0xFFFF) == 0x8001){// end run event
        event.Print();
        //EndRun(0,fCurrentRunNumber,0);
      } else if ((eventId & 0xFFFF) == 0x8002){
        event.Print();
        printf("Log message: %s\n", event.GetData());
      }else { // all other events
        // Set the bank list for midas event.
        event.SetBankList();
        // Set the midas event pointer in the physics event.
        fDataContainer->SetMidasEventPointer(event);
        //ProcessEvent(event);
        ProcessMidasEvent(*fDataContainer);
        // Cleanup the information for this event.
        fDataContainer->CleanupEvent();
      }
      if((i%500)==0){
        printf("Processing event %d\n",i);
      }
      // Check if we have processed desired number of events.
      i++;
      if ((fMaxEvents!=0)&&(i>=fMaxEvents)){
        printf("Reached event %d, exiting loop.\n",i);
        break;
      }
    }
  f.Close();
  EndRun(0,fCurrentRunNumber,0);
  CloseRootFile();
  // start the ROOT GUI event loop
  //  app->Run(kTRUE);
  return 0;
}
void TRootanaDisplay::Reset () [inherited]
This method calls a couple other methods for resets the histograms. This method is attached using the ROOT signal/input system to the reset button on the canvas.
void TRootanaDisplay::Reset () [inherited]
This method calls a couple other methods for resets the histograms. This method is attached using the ROOT signal/input system to the reset button on the canvas.
Definition at line 204 of file TRootanaDisplay.cxx.
References TRootanaDisplay::fCanvasHandlers, TRootanaDisplay::ResetHistograms(), and TRootanaDisplay::UpdatePlotsAction().
{
  // Call the reset functions defined in user event loop.
  ResetHistograms();
  // Call the user defined canvas classes.
  for(unsigned int i = 0; i < fCanvasHandlers.size(); i++)
      fCanvasHandlers[i].second->ResetCanvasHistograms();
  UpdatePlotsAction();
}
void MyTestLoop::ResetHistograms () [inline, virtual]
This method can be implemented by users to plotting of current canvas.
Reimplemented from TRootanaDisplay.
Definition at line 65 of file display_example.cxx.
References sizeBankFR10.
{
    sizeBankFR10->Reset();
  }
void TRootanaEventLoop::SetCurrentRunNumber (int run) [inline, inherited]
Current Run Number.
Definition at line 99 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fCurrentRunNumber.
{fCurrentRunNumber = run;};
void TRootanaEventLoop::SetCurrentRunNumber (int run) [inline, inherited]
Current Run Number.
Definition at line 99 of file TRootanaEventLoop.hxx.
References TRootanaEventLoop::fCurrentRunNumber.
{fCurrentRunNumber = run;};
void TRootanaDisplay::SetDisplayName (std::string name) [inline, inherited]
Set Display name.
Definition at line 116 of file TRootanaDisplay.hxx.
References TRootanaDisplay::fDisplayName.
{fDisplayName = name;}
void TRootanaDisplay::SetDisplayName (std::string name) [inline, inherited]
Set Display name.
Definition at line 116 of file TRootanaDisplay.hxx.
References TRootanaDisplay::fDisplayName.
Referenced by AddAllCanvases().
{fDisplayName = name;}
void TRootanaDisplay::SetNumberSkipEvent (int number) [inline, inherited]
Function so that user can specify at outset how many events to skip before refreshing display (in online mode).
Definition at line 107 of file TRootanaDisplay.hxx.
References TRootanaDisplay::fMainWindow, TRootanaDisplay::fNumberSkipEventsOnline, and TMainDisplayWindow::GetSkipEventButton().
{
    fNumberSkipEventsOnline = number;
    if(fMainWindow->GetSkipEventButton())
      fMainWindow->GetSkipEventButton()->GetNumberEntry()->SetIntNumber(number);
  }
void TRootanaDisplay::SetNumberSkipEvent (int number) [inline, inherited]
Function so that user can specify at outset how many events to skip before refreshing display (in online mode).
Definition at line 107 of file TRootanaDisplay.hxx.
References TRootanaDisplay::fMainWindow, TRootanaDisplay::fNumberSkipEventsOnline, and TMainDisplayWindow::GetSkipEventButton().
Referenced by AddAllCanvases().
{
    fNumberSkipEventsOnline = number;
    if(fMainWindow->GetSkipEventButton())
      fMainWindow->GetSkipEventButton()->GetNumberEntry()->SetIntNumber(number);
  }
void MyTestLoop::UpdateHistograms (TDataContainer & dataContainer) [inline, virtual]
This method can be implemented by users to update user histograms.
Reimplemented from TRootanaDisplay.
Definition at line 69 of file display_example.cxx.
References TDataContainer::GetMidasData(), TMidasEvent::LocateBank(), and sizeBankFR10.
{
    void *ptr;
    // Update histograms
    int size = dataContainer.GetMidasData().LocateBank(NULL, "FR10", &ptr);
    sizeBankFR10->Fill(size);
  }
void TRootanaDisplay::UpdatePlotsAction () [inherited]
void TRootanaDisplay::UpdatePlotsAction () [inherited]
Definition at line 163 of file TRootanaDisplay.cxx.
References TRootanaDisplay::fCachedDataContainer, TRootanaDisplay::fCanvasHandlers, TRootanaDisplay::fMainWindow, TRootanaEventLoop::GetCurrentRunNumber(), TMainDisplayWindow::GetCurrentTabNumber(), TRootanaDisplay::GetDisplayName(), TRootanaDisplay::GetDisplayWindow(), TMainDisplayWindow::GetEmbeddedCanvas(), TMainDisplayWindow::GetMain(), TDataContainer::GetMidasData(), TMidasEvent::GetSerialNumber(), TRootanaEventLoop::IsOnline(), TRootanaDisplay::PlotCanvas(), and TMainDisplayWindow::ResetSize().
Referenced by TRootanaDisplay::BeginRun(), TRootanaDisplay::EndRun(), TRootanaDisplay::ProcessMidasEvent(), and TRootanaDisplay::Reset().
{
  if(!fCachedDataContainer){
    char displayTitle[200];
    sprintf(displayTitle,"%s (): run %i (no events yet)",
            GetDisplayName().c_str(),GetCurrentRunNumber());
    GetDisplayWindow()->GetMain()->SetWindowName(displayTitle);
    return;
  }
  // Execute the plotting actions from user event loop.
  PlotCanvas(*fCachedDataContainer);
  // See if we find a user class that describes this tab.
  int currentTab = GetDisplayWindow()->GetCurrentTabNumber();
  for(unsigned int i = 0; i < fCanvasHandlers.size(); i++){
    if(currentTab == fCanvasHandlers[i].first){
      TRootEmbeddedCanvas* embed = GetDisplayWindow()->GetEmbeddedCanvas(currentTab);
      fCanvasHandlers[i].second->PlotCanvas(*fCachedDataContainer,embed);
    }
  }
  // Set the display title
  char displayTitle[200];
  if(IsOnline())
    sprintf(displayTitle,"%s (online): run %i event %i",
            GetDisplayName().c_str(),GetCurrentRunNumber(),
            fCachedDataContainer->GetMidasData().GetSerialNumber());
  else
    sprintf(displayTitle,"%s (offline): run %i event %i",
            GetDisplayName().c_str(),GetCurrentRunNumber(),
            fCachedDataContainer->GetMidasData().GetSerialNumber());
  GetDisplayWindow()->GetMain()->SetWindowName(displayTitle);
  // Update canvas and window sizes
  fMainWindow->ResetSize();
}
void MyTestLoop::Usage (void) [inline, virtual]
Called when there is a usage error. This code should print a usage message and then return.
Reimplemented from TRootanaEventLoop.
Definition at line 84 of file analyzer_example.cxx.
                  {
    std::cout << "\t-D option: this is a fun new option " << std::endl;
  }
Member Data Documentation
TDirectory * TRootanaEventLoop::fOnlineHistDir [protected, inherited]
TDirectory for online histograms.
Definition at line 154 of file TRootanaEventLoop.hxx.
Referenced by TRootanaEventLoop::ExecuteLoop(), ProcessMidasEvent(), and TRootanaEventLoop::TRootanaEventLoop().
TDirectory * TRootanaEventLoop::fOnlineHistDir [protected, inherited]
TDirectory for online histograms.
Definition at line 154 of file TRootanaEventLoop.hxx.
Referenced by TRootanaEventLoop::ExecuteLoop(), ProcessMidasEvent(), and TRootanaEventLoop::TRootanaEventLoop().
static TRootanaEventLoop * TRootanaEventLoop::fTRootanaEventLoop = NULL [static, protected, inherited]
The static pointer to the singleton instance.
Definition at line 151 of file TRootanaEventLoop.hxx.
Referenced by TRootanaEventLoop::CreateSingleton(), and TRootanaEventLoop::Get().
static TRootanaEventLoop * TRootanaEventLoop::fTRootanaEventLoop = NULL [static, protected, inherited]
The static pointer to the singleton instance.
Definition at line 151 of file TRootanaEventLoop.hxx.
Referenced by TRootanaEventLoop::CreateSingleton(), and TRootanaEventLoop::Get().
int MyTestLoop::nnn [private]
Definition at line 15 of file analyzer_example.cxx.
Referenced by MyTestLoop(), and ProcessMidasEvent().
TH1F* MyTestLoop::sizeBankFR10 [private]
Definition at line 45 of file display_example.cxx.
Referenced by MyTestLoop(), PlotCanvas(), ResetHistograms(), and UpdateHistograms().
The documentation for this class was generated from the following files:
libAnalyzer/analyzer_example.cxx
libAnalyzerDisplay/display_example.cxx