ROOT Analyzer: TDataContainer Class Reference
TDataContainer Class Reference
#include <TDataContainer.hxx>
Public Member Functions
TDataContainer ()
TDataContainer (const TDataContainer &dataContainer)
~TDataContainer ()
TMidasEvent & GetMidasData () const
Get the MIDAS data for this event, in TMidasEvent format.
TMidasEvent & GetMidasEvent () const
template<typename T >
T * GetEventData (const char *name)
Add a templated function that returns event data in the format that we want.
void CleanupEvent ()
void SetMidasEventPointer (TMidasEvent &event)
TDataContainer ()
TDataContainer (const TDataContainer &dataContainer)
~TDataContainer ()
TMidasEvent & GetMidasData () const
Get the MIDAS data for this event, in TMidasEvent format.
TMidasEvent & GetMidasEvent () const
template<typename T >
T * GetEventData (const char *name)
Add a templated function that returns event data in the format that we want.
void CleanupEvent ()
void SetMidasEventPointer (TMidasEvent &event)
Private Member Functions
TDataContainer & operator= (const TDataContainer &event)
For the moment make empty assign operator.
TDataContainer & operator= (const TDataContainer &event)
For the moment make empty assign operator.
Private Attributes
TMidasEvent * fMidasEventPointer
bool fOwnMidasEventMemory
Do we own the memory pointed to by TMidasEvent pointer?
std::vector< TGenericData * > fEventDataList
Detailed Description
This class is what will get passed back to users for each midas event. It will contain a pointer to the midas event, which the user can access. It will also contain routines that the user can call to access decoded versions of the midas banks. Generally the decoded information will be cleaned out at the end of each event; but there will be options to allow this information to persist.
Definition at line 28 of file TDataContainer.hxx.
Constructor & Destructor Documentation
TDataContainer::TDataContainer () [inline]
Definition at line 34 of file TDataContainer.hxx.
                  :
    fMidasEventPointer(0), fOwnMidasEventMemory(false)
  {}
TDataContainer::TDataContainer (const TDataContainer & dataContainer)
Definition at line 6 of file TDataContainer.cxx.
References fMidasEventPointer, fOwnMidasEventMemory, and GetMidasData().
{
  fMidasEventPointer = new TMidasEvent(dataContainer.GetMidasData());
  fOwnMidasEventMemory = true;
}
TDataContainer::~TDataContainer ()
Definition at line 13 of file TDataContainer.cxx.
References fEventDataList, fMidasEventPointer, and fOwnMidasEventMemory.
{
  if(fOwnMidasEventMemory)
    delete fMidasEventPointer;
  for(unsigned int i = 0; i < fEventDataList.size(); i++){
    delete fEventDataList[i];
  }
}
TDataContainer::TDataContainer () [inline]
Definition at line 34 of file TDataContainer.hxx.
                  :
    fMidasEventPointer(0), fOwnMidasEventMemory(false)
  {}
TDataContainer::TDataContainer (const TDataContainer & dataContainer)
TDataContainer::~TDataContainer ()
Member Function Documentation
void TDataContainer::CleanupEvent ()
Method to clean up the current events list of event data. Generally this will delete all the existing information, but this behaviour may be modified in some cases.
void TDataContainer::CleanupEvent ()
Method to clean up the current events list of event data. Generally this will delete all the existing information, but this behaviour may be modified in some cases.
Definition at line 43 of file TDataContainer.cxx.
References fEventDataList.
Referenced by TRootanaEventLoop::ProcessMidasFile().
{
  for(unsigned int i = 0; i < fEventDataList.size(); i++){
    delete fEventDataList[i];
  }
  fEventDataList.clear();
}
template<typename T > T* TDataContainer::GetEventData (const char * name) [inline]
Add a templated function that returns event data in the format that we want.
If we couldn't find bank, return null.
Definition at line 48 of file TDataContainer.hxx.
References fEventDataList, TMidasEvent::FindBank(), and GetMidasData().
{
    // Try to find a cached version of this bank
    for(unsigned int ibank = 0; ibank < fEventDataList.size(); ibank++){
      if(fEventDataList[ibank]->GetName().compare(name) == 0){
        // Found bank.  Now check it has correct type.
        T* cast_bank = dynamic_cast<T*>(fEventDataList[ibank]);
        // Throw exception if cached bank is of different type.
        if(!cast_bank){
          std::cout << "TMidasEvent::GetMidasBank: ERROR: you requested bank with name=" << name << std::endl
                    << "A cached version of this bank (of type " << typeid(fEventDataList[ibank]).name()
                    << ") already exists in event; cannot create bank class of new type "
                    << typeid(T).name()<<std::endl;
          throw failed_midas_bank_cast();
        }
        return cast_bank;
      }
    }
    void *ptr;
    int bklen,bktype;
    int status = GetMidasData().FindBank(name, &bklen, &bktype, &ptr);
    /// If we couldn't find bank, return null.
    if(status == 0) return 0;
    T *bank = new T(bklen,bktype,name, ptr);
     // Cache a version of this bank...
    fEventDataList.push_back(bank);
    return bank;
  }
template<typename T > T* TDataContainer::GetEventData (const char * name) [inline]
Add a templated function that returns event data in the format that we want.
If we couldn't find bank, return null.
Definition at line 48 of file TDataContainer.hxx.
References fEventDataList, TMidasEvent::FindBank(), and GetMidasData().
Referenced by MyTestLoop::ProcessMidasEvent(), TSimpleExampleCanvas::UpdateCanvasHistograms(), and TComplicatedExampleCanvas::UpdateCanvasHistograms().
{
    // Try to find a cached version of this bank
    for(unsigned int ibank = 0; ibank < fEventDataList.size(); ibank++){
      if(fEventDataList[ibank]->GetName().compare(name) == 0){
        // Found bank.  Now check it has correct type.
        T* cast_bank = dynamic_cast<T*>(fEventDataList[ibank]);
        // Throw exception if cached bank is of different type.
        if(!cast_bank){
          std::cout << "TMidasEvent::GetMidasBank: ERROR: you requested bank with name=" << name << std::endl
                    << "A cached version of this bank (of type " << typeid(fEventDataList[ibank]).name()
                    << ") already exists in event; cannot create bank class of new type "
                    << typeid(T).name()<<std::endl;
          throw failed_midas_bank_cast();
        }
        return cast_bank;
      }
    }
    void *ptr;
    int bklen,bktype;
    int status = GetMidasData().FindBank(name, &bklen, &bktype, &ptr);
    /// If we couldn't find bank, return null.
    if(status == 0) return 0;
    T *bank = new T(bklen,bktype,name, ptr);
     // Cache a version of this bank...
    fEventDataList.push_back(bank);
    return bank;
  }
TMidasEvent& TDataContainer::GetMidasData () const
Get the MIDAS data for this event, in TMidasEvent format.
TMidasEvent & TDataContainer::GetMidasData () const
Get the MIDAS data for this event, in TMidasEvent format.
Definition at line 66 of file TDataContainer.cxx.
References fMidasEventPointer.
Referenced by GetEventData(), GetMidasEvent(), MyTestLoop::ProcessMidasEvent(), TDataContainer(), MyTestLoop::UpdateHistograms(), and TRootanaDisplay::UpdatePlotsAction().
{
  // Make sure that point is valid.
  if(fMidasEventPointer==0){
    throw TDataContainerNoValidMidasEvent();
  }
  return *fMidasEventPointer;
}
TMidasEvent& TDataContainer::GetMidasEvent () const [inline]
Definition at line 44 of file TDataContainer.hxx.
References GetMidasData().
{ return GetMidasData(); }
TMidasEvent& TDataContainer::GetMidasEvent () const [inline]
Definition at line 44 of file TDataContainer.hxx.
References GetMidasData().
{ return GetMidasData(); }
TDataContainer& TDataContainer::operator= (const TDataContainer & event) [private]
For the moment make empty assign operator.
TDataContainer& TDataContainer::operator= (const TDataContainer & event) [private]
For the moment make empty assign operator.
void TDataContainer::SetMidasEventPointer (TMidasEvent & event)
This is the ugly function where we de-reference to get pointer for a TMidasEvent (ugly!). In this case TDataContainer does not own the memory referenced by fMidasEventPointer.
void TDataContainer::SetMidasEventPointer (TMidasEvent & event)
This is the ugly function where we de-reference to get pointer for a TMidasEvent (ugly!). In this case TDataContainer does not own the memory referenced by fMidasEventPointer.
Definition at line 52 of file TDataContainer.cxx.
References fMidasEventPointer, and fOwnMidasEventMemory.
Referenced by TRootanaEventLoop::ProcessMidasFile().
{
  // If the MidasPointer is still valid and we own the memory associated with it,
  // then we shouldn't be reseting the fMidasEventPointer.
  if(fOwnMidasEventMemory && fMidasEventPointer){
    throw TDataContainerBadPointerReset();
  }
  fMidasEventPointer = &event; // ugly!
  fOwnMidasEventMemory = false;
}
Member Data Documentation
std::vector< TGenericData * > TDataContainer::fEventDataList [private]
This is the list of banks associated with this event. The event owns these banks and needs to take care of deleting them.
Definition at line 110 of file TDataContainer.hxx.
Referenced by CleanupEvent(), GetEventData(), and ~TDataContainer().
TMidasEvent * TDataContainer::fMidasEventPointer [private]
Pointer to the TMidasEvent; In some cases we own the memory referenced by pointer; other cases not
Definition at line 98 of file TDataContainer.hxx.
Referenced by GetMidasData(), SetMidasEventPointer(), TDataContainer(), and ~TDataContainer().
bool TDataContainer::fOwnMidasEventMemory [private]
Do we own the memory pointed to by TMidasEvent pointer?
Definition at line 101 of file TDataContainer.hxx.
Referenced by SetMidasEventPointer(), TDataContainer(), and ~TDataContainer().
The documentation for this class was generated from the following files:
include/TDataContainer.hxx
libAnalyzer/TDataContainer.hxx
libAnalyzer/TDataContainer.cxx