ROOT Analyzer: TGenericData Class Reference
TGenericData Class Reference
#include <TGenericData.hxx>
Public Member Functions
TGenericData (int bklen, int bktype, const char *name, void *pdata)
virtual ~TGenericData ()
const uint16_t * GetData16 () const
const uint32_t * GetData32 () const
const uint64_t * GetData64 () const
int GetSize () const
int GetType () const
std::string GetName () const
void Dump ()
Dump the bank contents in an unstructured way.
virtual void Print ()
Print the bank contents in a structured way.
TGenericData (int bklen, int bktype, const char *name, void *pdata)
virtual ~TGenericData ()
const uint16_t * GetData16 () const
const uint32_t * GetData32 () const
const uint64_t * GetData64 () const
int GetSize () const
int GetType () const
std::string GetName () const
void Dump ()
Dump the bank contents in an unstructured way.
virtual void Print ()
Print the bank contents in a structured way.
Private Attributes
int fSize
Size of the bank (in what units?).
int fBankType
Bank data type (MIDAS TID_xxx).
std::string fBankName
Bank name.
void * fData
Detailed Description
Definition at line 7 of file TGenericData.hxx.
Constructor & Destructor Documentation
TGenericData::TGenericData (int bklen, int bktype, const char * name, void * pdata) [inline]
Definition at line 14 of file TGenericData.hxx.
                                                                    :fSize(bklen),
fBankType(bktype), fBankName(name),fData(pdata){
  };
virtual TGenericData::~TGenericData () [inline, virtual]
Definition at line 20 of file TGenericData.hxx.
{};
TGenericData::TGenericData (int bklen, int bktype, const char * name, void * pdata) [inline]
Definition at line 14 of file TGenericData.hxx.
                                                                    :fSize(bklen),
fBankType(bktype), fBankName(name),fData(pdata){
  };
virtual TGenericData::~TGenericData () [inline, virtual]
Definition at line 20 of file TGenericData.hxx.
{};
Member Function Documentation
void TGenericData::Dump () [inline]
Dump the bank contents in an unstructured way.
Definition at line 38 of file TGenericData.hxx.
References GetData32(), GetName(), and GetSize().
             {
    std::cout << "Generic decoder for bank named " <<  GetName().c_str() << std::endl;
    for(int i = 0; i < GetSize(); i++){
      std::cout << std::hex << "0x" << GetData32()[i] << std::dec << std::endl;
    }
  }
void TGenericData::Dump () [inline]
Dump the bank contents in an unstructured way.
Definition at line 38 of file TGenericData.hxx.
References GetData32(), GetName(), and GetSize().
Referenced by Print().
             {
    std::cout << "Generic decoder for bank named " <<  GetName().c_str() << std::endl;
    for(int i = 0; i < GetSize(); i++){
      std::cout << std::hex << "0x" << GetData32()[i] << std::dec << std::endl;
    }
  }
const uint16_t* TGenericData::GetData16 () const [inline]
Definition at line 23 of file TGenericData.hxx.
References fData.
{ return reinterpret_cast<const uint16_t*>(fData); }
const uint16_t* TGenericData::GetData16 () const [inline]
Definition at line 23 of file TGenericData.hxx.
References fData.
{ return reinterpret_cast<const uint16_t*>(fData); }
const uint32_t* TGenericData::GetData32 () const [inline]
Definition at line 26 of file TGenericData.hxx.
References fData.
{ return reinterpret_cast<const uint32_t*>(fData); }
const uint32_t* TGenericData::GetData32 () const [inline]
Definition at line 26 of file TGenericData.hxx.
References fData.
Referenced by Dump(), TMesytecData::TMesytecData(), TV1190Data::TV1190Data(), and TV792Data::TV792Data().
{ return reinterpret_cast<const uint32_t*>(fData); }
const uint64_t* TGenericData::GetData64 () const [inline]
Definition at line 29 of file TGenericData.hxx.
References fData.
{ return reinterpret_cast<const uint64_t*>(fData); }
const uint64_t* TGenericData::GetData64 () const [inline]
Definition at line 29 of file TGenericData.hxx.
References fData.
{ return reinterpret_cast<const uint64_t*>(fData); }
std::string TGenericData::GetName () const [inline]
Definition at line 35 of file TGenericData.hxx.
References fBankName.
{return fBankName;}
std::string TGenericData::GetName () const [inline]
Definition at line 35 of file TGenericData.hxx.
References fBankName.
Referenced by Dump(), TV792Data::Print(), TV1190Data::Print(), and TMesytecData::Print().
{return fBankName;}
int TGenericData::GetSize () const [inline]
Definition at line 31 of file TGenericData.hxx.
References fSize.
{return fSize;}
int TGenericData::GetSize () const [inline]
Definition at line 31 of file TGenericData.hxx.
References fSize.
Referenced by Dump(), TMesytecData::TMesytecData(), TV1190Data::TV1190Data(), and TV792Data::TV792Data().
{return fSize;}
int TGenericData::GetType () const [inline]
Definition at line 33 of file TGenericData.hxx.
References fBankType.
{return fBankType;}
int TGenericData::GetType () const [inline]
Definition at line 33 of file TGenericData.hxx.
References fBankType.
{return fBankType;}
virtual void TGenericData::Print () [inline, virtual]
Print the bank contents in a structured way.
Reimplemented in TMesytecData, TV1190Data, TV792Data, TMesytecData, TV1190Data, and TV792Data.
Definition at line 48 of file TGenericData.hxx.
References Dump().
                      {
    Dump();
  }
virtual void TGenericData::Print () [inline, virtual]
Print the bank contents in a structured way.
Reimplemented in TMesytecData, TV1190Data, TV792Data, TMesytecData, TV1190Data, and TV792Data.
Definition at line 48 of file TGenericData.hxx.
References Dump().
                      {
    Dump();
  }
Member Data Documentation
std::string TGenericData::fBankName [private]
Bank name.
Definition at line 61 of file TGenericData.hxx.
Referenced by GetName().
int TGenericData::fBankType [private]
Bank data type (MIDAS TID_xxx).
Definition at line 58 of file TGenericData.hxx.
Referenced by GetType().
void * TGenericData::fData [private]
Pointer to the unstructured data. The data itself is NOT owned by TGenericData.
Definition at line 65 of file TGenericData.hxx.
Referenced by GetData16(), GetData32(), and GetData64().
int TGenericData::fSize [private]
Size of the bank (in what units?).
Definition at line 55 of file TGenericData.hxx.
Referenced by GetSize().
The documentation for this class was generated from the following files:
include/TGenericData.hxx
libAnalyzer/TGenericData.hxx