ROOT Analyzer: TMainDisplayWindow Class Reference
TMainDisplayWindow Class Reference
#include <TMainDisplayWindow.hxx>
Public Member Functions
TGTextButton * GetResetButton ()
TGTextButton * GetNextButton ()
TGNumberEntry * GetSkipEventButton ()
TMainDisplayWindow (const TGWindow *p, UInt_t w, UInt_t h, bool isOffline)
virtual ~TMainDisplayWindow ()
void QuitButtonAction ()
Method to call when 'quit' button is pressed.
void SavePadButtonAction ()
Method to call when 'save pad' button is pressed.
void SaveCanvasButtonAction ()
Method to call when 'save canvas' button is pressed.
void PauseResumeButtonAction ()
Method to call when 'pause/resume' button is pressed.
bool IsDisplayPaused ()
void AddCanvas (std::string name)
void BuildWindow ()
void ResetSize ()
This resizing is still not working right! The secondary tabs are not properly resizing!!!
TRootEmbeddedCanvas * GetEmbeddedCanvas (int iTab)
TRootEmbeddedCanvas * GetEmbeddedCanvas (const char *name)
TCanvas * GetCanvas (int iTab)
Get a particular canvas based on index number.
TCanvas * GetCanvas (const char *name)
Get a particular canvas based on canvas name.
int GetCurrentTabNumber ()
Return the index number for the current tab.
std::string GetCurrentTabName ()
Return the canvas name for the current tab.
TGMainFrame * GetMain ()
TGTab * GetTab ()
TGTextButton * GetResetButton ()
TGTextButton * GetNextButton ()
TGNumberEntry * GetSkipEventButton ()
TMainDisplayWindow (const TGWindow *p, UInt_t w, UInt_t h, bool isOffline)
virtual ~TMainDisplayWindow ()
void QuitButtonAction ()
Method to call when 'quit' button is pressed.
void SavePadButtonAction ()
Method to call when 'save pad' button is pressed.
void SaveCanvasButtonAction ()
Method to call when 'save canvas' button is pressed.
void PauseResumeButtonAction ()
Method to call when 'pause/resume' button is pressed.
bool IsDisplayPaused ()
void AddCanvas (std::string name)
void BuildWindow ()
void ResetSize ()
TRootEmbeddedCanvas * GetEmbeddedCanvas (int iTab)
TRootEmbeddedCanvas * GetEmbeddedCanvas (const char *name)
TCanvas * GetCanvas (int iTab)
Get a particular canvas based on index number.
TCanvas * GetCanvas (const char *name)
Get a particular canvas based on canvas name.
int GetCurrentTabNumber ()
Return the index number for the current tab.
std::string GetCurrentTabName ()
Return the canvas name for the current tab.
TGMainFrame * GetMain ()
TGTab * GetTab ()
Private Attributes
TGMainFrame * fMain
TGTab * fTab
TGFrame * fFrame
TGHorizontalFrame * fHframe
bool fIsOffline
bool fProcessingPaused
Is processing paused?
TGTextButton * fSavePadButton
Buttons to make plots of current pad/canvas.
TGTextButton * fSaveCanvasButton
TGTextButton * fNextButton
TGTextButton * fResetButton
TGTextButton * fQuitButton
TGTextButton * fPauseButton
TGNumberEntry * fNumberSkipEventButton
Detailed Description
Definition at line 18 of file TMainDisplayWindow.hxx.
Constructor & Destructor Documentation
TMainDisplayWindow::TMainDisplayWindow (const TGWindow * p, UInt_t w, UInt_t h, bool isOffline)
TMainDisplayWindow::~TMainDisplayWindow () [virtual]
Definition at line 258 of file TMainDisplayWindow.cxx.
References fMain, and fTab.
{
  delete fMain;
  delete fTab;
}
TMainDisplayWindow::TMainDisplayWindow (const TGWindow * p, UInt_t w, UInt_t h, bool isOffline)
virtual TMainDisplayWindow::~TMainDisplayWindow () [virtual]
Member Function Documentation
void TMainDisplayWindow::AddCanvas (std::string name)
void TMainDisplayWindow::AddCanvas (std::string name)
Definition at line 131 of file TMainDisplayWindow.cxx.
References fDefaultHeight, fDefaultWidth, and fTab.
Referenced by TRootanaDisplay::AddSingleCanvas().
{
  // Add a new tab element, of type TGCompositeFrame
  TGCompositeFrame *compositeFrame = fTab->AddTab(name.c_str());
  compositeFrame->SetLayoutManager(new TGVerticalLayout(compositeFrame));
  // Add a canvas within that composite frame.
  char cname[500];
  sprintf(cname,"Canvas_%i",fTab->GetNumberOfTabs() - 1);
  TRootEmbeddedCanvas *embed_canvas  = new TRootEmbeddedCanvas(cname, compositeFrame,fDefaultWidth,fDefaultHeight);
  compositeFrame->AddFrame(embed_canvas, new TGLayoutHints(kLHintsTop | kLHintsExpandX,5,5,5,0));
}
void TMainDisplayWindow::BuildWindow ()
This method should be called just once, after you have added all the canvases and tabs that you want.
void TMainDisplayWindow::BuildWindow ()
This method should be called just once, after you have added all the canvases and tabs that you want.
Definition at line 146 of file TMainDisplayWindow.cxx.
References fMain.
Referenced by TRootanaDisplay::InitializeMainWindow().
{
  fMain->MapSubwindows();
  // Initialize the layout algorithm
  fMain->Resize(fMain->GetDefaultSize());
  // Map main frame
  fMain->MapWindow();
}
TCanvas* TMainDisplayWindow::GetCanvas (const char * name)
Get a particular canvas based on canvas name.
TCanvas* TMainDisplayWindow::GetCanvas (int iTab)
Get a particular canvas based on index number.
TCanvas * TMainDisplayWindow::GetCanvas (const char * name)
Get a particular canvas based on canvas name.
Definition at line 225 of file TMainDisplayWindow.cxx.
References GetEmbeddedCanvas().
{
  TRootEmbeddedCanvas* embed = GetEmbeddedCanvas(name);
  if(embed) return embed->GetCanvas();
  return 0;
}
TCanvas * TMainDisplayWindow::GetCanvas (int iTab)
Get a particular canvas based on index number.
Definition at line 218 of file TMainDisplayWindow.cxx.
References GetEmbeddedCanvas().
Referenced by MyTestLoop::PlotCanvas().
{
  TRootEmbeddedCanvas* embed = GetEmbeddedCanvas(iTab);
  if(embed) return embed->GetCanvas();
  return 0;
}
std::string TMainDisplayWindow::GetCurrentTabName ()
Return the canvas name for the current tab.
std::string TMainDisplayWindow::GetCurrentTabName ()
Return the canvas name for the current tab.
Definition at line 232 of file TMainDisplayWindow.cxx.
References fTab.
{
  TIter nextTab(fTab->GetList());
  nextTab();  // Skip the first element.  This is the overall TGCompositeFrame, not the tabbed one.
  // Get the index for the current canvas
  int index = fTab->GetCurrent();
  TGFrameElement *el;
  TGTabElement *tab = 0;
  TGCompositeFrame *comp = 0;
  // Loop over the number of tabs, until we find the right one.
  for(int i = 0; i <= index; i++){
    el = (TGFrameElement *) nextTab();
    tab  = (TGTabElement *) el->fFrame;
    el   = (TGFrameElement *) nextTab();
    comp = (TGCompositeFrame *) el->fFrame;
  }
  if(tab){
    return std::string(*tab->GetText());
  }
  return std::string("not found");
}
int TMainDisplayWindow::GetCurrentTabNumber () [inline]
Return the index number for the current tab.
Definition at line 99 of file TMainDisplayWindow.hxx.
References fTab.
{return fTab->GetCurrent();}
int TMainDisplayWindow::GetCurrentTabNumber () [inline]
Return the index number for the current tab.
Definition at line 99 of file TMainDisplayWindow.hxx.
References fTab.
Referenced by TRootanaDisplay::UpdatePlotsAction().
{return fTab->GetCurrent();}
TRootEmbeddedCanvas* TMainDisplayWindow::GetEmbeddedCanvas (const char * name)
TRootEmbeddedCanvas* TMainDisplayWindow::GetEmbeddedCanvas (int iTab)
TRootEmbeddedCanvas * TMainDisplayWindow::GetEmbeddedCanvas (const char * name)
Definition at line 193 of file TMainDisplayWindow.cxx.
References fTab, and GetTRootEmbeddedCanvasFromTGCompositeFrame().
{
  // First find which tab has this name.  This is awkward because the
  // TGCompositeFrame doesn't actully store the name; only the tab element does.
  TIter nextTab(fTab->GetList());
  nextTab();  // Skip the first element.  This is the overall TGCompositeFrame, not the tabbed one.
  TGFrameElement *el;
  TGTabElement *tab = 0;
  TGCompositeFrame *comp = 0;
  while ((el = (TGFrameElement *) nextTab())) {
    tab  = (TGTabElement *) el->fFrame;
    el   = (TGFrameElement *) nextTab();
    if (*tab->GetText() == name){
      comp = (TGCompositeFrame *) el->fFrame;
    }
  }
  // Now return the embedded canvas
  return GetTRootEmbeddedCanvasFromTGCompositeFrame(comp);
}
TRootEmbeddedCanvas * TMainDisplayWindow::GetEmbeddedCanvas (int iTab)
Definition at line 185 of file TMainDisplayWindow.cxx.
References fTab, and GetTRootEmbeddedCanvasFromTGCompositeFrame().
Referenced by GetCanvas(), and TRootanaDisplay::UpdatePlotsAction().
{
  TGCompositeFrame* frame = fTab->GetTabContainer(iTab);
  return GetTRootEmbeddedCanvasFromTGCompositeFrame(frame);
}
TGMainFrame* TMainDisplayWindow::GetMain () [inline]
Definition at line 105 of file TMainDisplayWindow.hxx.
References fMain.
{return fMain;};
TGMainFrame* TMainDisplayWindow::GetMain () [inline]
Definition at line 105 of file TMainDisplayWindow.hxx.
References fMain.
Referenced by TRootanaDisplay::UpdatePlotsAction().
{return fMain;};
TGTextButton* TMainDisplayWindow::GetNextButton () [inline]
Definition at line 57 of file TMainDisplayWindow.hxx.
References fNextButton.
{ return fNextButton;}
TGTextButton* TMainDisplayWindow::GetNextButton () [inline]
Definition at line 57 of file TMainDisplayWindow.hxx.
References fNextButton.
Referenced by TRootanaDisplay::InitializeMainWindow().
{ return fNextButton;}
TGTextButton* TMainDisplayWindow::GetResetButton () [inline]
Definition at line 55 of file TMainDisplayWindow.hxx.
References fResetButton.
{ return fResetButton;}
TGTextButton* TMainDisplayWindow::GetResetButton () [inline]
Definition at line 55 of file TMainDisplayWindow.hxx.
References fResetButton.
Referenced by TRootanaDisplay::InitializeMainWindow().
{ return fResetButton;}
TGNumberEntry* TMainDisplayWindow::GetSkipEventButton () [inline]
Definition at line 59 of file TMainDisplayWindow.hxx.
References fNumberSkipEventButton.
{ return fNumberSkipEventButton;}
TGNumberEntry* TMainDisplayWindow::GetSkipEventButton () [inline]
Definition at line 59 of file TMainDisplayWindow.hxx.
References fNumberSkipEventButton.
Referenced by TRootanaDisplay::EventSkipButtonPushed(), TRootanaDisplay::InitializeMainWindow(), and TRootanaDisplay::SetNumberSkipEvent().
{ return fNumberSkipEventButton;}
TGTab* TMainDisplayWindow::GetTab () [inline]
Definition at line 106 of file TMainDisplayWindow.hxx.
References fTab.
{return fTab;};
TGTab* TMainDisplayWindow::GetTab () [inline]
Definition at line 106 of file TMainDisplayWindow.hxx.
References fTab.
Referenced by TRootanaDisplay::AddSingleCanvas(), and TRootanaDisplay::InitializeMainWindow().
{return fTab;};
bool TMainDisplayWindow::IsDisplayPaused () [inline]
Definition at line 78 of file TMainDisplayWindow.hxx.
References fProcessingPaused.
{
    return fProcessingPaused;
  }
bool TMainDisplayWindow::IsDisplayPaused () [inline]
Definition at line 78 of file TMainDisplayWindow.hxx.
References fProcessingPaused.
Referenced by TRootanaDisplay::ProcessMidasEvent().
{
    return fProcessingPaused;
  }
void TMainDisplayWindow::PauseResumeButtonAction ()
Method to call when 'pause/resume' button is pressed.
void TMainDisplayWindow::PauseResumeButtonAction ()
Method to call when 'pause/resume' button is pressed.
Definition at line 312 of file TMainDisplayWindow.cxx.
References fPauseButton, fProcessingPaused, fSaveCanvasButton, and fSavePadButton.
{
  if(fProcessingPaused){
    fProcessingPaused = false;
    fPauseButton->SetText("Pause");
    fSavePadButton->SetEnabled(false);
    fSaveCanvasButton->SetEnabled(false);
  }else{
    fProcessingPaused = true;
    fPauseButton->SetText("Resume");
    fSavePadButton->SetEnabled(true);
    fSaveCanvasButton->SetEnabled(true);
  }
}
void TMainDisplayWindow::QuitButtonAction ()
Method to call when 'quit' button is pressed.
void TMainDisplayWindow::QuitButtonAction ()
Method to call when 'quit' button is pressed.
Definition at line 267 of file TMainDisplayWindow.cxx.
{
   gApplication->Terminate(0);
}
void TMainDisplayWindow::ResetSize ()
void TMainDisplayWindow::ResetSize ()
This resizing is still not working right! The secondary tabs are not properly resizing!!!
Definition at line 96 of file TMainDisplayWindow.cxx.
References fMain, and fTab.
Referenced by TRootanaDisplay::ProcessMidasEvent(), and TRootanaDisplay::UpdatePlotsAction().
{
  // Resize each part of the tab.
  for(int itab = 0; itab < fTab->GetNumberOfTabs() ; itab++){
    TGCompositeFrame* frame = fTab->GetTabContainer(itab);
    // This is awkward.  Each composite frame actually has a bunch of elements.
    // Try to resize all the elements that are TGFrameElements.
    // This seems to work if the added frame is a TRootEmbeddedCanvas; not sure
    // otherwise.
    TList* mylist = frame->GetList();
    TIter next(mylist);
    while (TObject *obj = next()){
      TGFrameElement *frame_element = dynamic_cast<TGFrameElement*>(obj);
      if(frame_element){
        frame_element->fFrame->Resize((frame_element->fFrame->GetDefaultSize().fWidth)
                                      *(fMain->GetSize().fWidth)/(fMain->GetDefaultSize().fWidth),
                                      (frame_element->fFrame->GetDefaultSize().fHeight)
                                      *(fMain->GetSize().fHeight)/(fMain->GetDefaultSize().fHeight));
        //std::cout << "Frame " << frame_element->fFrame->GetDefaultSize().fWidth << " " << fMain->GetSize().fWidth << " "
        //        << fMain->GetDefaultSize().fWidth << " " << frame_element->fFrame->GetDefaultSize().fHeight << " "
        //        << fMain->GetSize().fHeight << " " << fMain->GetDefaultSize().fHeight << std::endl;
      }else
        std::cout << "TMainDisplayWindow::ResetSize::  Dynamic cast of obj to TGFrameElement failed." << std::endl;
    }
  }
}
void TMainDisplayWindow::SaveCanvasButtonAction ()
Method to call when 'save canvas' button is pressed.
void TMainDisplayWindow::SaveCanvasButtonAction ()
Method to call when 'save canvas' button is pressed.
Definition at line 298 of file TMainDisplayWindow.cxx.
References filetypes, and fMain.
{
  static TString dir(".");
  TGFileInfo fi;
  fi.fFileTypes = filetypes;
  fi.fIniDir    = StrDup(dir);
  new TGFileDialog(gClient->GetRoot(), fMain, kFDSave, &fi);
  printf("Open file: %s (dir: %s)\n", fi.fFilename,
         fi.fIniDir);
  gPad->GetCanvas()->SaveAs(fi.fFilename);
}
void TMainDisplayWindow::SavePadButtonAction ()
Method to call when 'save pad' button is pressed.
void TMainDisplayWindow::SavePadButtonAction ()
Method to call when 'save pad' button is pressed.
Definition at line 278 of file TMainDisplayWindow.cxx.
References filetypes, and fMain.
{
  static TString dir(".");
  TGFileInfo fi;
  fi.fFileTypes = filetypes;
  fi.fIniDir    = StrDup(dir);
  new TGFileDialog(gClient->GetRoot(), fMain, kFDSave, &fi);
  printf("Open file: %s (dir: %s)\n", fi.fFilename,
         fi.fIniDir);
  // Resize pad while saving; to get good image resolution.fTab
  double xl = gPad->GetXlowNDC(), xh = gPad->GetXlowNDC() + gPad->GetWNDC();
  double yl = gPad->GetYlowNDC(), yh = gPad->GetYlowNDC() + gPad->GetHNDC();
  gPad->SetPad(0,0,1.0,1.0);
  gPad->SaveAs(fi.fFilename);
  gPad->SetPad(xl,yl,xh,yh);
  gPad->Update();
}
Member Data Documentation
TGFrame * TMainDisplayWindow::fFrame [private]
Definition at line 25 of file TMainDisplayWindow.hxx.
TGHorizontalFrame * TMainDisplayWindow::fHframe [private]
Definition at line 26 of file TMainDisplayWindow.hxx.
bool TMainDisplayWindow::fIsOffline [private]
Variables to keep track of state of display Are we processing offline?
Definition at line 30 of file TMainDisplayWindow.hxx.
TGMainFrame * TMainDisplayWindow::fMain [private]
Definition at line 23 of file TMainDisplayWindow.hxx.
Referenced by BuildWindow(), GetMain(), ResetSize(), SaveCanvasButtonAction(), SavePadButtonAction(), and ~TMainDisplayWindow().
TGTextButton * TMainDisplayWindow::fNextButton [private]
Definition at line 39 of file TMainDisplayWindow.hxx.
Referenced by GetNextButton().
TGNumberEntry * TMainDisplayWindow::fNumberSkipEventButton [private]
Definition at line 51 of file TMainDisplayWindow.hxx.
Referenced by GetSkipEventButton().
TGTextButton * TMainDisplayWindow::fPauseButton [private]
Definition at line 48 of file TMainDisplayWindow.hxx.
Referenced by PauseResumeButtonAction().
bool TMainDisplayWindow::fProcessingPaused [private]
Is processing paused?
Definition at line 32 of file TMainDisplayWindow.hxx.
Referenced by IsDisplayPaused(), and PauseResumeButtonAction().
TGTextButton * TMainDisplayWindow::fQuitButton [private]
Definition at line 45 of file TMainDisplayWindow.hxx.
TGTextButton * TMainDisplayWindow::fResetButton [private]
Definition at line 42 of file TMainDisplayWindow.hxx.
Referenced by GetResetButton().
TGTextButton * TMainDisplayWindow::fSaveCanvasButton [private]
Definition at line 36 of file TMainDisplayWindow.hxx.
Referenced by PauseResumeButtonAction().
TGTextButton * TMainDisplayWindow::fSavePadButton [private]
Buttons to make plots of current pad/canvas.
Definition at line 35 of file TMainDisplayWindow.hxx.
Referenced by PauseResumeButtonAction().
TGTab * TMainDisplayWindow::fTab [private]
Definition at line 24 of file TMainDisplayWindow.hxx.
Referenced by AddCanvas(), GetCurrentTabName(), GetCurrentTabNumber(), GetEmbeddedCanvas(), GetTab(), ResetSize(), and ~TMainDisplayWindow().
The documentation for this class was generated from the following files:
include/TMainDisplayWindow.hxx
libAnalyzerDisplay/TMainDisplayWindow.hxx
libAnalyzerDisplay/TMainDisplayWindow.cxx