ROOT Analyzer: TRootanaEventLoop Class Reference
TRootanaEventLoop Class Reference
#include <TRootanaEventLoop.hxx>
Public Member Functions
virtual ~TRootanaEventLoop ()
TDataContainer * GetDataContainer ()
Method to get the data container that event loop owns.
virtual bool ProcessMidasEvent (TDataContainer &dataContainer)=0
virtual void Initialize (void)
virtual void BeginRun (int transition, int run, int time)
virtual void EndRun (int transition, int run, int time)
virtual void Finalize ()
virtual void Usage (void)
virtual bool CheckOption (std::string option)
bool IsOnline () const
Are we processing online data?
bool IsOffline () const
Are we processing offline data?
int GetCurrentRunNumber () const
Current Run Number.
void SetCurrentRunNumber (int run)
Current Run Number.
int ExecuteLoop (int argc, char *argv[])
Method to actually process the Midas information, either as file or online.
int ProcessMidasFile (TApplication *app, const char *fname)
void DisableAutoMainWindow ()
Disable automatic creation of MainWindow.
VirtualOdb * GetODB ()
Get pointer to ODB variables.
void OpenRootFile (int run)
Open output ROOT file.
void CloseRootFile ()
Cloe output ROOT file.
void DisableRootOutput (bool disable=true)
virtual ~TRootanaEventLoop ()
TDataContainer * GetDataContainer ()
Method to get the data container that event loop owns.
virtual bool ProcessMidasEvent (TDataContainer &dataContainer)=0
virtual void Initialize (void)
virtual void BeginRun (int transition, int run, int time)
virtual void EndRun (int transition, int run, int time)
virtual void Finalize ()
virtual void Usage (void)
virtual bool CheckOption (std::string option)
bool IsOnline () const
Are we processing online data?
bool IsOffline () const
Are we processing offline data?
int GetCurrentRunNumber () const
Current Run Number.
void SetCurrentRunNumber (int run)
Current Run Number.
int ExecuteLoop (int argc, char *argv[])
Method to actually process the Midas information, either as file or online.
int ProcessMidasFile (TApplication *app, const char *fname)
void DisableAutoMainWindow ()
Disable automatic creation of MainWindow.
VirtualOdb * GetODB ()
Get pointer to ODB variables.
void OpenRootFile (int run)
Open output ROOT file.
void CloseRootFile ()
Cloe output ROOT file.
void DisableRootOutput (bool disable=true)
Static Public Member Functions
static TRootanaEventLoop & Get (void)
template<typename T >
static void CreateSingleton ()
static TRootanaEventLoop & Get (void)
template<typename T >
static void CreateSingleton ()
Protected Member Functions
bool CreateOutputFile (std::string name, std::string options="RECREATE")
TRootanaEventLoop ()
bool CreateOutputFile (std::string name, std::string options="RECREATE")
TRootanaEventLoop ()
Protected Attributes
TDirectory * fOnlineHistDir
TDirectory for online histograms.
Static Protected Attributes
static TRootanaEventLoop * fTRootanaEventLoop = NULL
The static pointer to the singleton instance.
Private Member Functions
void PrintHelp ()
Help Message.
void PrintHelp ()
Help Message.
Private Attributes
TFile * fOutputFile
Output ROOT file.
bool fDisableRootOutput
Variable for disabling/enabling Root output.
VirtualOdb * fODB
Pointer to the ODB access instance.
bool fIsOffline
Are we processing offline or online data?
int fCurrentRunNumber
Current run number.
TDataContainer * fDataContainer
int fMaxEvents
TApplication * fApp
bool fCreateMainWindow
Detailed Description
This is a base class for event loops that are derived from rootana.
The user should create a class that derives from this TRootanaEventLoop class and then fill in the methods that they want to implement.
The user must implement the method ProcessMidasEvent(), which will get executed on each event.
The user can also implement methods like Initialize, BeginRun, EndRun, Finalize if there are actions they want to execute at certain points.
The event loop will work in both offline and online mode (online only if the user has MIDAS installed).
In example of this type of event loop is shown in examples/analyzer_example.cxx
Definition at line 40 of file TRootanaEventLoop.hxx.
Constructor & Destructor Documentation
TRootanaEventLoop::~TRootanaEventLoop () [virtual]
Definition at line 60 of file TRootanaEventLoop.cxx.
References CloseRootFile(), and fODB.
{
  if(fODB) delete fODB;
  CloseRootFile();
}
TRootanaEventLoop::TRootanaEventLoop () [protected]
Create the TApplication
Definition at line 41 of file TRootanaEventLoop.cxx.
References fApp, fCreateMainWindow, fCurrentRunNumber, fDataContainer, fDisableRootOutput, fIsOffline, fMaxEvents, fODB, fOnlineHistDir, and fOutputFile.
{
  fOutputFile = 0;
  fDisableRootOutput = false;
  fODB = 0;
  fOnlineHistDir = 0;
  fMaxEvents = 0;
  fCurrentRunNumber = 0;
  fIsOffline = true;
  fCreateMainWindow = true;
  fDataContainer = new TDataContainer();
  /// Create the TApplication
  char **argv2 = NULL;
  fApp = new TApplication("rootana", 0, argv2);
}
virtual TRootanaEventLoop::~TRootanaEventLoop () [virtual]
TRootanaEventLoop::TRootanaEventLoop () [protected]
Member Function Documentation
virtual void TRootanaEventLoop::BeginRun (int transition, int run, int time) [virtual]
Called before the first event of a file is read, but you should prefer Initialize() for general initialization. This method will be called once for each input file.
Reimplemented in TRootanaDisplay, MyTestLoop, and TRootanaDisplay.
void TRootanaEventLoop::BeginRun (int transition, int run, int time) [virtual]
Called before the first event of a file is read, but you should prefer Initialize() for general initialization. This method will be called once for each input file.
Reimplemented in TRootanaDisplay, MyTestLoop, and TRootanaDisplay.
Definition at line 70 of file TRootanaEventLoop.cxx.
Referenced by ProcessMidasFile().
{};
virtual bool TRootanaEventLoop::CheckOption (std::string option) [virtual]
Check an option and return true if it is valid. The return value is used to flag errors during option handling. If the options are valid, then CheckOption should return true to indicate success. If there is a problem processing the options, then CheckOption should return false. If this returns false, then the event loop will print the Usage message and exit with a non zero value (i.e. indicate failure).
Reimplemented in MyTestLoop.
bool TRootanaEventLoop::CheckOption (std::string option) [virtual]
Check an option and return true if it is valid. The return value is used to flag errors during option handling. If the options are valid, then CheckOption should return true to indicate success. If there is a problem processing the options, then CheckOption should return false. If this returns false, then the event loop will print the Usage message and exit with a non zero value (i.e. indicate failure).
Reimplemented in MyTestLoop.
Definition at line 79 of file TRootanaEventLoop.cxx.
Referenced by ExecuteLoop().
{return false;}
void TRootanaEventLoop::CloseRootFile ()
Cloe output ROOT file.
void TRootanaEventLoop::CloseRootFile ()
Cloe output ROOT file.
Definition at line 342 of file TRootanaEventLoop.cxx.
References fOutputFile.
Referenced by ProcessMidasFile(), and ~TRootanaEventLoop().
{
  std::cout << "Closing ROOT file " << std::endl;
  if(fOutputFile) {
    fOutputFile->Write();
    fOutputFile->Close();
    fOutputFile=0;
  }
}
bool TRootanaEventLoop::CreateOutputFile (std::string name, std::string options = "RECREATE") [inline, protected]
Definition at line 140 of file TRootanaEventLoop.hxx.
References fOutputFile.
{
    fOutputFile = new TFile(name.c_str(),options.c_str());
    return true;
  }
bool TRootanaEventLoop::CreateOutputFile (std::string name, std::string options = "RECREATE") [inline, protected]
Definition at line 140 of file TRootanaEventLoop.hxx.
References fOutputFile.
{
    fOutputFile = new TFile(name.c_str(),options.c_str());
    return true;
  }
template<typename T > static void TRootanaEventLoop::CreateSingleton () [inline, static]
This static templated function will make it a little easier for users to create the singleton instance.
Definition at line 114 of file TRootanaEventLoop.hxx.
References fTRootanaEventLoop.
  {
    if(fTRootanaEventLoop)
      std::cout << "Singleton has already been created" << std::endl;
    else
      fTRootanaEventLoop = new T();
  }
template<typename T > static void TRootanaEventLoop::CreateSingleton () [inline, static]
This static templated function will make it a little easier for users to create the singleton instance.
Definition at line 114 of file TRootanaEventLoop.hxx.
References fTRootanaEventLoop.
  {
    if(fTRootanaEventLoop)
      std::cout << "Singleton has already been created" << std::endl;
    else
      fTRootanaEventLoop = new T();
  }
void TRootanaEventLoop::DisableAutoMainWindow () [inline]
Disable automatic creation of MainWindow.
Definition at line 124 of file TRootanaEventLoop.hxx.
References fCreateMainWindow.
{  fCreateMainWindow = false;}
void TRootanaEventLoop::DisableAutoMainWindow () [inline]
Disable automatic creation of MainWindow.
Definition at line 124 of file TRootanaEventLoop.hxx.
References fCreateMainWindow.
{  fCreateMainWindow = false;}
void TRootanaEventLoop::DisableRootOutput (bool disable = true) [inline]
Definition at line 136 of file TRootanaEventLoop.hxx.
References fDisableRootOutput.
{fDisableRootOutput = disable;};
void TRootanaEventLoop::DisableRootOutput (bool disable = true) [inline]
Definition at line 136 of file TRootanaEventLoop.hxx.
References fDisableRootOutput.
{fDisableRootOutput = disable;};
virtual void TRootanaEventLoop::EndRun (int transition, int run, int time) [virtual]
Called after the last event of a file is read, but you should prefer Finalize() for general finalization. This method will be called once for each input file.
Reimplemented in TRootanaDisplay, MyTestLoop, and TRootanaDisplay.
void TRootanaEventLoop::EndRun (int transition, int run, int time) [virtual]
Called after the last event of a file is read, but you should prefer Finalize() for general finalization. This method will be called once for each input file.
Reimplemented in TRootanaDisplay, MyTestLoop, and TRootanaDisplay.
Definition at line 72 of file TRootanaEventLoop.cxx.
Referenced by ProcessMidasFile().
{};
int TRootanaEventLoop::ExecuteLoop (int argc, char * argv[])
Method to actually process the Midas information, either as file or online.
int TRootanaEventLoop::ExecuteLoop (int argc, char * argv[])
Method to actually process the Midas information, either as file or online.
Definition at line 105 of file TRootanaEventLoop.cxx.
References TDirectory::cd(), CheckOption(), fApp, fCreateMainWindow, Finalize(), fIsOffline, fMaxEvents, fOnlineHistDir, Initialize(), PrintHelp(), ProcessMidasFile(), and StartNetDirectoryServer().
Referenced by main().
{
  setbuf(stdout,NULL);
  setbuf(stderr,NULL);
  signal(SIGILL,  SIG_DFL);
  signal(SIGBUS,  SIG_DFL);
  signal(SIGSEGV, SIG_DFL);
  std::vector<std::string> args;
  for (int i=0; i<argc; i++)
    {
      if (strcmp(argv[i],"-h")==0)
        PrintHelp(); // does not return
      args.push_back(argv[i]);
    }
  if(gROOT->IsBatch()) {
    printf("Cannot run in batch mode\n");
    return 1;
  }
  bool forceEnableGraphics = false;
  bool testMode = false;
  int  tcpPort = 0;
  const char* hostname = NULL;
  const char* exptname = NULL;
  for (unsigned int i=1; i<args.size(); i++) // loop over the commandline options
    {
      const char* arg = args[i].c_str();
      //printf("argv[%d] is %s\n",i,arg);
      if (strncmp(arg,"-e",2)==0)  // Event cutoff flag (only applicable in offline mode)
        fMaxEvents = atoi(arg+2);
      else if (strncmp(arg,"-m",2)==0) // Enable memory debugging
        ;//      gEnableShowMem = true;
      else if (strncmp(arg,"-P",2)==0) // Set the histogram server port
        tcpPort = atoi(arg+2);
      else if (strcmp(arg,"-T")==0)
        testMode = true;
      else if (strcmp(arg,"-g")==0)
        forceEnableGraphics = true;
      else if (strncmp(arg,"-H",2)==0)
        hostname = strdup(arg+2);
      else if (strncmp(arg,"-E",2)==0)
        exptname = strdup(arg+2);
      else if (strcmp(arg,"-h")==0)
        PrintHelp(); // does not return
      else if(arg[0] == '-' && !CheckOption(args[i])) // Chec if a user-defined option
        PrintHelp(); // does not return
    }
  // Do quick check if we are processing online or offline.
  // Want to know before we initialize.
  fIsOffline = false;
  for (unsigned int i=1; i<args.size(); i++){
    const char* arg = args[i].c_str();
    if (arg[0] != '-')
      {
        fIsOffline = true;
      }
  }
  MainWindow *mainWindow=0;
  if(fCreateMainWindow){
    mainWindow = new MainWindow(gClient->GetRoot(), 200, 300);
  }
   gROOT->cd();
   fOnlineHistDir = new TDirectory("rootana", "rootana online plots");
#ifdef HAVE_LIBNETDIRECTORY
   if (tcpPort)
     StartNetDirectoryServer(tcpPort, fOnlineHistDir);
#else
   if (tcpPort)
     fprintf(stderr,"ERROR: No support for the TNetDirectory server!\n");
#endif
   // Initialize the event loop with user initialization.
   Initialize();
   for (unsigned int i=1; i<args.size(); i++){
     const char* arg = args[i].c_str();
     if (arg[0] != '-')
       {
           ProcessMidasFile(fApp,arg);
       }
   }
   if (testMode){
     std::cout << "Entering test mode." << std::endl;
     fOnlineHistDir->cd();
     TH1D* hh = new TH1D("test", "test", 100, 0, 100);
     hh->Fill(1);
     hh->Fill(10);
     hh->Fill(50);
     fApp->Run(kTRUE);
     if(fCreateMainWindow) delete mainWindow;
     return 0;
   }
   // if we processed some data files,
   // do not go into online mode.
   if (fIsOffline){
     if(fCreateMainWindow) delete mainWindow;
     return 0;
   }
#ifdef HAVE_MIDAS
   ProcessMidasOnline(fApp, hostname, exptname);;
#endif
   if(fCreateMainWindow) delete mainWindow;
   Finalize();
   return 0;
}
virtual void TRootanaEventLoop::Finalize () [virtual]
Called after the last event has been processed, but before any open output files are closed.
void TRootanaEventLoop::Finalize () [virtual]
Called after the last event has been processed, but before any open output files are closed.
Definition at line 74 of file TRootanaEventLoop.cxx.
Referenced by ExecuteLoop().
{};
static TRootanaEventLoop& TRootanaEventLoop::Get (void) [static]
TRootanaEventLoop & TRootanaEventLoop::Get (void) [static]
Definition at line 29 of file TRootanaEventLoop.cxx.
References fTRootanaEventLoop.
Referenced by main().
{
  if(!fTRootanaEventLoop){
    std::cerr << "Singleton Not Instantiated! "
              << " Need to call something like SomeClass::CreateSingleton<SomeClass>(); Exiting!"
              <<std::endl; exit(0);
  }
  return *fTRootanaEventLoop;
}
int TRootanaEventLoop::GetCurrentRunNumber () const [inline]
Current Run Number.
Definition at line 96 of file TRootanaEventLoop.hxx.
References fCurrentRunNumber.
{return fCurrentRunNumber;};
int TRootanaEventLoop::GetCurrentRunNumber () const [inline]
Current Run Number.
Definition at line 96 of file TRootanaEventLoop.hxx.
References fCurrentRunNumber.
Referenced by MyTestLoop::ProcessMidasEvent(), and TRootanaDisplay::UpdatePlotsAction().
{return fCurrentRunNumber;};
TDataContainer* TRootanaEventLoop::GetDataContainer () [inline]
Method to get the data container that event loop owns.
Definition at line 49 of file TRootanaEventLoop.hxx.
References fDataContainer.
{return fDataContainer;};
TDataContainer* TRootanaEventLoop::GetDataContainer () [inline]
Method to get the data container that event loop owns.
Definition at line 49 of file TRootanaEventLoop.hxx.
References fDataContainer.
{return fDataContainer;};
VirtualOdb* TRootanaEventLoop::GetODB () [inline]
Get pointer to ODB variables.
Definition at line 127 of file TRootanaEventLoop.hxx.
References fODB.
{return fODB;}
VirtualOdb* TRootanaEventLoop::GetODB () [inline]
Get pointer to ODB variables.
Definition at line 127 of file TRootanaEventLoop.hxx.
References fODB.
{return fODB;}
virtual void TRootanaEventLoop::Initialize (void) [virtual]
Called after the arguments are processes but before reading the first event is read
Reimplemented in TRootanaDisplay, and TRootanaDisplay.
void TRootanaEventLoop::Initialize (void) [virtual]
Called after the arguments are processes but before reading the first event is read
Reimplemented in TRootanaDisplay, and TRootanaDisplay.
Definition at line 68 of file TRootanaEventLoop.cxx.
Referenced by ExecuteLoop().
{};
bool TRootanaEventLoop::IsOffline () const [inline]
Are we processing offline data?
Definition at line 93 of file TRootanaEventLoop.hxx.
References fIsOffline.
{return fIsOffline;};
bool TRootanaEventLoop::IsOffline () const [inline]
Are we processing offline data?
Definition at line 93 of file TRootanaEventLoop.hxx.
References fIsOffline.
Referenced by TRootanaDisplay::InitializeMainWindow().
{return fIsOffline;};
bool TRootanaEventLoop::IsOnline () const [inline]
Are we processing online data?
Definition at line 90 of file TRootanaEventLoop.hxx.
References fIsOffline.
{return !fIsOffline;};
bool TRootanaEventLoop::IsOnline () const [inline]
Are we processing online data?
Definition at line 90 of file TRootanaEventLoop.hxx.
References fIsOffline.
Referenced by TRootanaDisplay::InitializeMainWindow(), TRootanaDisplay::ProcessMidasEvent(), and TRootanaDisplay::UpdatePlotsAction().
{return !fIsOffline;};
void TRootanaEventLoop::OpenRootFile (int run)
Open output ROOT file.
void TRootanaEventLoop::OpenRootFile (int run)
Open output ROOT file.
Definition at line 319 of file TRootanaEventLoop.cxx.
References fDisableRootOutput, fOutputFile, and NetDirectoryExport().
Referenced by ProcessMidasFile().
{
  if(fDisableRootOutput) return;
  if(fOutputFile) {
    fOutputFile->Write();
    fOutputFile->Close();
    fOutputFile=0;
  }
  char filename[1024];
  sprintf(filename, "output%05d.root", run);
  fOutputFile = new TFile(filename,"RECREATE");
  std::cout << "Opened output file with name : " << filename << std::endl;
#ifdef HAVE_LIBNETDIRECTORY
  NetDirectoryExport(fOutputFile, "outputFile");
#endif
}
void TRootanaEventLoop::PrintHelp () [private]
Help Message.
void TRootanaEventLoop::PrintHelp () [private]
Help Message.
Definition at line 82 of file TRootanaEventLoop.cxx.
References Usage().
Referenced by ExecuteLoop().
{
  printf("\nUsage:\n");
  printf("\n./analyzer.exe [-h] [-Hhostname] [-Eexptname] [-eMaxEvents] [-P9091] [-p9090] [-m] [-g] [file1 file2 ...]\n");
  printf("\n");
  printf("\t-h: print this help message\n");
  printf("\t-T: test mode - start and serve a test histogram\n");
  printf("\t-Hhostname: connect to MIDAS experiment on given host\n");
  printf("\t-Eexptname: connect to this MIDAS experiment\n");
  printf("\t-P: Start the TNetDirectory server on specified tcp port (for use with roody -Plocalhost:9091)\n");
  printf("\t-p: Start the old midas histogram server on specified tcp port (for use with roody -Hlocalhost:9090)\n");
  printf("\t-e: Number of events to read from input data files\n");
  //printf("\t-m: Enable memory leak debugging\n");
  printf("\t-g: Enable graphics display when processing data files\n");
  Usage();  // Print description of user options.
  printf("\n");
  printf("Example1: analyze online data: ./analyzer.exe -P9091\n");
  printf("Example2: analyze existing data: ./analyzer.exe /data/alpha/current/run00500.mid\n");
  exit(1);
}
virtual bool TRootanaEventLoop::ProcessMidasEvent (TDataContainer & dataContainer) [pure virtual]
The main method, called for each event. Users must implement this function!
Implemented in TRootanaDisplay, MyTestLoop, and TRootanaDisplay.
virtual bool TRootanaEventLoop::ProcessMidasEvent (TDataContainer & dataContainer) [pure virtual]
The main method, called for each event. Users must implement this function!
Implemented in TRootanaDisplay, MyTestLoop, and TRootanaDisplay.
Referenced by ProcessMidasFile().
int TRootanaEventLoop::ProcessMidasFile (TApplication * app, const char * fname)
int TRootanaEventLoop::ProcessMidasFile (TApplication * app, const char * fname)
Treat the begin run and end run events differently.
Definition at line 232 of file TRootanaEventLoop.cxx.
References BeginRun(), TDataContainer::CleanupEvent(), TMidasFile::Close(), CloseRootFile(), EndRun(), fCurrentRunNumber, fDataContainer, fMaxEvents, fODB, TMidasEvent::GetData(), TMidasEvent::GetSerialNumber(), TMidasFile::Open(), OpenRootFile(), ProcessMidasEvent(), TMidasFile::Read(), and TDataContainer::SetMidasEventPointer().
Referenced by ExecuteLoop().
{
  TMidasFile f;
  bool tryOpen = f.Open(fname);
  if (!tryOpen){
    printf("Cannot open input file \"%s\"\n",fname);
    return -1;
  }
  int i=0;
  while (1)
    {
      TMidasEvent event;
      if (!f.Read(&event))
        break;
      /// Treat the begin run and end run events differently.
      int eventId = event.GetEventId();
      if ((eventId & 0xFFFF) == 0x8000){// begin run event
        event.Print();
        // Load ODB contents from the ODB XML file
        if (fODB) delete fODB;
        fODB = new XmlOdb(event.GetData(),event.GetDataSize());
        fCurrentRunNumber = event.GetSerialNumber();
        OpenRootFile(fCurrentRunNumber);
        BeginRun(0,event.GetSerialNumber(),0);
      } else if ((eventId & 0xFFFF) == 0x8001){// end run event
        event.Print();
        //EndRun(0,fCurrentRunNumber,0);
      } else if ((eventId & 0xFFFF) == 0x8002){
        event.Print();
        printf("Log message: %s\n", event.GetData());
      }else { // all other events
        // Set the bank list for midas event.
        event.SetBankList();
        // Set the midas event pointer in the physics event.
        fDataContainer->SetMidasEventPointer(event);
        //ProcessEvent(event);
        ProcessMidasEvent(*fDataContainer);
        // Cleanup the information for this event.
        fDataContainer->CleanupEvent();
      }
      if((i%500)==0){
        printf("Processing event %d\n",i);
      }
      // Check if we have processed desired number of events.
      i++;
      if ((fMaxEvents!=0)&&(i>=fMaxEvents)){
        printf("Reached event %d, exiting loop.\n",i);
        break;
      }
    }
  f.Close();
  EndRun(0,fCurrentRunNumber,0);
  CloseRootFile();
  // start the ROOT GUI event loop
  //  app->Run(kTRUE);
  return 0;
}
void TRootanaEventLoop::SetCurrentRunNumber (int run) [inline]
Current Run Number.
Definition at line 99 of file TRootanaEventLoop.hxx.
References fCurrentRunNumber.
{fCurrentRunNumber = run;};
void TRootanaEventLoop::SetCurrentRunNumber (int run) [inline]
Current Run Number.
Definition at line 99 of file TRootanaEventLoop.hxx.
References fCurrentRunNumber.
{fCurrentRunNumber = run;};
virtual void TRootanaEventLoop::Usage (void) [virtual]
Called when there is a usage error. This code should print a usage message and then return.
Reimplemented in MyTestLoop.
void TRootanaEventLoop::Usage (void) [virtual]
Called when there is a usage error. This code should print a usage message and then return.
Reimplemented in MyTestLoop.
Definition at line 76 of file TRootanaEventLoop.cxx.
Referenced by PrintHelp().
{};
Member Data Documentation
TApplication * TRootanaEventLoop::fApp [private]
Definition at line 196 of file TRootanaEventLoop.hxx.
Referenced by ExecuteLoop(), and TRootanaEventLoop().
bool TRootanaEventLoop::fCreateMainWindow [private]
Definition at line 199 of file TRootanaEventLoop.hxx.
Referenced by DisableAutoMainWindow(), ExecuteLoop(), and TRootanaEventLoop().
int TRootanaEventLoop::fCurrentRunNumber [private]
Current run number.
Definition at line 176 of file TRootanaEventLoop.hxx.
Referenced by GetCurrentRunNumber(), ProcessMidasFile(), SetCurrentRunNumber(), and TRootanaEventLoop().
TDataContainer * TRootanaEventLoop::fDataContainer [private]
Pointer to the physics event; the physics event is what we pass to user. The midas event is accessible through physics event. We make a single instance of the physics event for whole execution, because sometimes the decoded information needs to persist across multiple midas events.
Definition at line 184 of file TRootanaEventLoop.hxx.
Referenced by GetDataContainer(), ProcessMidasFile(), and TRootanaEventLoop().
bool TRootanaEventLoop::fDisableRootOutput [private]
Variable for disabling/enabling Root output.
Definition at line 167 of file TRootanaEventLoop.hxx.
Referenced by DisableRootOutput(), OpenRootFile(), and TRootanaEventLoop().
bool TRootanaEventLoop::fIsOffline [private]
Are we processing offline or online data?
Definition at line 173 of file TRootanaEventLoop.hxx.
Referenced by ExecuteLoop(), IsOffline(), IsOnline(), and TRootanaEventLoop().
int TRootanaEventLoop::fMaxEvents [private]
Definition at line 193 of file TRootanaEventLoop.hxx.
Referenced by ExecuteLoop(), ProcessMidasFile(), and TRootanaEventLoop().
VirtualOdb * TRootanaEventLoop::fODB [private]
Pointer to the ODB access instance.
Definition at line 170 of file TRootanaEventLoop.hxx.
Referenced by GetODB(), ProcessMidasFile(), TRootanaEventLoop(), and ~TRootanaEventLoop().
TDirectory * TRootanaEventLoop::fOnlineHistDir [protected]
TDirectory for online histograms.
Definition at line 154 of file TRootanaEventLoop.hxx.
Referenced by ExecuteLoop(), MyTestLoop::ProcessMidasEvent(), and TRootanaEventLoop().
TFile * TRootanaEventLoop::fOutputFile [private]
Output ROOT file.
Definition at line 164 of file TRootanaEventLoop.hxx.
Referenced by CloseRootFile(), CreateOutputFile(), OpenRootFile(), and TRootanaEventLoop().
static TRootanaEventLoop * TRootanaEventLoop::fTRootanaEventLoop = NULL [static, protected]
The static pointer to the singleton instance.
Definition at line 151 of file TRootanaEventLoop.hxx.
Referenced by CreateSingleton(), and Get().
The documentation for this class was generated from the following files:
include/TRootanaEventLoop.hxx
libAnalyzer/TRootanaEventLoop.hxx
libAnalyzer/TRootanaEventLoop.cxx