ROOT Analyzer: TMidasEvent Class Reference
TMidasEvent Class Reference
MIDAS event.
#include <TMidasEvent.h>
Public Member Functions
TMidasEvent ()
default constructor
TMidasEvent (const TMidasEvent &)
copy constructor
~TMidasEvent ()
destructor
TMidasEvent & operator= (const TMidasEvent &)
assignement operator
void Clear ()
clear event for reuse
void Copy (const TMidasEvent &)
copy helper
void Print (const char *option="") const
show all event information
uint16_t GetEventId () const
return the event id
uint16_t GetTriggerMask () const
return the triger mask
uint32_t GetSerialNumber () const
return the serial number
uint32_t GetTimeStamp () const
return the time stamp (unix time in seconds)
uint32_t GetDataSize () const
return the event size
const char * GetBankList () const
return a list of data banks
int FindBank (const char *bankName, int *bankLength, int *bankType, void **bankPtr) const
int LocateBank (const void *unused, const char *bankName, void **bankPtr) const
bool IsBank32 () const
returns "true" if event uses 32-bit banks
int IterateBank (TMidas_BANK **, char **pdata) const
iterate through 16-bit data banks
int IterateBank32 (TMidas_BANK32 **, char **pdata) const
iterate through 32-bit data banks
TMidas_EVENT_HEADER * GetEventHeader ()
return pointer to the event header
char * GetData ()
return pointer to the data buffer
void AllocateData ()
allocate data buffer using the existing event header
void SetData (uint32_t dataSize, char *dataBuffer)
set an externally allocated data buffer
int SetBankList ()
create the list of data banks, return number of banks
bool IsGoodSize () const
validate the event length
void SwapBytesEventHeader ()
convert event header between little-endian (Linux-x86) and big endian (MacOS-PPC)
int SwapBytes (bool)
convert event data between little-endian (Linux-x86) and big endian (MacOS-PPC)
TMidasEvent ()
default constructor
TMidasEvent (const TMidasEvent &)
copy constructor
~TMidasEvent ()
destructor
TMidasEvent & operator= (const TMidasEvent &)
assignement operator
void Clear ()
clear event for reuse
void Copy (const TMidasEvent &)
copy helper
void Print (const char *option="") const
show all event information
uint16_t GetEventId () const
return the event id
uint16_t GetTriggerMask () const
return the triger mask
uint32_t GetSerialNumber () const
return the serial number
uint32_t GetTimeStamp () const
return the time stamp (unix time in seconds)
uint32_t GetDataSize () const
return the event size
const char * GetBankList () const
return a list of data banks
int FindBank (const char *bankName, int *bankLength, int *bankType, void **bankPtr) const
int LocateBank (const void *unused, const char *bankName, void **bankPtr) const
bool IsBank32 () const
returns "true" if event uses 32-bit banks
int IterateBank (TMidas_BANK **, char **pdata) const
iterate through 16-bit data banks
int IterateBank32 (TMidas_BANK32 **, char **pdata) const
iterate through 32-bit data banks
TMidas_EVENT_HEADER * GetEventHeader ()
return pointer to the event header
char * GetData ()
return pointer to the data buffer
void AllocateData ()
allocate data buffer using the existing event header
void SetData (uint32_t dataSize, char *dataBuffer)
set an externally allocated data buffer
int SetBankList ()
create the list of data banks, return number of banks
bool IsGoodSize () const
validate the event length
void SwapBytesEventHeader ()
convert event header between little-endian (Linux-x86) and big endian (MacOS-PPC)
int SwapBytes (bool)
convert event data between little-endian (Linux-x86) and big endian (MacOS-PPC)
Protected Attributes
TMidas_EVENT_HEADER fEventHeader
event header
char * fData
event data buffer
int fBanksN
number of banks in this event
char * fBankList
list of bank names in this event
bool fAllocatedByUs
"true" if we own the data buffer
Detailed Description
MIDAS event.
C++ class representing one midas event.
Objects of this class are created by reading midas events from a file, by reading them from a midas shared memory buffer or by receiving them through the mserver
Definition at line 21 of file TMidasEvent.h.
Constructor & Destructor Documentation
TMidasEvent::TMidasEvent ()
default constructor
Definition at line 15 of file TMidasEvent.cxx.
References fAllocatedByUs, fBankList, fBanksN, fData, TMidas_EVENT_HEADER::fDataSize, fEventHeader, TMidas_EVENT_HEADER::fEventId, TMidas_EVENT_HEADER::fSerialNumber, TMidas_EVENT_HEADER::fTimeStamp, and TMidas_EVENT_HEADER::fTriggerMask.
{
  fData = NULL;
  fAllocatedByUs = false;
  fBanksN = 0;
  fBankList = NULL;
  fEventHeader.fEventId      = 0;
  fEventHeader.fTriggerMask  = 0;
  fEventHeader.fSerialNumber = 0;
  fEventHeader.fTimeStamp    = 0;
  fEventHeader.fDataSize     = 0;
}
TMidasEvent::TMidasEvent (const TMidasEvent & rhs)
copy constructor
Definition at line 44 of file TMidasEvent.cxx.
References Copy().
{
  Copy(rhs);
}
TMidasEvent::~TMidasEvent ()
destructor
Definition at line 49 of file TMidasEvent.cxx.
References Clear().
{
  Clear();
}
TMidasEvent::TMidasEvent ()
default constructor
TMidasEvent::TMidasEvent (const TMidasEvent &)
copy constructor
TMidasEvent::~TMidasEvent ()
destructor
Member Function Documentation
void TMidasEvent::AllocateData ()
allocate data buffer using the existing event header
void TMidasEvent::AllocateData ()
allocate data buffer using the existing event header
Definition at line 321 of file TMidasEvent.cxx.
References fAllocatedByUs, fData, TMidas_EVENT_HEADER::fDataSize, fEventHeader, and IsGoodSize().
Referenced by GetData().
{
  assert(!fAllocatedByUs);
  assert(IsGoodSize());
  fData = (char*)malloc(fEventHeader.fDataSize);
  assert(fData);
  fAllocatedByUs = true;
}
void TMidasEvent::Clear ()
clear event for reuse
void TMidasEvent::Clear ()
clear event for reuse
Definition at line 63 of file TMidasEvent.cxx.
References fAllocatedByUs, fBankList, fBanksN, fData, TMidas_EVENT_HEADER::fDataSize, fEventHeader, TMidas_EVENT_HEADER::fEventId, TMidas_EVENT_HEADER::fSerialNumber, TMidas_EVENT_HEADER::fTimeStamp, and TMidas_EVENT_HEADER::fTriggerMask.
Referenced by operator=(), TMidasFile::Read(), and ~TMidasEvent().
{
  if (fBankList)
    free(fBankList);
  fBankList = NULL;
  if (fData && fAllocatedByUs)
    free(fData);
  fData = NULL;
  fAllocatedByUs = false;
  fBanksN = 0;
  fEventHeader.fEventId      = 0;
  fEventHeader.fTriggerMask  = 0;
  fEventHeader.fSerialNumber = 0;
  fEventHeader.fTimeStamp    = 0;
  fEventHeader.fDataSize     = 0;
}
void TMidasEvent::Copy (const TMidasEvent &)
copy helper
void TMidasEvent::Copy (const TMidasEvent & rhs)
copy helper
Definition at line 30 of file TMidasEvent.cxx.
References fAllocatedByUs, fBankList, fBanksN, fData, TMidas_EVENT_HEADER::fDataSize, and fEventHeader.
Referenced by operator=(), and TMidasEvent().
{
  fEventHeader = rhs.fEventHeader;
  fData        = (char*)malloc(fEventHeader.fDataSize);
  assert(fData);
  memcpy(fData, rhs.fData, fEventHeader.fDataSize);
  fAllocatedByUs = true;
  fBanksN      = rhs.fBanksN;
  fBankList    = strdup(rhs.fBankList);
  assert(fBankList);
}
int TMidasEvent::FindBank (const char * bankName, int * bankLength, int * bankType, void ** bankPtr) const
int TMidasEvent::FindBank (const char * bankName, int * bankLength, int * bankType, void ** bankPtr) const
Find a data bank.
Parameters:
[in] name Name of the data bank to look for.
[out] bklen Number of array elements in this bank.
[out] bktype Bank data type (MIDAS TID_xxx).
[out] pdata Pointer to bank data, Returns NULL if bank not found.
Returns:
1 if bank found, 0 otherwise.
Definition at line 160 of file TMidasEvent.cxx.
References fData, TMidas_BANK::fDataSize, TMidas_BANK_HEADER::fDataSize, TMidas_BANK32::fDataSize, TMidas_BANK_HEADER::fFlags, TMidas_BANK::fName, TMidas_BANK32::fName, TMidas_BANK::fType, TMidas_BANK32::fType, IterateBank32(), and TID_SIZE.
Referenced by TDataContainer::GetEventData(), LocateBank(), and Print().
{
  /// Find a data bank.
  /// \param [in] name Name of the data bank to look for.
  /// \param [out] bklen Number of array elements in this bank.
  /// \param [out] bktype Bank data type (MIDAS TID_xxx).
  /// \param [out] pdata Pointer to bank data, Returns NULL if bank not found.
  /// \returns 1 if bank found, 0 otherwise.
  ///
  const TMidas_BANK_HEADER *pbkh = (const TMidas_BANK_HEADER*)fData;
  TMidas_BANK *pbk;
  //uint32_t dname;
  if (((pbkh->fFlags & (1<<4)) > 0)) {
#if 0
    TMidas_BANK32 *pbk32;
    pbk32 = (TMidas_BANK32 *) (pbkh + 1);
    memcpy(&dname, name, 4);
    do {
      if (*((uint32_t *) pbk32->fName) == dname) {
        *pdata = pbk32 + 1;
        if (TID_SIZE[pbk32->fType & 0xFF] == 0)
          *bklen = pbk32->fDataSize;
        else
          *bklen = pbk32->fDataSize / TID_SIZE[pbk32->fType & 0xFF];
        *bktype = pbk32->fType;
        return 1;
      }
      pbk32 = (TMidas_BANK32 *) ((char*) (pbk32 + 1) +
                          (((pbk32->fDataSize)+7) & ~7));
    } while ((char*) pbk32 < (char*) pbkh + pbkh->fDataSize + sizeof(TMidas_BANK_HEADER));
#endif
    TMidas_BANK32 *pbk32 = NULL;
    while (1) {
      IterateBank32(&pbk32, (char**)pdata);
      //printf("looking for [%s] got [%s]\n", name, pbk32->fName);
      if (pbk32 == NULL)
        break;
      if (name[0]==pbk32->fName[0] &&
          name[1]==pbk32->fName[1] &&
          name[2]==pbk32->fName[2] &&
          name[3]==pbk32->fName[3]) {
        if (TID_SIZE[pbk32->fType & 0xFF] == 0)
          *bklen = pbk32->fDataSize;
        else
          *bklen = pbk32->fDataSize / TID_SIZE[pbk32->fType & 0xFF];
        *bktype = pbk32->fType;
        return 1;
      }
    }
  } else {
    pbk = (TMidas_BANK *) (pbkh + 1);
    do {
      if (name[0]==pbk->fName[0] &&
          name[1]==pbk->fName[1] &&
          name[2]==pbk->fName[2] &&
          name[3]==pbk->fName[3]) {
        *pdata = pbk + 1;
        if (TID_SIZE[pbk->fType & 0xFF] == 0)
          *bklen = pbk->fDataSize;
        else
          *bklen = pbk->fDataSize / TID_SIZE[pbk->fType & 0xFF];
        *bktype = pbk->fType;
        return 1;
      }
      pbk = (TMidas_BANK *) ((char*) (pbk + 1) + (((pbk->fDataSize)+7) & ~7));
    } while ((char*) pbk < (char*) pbkh + pbkh->fDataSize + sizeof(TMidas_BANK_HEADER));
  }
  //
  // bank not found
  //
  *pdata = NULL;
  return 0;
}
const char* TMidasEvent::GetBankList () const
return a list of data banks
const char * TMidasEvent::GetBankList () const
return a list of data banks
Definition at line 330 of file TMidasEvent.cxx.
References fBankList.
{
  return fBankList;
}
char* TMidasEvent::GetData ()
return pointer to the data buffer
char * TMidasEvent::GetData ()
return pointer to the data buffer
Definition at line 118 of file TMidasEvent.cxx.
References AllocateData(), and fData.
Referenced by main(), TRootanaEventLoop::ProcessMidasFile(), ProcessMidasFile(), TMidasFile::Read(), and TMidasFile::Write().
{
  if (!fData)
    AllocateData();
  return fData;
}
uint32_t TMidasEvent::GetDataSize () const
return the event size
uint32_t TMidasEvent::GetDataSize () const
return the event size
Definition at line 113 of file TMidasEvent.cxx.
References TMidas_EVENT_HEADER::fDataSize, and fEventHeader.
Referenced by TMidasFile::Read(), and TMidasFile::Write().
{
  return fEventHeader.fDataSize;
}
TMidas_EVENT_HEADER* TMidasEvent::GetEventHeader ()
return pointer to the event header
TMidas_EVENT_HEADER * TMidasEvent::GetEventHeader ()
return pointer to the event header
Definition at line 125 of file TMidasEvent.cxx.
References fEventHeader.
Referenced by eventHandler(), TMidasFile::Read(), and TMidasFile::Write().
{
  return &fEventHeader;
}
uint16_t TMidasEvent::GetEventId () const
return the event id
uint16_t TMidasEvent::GetEventId () const
return the event id
Definition at line 93 of file TMidasEvent.cxx.
References fEventHeader, and TMidas_EVENT_HEADER::fEventId.
{
  return fEventHeader.fEventId;
}
uint32_t TMidasEvent::GetSerialNumber () const
return the serial number
uint32_t TMidasEvent::GetSerialNumber () const
return the serial number
Definition at line 103 of file TMidasEvent.cxx.
References fEventHeader, and TMidas_EVENT_HEADER::fSerialNumber.
Referenced by TRootanaEventLoop::ProcessMidasFile(), ProcessMidasFile(), and TRootanaDisplay::UpdatePlotsAction().
{
  return fEventHeader.fSerialNumber;
}
uint32_t TMidasEvent::GetTimeStamp () const
return the time stamp (unix time in seconds)
uint32_t TMidasEvent::GetTimeStamp () const
return the time stamp (unix time in seconds)
Definition at line 108 of file TMidasEvent.cxx.
References fEventHeader, and TMidas_EVENT_HEADER::fTimeStamp.
{
  return fEventHeader.fTimeStamp;
}
uint16_t TMidasEvent::GetTriggerMask () const
return the triger mask
uint16_t TMidasEvent::GetTriggerMask () const
return the triger mask
Definition at line 98 of file TMidasEvent.cxx.
References fEventHeader, and TMidas_EVENT_HEADER::fTriggerMask.
{
  return fEventHeader.fTriggerMask;
}
bool TMidasEvent::IsBank32 () const
returns "true" if event uses 32-bit banks
bool TMidasEvent::IsBank32 () const
returns "true" if event uses 32-bit banks
Definition at line 135 of file TMidasEvent.cxx.
References fData.
Referenced by SetBankList(), and SwapBytes().
{
  return ((TMidas_BANK_HEADER *)fData)->fFlags & (1<<4);
}
bool TMidasEvent::IsGoodSize () const
validate the event length
bool TMidasEvent::IsGoodSize () const
validate the event length
Definition at line 130 of file TMidasEvent.cxx.
References TMidas_EVENT_HEADER::fDataSize, and fEventHeader.
Referenced by AllocateData(), TMidasFile::Read(), and SetData().
{
  return fEventHeader.fDataSize > 0 && fEventHeader.fDataSize <= 500 * 1024 * 1024;
}
int TMidasEvent::IterateBank (TMidas_BANK ** , char ** pdata) const
iterate through 16-bit data banks
int TMidasEvent::IterateBank (TMidas_BANK ** pbk, char ** pdata) const
iterate through 16-bit data banks
Iterates through banks inside an event. The function can be used to enumerate all banks of an event.
Parameters:
[in] pbk Pointer to the bank header, must be NULL for the first call to this function. Returns NULL if no more banks
[in] pdata Pointer to data area of bank. Returns NULL if no more banks
Returns:
Size of bank in bytes or 0 if no more banks.
Definition at line 382 of file TMidasEvent.cxx.
References fData, and TMidas_BANK::fDataSize.
Referenced by SetBankList().
{
  /// Iterates through banks inside an event. The function can be used
  /// to enumerate all banks of an event.
  /// \param [in] pbk Pointer to the bank header, must be NULL for the
  /// first call to this function. Returns NULL if no more banks
  /// \param [in] pdata Pointer to data area of bank. Returns NULL if no more banks
  /// \returns Size of bank in bytes or 0 if no more banks.
  ///
  const TMidas_BANK_HEADER* event = (const TMidas_BANK_HEADER*)fData;
  if (*pbk == NULL)
    *pbk = (TMidas_BANK *) (event + 1);
  else
    *pbk = (TMidas_BANK *) ((char*) (*pbk + 1) + ((((*pbk)->fDataSize)+7) & ~7));
  *pdata = (char*)((*pbk) + 1);
  if ((char*) *pbk >=  (char*) event + event->fDataSize + sizeof(TMidas_BANK_HEADER))
    {
      *pbk = NULL;
      *pdata = NULL;
      return 0;
    }
  return (*pbk)->fDataSize;
}
int TMidasEvent::IterateBank32 (TMidas_BANK32 ** , char ** pdata) const
iterate through 32-bit data banks
int TMidasEvent::IterateBank32 (TMidas_BANK32 ** pbk, char ** pdata) const
iterate through 32-bit data banks
See IterateBank()
Definition at line 410 of file TMidasEvent.cxx.
References fData, TMidas_BANK32::fDataSize, TMidas_BANK32::fType, and TID_MAX.
Referenced by FindBank(), and SetBankList().
{
  /// See IterateBank()
  const TMidas_BANK_HEADER* event = (const TMidas_BANK_HEADER*)fData;
  if (*pbk == NULL)
    *pbk = (TMidas_BANK32 *) (event + 1);
  else {
    uint32_t length = (*pbk)->fDataSize;
    uint32_t length_adjusted = (length+7) & ~7;
    //printf("length %6d 0x%08x, 0x%08x\n", length, length, length_adjusted);
    *pbk = (TMidas_BANK32 *) ((char*) (*pbk + 1) + length_adjusted);
  }
  TMidas_BANK32 *bk4 = (TMidas_BANK32*)(((char*) *pbk) + 4);
  //printf("iterate bank32: pbk 0x%p, align %d, type %d %d, name [%s], next [%s], TID_MAX %d\n", *pbk, (int)( ((uint64_t)(*pbk))&7), (*pbk)->fType, bk4->fType, (*pbk)->fName, bk4->fName, TID_MAX);
  if ((*pbk)->fType > TID_MAX) // bad - unknown bank type - it's invalid MIDAS file?
    {
      if (bk4->fType <= TID_MAX) // okey, this is a malformed T2K/ND280 data file
        {
          *pbk = bk4;
          //printf("iterate bank32: pbk 0x%p, align %d, type %d, name [%s]\n", *pbk, (int)(((uint64_t)(*pbk))&7), (*pbk)->fType, (*pbk)->fName);
        }
      else
        {
          // truncate invalid data
          *pbk = NULL;
          *pdata = NULL;
          return 0;
        }
    }
  *pdata = (char*)((*pbk) + 1);
  if ((char*) *pbk >= (char*)event  + event->fDataSize + sizeof(TMidas_BANK_HEADER))
    {
      *pbk = NULL;
      *pdata = NULL;
      return 0;
    }
  return (*pbk)->fDataSize;
}
int TMidasEvent::LocateBank (const void * unused, const char * bankName, void ** bankPtr) const
int TMidasEvent::LocateBank (const void * unused, const char * bankName, void ** bankPtr) const
See FindBank()
Definition at line 140 of file TMidasEvent.cxx.
References FindBank().
Referenced by MyTestLoop::ProcessMidasEvent(), and MyTestLoop::UpdateHistograms().
{
  /// See FindBank()
  int bktype, bklen;
  int status = FindBank(name, &bklen, &bktype, pdata);
  if (!status)
    {
      *pdata = NULL;
      return 0;
    }
  return bklen;
}
TMidasEvent& TMidasEvent::operator= (const TMidasEvent &)
assignement operator
TMidasEvent & TMidasEvent::operator= (const TMidasEvent & rhs)
assignement operator
Definition at line 54 of file TMidasEvent.cxx.
References Clear(), and Copy().
{
  if (&rhs != this)
    Clear();
  this->Copy(rhs);
  return *this;
}
void TMidasEvent::Print (const char * option = "") const
show all event information
void TMidasEvent::Print (const char * option = "") const
show all event information
Print data held in this class.
Parameters:
[in] option If 'a' (for "all") then the raw data will be printed out too.
Definition at line 243 of file TMidasEvent.cxx.
References fBankList, fBanksN, TMidas_EVENT_HEADER::fDataSize, fEventHeader, TMidas_EVENT_HEADER::fEventId, FindBank(), TMidas_EVENT_HEADER::fSerialNumber, TMidas_EVENT_HEADER::fTimeStamp, and TMidas_EVENT_HEADER::fTriggerMask.
{
  /// Print data held in this class.
  /// \param [in] option If 'a' (for "all") then the raw data will be
  /// printed out too.
  ///
  time_t t = (time_t)fEventHeader.fTimeStamp;
  printf("Event start:\n");
  printf("  event id:       0x%04x\n", fEventHeader.fEventId);
  printf("  trigger mask:   0x%04x\n", fEventHeader.fTriggerMask);
  printf("  serial number:%8d\n", fEventHeader.fSerialNumber);
  printf("  time stamp:     %d, %s", fEventHeader.fTimeStamp, ctime(&t));
  printf("  data size:    %8d\n", fEventHeader.fDataSize);
  if ((fEventHeader.fEventId & 0xffff) == 0x8000)
    {
      printf("Begin of run %d\n", fEventHeader.fSerialNumber);
    }
  else if ((fEventHeader.fEventId & 0xffff) == 0x8001)
    {
      printf("End of run %d\n", fEventHeader.fSerialNumber);
    }
  else if (fBanksN <= 0)
    {
      printf("TMidasEvent::Print: Use SetBankList() before Print() to print bank data\n");
    }
  else
    {
      printf("Banks: %s\n", fBankList);
      for (int i = 0; i < fBanksN * 4; i += 4)
        {
          int bankLength = 0;
          int bankType = 0;
          void *pdata = 0;
          int found = FindBank(&fBankList[i], &bankLength, &bankType, &pdata);
          printf("Bank %c%c%c%c, length %6d, type %2d\n",
                 fBankList[i], fBankList[i+1], fBankList[i+2], fBankList[i+3],
                 bankLength, bankType);
          if (option[0] == 'a' && found)
            switch (bankType)
              {
              case 4: // TID_WORD
                for (int j = 0; j < bankLength; j++)
                  printf("0x%04x%c", ((uint16_t*)pdata)[j], (j%10==9)?'\n':' ');
                printf("\n");
                break;
              case 6: // TID_DWORD
                for (int j = 0; j < bankLength; j++)
                  printf("0x%08x%c", ((uint32_t*)pdata)[j], (j%10==9)?'\n':' ');
                printf("\n");
                break;
              case 7: // TID_nd280 (like a DWORD?)
                for (int j = 0; j < bankLength; j++)
                  printf("0x%08x%c", ((uint32_t*)pdata)[j], (j%10==9)?'\n':' ');
                printf("\n");
                break;
              case 9: // TID_FLOAT
                for (int j = 0; j < bankLength; j++)
                  printf("%.8g%c", ((float*)pdata)[j], (j%10==9)?'\n':' ');
                printf("\n");
                break;
              case 10: // TID_DOUBLE
                for (int j = 0; j < bankLength; j++)
                  printf("%.16g%c", ((double*)pdata)[j], (j%10==9)?'\n':' ');
                printf("\n");
                break;
              default:
                printf("TMidasEvent::Print: Do not know how to print bank of type %d\n", bankType);
                break;
              }
        }
    }
}
int TMidasEvent::SetBankList ()
create the list of data banks, return number of banks
int TMidasEvent::SetBankList ()
create the list of data banks, return number of banks
Definition at line 335 of file TMidasEvent.cxx.
References fBankList, fBanksN, fEventHeader, TMidas_EVENT_HEADER::fEventId, TMidas_BANK::fName, TMidas_BANK32::fName, IsBank32(), IterateBank(), and IterateBank32().
{
  if (fEventHeader.fEventId <= 0)
    return 0;
  if (fBankList)
    return fBanksN;
  int listSize = 0;
  fBanksN = 0;
  TMidas_BANK32 *pmbk32 = NULL;
  TMidas_BANK *pmbk = NULL;
  char *pdata = NULL;
  while (1)
    {
      if (fBanksN*4 >= listSize)
        {
          listSize += 400;
          fBankList = (char*)realloc(fBankList, listSize);
        }
      if (IsBank32())
        {
          IterateBank32(&pmbk32, &pdata);
          if (pmbk32 == NULL)
            break;
          memcpy(fBankList+fBanksN*4, pmbk32->fName, 4);
          fBanksN++;
        }
      else
        {
          IterateBank(&pmbk, &pdata);
          if (pmbk == NULL)
            break;
          memcpy(fBankList+fBanksN*4, pmbk->fName, 4);
          fBanksN++;
        }
    }
  fBankList[fBanksN*4] = 0;
  return fBanksN;
}
void TMidasEvent::SetData (uint32_t dataSize, char * dataBuffer)
set an externally allocated data buffer
void TMidasEvent::SetData (uint32_t dataSize, char * dataBuffer)
set an externally allocated data buffer
Definition at line 83 of file TMidasEvent.cxx.
References fAllocatedByUs, fData, TMidas_EVENT_HEADER::fDataSize, fEventHeader, IsGoodSize(), and SwapBytes().
{
  fEventHeader.fDataSize = size;
  assert(!fAllocatedByUs);
  assert(IsGoodSize());
  fData = data;
  fAllocatedByUs = false;
  SwapBytes(false);
}
int TMidasEvent::SwapBytes (bool)
convert event data between little-endian (Linux-x86) and big endian (MacOS-PPC)
int TMidasEvent::SwapBytes (bool force)
convert event data between little-endian (Linux-x86) and big endian (MacOS-PPC)
Definition at line 501 of file TMidasEvent.cxx.
References DWORD_SWAP, fData, TMidas_BANK::fDataSize, TMidas_BANK32::fDataSize, TMidas_EVENT_HEADER::fDataSize, TMidas_BANK_HEADER::fDataSize, fEventHeader, TMidas_BANK_HEADER::fFlags, TMidas_BANK::fType, TMidas_BANK32::fType, IsBank32(), QWORD_SWAP, and WORD_SWAP.
Referenced by TMidasFile::Read(), and SetData().
{
  TMidas_BANK_HEADER *pbh;
  TMidas_BANK *pbk;
  TMidas_BANK32 *pbk32;
  void *pdata;
  uint16_t type;
  pbh = (TMidas_BANK_HEADER *) fData;
  uint32_t dssw = pbh->fDataSize;
  DWORD_SWAP(&dssw);
  //printf("SwapBytes %d, flags 0x%x 0x%x\n", force, pbh->fFlags, pbh->fDataSize);
  //printf("evh.datasize: 0x%08x, SwapBytes: %d, pbh.flags: 0x%08x, pbh.datasize: 0x%08x swapped 0x%08x\n", fEventHeader.fDataSize, force, pbh->fFlags, pbh->fDataSize, dssw);
  //
  // only swap if flags in high 16-bit
  //
  if (pbh->fFlags < 0x10000 && ! force)
    return 0;
  if (pbh->fDataSize == 0x6d783f3c) // string "<xml..." in wrong-endian format
    return 1;
  if (pbh->fDataSize == 0x3c3f786d) // string "<xml..."
    return 1;
  if (dssw > fEventHeader.fDataSize + 100) // swapped data size looks wrong. do not swap.
    return 1;
  //
  // swap bank header
  //
  DWORD_SWAP(&pbh->fDataSize);
  DWORD_SWAP(&pbh->fFlags);
  //
  // check for 32-bit banks
  //
  bool b32 = IsBank32();
  pbk = (TMidas_BANK *) (pbh + 1);
  pbk32 = (TMidas_BANK32 *) pbk;
  //
  // scan event
  //
  while ((char*) pbk < (char*) pbh + pbh->fDataSize + sizeof(TMidas_BANK_HEADER)) {
    //
    // swap bank header
    //
    if (b32) {
      DWORD_SWAP(&pbk32->fType);
      DWORD_SWAP(&pbk32->fDataSize);
      pdata = pbk32 + 1;
      type = (uint16_t) pbk32->fType;
    } else {
      WORD_SWAP(&pbk->fType);
      WORD_SWAP(&pbk->fDataSize);
      pdata = pbk + 1;
      type = pbk->fType;
    }
    //
    // pbk points to next bank
    //
    if (b32) {
      assert(pbk32->fDataSize < fEventHeader.fDataSize + 100);
      pbk32 = (TMidas_BANK32 *) ((char*) (pbk32 + 1) +
                          (((pbk32->fDataSize)+7) & ~7));
      pbk = (TMidas_BANK *) pbk32;
    } else {
      assert(pbk->fDataSize < fEventHeader.fDataSize + 100);
      pbk = (TMidas_BANK *) ((char*) (pbk + 1) +  (((pbk->fDataSize)+7) & ~7));
      pbk32 = (TMidas_BANK32 *) pbk;
    }
    switch (type) {
    case 4:
    case 5:
      while (pdata < pbk) {
        WORD_SWAP(pdata);
        pdata = ((char*)pdata) + 2;
      }
      break;
    case 6:
    case 7:
    case 8:
    case 9:
      while (pdata < pbk) {
        DWORD_SWAP(pdata);
        pdata = ((char*)pdata) + 4;
      }
      break;
    case 10:
      while (pdata < pbk) {
        QWORD_SWAP(pdata);
        pdata = ((char*)pdata) + 8;
      }
      break;
    }
  }
  return 1;
}
void TMidasEvent::SwapBytesEventHeader ()
convert event header between little-endian (Linux-x86) and big endian (MacOS-PPC)
void TMidasEvent::SwapBytesEventHeader ()
convert event header between little-endian (Linux-x86) and big endian (MacOS-PPC)
Definition at line 492 of file TMidasEvent.cxx.
References DWORD_SWAP, TMidas_EVENT_HEADER::fDataSize, fEventHeader, TMidas_EVENT_HEADER::fEventId, TMidas_EVENT_HEADER::fSerialNumber, TMidas_EVENT_HEADER::fTimeStamp, TMidas_EVENT_HEADER::fTriggerMask, and WORD_SWAP.
Referenced by TMidasFile::Read().
{
  WORD_SWAP(&fEventHeader.fEventId);
  WORD_SWAP(&fEventHeader.fTriggerMask);
  DWORD_SWAP(&fEventHeader.fSerialNumber);
  DWORD_SWAP(&fEventHeader.fTimeStamp);
  DWORD_SWAP(&fEventHeader.fDataSize);
}
Member Data Documentation
bool TMidasEvent::fAllocatedByUs [protected]
"true" if we own the data buffer
Definition at line 73 of file TMidasEvent.h.
Referenced by AllocateData(), Clear(), Copy(), SetData(), and TMidasEvent().
char * TMidasEvent::fBankList [protected]
list of bank names in this event
Definition at line 72 of file TMidasEvent.h.
Referenced by Clear(), Copy(), GetBankList(), Print(), SetBankList(), and TMidasEvent().
int TMidasEvent::fBanksN [protected]
number of banks in this event
Definition at line 71 of file TMidasEvent.h.
Referenced by Clear(), Copy(), Print(), SetBankList(), and TMidasEvent().
char * TMidasEvent::fData [protected]
event data buffer
Definition at line 70 of file TMidasEvent.h.
Referenced by AllocateData(), Clear(), Copy(), FindBank(), GetData(), IsBank32(), IterateBank(), IterateBank32(), SetData(), SwapBytes(), and TMidasEvent().
TMidas_EVENT_HEADER TMidasEvent::fEventHeader [protected]
event header
Definition at line 69 of file TMidasEvent.h.
Referenced by AllocateData(), Clear(), Copy(), GetDataSize(), GetEventHeader(), GetEventId(), GetSerialNumber(), GetTimeStamp(), GetTriggerMask(), IsGoodSize(), Print(), SetBankList(), SetData(), SwapBytes(), SwapBytesEventHeader(), and TMidasEvent().
The documentation for this class was generated from the following files:
include/TMidasEvent.h
libMidasInterface/TMidasEvent.h
libMidasInterface/TMidasEvent.cxx