ROOT Analyzer: VirtualOdb Struct Reference
VirtualOdb Struct Reference
Interface class for ODB access.
#include <VirtualOdb.h>
Public Member Functions
virtual int odbReadArraySize (const char *name)=0
Read size of an array.
virtual int odbReadAny (const char *name, int index, int tid, void *buf, int bufsize=0)=0
Read value of arbitrary type.
virtual int odbReadInt (const char *name, int index=0, int defaultValue=0)=0
Read an integer value, midas type TID_INT.
virtual uint32_t odbReadUint32 (const char *name, int index=0, uint32_t defaultValue=0)=0
Read an unsigned 32-bit integer value, midas type TID_DWORD.
virtual float odbReadFloat (const char *name, int index=0, float defaultValue=0)=0
Read an 32-bit floating point value, midas type TID_FLOAT.
virtual double odbReadDouble (const char *name, int index=0, double defaultValue=0)=0
Read an 64-bit floating point value, midas type TID_DOUBLET.
virtual bool odbReadBool (const char *name, int index=0, bool defaultValue=false)=0
Read a boolean value, midas type TID_BOOL.
virtual const char * odbReadString (const char *name, int index=0, const char *defaultValue=NULL)=0
Read a string value, midas type TID_STRING.
virtual ~VirtualOdb ()
Destructor has to be virtual.
virtual int odbReadArraySize (const char *name)=0
Read size of an array.
virtual int odbReadAny (const char *name, int index, int tid, void *buf, int bufsize=0)=0
Read value of arbitrary type.
virtual int odbReadInt (const char *name, int index=0, int defaultValue=0)=0
Read an integer value, midas type TID_INT.
virtual uint32_t odbReadUint32 (const char *name, int index=0, uint32_t defaultValue=0)=0
Read an unsigned 32-bit integer value, midas type TID_DWORD.
virtual float odbReadFloat (const char *name, int index=0, float defaultValue=0)=0
Read an 32-bit floating point value, midas type TID_FLOAT.
virtual double odbReadDouble (const char *name, int index=0, double defaultValue=0)=0
Read an 64-bit floating point value, midas type TID_DOUBLET.
virtual bool odbReadBool (const char *name, int index=0, bool defaultValue=false)=0
Read a boolean value, midas type TID_BOOL.
virtual const char * odbReadString (const char *name, int index=0, const char *defaultValue=NULL)=0
Read a string value, midas type TID_STRING.
virtual ~VirtualOdb ()
Destructor has to be virtual.
Detailed Description
Interface class for ODB access.
Definition at line 16 of file VirtualOdb.h.
Constructor & Destructor Documentation
virtual VirtualOdb::~VirtualOdb () [inline, virtual]
Destructor has to be virtual.
Definition at line 37 of file VirtualOdb.h.
{ /* empty */ }; // dtor
virtual VirtualOdb::~VirtualOdb () [inline, virtual]
Destructor has to be virtual.
Definition at line 37 of file VirtualOdb.h.
{ /* empty */ }; // dtor
Member Function Documentation
virtual int VirtualOdb::odbReadAny (const char * name, int index, int tid, void * buf, int bufsize = 0) [pure virtual]
Read value of arbitrary type.
Implemented in HttpOdb, TMidasOnline, XmlOdb, HttpOdb, TMidasOnline, and XmlOdb.
virtual int VirtualOdb::odbReadAny (const char * name, int index, int tid, void * buf, int bufsize = 0) [pure virtual]
Read value of arbitrary type.
Implemented in HttpOdb, TMidasOnline, XmlOdb, HttpOdb, TMidasOnline, and XmlOdb.
virtual int VirtualOdb::odbReadArraySize (const char * name) [pure virtual]
Read size of an array.
Implemented in HttpOdb, TMidasOnline, XmlOdb, HttpOdb, TMidasOnline, and XmlOdb.
virtual int VirtualOdb::odbReadArraySize (const char * name) [pure virtual]
Read size of an array.
Implemented in HttpOdb, TMidasOnline, XmlOdb, HttpOdb, TMidasOnline, and XmlOdb.
Referenced by main().
virtual bool VirtualOdb::odbReadBool (const char * name, int index = 0, bool defaultValue = false) [pure virtual]
Read a boolean value, midas type TID_BOOL.
Implemented in HttpOdb, TMidasOnline, XmlOdb, HttpOdb, TMidasOnline, and XmlOdb.
virtual bool VirtualOdb::odbReadBool (const char * name, int index = 0, bool defaultValue = false) [pure virtual]
Read a boolean value, midas type TID_BOOL.
Implemented in HttpOdb, TMidasOnline, XmlOdb, HttpOdb, TMidasOnline, and XmlOdb.
Referenced by main(), and startRun().
virtual double VirtualOdb::odbReadDouble (const char * name, int index = 0, double defaultValue = 0) [pure virtual]
Read an 64-bit floating point value, midas type TID_DOUBLET.
Implemented in HttpOdb, TMidasOnline, XmlOdb, HttpOdb, TMidasOnline, and XmlOdb.
virtual double VirtualOdb::odbReadDouble (const char * name, int index = 0, double defaultValue = 0) [pure virtual]
Read an 64-bit floating point value, midas type TID_DOUBLET.
Implemented in HttpOdb, TMidasOnline, XmlOdb, HttpOdb, TMidasOnline, and XmlOdb.
Referenced by main().
virtual float VirtualOdb::odbReadFloat (const char * name, int index = 0, float defaultValue = 0) [pure virtual]
Read an 32-bit floating point value, midas type TID_FLOAT.
Implemented in HttpOdb, TMidasOnline, XmlOdb, HttpOdb, TMidasOnline, and XmlOdb.
virtual float VirtualOdb::odbReadFloat (const char * name, int index = 0, float defaultValue = 0) [pure virtual]
Read an 32-bit floating point value, midas type TID_FLOAT.
Implemented in HttpOdb, TMidasOnline, XmlOdb, HttpOdb, TMidasOnline, and XmlOdb.
virtual int VirtualOdb::odbReadInt (const char * name, int index = 0, int defaultValue = 0) [pure virtual]
Read an integer value, midas type TID_INT.
Implemented in HttpOdb, TMidasOnline, XmlOdb, HttpOdb, TMidasOnline, and XmlOdb.
virtual int VirtualOdb::odbReadInt (const char * name, int index = 0, int defaultValue = 0) [pure virtual]
Read an integer value, midas type TID_INT.
Implemented in HttpOdb, TMidasOnline, XmlOdb, HttpOdb, TMidasOnline, and XmlOdb.
Referenced by main().
virtual const char* VirtualOdb::odbReadString (const char * name, int index = 0, const char * defaultValue = NULL) [pure virtual]
Read a string value, midas type TID_STRING.
Implemented in HttpOdb, TMidasOnline, XmlOdb, HttpOdb, TMidasOnline, and XmlOdb.
virtual const char* VirtualOdb::odbReadString (const char * name, int index = 0, const char * defaultValue = NULL) [pure virtual]
Read a string value, midas type TID_STRING.
Implemented in HttpOdb, TMidasOnline, XmlOdb, HttpOdb, TMidasOnline, and XmlOdb.
Referenced by main().
virtual uint32_t VirtualOdb::odbReadUint32 (const char * name, int index = 0, uint32_t defaultValue = 0) [pure virtual]
Read an unsigned 32-bit integer value, midas type TID_DWORD.
Implemented in HttpOdb, TMidasOnline, XmlOdb, HttpOdb, TMidasOnline, and XmlOdb.
virtual uint32_t VirtualOdb::odbReadUint32 (const char * name, int index = 0, uint32_t defaultValue = 0) [pure virtual]
Read an unsigned 32-bit integer value, midas type TID_DWORD.
Implemented in HttpOdb, TMidasOnline, XmlOdb, HttpOdb, TMidasOnline, and XmlOdb.
Referenced by main().
The documentation for this struct was generated from the following files:
include/VirtualOdb.h
libMidasInterface/VirtualOdb.h