ROOT Analyzer: TMidasOnline Class Reference
TMidasOnline Class Reference
MIDAS online connection, including access to online ODB.
#include <TMidasOnline.h>
Public Types
typedef void(* TransitionHandler)(int transition, int run_number, int trans_time)
User handler for run state transition events.
typedef void(* EventHandler)(const void *header, const void *data, int length)
User handler for data events.
typedef void(* TransitionHandler)(int transition, int run_number, int trans_time)
User handler for run state transition events.
typedef void(* EventHandler)(const void *header, const void *data, int length)
User handler for data events.
Public Member Functions
int connect (const char *hostname, const char *exptname, const char *progname)
Connect to MIDAS experiment.
int disconnect ()
Disconnect from MIDAS.
bool poll (int mdelay)
Check for MIDAS events (run transitions, data requests).
void registerTransitions ()
Ask MIDAS to tell us about run transitions.
void setTransitionHandlers (TransitionHandler start, TransitionHandler stop, TransitionHandler pause, TransitionHandler resume)
Specify user handlers for run transitions.
bool checkTransitions ()
Check for pending transitions, call user handlers. Returns "true" if there were transitions.
void setEventHandler (EventHandler handler)
Specify user handler for data events.
int eventRequest (const char *bufferName, int eventId, int triggerMask, int samplingType, bool poll=false)
Request data for delivery via callback (setEventHandler) or by polling (via receiveEvent).
void deleteEventRequest (int requestId)
Delete data request.
int receiveEvent (int requestId, void *pevent, int size, bool async)
Receive event by polling.
int odbReadArraySize (const char *name)
Read size of an array.
int odbReadAny (const char *name, int index, int tid, void *buf, int bufsize=0)
Read value of arbitrary type.
int odbReadInt (const char *name, int index=0, int defaultValue=0)
Read an integer value, midas type TID_INT.
uint32_t odbReadUint32 (const char *name, int index=0, uint32_t defaultValue=0)
Read an unsigned 32-bit integer value, midas type TID_DWORD.
double odbReadDouble (const char *name, int index=0, double defaultValue=0)
Read an 64-bit floating point value, midas type TID_DOUBLET.
float odbReadFloat (const char *name, int index=0, float defaultValue=0)
Read an 32-bit floating point value, midas type TID_FLOAT.
bool odbReadBool (const char *name, int index=0, bool defaultValue=false)
Read a boolean value, midas type TID_BOOL.
const char * odbReadString (const char *name, int index=0, const char *defaultValue=NULL)
Read a string value, midas type TID_STRING.
int connect (const char *hostname, const char *exptname, const char *progname)
Connect to MIDAS experiment.
int disconnect ()
Disconnect from MIDAS.
bool poll (int mdelay)
Check for MIDAS events (run transitions, data requests).
void registerTransitions ()
Ask MIDAS to tell us about run transitions.
void setTransitionHandlers (TransitionHandler start, TransitionHandler stop, TransitionHandler pause, TransitionHandler resume)
Specify user handlers for run transitions.
bool checkTransitions ()
Check for pending transitions, call user handlers. Returns "true" if there were transitions.
void setEventHandler (EventHandler handler)
Specify user handler for data events.
int eventRequest (const char *bufferName, int eventId, int triggerMask, int samplingType, bool poll=false)
Request data for delivery via callback (setEventHandler) or by polling (via receiveEvent).
void deleteEventRequest (int requestId)
Delete data request.
int receiveEvent (int requestId, void *pevent, int size, bool async)
Receive event by polling.
int odbReadArraySize (const char *name)
Read size of an array.
int odbReadAny (const char *name, int index, int tid, void *buf, int bufsize=0)
Read value of arbitrary type.
int odbReadInt (const char *name, int index=0, int defaultValue=0)
Read an integer value, midas type TID_INT.
uint32_t odbReadUint32 (const char *name, int index=0, uint32_t defaultValue=0)
Read an unsigned 32-bit integer value, midas type TID_DWORD.
double odbReadDouble (const char *name, int index=0, double defaultValue=0)
Read an 64-bit floating point value, midas type TID_DOUBLET.
float odbReadFloat (const char *name, int index=0, float defaultValue=0)
Read an 32-bit floating point value, midas type TID_FLOAT.
bool odbReadBool (const char *name, int index=0, bool defaultValue=false)
Read a boolean value, midas type TID_BOOL.
const char * odbReadString (const char *name, int index=0, const char *defaultValue=NULL)
Read a string value, midas type TID_STRING.
Static Public Member Functions
static TMidasOnline * instance ()
static TMidasOnline * instance ()
Public Attributes
std::string fHostname
hostname where the mserver is running, blank if using shared memory
std::string fExptname
experiment name, blank if only one experiment defined in exptab
int fDB
ODB handle.
TransitionHandler fStartHandler
TransitionHandler fStopHandler
TransitionHandler fPauseHandler
TransitionHandler fResumeHandler
EventRequest * fEventRequests
EventHandler fEventHandler
Private Member Functions
TMidasOnline ()
default constructor is private for singleton classes
virtual ~TMidasOnline ()
destructor is private for singleton classes
TMidasOnline ()
default constructor is private for singleton classes
virtual ~TMidasOnline ()
destructor is private for singleton classes
Static Private Attributes
static TMidasOnline * gfMidas = NULL
Detailed Description
MIDAS online connection, including access to online ODB.
Definition at line 36 of file TMidasOnline.h.
Member Typedef Documentation
typedef void(* TMidasOnline::EventHandler)(const void *header, const void *data, int length)
User handler for data events.
Definition at line 44 of file TMidasOnline.h.
typedef void(* TMidasOnline::EventHandler)(const void *header, const void *data, int length)
User handler for data events.
Definition at line 44 of file TMidasOnline.h.
typedef void(* TMidasOnline::TransitionHandler)(int transition, int run_number, int trans_time)
User handler for run state transition events.
Definition at line 41 of file TMidasOnline.h.
typedef void(* TMidasOnline::TransitionHandler)(int transition, int run_number, int trans_time)
User handler for run state transition events.
Definition at line 41 of file TMidasOnline.h.
Constructor & Destructor Documentation
TMidasOnline::TMidasOnline () [private]
default constructor is private for singleton classes
Definition at line 22 of file TMidasOnline.cxx.
References fDB, fEventHandler, fEventRequests, fPauseHandler, fResumeHandler, fStartHandler, and fStopHandler.
Referenced by instance().
{
  fDB = 0;
  fStartHandler  = 0;
  fStopHandler   = 0;
  fPauseHandler  = 0;
  fResumeHandler = 0;
  fEventRequests = 0;
  fEventHandler  = 0;
}
TMidasOnline::~TMidasOnline () [private, virtual]
destructor is private for singleton classes
Definition at line 33 of file TMidasOnline.cxx.
References disconnect().
{
  disconnect();
}
TMidasOnline::TMidasOnline () [private]
default constructor is private for singleton classes
virtual TMidasOnline::~TMidasOnline () [private, virtual]
destructor is private for singleton classes
Member Function Documentation
bool TMidasOnline::checkTransitions ()
Check for pending transitions, call user handlers. Returns "true" if there were transitions.
bool TMidasOnline::checkTransitions ()
Check for pending transitions, call user handlers. Returns "true" if there were transitions.
Definition at line 120 of file TMidasOnline.cxx.
References fPauseHandler, fResumeHandler, fStartHandler, and fStopHandler.
Referenced by poll().
{
  int transition, run_number, trans_time;
  int status = cm_query_transition(&transition, &run_number, &trans_time);
  if (status != CM_SUCCESS)
    return false;
  //printf("cm_query_transition: status %d, tr %d, run %d, time %d\n",status,transition,run_number,trans_time);
  if (transition == TR_START)
    {
      if (fStartHandler)
        (*fStartHandler)(transition,run_number,trans_time);
      return true;
    }
  else if (transition == TR_STOP)
    {
      if (fStopHandler)
        (*fStopHandler)(transition,run_number,trans_time);
      return true;
    }
  else if (transition == TR_PAUSE)
    {
      if (fPauseHandler)
        (*fPauseHandler)(transition,run_number,trans_time);
      return true;
    }
  else if (transition == TR_RESUME)
    {
      if (fResumeHandler)
        (*fResumeHandler)(transition,run_number,trans_time);
      return true;
    }
  return false;
}
int TMidasOnline::connect (const char * hostname, const char * exptname, const char * progname)
Connect to MIDAS experiment.
int TMidasOnline::connect (const char * hostname, const char * exptname, const char * progname)
Connect to MIDAS experiment.
Definition at line 46 of file TMidasOnline.cxx.
References fDB, fExptname, and fHostname.
Referenced by main().
{
  int status;
  char xhostname[HOST_NAME_LENGTH];
  char xexptname[NAME_LENGTH];
  /* get default from environment */
  status = cm_get_environment(xhostname, sizeof(xhostname), xexptname, sizeof(xexptname));
  assert(status == CM_SUCCESS);
  if (hostname)
    strlcpy(xhostname,hostname,sizeof(xhostname));
  if (exptname)
    strlcpy(xexptname,exptname,sizeof(xexptname));
  fHostname = xhostname;
  fExptname = xexptname;
  fprintf(stderr, "TMidasOnline::connect: Connecting to experiment \"%s\" on host \"%s\"\n", fExptname.c_str(), fHostname.c_str());
  //int watchdog = DEFAULT_WATCHDOG_TIMEOUT;
  int watchdog = 60*1000;
  status = cm_connect_experiment1((char*)fHostname.c_str(), (char*)fExptname.c_str(), (char*)progname, NULL, DEFAULT_ODB_SIZE, watchdog);
  if (status == CM_UNDEF_EXP)
    {
      fprintf(stderr, "TMidasOnline::connect: Error: experiment \"%s\" not defined.\n", fExptname.c_str());
      return -1;
    }
  else if (status != CM_SUCCESS)
    {
      fprintf(stderr, "TMidasOnline::connect: Cannot connect to MIDAS, status %d.\n", status);
      return -1;
    }
  status = cm_get_experiment_database(&fDB, NULL);
  assert(status == CM_SUCCESS);
  cm_set_watchdog_params(true, 60*1000);
  return 0;
}
void TMidasOnline::deleteEventRequest (int requestId)
Delete data request.
void TMidasOnline::deleteEventRequest (int requestId)
Delete data request.
Definition at line 285 of file TMidasOnline.cxx.
References fEventRequests, and EventRequest::fNext.
{
  for (EventRequest* r = fEventRequests; r != NULL; r = r->fNext)
    if (r->fRequestId == requestId)
      {
        int status = bm_delete_request(r->fRequestId);
        assert(status == BM_SUCCESS);
        r->fBufferHandle = -1;
        r->fRequestId    = -1;
      }
}
int TMidasOnline::disconnect ()
Disconnect from MIDAS.
int TMidasOnline::disconnect ()
Disconnect from MIDAS.
Definition at line 92 of file TMidasOnline.cxx.
References fDB, fExptname, and fHostname.
Referenced by poll(), and ~TMidasOnline().
{
  if (fDB)
    {
      fprintf(stderr, "TMidasOnline::disconnect: Disconnecting from experiment \"%s\" on host \"%s\"\n", fExptname.c_str(), fHostname.c_str());
      cm_disconnect_experiment();
      fDB = 0;
    }
  return 0;
}
int TMidasOnline::eventRequest (const char * bufferName, int eventId, int triggerMask, int samplingType, bool poll = false)
Request data for delivery via callback (setEventHandler) or by polling (via receiveEvent).
int TMidasOnline::eventRequest (const char * bufferName, int eventId, int triggerMask, int samplingType, bool poll = false)
Request data for delivery via callback (setEventHandler) or by polling (via receiveEvent).
Definition at line 244 of file TMidasOnline.cxx.
References EVENT_BUFFER_SIZE, eventCallback(), EventRequest::fBufferHandle, EventRequest::fBufferName, EventRequest::fEventId, fEventRequests, EventRequest::fNext, EventRequest::fRequestId, EventRequest::fSamplingType, and EventRequest::fTriggerMask.
{
  int status;
  EventRequest* r = new EventRequest();
  if (bufferName == NULL)
    bufferName = EVENT_BUFFER_NAME;
  r->fNext         = NULL;
  r->fBufferName   = bufferName;
  r->fEventId      = eventId;
  r->fTriggerMask  = triggerMask;
  r->fSamplingType = samplingType;
  /*---- open event buffer ---------------------------------------*/
  status = bm_open_buffer((char*)bufferName, EVENT_BUFFER_SIZE, &r->fBufferHandle);
  if (status!=SUCCESS && status!=BM_CREATED)
    {
      fprintf(stderr, "TMidasOnline::eventRequest: Cannot find data buffer \"%s\", bm_open_buffer() error %d\n", bufferName, status);
      return -1;
    }
  /* set the default buffer cache size */
  status = bm_set_cache_size(r->fBufferHandle, 100000, 0);
  assert(status == BM_SUCCESS);
  if (poll)
    status = bm_request_event(r->fBufferHandle, r->fEventId, r->fTriggerMask, r->fSamplingType, &r->fRequestId, NULL);
  else
    status = bm_request_event(r->fBufferHandle, r->fEventId, r->fTriggerMask, r->fSamplingType, &r->fRequestId, eventCallback);
  assert(status == BM_SUCCESS);
  fprintf(stderr, "TMidasOnline::eventRequest: Event request: buffer \"%s\" (%d), event id 0x%x, trigger mask 0x%x, sample %d, request id: %d\n",bufferName,r->fBufferHandle,r->fEventId,r->fTriggerMask,r->fSamplingType,r->fRequestId);
  r->fNext = fEventRequests;
  fEventRequests = r;
  return r->fRequestId;
};
static TMidasOnline* TMidasOnline::instance () [static]
TMidasOnline is a singleton class. Call instance() to get a reference to the one instance of this class.
TMidasOnline * TMidasOnline::instance () [static]
TMidasOnline is a singleton class. Call instance() to get a reference to the one instance of this class.
Definition at line 38 of file TMidasOnline.cxx.
References gfMidas, and TMidasOnline().
Referenced by eventCallback(), and main().
{
  if (!gfMidas)
    gfMidas = new TMidasOnline();
  return gfMidas;
}
int TMidasOnline::odbReadAny (const char * name, int index, int tid, void * buf, int bufsize = 0) [virtual]
Read value of arbitrary type.
Implements VirtualOdb.
int TMidasOnline::odbReadAny (const char * name, int index, int tid, void * buf, int bufsize = 0) [virtual]
Read value of arbitrary type.
Implements VirtualOdb.
Definition at line 371 of file TMidasOnline.cxx.
References fDB.
Referenced by odbReadBool(), odbReadDouble(), odbReadFloat(), odbReadInt(), odbReadString(), and odbReadUint32().
{
  int status;
  int size = bufsize;
  HNDLE hdir = 0;
  HNDLE hkey;
  if (size == 0)
    size = rpc_tid_size(tid);
  status = db_find_key (fDB, hdir, (char*)name, &hkey);
  if (status == SUCCESS)
    {
      status = db_get_data_index(fDB, hkey, buf, &size, index, tid);
      if (status != SUCCESS)
        {
          cm_msg(MERROR, "TMidasOnline", "Cannot read \'%s\'[%d] of type %d from odb, db_get_data_index() status %d", name, index, tid, status);
          return -1;
        }
      return 0;
    }
  else if (status == DB_NO_KEY)
    {
      cm_msg(MINFO, "TMidasOnline", "Creating \'%s\'[%d] of type %d", name, index, tid);
      status = db_create_key(fDB, hdir, (char*)name, tid);
      if (status != SUCCESS)
        {
          cm_msg (MERROR, "TMidasOnline", "Cannot create \'%s\' of type %d, db_create_key() status %d", name, tid, status);
          return -1;
        }
      status = db_find_key (fDB, hdir, (char*)name, &hkey);
      if (status != SUCCESS)
        {
          cm_msg(MERROR, "TMidasOnline", "Cannot create \'%s\', db_find_key() status %d", name, status);
          return -1;
        }
      status = db_set_data_index(fDB, hkey, buf, size, index, tid);
      if (status != SUCCESS)
        {
          cm_msg(MERROR, "TMidasOnline", "Cannot write \'%s\'[%d] of type %d to odb, db_set_data_index() status %d", name, index, tid, status);
          return -1;
        }
      return 0;
    }
  else
    {
      cm_msg(MERROR, "TMidasOnline", "Cannot read \'%s\'[%d] from odb, db_find_key() status %d", name, index, status);
      return -1;
    }
};
int TMidasOnline::odbReadArraySize (const char * name) [virtual]
Read size of an array.
Implements VirtualOdb.
int TMidasOnline::odbReadArraySize (const char * name) [virtual]
Read size of an array.
Implements VirtualOdb.
Definition at line 353 of file TMidasOnline.cxx.
References fDB.
{
  int status;
  HNDLE hdir = 0;
  HNDLE hkey;
  KEY key;
  status = db_find_key (fDB, hdir, (char*)name, &hkey);
  if (status != SUCCESS)
    return 0;
  status = db_get_key(fDB, hkey, &key);
  if (status != SUCCESS)
    return 0;
  return key.num_values;
}
bool TMidasOnline::odbReadBool (const char * name, int index = 0, bool defaultValue = false) [virtual]
Read a boolean value, midas type TID_BOOL.
Implements VirtualOdb.
bool TMidasOnline::odbReadBool (const char * name, int index = 0, bool defaultValue = false) [virtual]
Read a boolean value, midas type TID_BOOL.
Implements VirtualOdb.
Definition at line 316 of file TMidasOnline.cxx.
References odbReadAny().
{
  uint32_t value = defaultValue;
  if (odbReadAny(name,index,TID_BOOL,&value) == 0)
    return value;
  else
    return defaultValue;
};
double TMidasOnline::odbReadDouble (const char * name, int index = 0, double defaultValue = 0) [virtual]
Read an 64-bit floating point value, midas type TID_DOUBLET.
Implements VirtualOdb.
double TMidasOnline::odbReadDouble (const char * name, int index = 0, double defaultValue = 0) [virtual]
Read an 64-bit floating point value, midas type TID_DOUBLET.
Implements VirtualOdb.
Definition at line 334 of file TMidasOnline.cxx.
References odbReadAny().
{
  double value = defaultValue;
  if (odbReadAny(name,index,TID_DOUBLE,&value) == 0)
    return value;
  else
    return defaultValue;
};
float TMidasOnline::odbReadFloat (const char * name, int index = 0, float defaultValue = 0) [virtual]
Read an 32-bit floating point value, midas type TID_FLOAT.
Implements VirtualOdb.
float TMidasOnline::odbReadFloat (const char * name, int index = 0, float defaultValue = 0) [virtual]
Read an 32-bit floating point value, midas type TID_FLOAT.
Implements VirtualOdb.
Definition at line 325 of file TMidasOnline.cxx.
References odbReadAny().
{
  float value = defaultValue;
  if (odbReadAny(name,index,TID_FLOAT,&value) == 0)
    return value;
  else
    return defaultValue;
};
int TMidasOnline::odbReadInt (const char * name, int index = 0, int defaultValue = 0) [virtual]
Read an integer value, midas type TID_INT.
Implements VirtualOdb.
int TMidasOnline::odbReadInt (const char * name, int index = 0, int defaultValue = 0) [virtual]
Read an integer value, midas type TID_INT.
Implements VirtualOdb.
Definition at line 298 of file TMidasOnline.cxx.
References odbReadAny().
{
  int value = defaultValue;
  if (odbReadAny(name,index,TID_INT,&value) == 0)
    return value;
  else
    return defaultValue;
};
const char* TMidasOnline::odbReadString (const char * name, int index = 0, const char * defaultValue = NULL) [virtual]
Read a string value, midas type TID_STRING.
Implements VirtualOdb.
const char * TMidasOnline::odbReadString (const char * name, int index = 0, const char * defaultValue = NULL) [virtual]
Read a string value, midas type TID_STRING.
Implements VirtualOdb.
Definition at line 343 of file TMidasOnline.cxx.
References odbReadAny().
{
  const int bufsize = 1024;
  static char buf[bufsize];
  if (odbReadAny(name, index, TID_STRING, buf, bufsize) == 0)
    return buf;
  else
    return defaultValue;
};
uint32_t TMidasOnline::odbReadUint32 (const char * name, int index = 0, uint32_t defaultValue = 0) [virtual]
Read an unsigned 32-bit integer value, midas type TID_DWORD.
Implements VirtualOdb.
uint32_t TMidasOnline::odbReadUint32 (const char * name, int index = 0, uint32_t defaultValue = 0) [virtual]
Read an unsigned 32-bit integer value, midas type TID_DWORD.
Implements VirtualOdb.
Definition at line 307 of file TMidasOnline.cxx.
References odbReadAny().
{
  uint32_t value = defaultValue;
  if (odbReadAny(name,index,TID_DWORD,&value) == 0)
    return value;
  else
    return defaultValue;
};
bool TMidasOnline::poll (int mdelay)
Check for MIDAS events (run transitions, data requests).
bool TMidasOnline::poll (int mdelay)
Check for MIDAS events (run transitions, data requests).
Definition at line 160 of file TMidasOnline.cxx.
References checkTransitions(), and disconnect().
{
  //printf("poll!\n");
  if (checkTransitions())
    return true;
  int status = cm_yield(mdelay);
  if (status == RPC_SHUTDOWN || status == SS_ABORT)
    {
      fprintf(stderr, "TMidasOnline::poll: cm_yield(%d) status %d, shutting down.\n",mdelay,status);
      disconnect();
      return false;
    }
  return true;
}
int TMidasOnline::receiveEvent (int requestId, void * pevent, int size, bool async)
Receive event by polling.
int TMidasOnline::receiveEvent (int requestId, void * pevent, int size, bool async)
Receive event by polling.
Definition at line 202 of file TMidasOnline.cxx.
References EventRequest::fBufferHandle, fEventRequests, EventRequest::fNext, and EventRequest::fRequestId.
{
  EventRequest* r = fEventRequests;
  while (1)
    {
      if (!r)
        {
          fprintf(stderr, "TMidasOnline::receiveEvent: Cannot find request %d\n", requestId);
          return -1;
        }
      if (r->fRequestId == requestId)
        break;
      r = r->fNext;
    }
  int flag = 0;
  if (async)
    flag = ASYNC;
  int status = bm_receive_event(r->fBufferHandle, pevent, &size, flag);
  if (status == BM_ASYNC_RETURN)
    {
      return 0;
    }
  if (status != BM_SUCCESS)
    {
      fprintf(stderr, "TMidasOnline::receiveEvent: bm_receive_event() error %d\n", status);
      return -1;
    }
  return size;
}
void TMidasOnline::registerTransitions ()
Ask MIDAS to tell us about run transitions.
void TMidasOnline::registerTransitions ()
Ask MIDAS to tell us about run transitions.
Definition at line 104 of file TMidasOnline.cxx.
{
  cm_register_transition(TR_START,  NULL, 300);
  cm_register_transition(TR_PAUSE,  NULL, 700);
  cm_register_transition(TR_RESUME, NULL, 300);
  cm_register_transition(TR_STOP,   NULL, 700);
}
void TMidasOnline::setEventHandler (EventHandler handler)
Specify user handler for data events.
void TMidasOnline::setEventHandler (EventHandler handler)
Specify user handler for data events.
Definition at line 178 of file TMidasOnline.cxx.
References fEventHandler.
{
  fEventHandler  = handler;
}
void TMidasOnline::setTransitionHandlers (TransitionHandler start, TransitionHandler stop, TransitionHandler pause, TransitionHandler resume)
Specify user handlers for run transitions.
void TMidasOnline::setTransitionHandlers (TransitionHandler start, TransitionHandler stop, TransitionHandler pause, TransitionHandler resume)
Specify user handlers for run transitions.
Definition at line 112 of file TMidasOnline.cxx.
References fPauseHandler, fResumeHandler, fStartHandler, and fStopHandler.
{
  fStartHandler  = start;
  fStopHandler   = stop;
  fPauseHandler  = pause;
  fResumeHandler = resume;
}
Member Data Documentation
int TMidasOnline::fDB
ODB handle.
Definition at line 51 of file TMidasOnline.h.
Referenced by connect(), disconnect(), odbReadAny(), odbReadArraySize(), and TMidasOnline().
EventHandler TMidasOnline::fEventHandler
Definition at line 59 of file TMidasOnline.h.
Referenced by eventCallback(), setEventHandler(), and TMidasOnline().
EventRequest * TMidasOnline::fEventRequests
Definition at line 58 of file TMidasOnline.h.
Referenced by deleteEventRequest(), eventRequest(), receiveEvent(), and TMidasOnline().
std::string TMidasOnline::fExptname
experiment name, blank if only one experiment defined in exptab
Definition at line 49 of file TMidasOnline.h.
Referenced by connect(), and disconnect().
std::string TMidasOnline::fHostname
hostname where the mserver is running, blank if using shared memory
Definition at line 48 of file TMidasOnline.h.
Referenced by connect(), and disconnect().
TransitionHandler TMidasOnline::fPauseHandler
Definition at line 55 of file TMidasOnline.h.
Referenced by checkTransitions(), setTransitionHandlers(), and TMidasOnline().
TransitionHandler TMidasOnline::fResumeHandler
Definition at line 56 of file TMidasOnline.h.
Referenced by checkTransitions(), setTransitionHandlers(), and TMidasOnline().
TransitionHandler TMidasOnline::fStartHandler
Definition at line 53 of file TMidasOnline.h.
Referenced by checkTransitions(), setTransitionHandlers(), and TMidasOnline().
TransitionHandler TMidasOnline::fStopHandler
Definition at line 54 of file TMidasOnline.h.
Referenced by checkTransitions(), setTransitionHandlers(), and TMidasOnline().
static TMidasOnline * TMidasOnline::gfMidas = NULL [static, private]
TMidasOnline is a singleton class: only one instance is allowed at any time
Definition at line 64 of file TMidasOnline.h.
Referenced by instance().
The documentation for this class was generated from the following files:
include/TMidasOnline.h
libMidasInterface/TMidasOnline.h
libMidasInterface/TMidasOnline.cxx