ROOT Analyzer: THistogramArrayBase Class Reference
THistogramArrayBase Class Reference
#include <THistogramArrayBase.h>
Public Member Functions
THistogramArrayBase ()
virtual ~THistogramArrayBase ()
virtual void UpdateHistograms (TDataContainer &dataContainer)=0
Update the histograms for this canvas.
TH1 * GetHistogram (unsigned int i)
A helper method for accessing each histogram. Does bounds checking.
virtual void BeginRun (int transition, int run, int time)
Take actions at begin run.
virtual void EndRun (int transition, int run, int time)
Take actions at end run.
THistogramArrayBase ()
virtual ~THistogramArrayBase ()
virtual void UpdateHistograms (TDataContainer &dataContainer)=0
Update the histograms for this canvas.
TH1 * GetHistogram (unsigned int i)
A helper method for accessing each histogram. Does bounds checking.
virtual void BeginRun (int transition, int run, int time)
Take actions at begin run.
virtual void EndRun (int transition, int run, int time)
Take actions at end run.
Detailed Description
Base class for user to create an array of histograms. Features of the histogram array i) Histograms are all defined together. ii) Histograms are updated together
Users of this abstract base class should implement a class derived from must THistogramArrayBase that 1) define the histograms that you want in the constructor. 2) implement the UpdateHistograms(TDataContainer&) method.
The logic of this histogram array is based on it being a set of similar histograms; if you use this class for a set of dissimilar histograms (different binning, different quantities) the results will probably be unsatisfactory. The array'ness is actually implemented as a vector of TH1s.
Definition at line 28 of file THistogramArrayBase.h.
Constructor & Destructor Documentation
THistogramArrayBase::THistogramArrayBase () [inline]
Definition at line 30 of file THistogramArrayBase.h.
{}
virtual THistogramArrayBase::~THistogramArrayBase () [inline, virtual]
Definition at line 31 of file THistogramArrayBase.h.
{}
THistogramArrayBase::THistogramArrayBase () [inline]
Definition at line 30 of file THistogramArrayBase.h.
{}
virtual THistogramArrayBase::~THistogramArrayBase () [inline, virtual]
Definition at line 31 of file THistogramArrayBase.h.
{}
Member Function Documentation
virtual void THistogramArrayBase::BeginRun (int transition, int run, int time) [inline, virtual]
Take actions at begin run.
Definition at line 47 of file THistogramArrayBase.h.
{};
virtual void THistogramArrayBase::BeginRun (int transition, int run, int time) [inline, virtual]
Take actions at begin run.
Definition at line 47 of file THistogramArrayBase.h.
Referenced by TFancyHistogramCanvas::BeginRun().
{};
virtual void THistogramArrayBase::EndRun (int transition, int run, int time) [inline, virtual]
Take actions at end run.
Definition at line 50 of file THistogramArrayBase.h.
{};
virtual void THistogramArrayBase::EndRun (int transition, int run, int time) [inline, virtual]
Take actions at end run.
Definition at line 50 of file THistogramArrayBase.h.
Referenced by TFancyHistogramCanvas::EndRun().
{};
TH1* THistogramArrayBase::GetHistogram (unsigned int i) [inline]
A helper method for accessing each histogram. Does bounds checking.
Definition at line 37 of file THistogramArrayBase.h.
{
    if(i < 0 || i >= size()){
      std::cerr << "Invalid index (=" << i
                << ") requested in THistogramArrayBase::GetHistogram(int i) " << std::endl;
      return 0;
    }
    return (*this)[i];
  }
TH1* THistogramArrayBase::GetHistogram (unsigned int i) [inline]
A helper method for accessing each histogram. Does bounds checking.
Definition at line 37 of file THistogramArrayBase.h.
{
    if(i < 0 || i >= size()){
      std::cerr << "Invalid index (=" << i
                << ") requested in THistogramArrayBase::GetHistogram(int i) " << std::endl;
      return 0;
    }
    return (*this)[i];
  }
virtual void THistogramArrayBase::UpdateHistograms (TDataContainer & dataContainer) [pure virtual]
Update the histograms for this canvas.
virtual void THistogramArrayBase::UpdateHistograms (TDataContainer & dataContainer) [pure virtual]
Update the histograms for this canvas.
Referenced by TFancyHistogramCanvas::UpdateCanvasHistograms().
The documentation for this class was generated from the following files:
include/THistogramArrayBase.h
libAnalyzer/THistogramArrayBase.h