ROOT Analyzer: ServerTimer Class Reference
ServerTimer Class Reference
Public Member Functions
Bool_t Notify ()
Static Public Member Functions
static void StartServerTimer (int period_msec=100)
Static Public Attributes
static ServerTimer * fgTimer
Private Member Functions
~ServerTimer ()
ServerTimer ()
Detailed Description
Definition at line 58 of file RootLock.cxx.
Constructor & Destructor Documentation
ServerTimer::~ServerTimer () [inline, private]
Definition at line 100 of file RootLock.cxx.
  {
    //TurnOff();
  }
ServerTimer::ServerTimer () [inline, private]
Definition at line 105 of file RootLock.cxx.
Referenced by StartServerTimer().
  {
    //int period_msec = 100;
    //Start(period_msec,kTRUE);
  }
Member Function Documentation
Bool_t ServerTimer::Notify () [inline]
Definition at line 73 of file RootLock.cxx.
References gDebugLockRoot, gDoneSema(), gRootSema(), and gWaitSema().
  {
    if (gDebugLockRoot)
      fprintf(stderr, "ServerTimer::Notify!!\n");
    int notWaiting = gWaitSema.TryWait();
    if (gDebugLockRoot)
      printf("NotWaiting %d!\n", notWaiting);
    if (!notWaiting)
      {
        if (gDebugLockRoot)
          printf("Yeld root sema!\n");
        gRootSema.Post();
        TThread::Self()->Sleep(0, 1000000); // sleep in ns
        gDoneSema.Wait();
        if (gDebugLockRoot)
          printf("Recapture root sema!\n");
      }
    Reset();
    return kTRUE;
  }
static void ServerTimer::StartServerTimer (int period_msec = 100) [inline, static]
Definition at line 64 of file RootLock.cxx.
References fgTimer, and ServerTimer().
Referenced by StartLockRootTimer().
  {
    if (!fgTimer)
      {
        fgTimer = new ServerTimer();
        fgTimer->Start(period_msec,kTRUE);
      }
  }
Member Data Documentation
ServerTimer * ServerTimer::fgTimer [static]
Definition at line 62 of file RootLock.cxx.
Referenced by StartServerTimer().
The documentation for this class was generated from the following file:
libNetDirectory/RootLock.cxx