ROOT Analyzer: TNetDirectory Class Reference
TNetDirectory Class Reference
#include <TNetDirectory.h>
Public Types
enum { kCloseDirectory = BIT(7) }
enum { kCloseDirectory = BIT(7) }
Public Member Functions
TNetDirectory (const char *name, TDirectory *motherDir=0)
TNetDirectory (TNetDirectoryConnection *conn, const char *dirname, const std::string &path, TDirectory *motherDir)
virtual ~TNetDirectory ()
int Reconnect ()
void ResetTH1 (const char *name)
virtual void Append (TObject *obj)
virtual void Browse (TBrowser *b)
virtual void Clear (Option_t *option="")
virtual void Close (Option_t *option="")
virtual Bool_t cd (const char *path=0)
virtual void DeleteAll (Option_t *option="")
virtual void Delete (const char *namecycle="")
virtual void Draw (Option_t *option="")
virtual void FillBuffer (char *&buffer)
virtual TKey * FindKey (const char *keyname) const
virtual TKey * FindKeyAny (const char *keyname) const
virtual TObject * FindObject (const char *name) const
virtual TObject * FindObject (const TObject *obj) const
virtual TObject * FindObjectAny (const char *name) const
virtual TObject * Get (const char *namecycle)
virtual TDirectory * GetDirectory (const char *namecycle, Bool_t printError=false, const char *funcname="GetDirectory")
virtual void * GetObjectChecked (const char *namecycle, const char *classname)
virtual void * GetObjectChecked (const char *namecycle, const TClass *cl)
virtual void * GetObjectUnchecked (const char *namecycle)
virtual Int_t GetBufferSize () const
virtual TFile * GetFile () const
virtual TKey * GetKey (const char *name, Short_t cycle=9999) const
virtual TList * GetList () const
virtual TList * GetListOfKeys () const
virtual Int_t GetNbytesKeys () const
virtual Int_t GetNkeys () const
virtual Long64_t GetSeekDir () const
virtual Long64_t GetSeekParent () const
virtual Long64_t GetSeekKeys () const
virtual const char * GetPathStatic () const
virtual const char * GetPath () const
virtual void ls (Option_t *option="") const
virtual TDirectory * mkdir (const char *name, const char *title="")
virtual void Paint (Option_t *option="")
virtual void Print (Option_t *option="") const
virtual void Purge (Short_t nkeep=1)
virtual void pwd () const
virtual void ReadAll (Option_t *option="")
virtual Int_t ReadKeys ()
virtual void RecursiveRemove (TObject *obj)
virtual void rmdir (const char *name)
virtual void Save ()
virtual void SaveSelf (Bool_t force=kFALSE)
virtual void SetBufferSize (Int_t bufsize)
virtual void SetName (const char *newname)
virtual Int_t Sizeof () const
virtual Int_t Write (const char *name=0, Int_t opt=0, Int_t bufsiz=0)
virtual Int_t Write (const char *name=0, Int_t opt=0, Int_t bufsiz=0) const
virtual Int_t WriteTObject (const TObject *obj, const char *name=0, Option_t *option="")
virtual Int_t WriteObjectAny (const void *obj, const char *classname, const char *name, Option_t *option="")
virtual Int_t WriteObjectAny (const void *obj, const TClass *cl, const char *name, Option_t *option="")
virtual void WriteDirHeader ()
virtual void WriteKeys ()
TNetDirectory (const char *name, TDirectory *motherDir=0)
TNetDirectory (TNetDirectoryConnection *conn, const char *dirname, const std::string &path, TDirectory *motherDir)
virtual ~TNetDirectory ()
int Reconnect ()
void ResetTH1 (const char *name)
virtual void Append (TObject *obj)
virtual void Browse (TBrowser *b)
virtual void Clear (Option_t *option="")
virtual void Close (Option_t *option="")
virtual Bool_t cd (const char *path=0)
virtual void DeleteAll (Option_t *option="")
virtual void Delete (const char *namecycle="")
virtual void Draw (Option_t *option="")
virtual void FillBuffer (char *&buffer)
virtual TKey * FindKey (const char *keyname) const
virtual TKey * FindKeyAny (const char *keyname) const
virtual TObject * FindObject (const char *name) const
virtual TObject * FindObject (const TObject *obj) const
virtual TObject * FindObjectAny (const char *name) const
virtual TObject * Get (const char *namecycle)
virtual TDirectory * GetDirectory (const char *namecycle, Bool_t printError=false, const char *funcname="GetDirectory")
virtual void * GetObjectChecked (const char *namecycle, const char *classname)
virtual void * GetObjectChecked (const char *namecycle, const TClass *cl)
virtual void * GetObjectUnchecked (const char *namecycle)
virtual Int_t GetBufferSize () const
virtual TFile * GetFile () const
virtual TKey * GetKey (const char *name, Short_t cycle=9999) const
virtual TList * GetList () const
virtual TList * GetListOfKeys () const
virtual Int_t GetNbytesKeys () const
virtual Int_t GetNkeys () const
virtual Long64_t GetSeekDir () const
virtual Long64_t GetSeekParent () const
virtual Long64_t GetSeekKeys () const
virtual const char * GetPathStatic () const
virtual const char * GetPath () const
virtual void ls (Option_t *option="") const
virtual TDirectory * mkdir (const char *name, const char *title="")
virtual void Paint (Option_t *option="")
virtual void Print (Option_t *option="") const
virtual void Purge (Short_t nkeep=1)
virtual void pwd () const
virtual void ReadAll (Option_t *option="")
virtual Int_t ReadKeys ()
virtual void RecursiveRemove (TObject *obj)
virtual void rmdir (const char *name)
virtual void Save ()
virtual void SaveSelf (Bool_t force=kFALSE)
virtual void SetBufferSize (Int_t bufsize)
virtual void SetName (const char *newname)
virtual Int_t Sizeof () const
virtual Int_t Write (const char *name=0, Int_t opt=0, Int_t bufsiz=0)
virtual Int_t Write (const char *name=0, Int_t opt=0, Int_t bufsiz=0) const
virtual Int_t WriteTObject (const TObject *obj, const char *name=0, Option_t *option="")
virtual Int_t WriteObjectAny (const void *obj, const char *classname, const char *name, Option_t *option="")
virtual Int_t WriteObjectAny (const void *obj, const TClass *cl, const char *name, Option_t *option="")
virtual void WriteDirHeader ()
virtual void WriteKeys ()
void Add (TObject *obj)
void Add (TObject *obj)
Int_t AppendKey (TKey *key)
Int_t AppendKey (TKey *key)
void Build (TFile *motherFile=0, TDirectory *motherDir=0)
void Build (TFile *motherFile=0, TDirectory *motherDir=0)
virtual void Copy (TObject &) const
virtual void Copy (TObject &) const
template<class T >
void GetObject (const char *namecycle, T *&ptr)
template<class T >
void GetObject (const char *namecycle, T *&ptr)
const TDatime & GetCreationDate () const
const TDatime & GetCreationDate () const
const TDatime & GetModificationDate () const
const TDatime & GetModificationDate () const
TObject * GetMother () const
TObject * GetMother () const
TDirectory * GetMotherDir () const
TDirectory * GetMotherDir () const
TUUID GetUUID () const
TUUID GetUUID () const
Bool_t IsFolder () const
Bool_t IsFolder () const
Bool_t IsModified () const
Bool_t IsModified () const
Bool_t IsWritable () const
Bool_t IsWritable () const
void SetModified ()
void SetModified ()
void SetMother (const TObject *mother)
void SetMother (const TObject *mother)
void SetSeekDir (Long64_t v)
void SetSeekDir (Long64_t v)
void SetWritable (Bool_t writable=kTRUE)
void SetWritable (Bool_t writable=kTRUE)
template<class T >
Int_t WriteObject (const T *obj, const char *name, Option_t *option="")
template<class T >
Int_t WriteObject (const T *obj, const char *name, Option_t *option="")
Static Public Member Functions
static Bool_t Cd (const char *path)
static Bool_t Cd (const char *path)
static void DecodeNameCycle (const char *namecycle, char *name, Short_t &cycle)
static void DecodeNameCycle (const char *namecycle, char *name, Short_t &cycle)
static void EncodeNameCycle (char *buffer, const char *name, Short_t cycle)
static void EncodeNameCycle (char *buffer, const char *name, Short_t cycle)
Protected Member Functions
Bool_t cd1 (const char *path)
Buffer for GetPath() function.
Bool_t cd1 (const char *path)
Buffer for GetPath() function.
void FillFullPath (TString &buf) const
void FillFullPath (TString &buf) const
Static Protected Member Functions
static Bool_t Cd1 (const char *path)
static Bool_t Cd1 (const char *path)
Protected Attributes
TNetDirectoryConnection * fConn
std::string fPath
pointer to network connection
std::deque< TNetDirectory * > fSubDirs
Bool_t fModified
Bool_t fWritable
TDatime fDatimeC
TDatime fDatimeM
Int_t fNbytesKeys
Int_t fNbytesName
Int_t fBufferSize
Long64_t fSeekDir
Long64_t fSeekParent
Long64_t fSeekKeys
TFile * fFile
TObject * fMother
TList * fList
TList * fKeys
TUUID fUUID
TString fPathBuffer
Private Member Functions
TNetDirectory (const TNetDirectory &directory)
void operator= (const TNetDirectory &)
TNetDirectory ()
TNetDirectory (const TNetDirectory &directory)
void operator= (const TNetDirectory &)
TNetDirectory ()
Detailed Description
Definition at line 33 of file TNetDirectory.h.
Member Enumeration Documentation
anonymous enum [inherited]
Enumerator:
kCloseDirectory
Definition at line 74 of file TDirectory-example.h.
{ kCloseDirectory = BIT(7) };
anonymous enum [inherited]
Enumerator:
kCloseDirectory
Definition at line 74 of file TDirectory-example.h.
{ kCloseDirectory = BIT(7) };
Constructor & Destructor Documentation
TNetDirectory::TNetDirectory (const TNetDirectory & directory) [private]
TNetDirectory::TNetDirectory () [private]
Referenced by Get().
TNetDirectory::TNetDirectory (const char * name, TDirectory * motherDir = 0)
Definition at line 91 of file TNetDirectory.cxx.
References fConn, fPath, and gVerbose.
  : TDirectory(remoteServerName, remoteServerName, "", motherDir)
{
  if (gVerbose)
    printf("TNetDirectory::ctor: %s\n", remoteServerName);
  int port = 9091;
  char hostname[256];
  strcpy(hostname, remoteServerName);
  char* s = strchr(hostname, ':');
  if (s)
    {
      *s = 0;
      port = atoi(s+1);
    }
  fConn = new TNetDirectoryConnection(hostname, port);
  fPath = "";
}
TNetDirectory::TNetDirectory (TNetDirectoryConnection * conn, const char * dirname, const std::string & path, TDirectory * motherDir)
Definition at line 109 of file TNetDirectory.cxx.
References fConn, fPath, and gVerbose.
  : TDirectory(dirname, dirname, "", motherDir)
{
  if (gVerbose)
    printf("TNetDirectory::ctor: conn %p, path [%s]\n", conn, path.c_str());
  fConn = conn;
  fPath = path;
}
TNetDirectory::~TNetDirectory () [virtual]
Definition at line 118 of file TNetDirectory.cxx.
References fConn, and gVerbose.
{
  if (gVerbose)
    printf("TNetDirectory::dtor\n");
  fConn = NULL;
}
TNetDirectory::TNetDirectory (const TNetDirectory & directory) [private]
TNetDirectory::TNetDirectory () [private]
TNetDirectory::TNetDirectory (const char * name, TDirectory * motherDir = 0)
TNetDirectory::TNetDirectory (TNetDirectoryConnection * conn, const char * dirname, const std::string & path, TDirectory * motherDir)
virtual TNetDirectory::~TNetDirectory () [virtual]
Member Function Documentation
void TDirectory::Add (TObject * obj) [inline, inherited]
Definition at line 114 of file TDirectory-example.h.
References TDirectory::Append().
{ Append(obj); }
void TDirectory::Add (TObject * obj) [inline, inherited]
Definition at line 114 of file TDirectory-example.h.
References TDirectory::Append().
{ Append(obj); }
virtual void TNetDirectory::Append (TObject * obj) [virtual]
Reimplemented from TDirectory.
void TNetDirectory::Append (TObject * obj) [virtual]
Reimplemented from TDirectory.
Definition at line 152 of file TNetDirectory.cxx.
References fPath, and gVerbose.
{
  if (gVerbose)
    printf("TNetDirectory(%s)::Append(%p, name: %s)\n", fPath.c_str(), obj, obj->GetName());
}
Int_t TDirectory::AppendKey (TKey * key) [inherited]
Int_t TDirectory::AppendKey (TKey * key) [inherited]
virtual void TNetDirectory::Browse (TBrowser * b) [virtual]
Reimplemented from TDirectory.
void TNetDirectory::Browse (TBrowser * b) [virtual]
Reimplemented from TDirectory.
Definition at line 158 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
void TDirectory::Build (TFile * motherFile = 0, TDirectory * motherDir = 0) [inherited]
void TDirectory::Build (TFile * motherFile = 0, TDirectory * motherDir = 0) [inherited]
static Bool_t TDirectory::Cd (const char * path) [static, inherited]
static Bool_t TDirectory::Cd (const char * path) [static, inherited]
virtual Bool_t TNetDirectory::cd (const char * path = 0) [virtual]
Reimplemented from TDirectory.
Bool_t TNetDirectory::cd (const char * path = 0) [virtual]
Reimplemented from TDirectory.
Definition at line 161 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
static Bool_t TDirectory::Cd1 (const char * path) [static, protected, inherited]
static Bool_t TDirectory::Cd1 (const char * path) [static, protected, inherited]
Bool_t TDirectory::cd1 (const char * path) [protected, inherited]
Buffer for GetPath() function.
Bool_t TDirectory::cd1 (const char * path) [protected, inherited]
Buffer for GetPath() function.
virtual void TNetDirectory::Clear (Option_t * option = "") [virtual]
Reimplemented from TDirectory.
void TNetDirectory::Clear (Option_t * option = "") [virtual]
Reimplemented from TDirectory.
Definition at line 159 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual void TNetDirectory::Close (Option_t * option = "") [virtual]
Reimplemented from TDirectory.
void TNetDirectory::Close (Option_t * option = "") [virtual]
Reimplemented from TDirectory.
Definition at line 160 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual void TDirectory::Copy (TObject &) const [inline, virtual, inherited]
Definition at line 120 of file TDirectory-example.h.
{ MayNotUse("Copy(TObject &)"); }
virtual void TDirectory::Copy (TObject &) const [inline, virtual, inherited]
Definition at line 120 of file TDirectory-example.h.
{ MayNotUse("Copy(TObject &)"); }
static void TDirectory::DecodeNameCycle (const char * namecycle, char * name, Short_t & cycle) [static, inherited]
static void TDirectory::DecodeNameCycle (const char * namecycle, char * name, Short_t & cycle) [static, inherited]
virtual void TNetDirectory::Delete (const char * namecycle = "") [virtual]
Reimplemented from TDirectory.
void TNetDirectory::Delete (const char * namecycle = "") [virtual]
Reimplemented from TDirectory.
Definition at line 163 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual void TNetDirectory::DeleteAll (Option_t * option = "") [virtual]
Reimplemented from TDirectory.
void TNetDirectory::DeleteAll (Option_t * option = "") [virtual]
Reimplemented from TDirectory.
Definition at line 162 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual void TNetDirectory::Draw (Option_t * option = "") [virtual]
Reimplemented from TDirectory.
void TNetDirectory::Draw (Option_t * option = "") [virtual]
Reimplemented from TDirectory.
Definition at line 164 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
static void TDirectory::EncodeNameCycle (char * buffer, const char * name, Short_t cycle) [static, inherited]
static void TDirectory::EncodeNameCycle (char * buffer, const char * name, Short_t cycle) [static, inherited]
virtual void TNetDirectory::FillBuffer (char *& buffer) [virtual]
Reimplemented from TDirectory.
void TNetDirectory::FillBuffer (char *& buffer) [virtual]
Reimplemented from TDirectory.
Definition at line 165 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
void TDirectory::FillFullPath (TString & buf) const [protected, inherited]
void TDirectory::FillFullPath (TString & buf) const [protected, inherited]
virtual TKey* TNetDirectory::FindKey (const char * keyname) const [virtual]
Reimplemented from TDirectory.
TKey * TNetDirectory::FindKey (const char * keyname) const [virtual]
Reimplemented from TDirectory.
Definition at line 166 of file TNetDirectory.cxx.
{ assert(!"not implemented"); };
virtual TKey* TNetDirectory::FindKeyAny (const char * keyname) const [virtual]
Reimplemented from TDirectory.
TKey * TNetDirectory::FindKeyAny (const char * keyname) const [virtual]
Reimplemented from TDirectory.
Definition at line 167 of file TNetDirectory.cxx.
{ assert(!"not implemented"); };
virtual TObject* TNetDirectory::FindObject (const TObject * obj) const [virtual]
Reimplemented from TDirectory.
virtual TObject* TNetDirectory::FindObject (const char * name) const [virtual]
Reimplemented from TDirectory.
TObject * TNetDirectory::FindObject (const TObject * obj) const [virtual]
Reimplemented from TDirectory.
Definition at line 207 of file TNetDirectory.cxx.
{
  assert(!"not implemented");
}
TObject * TNetDirectory::FindObject (const char * name) const [virtual]
Reimplemented from TDirectory.
Definition at line 169 of file TNetDirectory.cxx.
References fConn, fPath, fSubDirs, gVerbose, TNetDirectoryConnection::ReadObject(), and TNetDirectoryConnection::Request().
{
  if (gVerbose)
    printf("TNetDirectory(%s)::FindObject(%s)\n", fPath.c_str(), name);
  for (unsigned int i=0; i<fSubDirs.size(); i++)
    {
      TNetDirectory *s = fSubDirs[i];
      if (strcmp(name, s->GetName()) == 0)
        {
          //printf("Return subdirectory %p [%s]\n", s, s->GetName());
          return s;
        }
    }
  std::string req = "FindObjectByName ";
  if (fPath.length() > 0)
    {
      req += fPath;
      req += "/";
    }
  req += name;
  fConn->Request(req.c_str());
  TObject *obj = fConn->ReadObject(TObject::Class());
  if (obj && strcmp(obj->IsA()->GetName(), "TObjString") == 0)
    {
      const char* s = ((TObjString*)obj)->GetName();
      if (strncmp(s, "TDirectory ", 11) == 0)
        {
          return NULL;
        }
    }
  return obj;
}
virtual TObject* TNetDirectory::FindObjectAny (const char * name) const [virtual]
Reimplemented from TDirectory.
TObject * TNetDirectory::FindObjectAny (const char * name) const [virtual]
Reimplemented from TDirectory.
Definition at line 212 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual TObject* TNetDirectory::Get (const char * namecycle) [virtual]
Reimplemented from TDirectory.
TObject * TNetDirectory::Get (const char * namecycle) [virtual]
Reimplemented from TDirectory.
Definition at line 214 of file TNetDirectory.cxx.
References fConn, fPath, fSubDirs, gVerbose, TNetDirectoryConnection::ReadObject(), TNetDirectoryConnection::Request(), and TNetDirectory().
{
  if (gVerbose)
    printf("TNetDirectory(%s)::Get(%s)\n", fPath.c_str(), namecycle);
  std::string req = "FindObjectByName "; // "Get ";
  if (fPath.length() > 0)
    {
      req += fPath;
      req += "/";
    }
  req += namecycle;
  fConn->Request(req.c_str());
  TObject *obj = fConn->ReadObject(TObject::Class());
  if (obj && strcmp(obj->IsA()->GetName(), "TObjString") == 0)
    {
      const char* s = ((TObjString*)obj)->GetName();
      if (strncmp(s, "TDirectory ", 11) == 0)
        {
          const char* dirname = s+11;
          if (gVerbose)
            printf("Got TDirectory %s\n", dirname);
          TNetDirectory *s = new TNetDirectory(fConn, dirname, fPath + "/" + dirname, this);
          fSubDirs.push_back(s);
          return s;
        }
    }
  return obj;
}
virtual Int_t TNetDirectory::GetBufferSize () const [virtual]
Reimplemented from TDirectory.
Int_t TNetDirectory::GetBufferSize () const [virtual]
Reimplemented from TDirectory.
Definition at line 251 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
const TDatime& TDirectory::GetCreationDate () const [inline, inherited]
Definition at line 141 of file TDirectory-example.h.
References TDirectory::fDatimeC.
{ return fDatimeC; }
const TDatime& TDirectory::GetCreationDate () const [inline, inherited]
Definition at line 141 of file TDirectory-example.h.
References TDirectory::fDatimeC.
{ return fDatimeC; }
virtual TDirectory* TNetDirectory::GetDirectory (const char * namecycle, Bool_t printError = false, const char * funcname = "GetDirectory") [virtual]
Reimplemented from TDirectory.
TDirectory * TNetDirectory::GetDirectory (const char * namecycle, Bool_t printError = false, const char * funcname = "GetDirectory") [virtual]
Reimplemented from TDirectory.
Definition at line 247 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual TFile* TNetDirectory::GetFile () const [virtual]
Reimplemented from TDirectory.
TFile * TNetDirectory::GetFile () const [virtual]
Reimplemented from TDirectory.
Definition at line 252 of file TNetDirectory.cxx.
{ return NULL; assert(!"not implemented"); return NULL; }
virtual TKey* TNetDirectory::GetKey (const char * name, Short_t cycle = 9999) const [virtual]
Reimplemented from TDirectory.
TKey * TNetDirectory::GetKey (const char * name, Short_t cycle = 9999) const [virtual]
Reimplemented from TDirectory.
Definition at line 253 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual TList* TNetDirectory::GetList () const [virtual]
Reimplemented from TDirectory.
TList * TNetDirectory::GetList () const [virtual]
Reimplemented from TDirectory.
Definition at line 254 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual TList* TNetDirectory::GetListOfKeys () const [virtual]
Reimplemented from TDirectory.
TList * TNetDirectory::GetListOfKeys () const [virtual]
Reimplemented from TDirectory.
Definition at line 256 of file TNetDirectory.cxx.
References fConn, fPath, gVerbose, TNetDirectoryConnection::ReadObject(), and TNetDirectoryConnection::Request().
{
  if (gVerbose)
    printf("TNetDirectory(%s)::GetListOfKeys()\n", fPath.c_str());
  std::string req = "GetListOfKeys";
  if (fPath.length() > 0)
    {
      req += " ";
      req += fPath;
    }
  fConn->Request(req.c_str());
  TList *keys = (TList*)fConn->ReadObject(TList::Class());
  if (keys == NULL)
    //    return fKeys;
    return NULL;
  //keys->Print();
  //keys->ls();
  return keys;
}
const TDatime& TDirectory::GetModificationDate () const [inline, inherited]
Definition at line 146 of file TDirectory-example.h.
References TDirectory::fDatimeM.
{ return fDatimeM; }
const TDatime& TDirectory::GetModificationDate () const [inline, inherited]
Definition at line 146 of file TDirectory-example.h.
References TDirectory::fDatimeM.
{ return fDatimeM; }
TObject* TDirectory::GetMother () const [inline, inherited]
Definition at line 147 of file TDirectory-example.h.
References TDirectory::fMother.
{ return fMother; }
TObject* TDirectory::GetMother () const [inline, inherited]
Definition at line 147 of file TDirectory-example.h.
References TDirectory::fMother.
{ return fMother; }
TDirectory* TDirectory::GetMotherDir () const [inline, inherited]
Definition at line 148 of file TDirectory-example.h.
References TDirectory::fMother.
{ return fMother==0 ? 0 : dynamic_cast<TDirectory*>(fMother); }
TDirectory* TDirectory::GetMotherDir () const [inline, inherited]
Definition at line 148 of file TDirectory-example.h.
References TDirectory::fMother.
{ return fMother==0 ? 0 : dynamic_cast<TDirectory*>(fMother); }
virtual Int_t TNetDirectory::GetNbytesKeys () const [virtual]
Reimplemented from TDirectory.
Int_t TNetDirectory::GetNbytesKeys () const [virtual]
Reimplemented from TDirectory.
Definition at line 278 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual Int_t TNetDirectory::GetNkeys () const [virtual]
Reimplemented from TDirectory.
Int_t TNetDirectory::GetNkeys () const [virtual]
Reimplemented from TDirectory.
Definition at line 279 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
template<class T > void TDirectory::GetObject (const char * namecycle, T *& ptr) [inline, inherited]
Definition at line 133 of file TDirectory-example.h.
References TDirectory::GetObjectChecked().
      {
         ptr = (T*)GetObjectChecked(namecycle,TBuffer::GetClass(typeid(T)));
      }
template<class T > void TDirectory::GetObject (const char * namecycle, T *& ptr) [inline, inherited]
Definition at line 133 of file TDirectory-example.h.
References TDirectory::GetObjectChecked().
      {
         ptr = (T*)GetObjectChecked(namecycle,TBuffer::GetClass(typeid(T)));
      }
virtual void* TNetDirectory::GetObjectChecked (const char * namecycle, const TClass * cl) [virtual]
Reimplemented from TDirectory.
virtual void* TNetDirectory::GetObjectChecked (const char * namecycle, const char * classname) [virtual]
Reimplemented from TDirectory.
void * TNetDirectory::GetObjectChecked (const char * namecycle, const TClass * cl) [virtual]
Reimplemented from TDirectory.
Definition at line 249 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
void * TNetDirectory::GetObjectChecked (const char * namecycle, const char * classname) [virtual]
Reimplemented from TDirectory.
Definition at line 248 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual void* TNetDirectory::GetObjectUnchecked (const char * namecycle) [virtual]
Reimplemented from TDirectory.
void * TNetDirectory::GetObjectUnchecked (const char * namecycle) [virtual]
Reimplemented from TDirectory.
Definition at line 250 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual const char* TNetDirectory::GetPath () const [virtual]
Reimplemented from TDirectory.
const char * TNetDirectory::GetPath () const [virtual]
Reimplemented from TDirectory.
Definition at line 284 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual const char* TNetDirectory::GetPathStatic () const [virtual]
Reimplemented from TDirectory.
const char * TNetDirectory::GetPathStatic () const [virtual]
Reimplemented from TDirectory.
Definition at line 283 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual Long64_t TNetDirectory::GetSeekDir () const [virtual]
Reimplemented from TDirectory.
Long64_t TNetDirectory::GetSeekDir () const [virtual]
Reimplemented from TDirectory.
Definition at line 280 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual Long64_t TNetDirectory::GetSeekKeys () const [virtual]
Reimplemented from TDirectory.
Long64_t TNetDirectory::GetSeekKeys () const [virtual]
Reimplemented from TDirectory.
Definition at line 282 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual Long64_t TNetDirectory::GetSeekParent () const [virtual]
Reimplemented from TDirectory.
Long64_t TNetDirectory::GetSeekParent () const [virtual]
Reimplemented from TDirectory.
Definition at line 281 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
TUUID TDirectory::GetUUID () const [inline, inherited]
Definition at line 156 of file TDirectory-example.h.
References TDirectory::fUUID.
{return fUUID;}
TUUID TDirectory::GetUUID () const [inline, inherited]
Definition at line 156 of file TDirectory-example.h.
References TDirectory::fUUID.
{return fUUID;}
Bool_t TDirectory::IsFolder () const [inline, inherited]
Definition at line 157 of file TDirectory-example.h.
{ return kTRUE; }
Bool_t TDirectory::IsFolder () const [inline, inherited]
Definition at line 157 of file TDirectory-example.h.
{ return kTRUE; }
Bool_t TDirectory::IsModified () const [inline, inherited]
Definition at line 158 of file TDirectory-example.h.
References TDirectory::fModified.
{ return fModified; }
Bool_t TDirectory::IsModified () const [inline, inherited]
Definition at line 158 of file TDirectory-example.h.
References TDirectory::fModified.
{ return fModified; }
Bool_t TDirectory::IsWritable () const [inline, inherited]
Definition at line 159 of file TDirectory-example.h.
References TDirectory::fWritable.
{ return fWritable; }
Bool_t TDirectory::IsWritable () const [inline, inherited]
Definition at line 159 of file TDirectory-example.h.
References TDirectory::fWritable.
{ return fWritable; }
virtual void TNetDirectory::ls (Option_t * option = "") const [virtual]
Reimplemented from TDirectory.
void TNetDirectory::ls (Option_t * option = "") const [virtual]
Reimplemented from TDirectory.
Definition at line 285 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual TDirectory* TNetDirectory::mkdir (const char * name, const char * title = "") [virtual]
Reimplemented from TDirectory.
TDirectory * TNetDirectory::mkdir (const char * name, const char * title = "") [virtual]
Reimplemented from TDirectory.
Definition at line 286 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
void TNetDirectory::operator= (const TNetDirectory &) [private]
Reimplemented from TDirectory.
void TNetDirectory::operator= (const TNetDirectory &) [private]
Reimplemented from TDirectory.
virtual void TNetDirectory::Paint (Option_t * option = "") [virtual]
Reimplemented from TDirectory.
void TNetDirectory::Paint (Option_t * option = "") [virtual]
Reimplemented from TDirectory.
Definition at line 287 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual void TNetDirectory::Print (Option_t * option = "") const [virtual]
Reimplemented from TDirectory.
void TNetDirectory::Print (Option_t * option = "") const [virtual]
Reimplemented from TDirectory.
Definition at line 289 of file TNetDirectory.cxx.
{
  TDirectory::Print(option);
}
virtual void TNetDirectory::Purge (Short_t nkeep = 1) [virtual]
Reimplemented from TDirectory.
void TNetDirectory::Purge (Short_t nkeep = 1) [virtual]
Reimplemented from TDirectory.
Definition at line 294 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual void TNetDirectory::pwd () const [virtual]
Reimplemented from TDirectory.
void TNetDirectory::pwd () const [virtual]
Reimplemented from TDirectory.
Definition at line 295 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual void TNetDirectory::ReadAll (Option_t * option = "") [virtual]
Reimplemented from TDirectory.
void TNetDirectory::ReadAll (Option_t * option = "") [virtual]
Reimplemented from TDirectory.
Definition at line 296 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual Int_t TNetDirectory::ReadKeys () [virtual]
Reimplemented from TDirectory.
Int_t TNetDirectory::ReadKeys () [virtual]
Reimplemented from TDirectory.
Definition at line 297 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
int TNetDirectory::Reconnect ()
int TNetDirectory::Reconnect ()
Definition at line 125 of file TNetDirectory.cxx.
References fConn, and TNetDirectoryConnection::Reconnect().
{
  return fConn->Reconnect();
}
virtual void TNetDirectory::RecursiveRemove (TObject * obj) [virtual]
Reimplemented from TDirectory.
void TNetDirectory::RecursiveRemove (TObject * obj) [virtual]
Reimplemented from TDirectory.
Definition at line 298 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
void TNetDirectory::ResetTH1 (const char * name)
void TNetDirectory::ResetTH1 (const char * name)
Definition at line 130 of file TNetDirectory.cxx.
References fConn, fPath, gVerbose, TNetDirectoryConnection::ReadObject(), and TNetDirectoryConnection::Request().
{
  if (gVerbose)
    printf("TNetDirectory(%s)::ResetTH1(%s)\n", fPath.c_str(), name);
  std::string req = "ResetTH1 ";
  if (fPath.length() > 0)
    {
      req += fPath;
      req += "/";
    }
  if (name && strlen(name)>0)
    {
      req += name;
    }
  fConn->Request(req.c_str());
  TObject *obj = fConn->ReadObject(TObject::Class());
  delete obj;
}
virtual void TNetDirectory::rmdir (const char * name) [virtual]
Reimplemented from TDirectory.
void TNetDirectory::rmdir (const char * name) [virtual]
Reimplemented from TDirectory.
Definition at line 299 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual void TNetDirectory::Save () [virtual]
Reimplemented from TDirectory.
void TNetDirectory::Save () [virtual]
Reimplemented from TDirectory.
Definition at line 300 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual void TNetDirectory::SaveSelf (Bool_t force = kFALSE) [virtual]
Reimplemented from TDirectory.
void TNetDirectory::SaveSelf (Bool_t force = kFALSE) [virtual]
Reimplemented from TDirectory.
Definition at line 301 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual void TNetDirectory::SetBufferSize (Int_t bufsize) [virtual]
Reimplemented from TDirectory.
void TNetDirectory::SetBufferSize (Int_t bufsize) [virtual]
Reimplemented from TDirectory.
Definition at line 302 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
void TDirectory::SetModified () [inline, inherited]
Definition at line 173 of file TDirectory-example.h.
References TDirectory::fModified.
{fModified = kTRUE;}
void TDirectory::SetModified () [inline, inherited]
Definition at line 173 of file TDirectory-example.h.
References TDirectory::fModified.
{fModified = kTRUE;}
void TDirectory::SetMother (const TObject * mother) [inline, inherited]
Definition at line 174 of file TDirectory-example.h.
References TDirectory::fMother.
{fMother = (TObject*)mother;}
void TDirectory::SetMother (const TObject * mother) [inline, inherited]
Definition at line 174 of file TDirectory-example.h.
References TDirectory::fMother.
{fMother = (TObject*)mother;}
virtual void TNetDirectory::SetName (const char * newname) [virtual]
Reimplemented from TDirectory.
void TNetDirectory::SetName (const char * newname) [virtual]
Reimplemented from TDirectory.
Definition at line 303 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
void TDirectory::SetSeekDir (Long64_t v) [inline, inherited]
Definition at line 176 of file TDirectory-example.h.
References TDirectory::fSeekDir.
{ fSeekDir = v; }
void TDirectory::SetSeekDir (Long64_t v) [inline, inherited]
Definition at line 176 of file TDirectory-example.h.
References TDirectory::fSeekDir.
{ fSeekDir = v; }
void TDirectory::SetWritable (Bool_t writable = kTRUE) [inherited]
void TDirectory::SetWritable (Bool_t writable = kTRUE) [inherited]
virtual Int_t TNetDirectory::Sizeof () const [virtual]
Reimplemented from TDirectory.
Int_t TNetDirectory::Sizeof () const [virtual]
Reimplemented from TDirectory.
Definition at line 304 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual Int_t TNetDirectory::Write (const char * name = 0, Int_t opt = 0, Int_t bufsiz = 0) const [virtual]
Reimplemented from TDirectory.
virtual Int_t TNetDirectory::Write (const char * name = 0, Int_t opt = 0, Int_t bufsiz = 0) [virtual]
Reimplemented from TDirectory.
Int_t TNetDirectory::Write (const char * name = 0, Int_t opt = 0, Int_t bufsiz = 0) const [virtual]
Reimplemented from TDirectory.
Definition at line 306 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
Int_t TNetDirectory::Write (const char * name = 0, Int_t opt = 0, Int_t bufsiz = 0) [virtual]
Reimplemented from TDirectory.
Definition at line 305 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual void TNetDirectory::WriteDirHeader () [virtual]
Reimplemented from TDirectory.
void TNetDirectory::WriteDirHeader () [virtual]
Reimplemented from TDirectory.
Definition at line 310 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual void TNetDirectory::WriteKeys () [virtual]
Reimplemented from TDirectory.
void TNetDirectory::WriteKeys () [virtual]
Reimplemented from TDirectory.
Definition at line 311 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
template<class T > Int_t TDirectory::WriteObject (const T * obj, const char * name, Option_t * option = "") [inline, inherited]
Definition at line 182 of file TDirectory-example.h.
References TDirectory::WriteObjectAny().
      {
         return WriteObjectAny(obj,TBuffer::GetClass(typeid(T)),name,option);
      }
template<class T > Int_t TDirectory::WriteObject (const T * obj, const char * name, Option_t * option = "") [inline, inherited]
Definition at line 182 of file TDirectory-example.h.
References TDirectory::WriteObjectAny().
      {
         return WriteObjectAny(obj,TBuffer::GetClass(typeid(T)),name,option);
      }
virtual Int_t TNetDirectory::WriteObjectAny (const void * obj, const TClass * cl, const char * name, Option_t * option = "") [virtual]
Reimplemented from TDirectory.
virtual Int_t TNetDirectory::WriteObjectAny (const void * obj, const char * classname, const char * name, Option_t * option = "") [virtual]
Reimplemented from TDirectory.
Int_t TNetDirectory::WriteObjectAny (const void * obj, const TClass * cl, const char * name, Option_t * option = "") [virtual]
Reimplemented from TDirectory.
Definition at line 309 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
Int_t TNetDirectory::WriteObjectAny (const void * obj, const char * classname, const char * name, Option_t * option = "") [virtual]
Reimplemented from TDirectory.
Definition at line 308 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
virtual Int_t TNetDirectory::WriteTObject (const TObject * obj, const char * name = 0, Option_t * option = "") [virtual]
Reimplemented from TDirectory.
Int_t TNetDirectory::WriteTObject (const TObject * obj, const char * name = 0, Option_t * option = "") [virtual]
Reimplemented from TDirectory.
Definition at line 307 of file TNetDirectory.cxx.
{ assert(!"not implemented"); }
Member Data Documentation
Int_t TDirectory::fBufferSize [protected, inherited]
Definition at line 52 of file TDirectory-example.h.
TNetDirectoryConnection * TNetDirectory::fConn [protected]
Definition at line 36 of file TNetDirectory.h.
Referenced by FindObject(), Get(), GetListOfKeys(), Reconnect(), ResetTH1(), TNetDirectory(), and ~TNetDirectory().
TDatime TDirectory::fDatimeC [protected, inherited]
Definition at line 48 of file TDirectory-example.h.
Referenced by TDirectory::GetCreationDate().
TDatime TDirectory::fDatimeM [protected, inherited]
Definition at line 49 of file TDirectory-example.h.
Referenced by TDirectory::GetModificationDate().
TFile * TDirectory::fFile [protected, inherited]
Definition at line 56 of file TDirectory-example.h.
Referenced by TDirectory::GetFile().
TList * TDirectory::fKeys [protected, inherited]
Definition at line 59 of file TDirectory-example.h.
Referenced by TDirectory::GetListOfKeys(), and TDirectory::GetNkeys().
TList * TDirectory::fList [protected, inherited]
Definition at line 58 of file TDirectory-example.h.
Referenced by TDirectory::GetList().
Bool_t TDirectory::fModified [protected, inherited]
Definition at line 46 of file TDirectory-example.h.
Referenced by TDirectory::IsModified(), and TDirectory::SetModified().
TObject * TDirectory::fMother [protected, inherited]
Definition at line 57 of file TDirectory-example.h.
Referenced by TDirectory::GetMother(), TDirectory::GetMotherDir(), and TDirectory::SetMother().
Int_t TDirectory::fNbytesKeys [protected, inherited]
Definition at line 50 of file TDirectory-example.h.
Referenced by TDirectory::GetNbytesKeys().
Int_t TDirectory::fNbytesName [protected, inherited]
Definition at line 51 of file TDirectory-example.h.
std::string TNetDirectory::fPath [protected]
pointer to network connection
Definition at line 37 of file TNetDirectory.h.
Referenced by Append(), FindObject(), Get(), GetListOfKeys(), ResetTH1(), and TNetDirectory().
TString TDirectory::fPathBuffer [protected, inherited]
Definition at line 61 of file TDirectory-example.h.
Long64_t TDirectory::fSeekDir [protected, inherited]
Definition at line 53 of file TDirectory-example.h.
Referenced by TDirectory::GetSeekDir(), and TDirectory::SetSeekDir().
Long64_t TDirectory::fSeekKeys [protected, inherited]
Definition at line 55 of file TDirectory-example.h.
Referenced by TDirectory::GetSeekKeys().
Long64_t TDirectory::fSeekParent [protected, inherited]
Definition at line 54 of file TDirectory-example.h.
Referenced by TDirectory::GetSeekParent().
std::deque< TNetDirectory * > TNetDirectory::fSubDirs [protected]
Definition at line 38 of file TNetDirectory.h.
Referenced by FindObject(), and Get().
TUUID TDirectory::fUUID [protected, inherited]
Definition at line 60 of file TDirectory-example.h.
Referenced by TDirectory::GetUUID().
Bool_t TDirectory::fWritable [protected, inherited]
Definition at line 47 of file TDirectory-example.h.
Referenced by TDirectory::IsWritable().
The documentation for this class was generated from the following files:
include/TNetDirectory.h
libNetDirectory/TNetDirectory.h
libNetDirectory/TNetDirectory.cxx