ROOT Analyzer: ADCMeasMesy Class Reference
ADCMeasMesy Class Reference
#include <TMesytecData.hxx>
Public Member Functions
uint32_t GetMeasurement () const
Get the ADC measurement.
uint32_t GetModuleID () const
Get Module ID.
uint32_t GetChannel () const
Get the channel number.
bool IsOutOfRange () const
Is Out Of Range?
uint32_t GetMeasurement () const
Get the ADC measurement.
uint32_t GetModuleID () const
Get Module ID.
uint32_t GetChannel () const
Get the channel number.
bool IsOutOfRange () const
Is Out Of Range?
Private Member Functions
ADCMeasMesy (uint32_t header, uint32_t measurement)
Constructor; need to pass in header and measurement.
ADCMeasMesy ()
ADCMeasMesy (uint32_t header, uint32_t measurement)
Constructor; need to pass in header and measurement.
ADCMeasMesy ()
Private Attributes
uint32_t adc_header_word
Fields to hold the header, measurement, extendedtimestamp words.
uint32_t adc_measurement_word
uint32_t adc_extendedtimestamp_word
Friends
class TMesytecData
Detailed Description
Class for each TDC measurement For the definition of obscure variables see the CAEN V1190 manual. Currently doesn't support reading out extended timestamp!
Definition at line 13 of file TMesytecData.hxx.
Constructor & Destructor Documentation
ADCMeasMesy::ADCMeasMesy (uint32_t header, uint32_t measurement) [inline, private]
Constructor; need to pass in header and measurement.
Definition at line 39 of file TMesytecData.hxx.
                                                    :
    adc_header_word(header),
    adc_measurement_word(measurement),
    adc_extendedtimestamp_word(0){};
ADCMeasMesy::ADCMeasMesy () [private]
ADCMeasMesy::ADCMeasMesy (uint32_t header, uint32_t measurement) [inline, private]
Constructor; need to pass in header and measurement.
Definition at line 39 of file TMesytecData.hxx.
                                                    :
    adc_header_word(header),
    adc_measurement_word(measurement),
    adc_extendedtimestamp_word(0){};
ADCMeasMesy::ADCMeasMesy () [private]
Member Function Documentation
uint32_t ADCMeasMesy::GetChannel () const [inline]
Get the channel number.
Definition at line 26 of file TMesytecData.hxx.
References adc_measurement_word.
{return ((adc_measurement_word & 0x1f0000) >> 16);}
uint32_t ADCMeasMesy::GetChannel () const [inline]
Get the channel number.
Definition at line 26 of file TMesytecData.hxx.
References adc_measurement_word.
Referenced by TMesytecData::Print().
{return ((adc_measurement_word & 0x1f0000) >> 16);}
uint32_t ADCMeasMesy::GetMeasurement () const
Get the ADC measurement.
uint32_t ADCMeasMesy::GetMeasurement () const
Get the ADC measurement.
Definition at line 7 of file TMesytecData.cxx.
References adc_measurement_word, and gBitResolution.
Referenced by TMesytecData::Print().
{return (adc_measurement_word & gBitResolution);}
uint32_t ADCMeasMesy::GetModuleID () const [inline]
Get Module ID.
Definition at line 23 of file TMesytecData.hxx.
References adc_header_word.
{return (adc_header_word & 0xff0000) >> 16;};
uint32_t ADCMeasMesy::GetModuleID () const [inline]
Get Module ID.
Definition at line 23 of file TMesytecData.hxx.
References adc_header_word.
{return (adc_header_word & 0xff0000) >> 16;};
bool ADCMeasMesy::IsOutOfRange () const [inline]
Is Out Of Range?
Definition at line 29 of file TMesytecData.hxx.
References adc_measurement_word.
{return ((adc_measurement_word & 0x4000) == 0x4000);}
bool ADCMeasMesy::IsOutOfRange () const [inline]
Is Out Of Range?
Definition at line 29 of file TMesytecData.hxx.
References adc_measurement_word.
Referenced by TMesytecData::Print().
{return ((adc_measurement_word & 0x4000) == 0x4000);}
Friends And Related Function Documentation
TMesytecData [friend]
Definition at line 15 of file TMesytecData.hxx.
Member Data Documentation
uint32_t ADCMeasMesy::adc_extendedtimestamp_word [private]
Definition at line 36 of file TMesytecData.hxx.
uint32_t ADCMeasMesy::adc_header_word [private]
Fields to hold the header, measurement, extendedtimestamp words.
Definition at line 34 of file TMesytecData.hxx.
Referenced by GetModuleID().
uint32_t ADCMeasMesy::adc_measurement_word [private]
Definition at line 35 of file TMesytecData.hxx.
Referenced by GetChannel(), GetMeasurement(), and IsOutOfRange().
The documentation for this class was generated from the following files:
include/TMesytecData.hxx
libAnalyzer/TMesytecData.hxx
libAnalyzer/TMesytecData.cxx