ROOT Analyzer: TMesytecData Class Reference
TMesytecData Class Reference
#include <TMesytecData.hxx>
Public Member Functions
TMesytecData (int bklen, int bktype, const char *name, void *pdata)
Constructor.
void Print ()
Print the bank contents in a structured way.
std::vector< ADCMeasMesy > & GetMeasurements ()
Get the Vector of ADC Measurements.
uint32_t GetADCResolution () const
uint32_t GetModuleID () const
Get Module ID.
uint32_t GetOutputFormat () const
Get Output format (???).
uint32_t GetTimeStamp () const
TMesytecData (int bklen, int bktype, const char *name, void *pdata)
Constructor.
void Print ()
Print the bank contents in a structured way.
std::vector< ADCMeasMesy > & GetMeasurements ()
Get the Vector of ADC Measurements.
uint32_t GetADCResolution () const
uint32_t GetModuleID () const
Get Module ID.
uint32_t GetOutputFormat () const
Get Output format (???).
uint32_t GetTimeStamp () const
const uint16_t * GetData16 () const
const uint16_t * GetData16 () const
const uint32_t * GetData32 () const
const uint32_t * GetData32 () const
const uint64_t * GetData64 () const
const uint64_t * GetData64 () const
int GetSize () const
int GetSize () const
int GetType () const
int GetType () const
std::string GetName () const
std::string GetName () const
void Dump ()
Dump the bank contents in an unstructured way.
void Dump ()
Dump the bank contents in an unstructured way.
Private Attributes
uint32_t fGlobalHeader
The overall global header.
uint32_t fGlobalTrailer
The overall global trailer.
std::vector< ADCMeasMesy > fMeasurements
Vector of ADC Measurements.
Detailed Description
Class to store data from Mesytec MADC32 module. For details on this module see: http://daq-plone.triumf.ca/HR/VME/mesytec-modules/MADC-32_V14_fw0126.pdf/at_download/file
Definition at line 54 of file TMesytecData.hxx.
Constructor & Destructor Documentation
TMesytecData::TMesytecData (int bklen, int bktype, const char * name, void * pdata)
Constructor.
Save the current header.
Definition at line 11 of file TMesytecData.cxx.
References fGlobalHeader, fGlobalTrailer, fMeasurements, gBitResolution, TGenericData::GetData32(), and TGenericData::GetSize().
                                                                              :
    TGenericData(bklen, bktype, name, pdata)
{
  /// Save the current header.
  fGlobalHeader =0;
  for(int i = 0; i < GetSize(); i++){
    uint32_t word = GetData32()[i];
    if( (word & 0xc0000000) == 0x40000000){ // header word
      fGlobalHeader = word;
      // Figure out which bit resolution we are using
      int bitresolution = ((fGlobalHeader & 0x7000) >> 12);
      if(bitresolution == 1)
        gBitResolution = 0x7ff;
      else if(bitresolution == 2)
        gBitResolution = 0xfff;
      else if(bitresolution == 4)
        gBitResolution = 0x1fff;
    }
    if( (word & 0xc0000000) == 0x00000000 &&
        (word & 0x3fe00000) == 0x04000000 ){ // Data word
      fMeasurements.push_back(ADCMeasMesy(fGlobalHeader,word));
    }
    if( (word & 0xc0000000) == 0x00000000 &&
        (word & 0x3fe00000) == 0x04000000 ){ // Data extended timestamp
      // Not currently supported!!!
    }
    if((word & 0xc0000000) == 0xc0000000){ // trailer word
      fGlobalTrailer = word;
    }
  }
}
TMesytecData::TMesytecData (int bklen, int bktype, const char * name, void * pdata)
Constructor.
Member Function Documentation
void TGenericData::Dump () [inline, inherited]
Dump the bank contents in an unstructured way.
Definition at line 38 of file TGenericData.hxx.
References TGenericData::GetData32(), TGenericData::GetName(), and TGenericData::GetSize().
             {
    std::cout << "Generic decoder for bank named " <<  GetName().c_str() << std::endl;
    for(int i = 0; i < GetSize(); i++){
      std::cout << std::hex << "0x" << GetData32()[i] << std::dec << std::endl;
    }
  }
void TGenericData::Dump () [inline, inherited]
Dump the bank contents in an unstructured way.
Definition at line 38 of file TGenericData.hxx.
References TGenericData::GetData32(), TGenericData::GetName(), and TGenericData::GetSize().
Referenced by TGenericData::Print().
             {
    std::cout << "Generic decoder for bank named " <<  GetName().c_str() << std::endl;
    for(int i = 0; i < GetSize(); i++){
      std::cout << std::hex << "0x" << GetData32()[i] << std::dec << std::endl;
    }
  }
uint32_t TMesytecData::GetADCResolution () const [inline]
Get ADC resolution (11, 12 or 13 bit); Return values: 1 -> 11 bit, 2 -> 12 bit, 3 -> 13 bit (??)
Definition at line 68 of file TMesytecData.hxx.
References fGlobalHeader.
{return (fGlobalHeader & 0x7000) >> 12;};
uint32_t TMesytecData::GetADCResolution () const [inline]
Get ADC resolution (11, 12 or 13 bit); Return values: 1 -> 11 bit, 2 -> 12 bit, 3 -> 13 bit (??)
Definition at line 68 of file TMesytecData.hxx.
References fGlobalHeader.
{return (fGlobalHeader & 0x7000) >> 12;};
const uint16_t* TGenericData::GetData16 () const [inline, inherited]
Definition at line 23 of file TGenericData.hxx.
References TGenericData::fData.
{ return reinterpret_cast<const uint16_t*>(fData); }
const uint16_t* TGenericData::GetData16 () const [inline, inherited]
Definition at line 23 of file TGenericData.hxx.
References TGenericData::fData.
{ return reinterpret_cast<const uint16_t*>(fData); }
const uint32_t* TGenericData::GetData32 () const [inline, inherited]
Definition at line 26 of file TGenericData.hxx.
References TGenericData::fData.
{ return reinterpret_cast<const uint32_t*>(fData); }
const uint32_t* TGenericData::GetData32 () const [inline, inherited]
Definition at line 26 of file TGenericData.hxx.
References TGenericData::fData.
Referenced by TGenericData::Dump(), TMesytecData(), TV1190Data::TV1190Data(), and TV792Data::TV792Data().
{ return reinterpret_cast<const uint32_t*>(fData); }
const uint64_t* TGenericData::GetData64 () const [inline, inherited]
Definition at line 29 of file TGenericData.hxx.
References TGenericData::fData.
{ return reinterpret_cast<const uint64_t*>(fData); }
const uint64_t* TGenericData::GetData64 () const [inline, inherited]
Definition at line 29 of file TGenericData.hxx.
References TGenericData::fData.
{ return reinterpret_cast<const uint64_t*>(fData); }
std::vector<ADCMeasMesy>& TMesytecData::GetMeasurements () [inline]
Get the Vector of ADC Measurements.
Definition at line 64 of file TMesytecData.hxx.
References fMeasurements.
{return fMeasurements;}
std::vector<ADCMeasMesy>& TMesytecData::GetMeasurements () [inline]
Get the Vector of ADC Measurements.
Definition at line 64 of file TMesytecData.hxx.
References fMeasurements.
Referenced by Print().
{return fMeasurements;}
uint32_t TMesytecData::GetModuleID () const [inline]
Get Module ID.
Definition at line 71 of file TMesytecData.hxx.
References fGlobalHeader.
{return (fGlobalHeader & 0xff0000) >> 16;};
uint32_t TMesytecData::GetModuleID () const [inline]
Get Module ID.
Definition at line 71 of file TMesytecData.hxx.
References fGlobalHeader.
Referenced by Print().
{return (fGlobalHeader & 0xff0000) >> 16;};
std::string TGenericData::GetName () const [inline, inherited]
Definition at line 35 of file TGenericData.hxx.
References TGenericData::fBankName.
{return fBankName;}
std::string TGenericData::GetName () const [inline, inherited]
Definition at line 35 of file TGenericData.hxx.
References TGenericData::fBankName.
Referenced by TGenericData::Dump(), TV792Data::Print(), TV1190Data::Print(), and Print().
{return fBankName;}
uint32_t TMesytecData::GetOutputFormat () const [inline]
Get Output format (???).
Definition at line 74 of file TMesytecData.hxx.
References fGlobalHeader.
{return (fGlobalHeader & 0x8000) >> 15;};
uint32_t TMesytecData::GetOutputFormat () const [inline]
Get Output format (???).
Definition at line 74 of file TMesytecData.hxx.
References fGlobalHeader.
{return (fGlobalHeader & 0x8000) >> 15;};
int TGenericData::GetSize () const [inline, inherited]
Definition at line 31 of file TGenericData.hxx.
References TGenericData::fSize.
{return fSize;}
int TGenericData::GetSize () const [inline, inherited]
Definition at line 31 of file TGenericData.hxx.
References TGenericData::fSize.
Referenced by TGenericData::Dump(), TMesytecData(), TV1190Data::TV1190Data(), and TV792Data::TV792Data().
{return fSize;}
uint32_t TMesytecData::GetTimeStamp () const [inline]
Definition at line 77 of file TMesytecData.hxx.
References fGlobalTrailer.
{return (fGlobalTrailer & 0x3fffffff);};
uint32_t TMesytecData::GetTimeStamp () const [inline]
Definition at line 77 of file TMesytecData.hxx.
References fGlobalTrailer.
Referenced by Print().
{return (fGlobalTrailer & 0x3fffffff);};
int TGenericData::GetType () const [inline, inherited]
Definition at line 33 of file TGenericData.hxx.
References TGenericData::fBankType.
{return fBankType;}
int TGenericData::GetType () const [inline, inherited]
Definition at line 33 of file TGenericData.hxx.
References TGenericData::fBankType.
{return fBankType;}
void TMesytecData::Print () [virtual]
Print the bank contents in a structured way.
Reimplemented from TGenericData.
void TMesytecData::Print () [virtual]
Print the bank contents in a structured way.
Reimplemented from TGenericData.
Definition at line 53 of file TMesytecData.cxx.
References gBitResolution, ADCMeasMesy::GetChannel(), ADCMeasMesy::GetMeasurement(), GetMeasurements(), GetModuleID(), TGenericData::GetName(), GetTimeStamp(), and ADCMeasMesy::IsOutOfRange().
{
  std::cout << "Data for Mesytec module in bank " << GetName() << std::endl;
  std::cout << "Module ID = " << GetModuleID() << std::endl;
  std::cout << "Bit resolution : 0x" << std::hex
            << gBitResolution << std::dec << std::endl;
  std::cout << "Timestamp = " << GetTimeStamp() << std::endl;
  std::vector<ADCMeasMesy> measurements = GetMeasurements();
  std::cout << "Number of measurements: " << measurements.size() << std::endl;
  for(unsigned int i = 0; i < measurements.size(); i++){
    ADCMeasMesy adcmeas = measurements[i];
    std::cout << "meas: " << adcmeas.GetMeasurement()
              << " [chan="<< adcmeas.GetChannel()
              <<",OOR=" << adcmeas.IsOutOfRange() << "]  ";
    if(i%2==1) std::cout <<  std::endl;
  }
  std::cout <<  std::endl;
}
Member Data Documentation
uint32_t TMesytecData::fGlobalHeader [private]
The overall global header.
Definition at line 77 of file TMesytecData.hxx.
Referenced by GetADCResolution(), GetModuleID(), GetOutputFormat(), and TMesytecData().
uint32_t TMesytecData::fGlobalTrailer [private]
The overall global trailer.
Definition at line 85 of file TMesytecData.hxx.
Referenced by GetTimeStamp(), and TMesytecData().
std::vector< ADCMeasMesy > TMesytecData::fMeasurements [private]
Vector of ADC Measurements.
Definition at line 88 of file TMesytecData.hxx.
Referenced by GetMeasurements(), and TMesytecData().
The documentation for this class was generated from the following files:
include/TMesytecData.hxx
libAnalyzer/TMesytecData.hxx
libAnalyzer/TMesytecData.cxx