ROOT Analyzer: MyPeriodic Class Reference
MyPeriodic Class Reference
Public Types
typedef void(* TimerHandler)(void)
typedef void(* TimerHandler)(void)
Public Member Functions
MyPeriodic (int period_msec, TimerHandler handler)
Bool_t Notify ()
~MyPeriodic ()
MyPeriodic (int period_msec, TimerHandler handler)
Bool_t Notify ()
~MyPeriodic ()
Public Attributes
int fPeriod_msec
TimerHandler fHandler
double fLastTime
Detailed Description
Definition at line 61 of file analyzer.cxx.
Member Typedef Documentation
typedef void(* MyPeriodic::TimerHandler)(void)
Definition at line 49 of file test_midasServer.cxx.
typedef void(* MyPeriodic::TimerHandler)(void)
Definition at line 64 of file analyzer.cxx.
Constructor & Destructor Documentation
MyPeriodic::MyPeriodic (int period_msec, TimerHandler handler) [inline]
Definition at line 70 of file analyzer.cxx.
References fHandler, fLastTime, fPeriod_msec, and GetTimeSec().
  {
    assert(handler != NULL);
    fPeriod_msec = period_msec;
    fHandler  = handler;
    fLastTime = GetTimeSec();
    Start(period_msec,kTRUE);
  }
MyPeriodic::~MyPeriodic () [inline]
Definition at line 97 of file analyzer.cxx.
  {
    TurnOff();
  }
MyPeriodic::MyPeriodic (int period_msec, TimerHandler handler) [inline]
Definition at line 55 of file test_midasServer.cxx.
References fHandler, fLastTime, fPeriod_msec, and GetTimeSec().
  {
    assert(handler != NULL);
    fPeriod_msec = period_msec;
    fHandler  = handler;
    fLastTime = GetTimeSec();
    Start(period_msec,kTRUE);
  }
MyPeriodic::~MyPeriodic () [inline]
Definition at line 82 of file test_midasServer.cxx.
  {
    TurnOff();
  }
Member Function Documentation
Bool_t MyPeriodic::Notify () [inline]
Definition at line 64 of file test_midasServer.cxx.
References fHandler, fLastTime, fPeriod_msec, and GetTimeSec().
  {
    double t = GetTimeSec();
    //printf("timer notify, period %f should be %f!\n",t-fLastTime,fPeriod_msec*0.001);
    if (t - fLastTime >= 0.9*fPeriod_msec*0.001)
      {
        //printf("timer: call handler %p\n",fHandler);
        if (fHandler)
          (*fHandler)();
        fLastTime = t;
      }
    Reset();
    return kTRUE;
  }
Bool_t MyPeriodic::Notify () [inline]
Definition at line 79 of file analyzer.cxx.
References fHandler, fLastTime, fPeriod_msec, and GetTimeSec().
  {
    double t = GetTimeSec();
    //printf("timer notify, period %f should be %f!\n",t-fLastTime,fPeriod_msec*0.001);
    if (t - fLastTime >= 0.9*fPeriod_msec*0.001)
      {
        //printf("timer: call handler %p\n",fHandler);
        if (fHandler)
          (*fHandler)();
        fLastTime = t;
      }
    Reset();
    return kTRUE;
  }
Member Data Documentation
TimerHandler MyPeriodic::fHandler
Definition at line 67 of file analyzer.cxx.
Referenced by MyPeriodic(), and Notify().
double MyPeriodic::fLastTime
Definition at line 68 of file analyzer.cxx.
Referenced by MyPeriodic(), and Notify().
int MyPeriodic::fPeriod_msec
Definition at line 66 of file analyzer.cxx.
Referenced by MyPeriodic(), and Notify().
The documentation for this class was generated from the following files:
analyzer.cxx
tests/test_midasServer.cxx