ROOT Analyzer: analyzer.cxx File Reference
analyzer.cxx File Reference
#include <stdio.h>
#include <sys/time.h>
#include <iostream>
#include <assert.h>
#include <signal.h>
#include "TMidasOnline.h"
#include "TMidasEvent.h"
#include "TMidasFile.h"
#include "XmlOdb.h"
#include <TSystem.h>
#include <TROOT.h>
#include <TApplication.h>
#include <TTimer.h>
#include <TFile.h>
#include <TDirectory.h>
#include <TGClient.h>
#include <TGFrame.h>
#include <TFolder.h>
#include "Globals.h"
#include <TH1D.h>
#include <TGMenu.h>
Classes
class MyPeriodic
class MainWindow
Defines
#define M_FILE_EXIT 0
Functions
double GetTimeSec ()
void startRun (int transition, int run, int time)
void endRun (int transition, int run, int time)
void HandleSample (int ichan, void *ptr, int wsize)
void HandleMidasEvent (TMidasEvent &event)
void eventHandler (const void *pheader, const void *pdata, int size)
int ProcessMidasFile (TApplication *app, const char *fname)
int ShowMem (const char *label)
void help ()
int main (int argc, char *argv[])
Variables
int gRunNumber = 0
bool gIsRunning = false
bool gIsPedestalsRun = false
bool gIsOffline = false
int gEventCutoff = 0
TDirectory * gOnlineHistDir = NULL
TFile * gOutputFile = NULL
VirtualOdb * gOdb = NULL
static bool gEnableShowMem = false
Define Documentation
#define M_FILE_EXIT 0
Definition at line 400 of file analyzer.cxx.
Referenced by MainWindow::MainWindow(), and MainWindow::ProcessMessage().
Function Documentation
void endRun (int transition, int run, int time)
Definition at line 135 of file analyzer.cxx.
References gIsRunning, gManaHistosFolder, gOutputFile, and gRunNumber.
Referenced by MainWindow::CloseWindow(), MainWindow::ProcessMessage(), and ProcessMidasFile().
{
  gIsRunning = false;
  gRunNumber = run;
#ifdef HAVE_MIDASSERVER
  if (gManaHistosFolder)
    gManaHistosFolder->Clear();
#endif
  if (gOutputFile)
    {
      gOutputFile->Write();
      gOutputFile->Close();             //close the histogram file
      gOutputFile = NULL;
    }
  printf("End of run %d\n",run);
}
void eventHandler (const void * pheader, const void * pdata, int size)
Definition at line 232 of file analyzer.cxx.
References TMidasEvent::GetEventHeader(), and HandleMidasEvent().
{
  TMidasEvent event;
  memcpy(event.GetEventHeader(), pheader, sizeof(TMidas_EVENT_HEADER));
  event.SetData(size, (char*)pdata);
  event.SetBankList();
  HandleMidasEvent(event);
}
double GetTimeSec ()
Definition at line 54 of file analyzer.cxx.
Referenced by MyPeriodic::MyPeriodic(), TPeriodicClass::Notify(), MyPeriodic::Notify(), and TPeriodicClass::TPeriodicClass().
{
  struct timeval tv;
  gettimeofday(&tv,NULL);
  return tv.tv_sec + 0.000001*tv.tv_usec;
}
void HandleMidasEvent (TMidasEvent & event)
Definition at line 189 of file analyzer.cxx.
References gIsPedestalsRun, gIsRunning, and HandleSample().
Referenced by eventHandler(), and ProcessMidasFile().
{
  int eventId = event.GetEventId();
  if (false&&(eventId == 1))
    {
      void *ptr;
      int size = event.LocateBank(NULL, "CHA3", &ptr);
      if (ptr)
        HandleSample(3, ptr, size);
    }
  if (false&&(eventId == 1)&&(gIsRunning==true)&&(gIsPedestalsRun==false)) // SIS data
    {
      //printf("SIS event\n");
      //event.Print();
      //void *ptr;
      //int size = event.LocateBank(event.GetData(),"MCS",&ptr);
      //HandleSIS(kMaxSisChannels,size,ptr);
    }
  else if (false&&(eventId == 2)&&(gIsRunning==true)) // ADC data
    {
      //printf("ADC event\n");
      //event.Print();
      //void *ptr;
      //int size = event.LocateBank(event.GetData(),"ADC",&ptr);
      //HandleBeamADC(kMaxADCChannels,size,ptr,event);
    }
  else if (false&&(eventId==5)&&(gIsRunning==true)&&(gIsPedestalsRun==false))// Scaler data
    {
      //event.Print();
      //void *sclrptr;
      //int sclrsize = event.LocateBank(event.GetData(),"SCLR",&sclrptr);
      //void *scrtptr;
      //int scrtsize = event.LocateBank(event.GetData(),"SCRT",&scrtptr);
      //HandleScaler(kMaxScalerChannels,sclrsize,sclrptr,scrtsize,scrtptr,event);
    }
  else
    {
      // unknown event type
      event.Print();
    }
}
void HandleSample (int ichan, void * ptr, int wsize)
Definition at line 157 of file analyzer.cxx.
References gDirectory, TDirectory::Get(), gManaHistosFolder, and gOutputFile.
Referenced by HandleMidasEvent().
{
  uint16_t *samples = (uint16_t*) ptr;
  int numSamples = wsize;
  if (numSamples != 512)
    return;
  char name[256];
  sprintf(name, "channel%d", ichan);
  if (gOutputFile)
    gOutputFile->cd();
  TH1D* samplePlot = (TH1D*)gDirectory->Get(name);
  if (!samplePlot)
    {
      printf("Create [%s]\n", name);
      samplePlot = new TH1D(name, name, numSamples, 0, numSamples);
      //samplePlot->SetMinimum(0);
#ifdef HAVE_MIDASSERVER
      if (gManaHistosFolder)
        gManaHistosFolder->Add(samplePlot);
#endif
    }
  for(int ti=0; ti<numSamples; ti++)
    samplePlot->SetBinContent(ti, samples[ti]);
}
void help ()
Definition at line 499 of file analyzer.cxx.
Referenced by main().
{
  printf("\nUsage:\n");
  printf("\n./analyzer.exe [-h] [-Hhostname] [-Eexptname] [-eMaxEvents] [-P9091] [-p9090] [-m] [-g] [file1 file2 ...]\n");
  printf("\n");
  printf("\t-h: print this help message\n");
  printf("\t-T: test mode - start and serve a test histogram\n");
  printf("\t-Hhostname: connect to MIDAS experiment on given host\n");
  printf("\t-Eexptname: connect to this MIDAS experiment\n");
  printf("\t-P: Start the TNetDirectory server on specified tcp port (for use with roody -Plocalhost:9091)\n");
  printf("\t-p: Start the old midas histogram server on specified tcp port (for use with roody -Hlocalhost:9090)\n");
  printf("\t-e: Number of events to read from input data files\n");
  printf("\t-m: Enable memory leak debugging\n");
  printf("\t-g: Enable graphics display when processing data files\n");
  printf("\n");
  printf("Example1: analyze online data: ./analyzer.exe -P9091\n");
  printf("Example2: analyze existing data: ./analyzer.exe /data/alpha/current/run00500.mid\n");
  exit(1);
}
int main (int argc, char * argv[])
Definition at line 521 of file analyzer.cxx.
References TDirectory::cd(), XmlServer::Export(), gEventCutoff, gIsOffline, help(), ProcessMidasFile(), XmlServer::SetVerbose(), XmlServer::Start(), StartMidasServer(), and StartNetDirectoryServer().
{
   setbuf(stdout,NULL);
   setbuf(stderr,NULL);
   signal(SIGILL,  SIG_DFL);
   signal(SIGBUS,  SIG_DFL);
   signal(SIGSEGV, SIG_DFL);
   signal(SIGPIPE, SIG_DFL);
   std::vector<std::string> args;
   for (int i=0; i<argc; i++)
     {
       if (strcmp(argv[i],"-h")==0)
         help(); // does not return
       args.push_back(argv[i]);
     }
   TApplication *app = new TApplication("rootana", &argc, argv);
   if(gROOT->IsBatch()) {
        printf("Cannot run in batch mode\n");
        return 1;
   }
   bool forceEnableGraphics = false;
   bool testMode = false;
   int  oldTcpPort = 0;
   int  tcpPort = 0;
   int  xmlTcpPort = 0;
   const char* hostname = NULL;
   const char* exptname = NULL;
   for (unsigned int i=1; i<args.size(); i++) // loop over the commandline options
     {
       const char* arg = args[i].c_str();
       //printf("argv[%d] is %s\n",i,arg);
       if (strncmp(arg,"-e",2)==0)  // Event cutoff flag (only applicable in offline mode)
         gEventCutoff = atoi(arg+2);
       else if (strncmp(arg,"-m",2)==0) // Enable memory debugging
         gEnableShowMem = true;
       else if (strncmp(arg,"-p",2)==0) // Set the histogram server port
         oldTcpPort = atoi(arg+2);
       else if (strncmp(arg,"-P",2)==0) // Set the histogram server port
         tcpPort = atoi(arg+2);
       else if (strncmp(arg,"-X",2)==0) // Set the histogram server port
         xmlTcpPort = atoi(arg+2);
       else if (strcmp(arg,"-T")==0)
         testMode = true;
       else if (strcmp(arg,"-g")==0)
         forceEnableGraphics = true;
       else if (strncmp(arg,"-H",2)==0)
         hostname = strdup(arg+2);
       else if (strncmp(arg,"-E",2)==0)
         exptname = strdup(arg+2);
       else if (strcmp(arg,"-h")==0)
         help(); // does not return
       else if (arg[0] == '-')
         help(); // does not return
    }
   MainWindow mainWindow(gClient->GetRoot(), 200, 300);
   gROOT->cd();
   gOnlineHistDir = new TDirectory("rootana", "rootana online plots");
#ifdef HAVE_MIDASSERVER
   if (oldTcpPort)
     StartMidasServer(oldTcpPort);
#else
   if (oldTcpPort)
     fprintf(stderr,"ERROR: No support for the old midas server!\n");
#endif
#ifdef HAVE_LIBNETDIRECTORY
   if (tcpPort)
     StartNetDirectoryServer(tcpPort, gOnlineHistDir);
#else
   if (tcpPort)
     fprintf(stderr,"ERROR: No support for the TNetDirectory server!\n");
#endif
#ifdef HAVE_XMLSERVER
   XmlServer* xmlServer = NULL;
   if (xmlTcpPort)
     {
        xmlServer = new XmlServer();
        xmlServer->SetVerbose(true);
        xmlServer->Start(xmlTcpPort);
        xmlServer->Export(gOnlineHistDir, gOnlineHistDir->GetName());
     }
#else
   if (xmlTcpPort)
     fprintf(stderr,"ERROR: No support for the XML Server!\n");
#endif
   gIsOffline = false;
   for (unsigned int i=1; i<args.size(); i++)
     {
       const char* arg = args[i].c_str();
       if (arg[0] != '-')
         {
           gIsOffline = true;
           //gEnableGraphics = false;
           //gEnableGraphics |= forceEnableGraphics;
           ProcessMidasFile(app,arg);
         }
     }
   if (testMode)
     {
       gOnlineHistDir->cd();
       TH1D* hh = new TH1D("test", "test", 100, 0, 100);
       hh->Fill(1);
       hh->Fill(10);
       hh->Fill(50);
       app->Run(kTRUE);
       return 0;
     }
   // if we processed some data files,
   // do not go into online mode.
   if (gIsOffline)
     return 0;
   gIsOffline = false;
   //gEnableGraphics = true;
#ifdef HAVE_MIDAS
   ProcessMidasOnline(app, hostname, exptname);
#endif
   return 0;
}
int ProcessMidasFile (TApplication * app, const char * fname)
Definition at line 241 of file analyzer.cxx.
References TMidasFile::Close(), endRun(), TMidasEvent::GetData(), TMidasEvent::GetSerialNumber(), gEventCutoff, gRunNumber, HandleMidasEvent(), TMidasFile::Open(), TMidasFile::Read(), and startRun().
Referenced by main().
{
  TMidasFile f;
  bool tryOpen = f.Open(fname);
  if (!tryOpen)
    {
      printf("Cannot open input file \"%s\"\n",fname);
      return -1;
    }
  int i=0;
  while (1)
    {
      TMidasEvent event;
      if (!f.Read(&event))
        break;
      int eventId = event.GetEventId();
      //printf("Have an event of type %d\n",eventId);
      if ((eventId & 0xFFFF) == 0x8000)
        {
          // begin run
          event.Print();
          //char buf[256];
          //memset(buf,0,sizeof(buf));
          //memcpy(buf,event.GetData(),255);
          //printf("buf is [%s]\n",buf);
          //
          // Load ODB contents from the ODB XML file
          //
          if (gOdb)
            delete gOdb;
          gOdb = new XmlOdb(event.GetData(),event.GetDataSize());
          startRun(0,event.GetSerialNumber(),0);
        }
      else if ((eventId & 0xFFFF) == 0x8001)
        {
          // end run
          event.Print();
        }
      else if ((eventId & 0xFFFF) == 0x8002)
        {
          // log message
          event.Print();
          printf("Log message: %s\n", event.GetData());
        }
      else
        {
          event.SetBankList();
          //event.Print();
          HandleMidasEvent(event);
        }
      if((i%500)==0)
        {
          //resetClock2time();
          printf("Processing event %d\n",i);
          //SISperiodic();
          //StepThroughSISBuffer();
        }
      i++;
      if ((gEventCutoff!=0)&&(i>=gEventCutoff))
        {
          printf("Reached event %d, exiting loop.\n",i);
          break;
        }
    }
  f.Close();
  endRun(0,gRunNumber,0);
  // start the ROOT GUI event loop
  //  app->Run(kTRUE);
  return 0;
}
int ShowMem (const char * label)
Definition at line 480 of file analyzer.cxx.
{
  if (!gEnableShowMem)
    return 0;
  FILE* fp = fopen("/proc/self/statm","r");
  if (!fp)
    return 0;
  int mem = 0;
  fscanf(fp,"%d",&mem);
  fclose(fp);
  if (label)
    printf("memory at %s is %d\n", label, mem);
  return mem;
}
void startRun (int transition, int run, int time)
Definition at line 104 of file analyzer.cxx.
References gIsPedestalsRun, gIsRunning, gOutputFile, gRunNumber, NetDirectoryExport(), and VirtualOdb::odbReadBool().
Referenced by ProcessMidasFile().
{
  gIsRunning = true;
  gRunNumber = run;
  gIsPedestalsRun = gOdb->odbReadBool("/experiment/edit on start/Pedestals run");
  printf("Begin run: %d, pedestal run: %d\n", gRunNumber, gIsPedestalsRun);
  if(gOutputFile!=NULL)
  {
    gOutputFile->Write();
    gOutputFile->Close();
    gOutputFile=NULL;
  }
  char filename[1024];
  sprintf(filename, "output%05d.root", run);
  gOutputFile = new TFile(filename, "RECREATE");
  //if (gOutputFile && !gOutputFile->IsOpen())
  //gOutputFile = NULL;
  assert(gOutputFile);
  assert(gOutputFile->IsOpen());
  //printf("gOutputFile: %p, isOpen %d\n", gOutputFile, gOutputFile->IsOpen());
#ifdef HAVE_LIBNETDIRECTORY
  NetDirectoryExport(gOutputFile, "outputFile");
#endif
}
Variable Documentation
bool gEnableShowMem = false [static]
Definition at line 478 of file analyzer.cxx.
int gEventCutoff = 0
Definition at line 46 of file analyzer.cxx.
Referenced by main(), and ProcessMidasFile().
bool gIsOffline = false
Definition at line 45 of file analyzer.cxx.
Referenced by main().
bool gIsPedestalsRun = false
Definition at line 44 of file analyzer.cxx.
Referenced by HandleMidasEvent(), and startRun().
bool gIsRunning = false
Definition at line 43 of file analyzer.cxx.
Referenced by MainWindow::CloseWindow(), endRun(), HandleMidasEvent(), MainWindow::ProcessMessage(), and startRun().
VirtualOdb* gOdb = NULL
Definition at line 50 of file analyzer.cxx.
TDirectory* gOnlineHistDir = NULL
Definition at line 48 of file analyzer.cxx.
TFile* gOutputFile = NULL
Definition at line 49 of file analyzer.cxx.
Referenced by endRun(), HandleSample(), and startRun().
int gRunNumber = 0
Definition at line 42 of file analyzer.cxx.
Referenced by MainWindow::CloseWindow(), endRun(), MainWindow::ProcessMessage(), ProcessMidasFile(), and startRun().