ROOT Analyzer: TDirectory Class Reference
TDirectory Class Reference
#include <TDirectory-example.h>
Classes
class TContext
Public Types
enum { kCloseDirectory = BIT(7) }
enum { kCloseDirectory = BIT(7) }
Public Member Functions
TDirectory ()
TDirectory (const char *name, const char *title, Option_t *option="", TDirectory *motherDir=0)
virtual ~TDirectory ()
virtual void Append (TObject *obj)
void Add (TObject *obj)
Int_t AppendKey (TKey *key)
virtual void Browse (TBrowser *b)
void Build (TFile *motherFile=0, TDirectory *motherDir=0)
virtual void Clear (Option_t *option="")
virtual void Close (Option_t *option="")
virtual void Copy (TObject &) const
virtual Bool_t cd (const char *path=0)
virtual void DeleteAll (Option_t *option="")
virtual void Delete (const char *namecycle="")
virtual void Draw (Option_t *option="")
virtual void FillBuffer (char *&buffer)
virtual TKey * FindKey (const char *keyname) const
virtual TKey * FindKeyAny (const char *keyname) const
virtual TObject * FindObject (const char *name) const
virtual TObject * FindObject (const TObject *obj) const
virtual TObject * FindObjectAny (const char *name) const
virtual TObject * Get (const char *namecycle)
virtual TDirectory * GetDirectory (const char *namecycle, Bool_t printError=false, const char *funcname="GetDirectory")
template<class T >
void GetObject (const char *namecycle, T *&ptr)
virtual void * GetObjectChecked (const char *namecycle, const char *classname)
virtual void * GetObjectChecked (const char *namecycle, const TClass *cl)
virtual void * GetObjectUnchecked (const char *namecycle)
virtual Int_t GetBufferSize () const
const TDatime & GetCreationDate () const
virtual TFile * GetFile () const
virtual TKey * GetKey (const char *name, Short_t cycle=9999) const
virtual TList * GetList () const
virtual TList * GetListOfKeys () const
const TDatime & GetModificationDate () const
TObject * GetMother () const
TDirectory * GetMotherDir () const
virtual Int_t GetNbytesKeys () const
virtual Int_t GetNkeys () const
virtual Long64_t GetSeekDir () const
virtual Long64_t GetSeekParent () const
virtual Long64_t GetSeekKeys () const
virtual const char * GetPathStatic () const
virtual const char * GetPath () const
TUUID GetUUID () const
Bool_t IsFolder () const
Bool_t IsModified () const
Bool_t IsWritable () const
virtual void ls (Option_t *option="") const
virtual TDirectory * mkdir (const char *name, const char *title="")
virtual void Paint (Option_t *option="")
virtual void Print (Option_t *option="") const
virtual void Purge (Short_t nkeep=1)
virtual void pwd () const
virtual void ReadAll (Option_t *option="")
virtual Int_t ReadKeys ()
virtual void RecursiveRemove (TObject *obj)
virtual void rmdir (const char *name)
virtual void Save ()
virtual void SaveSelf (Bool_t force=kFALSE)
virtual void SetBufferSize (Int_t bufsize)
void SetModified ()
void SetMother (const TObject *mother)
virtual void SetName (const char *newname)
void SetSeekDir (Long64_t v)
void SetWritable (Bool_t writable=kTRUE)
virtual Int_t Sizeof () const
virtual Int_t Write (const char *name=0, Int_t opt=0, Int_t bufsiz=0)
virtual Int_t Write (const char *name=0, Int_t opt=0, Int_t bufsiz=0) const
virtual Int_t WriteTObject (const TObject *obj, const char *name=0, Option_t *option="")
template<class T >
Int_t WriteObject (const T *obj, const char *name, Option_t *option="")
virtual Int_t WriteObjectAny (const void *obj, const char *classname, const char *name, Option_t *option="")
virtual Int_t WriteObjectAny (const void *obj, const TClass *cl, const char *name, Option_t *option="")
virtual void WriteDirHeader ()
virtual void WriteKeys ()
TDirectory ()
TDirectory (const char *name, const char *title, Option_t *option="", TDirectory *motherDir=0)
virtual ~TDirectory ()
virtual void Append (TObject *obj)
void Add (TObject *obj)
Int_t AppendKey (TKey *key)
virtual void Browse (TBrowser *b)
void Build (TFile *motherFile=0, TDirectory *motherDir=0)
virtual void Clear (Option_t *option="")
virtual void Close (Option_t *option="")
virtual void Copy (TObject &) const
virtual Bool_t cd (const char *path=0)
virtual void DeleteAll (Option_t *option="")
virtual void Delete (const char *namecycle="")
virtual void Draw (Option_t *option="")
virtual void FillBuffer (char *&buffer)
virtual TKey * FindKey (const char *keyname) const
virtual TKey * FindKeyAny (const char *keyname) const
virtual TObject * FindObject (const char *name) const
virtual TObject * FindObject (const TObject *obj) const
virtual TObject * FindObjectAny (const char *name) const
virtual TObject * Get (const char *namecycle)
virtual TDirectory * GetDirectory (const char *namecycle, Bool_t printError=false, const char *funcname="GetDirectory")
template<class T >
void GetObject (const char *namecycle, T *&ptr)
virtual void * GetObjectChecked (const char *namecycle, const char *classname)
virtual void * GetObjectChecked (const char *namecycle, const TClass *cl)
virtual void * GetObjectUnchecked (const char *namecycle)
virtual Int_t GetBufferSize () const
const TDatime & GetCreationDate () const
virtual TFile * GetFile () const
virtual TKey * GetKey (const char *name, Short_t cycle=9999) const
virtual TList * GetList () const
virtual TList * GetListOfKeys () const
const TDatime & GetModificationDate () const
TObject * GetMother () const
TDirectory * GetMotherDir () const
virtual Int_t GetNbytesKeys () const
virtual Int_t GetNkeys () const
virtual Long64_t GetSeekDir () const
virtual Long64_t GetSeekParent () const
virtual Long64_t GetSeekKeys () const
virtual const char * GetPathStatic () const
virtual const char * GetPath () const
TUUID GetUUID () const
Bool_t IsFolder () const
Bool_t IsModified () const
Bool_t IsWritable () const
virtual void ls (Option_t *option="") const
virtual TDirectory * mkdir (const char *name, const char *title="")
virtual void Paint (Option_t *option="")
virtual void Print (Option_t *option="") const
virtual void Purge (Short_t nkeep=1)
virtual void pwd () const
virtual void ReadAll (Option_t *option="")
virtual Int_t ReadKeys ()
virtual void RecursiveRemove (TObject *obj)
virtual void rmdir (const char *name)
virtual void Save ()
virtual void SaveSelf (Bool_t force=kFALSE)
virtual void SetBufferSize (Int_t bufsize)
void SetModified ()
void SetMother (const TObject *mother)
virtual void SetName (const char *newname)
void SetSeekDir (Long64_t v)
void SetWritable (Bool_t writable=kTRUE)
virtual Int_t Sizeof () const
virtual Int_t Write (const char *name=0, Int_t opt=0, Int_t bufsiz=0)
virtual Int_t Write (const char *name=0, Int_t opt=0, Int_t bufsiz=0) const
virtual Int_t WriteTObject (const TObject *obj, const char *name=0, Option_t *option="")
template<class T >
Int_t WriteObject (const T *obj, const char *name, Option_t *option="")
virtual Int_t WriteObjectAny (const void *obj, const char *classname, const char *name, Option_t *option="")
virtual Int_t WriteObjectAny (const void *obj, const TClass *cl, const char *name, Option_t *option="")
virtual void WriteDirHeader ()
virtual void WriteKeys ()
Static Public Member Functions
static Bool_t Cd (const char *path)
static void DecodeNameCycle (const char *namecycle, char *name, Short_t &cycle)
static void EncodeNameCycle (char *buffer, const char *name, Short_t cycle)
static Bool_t Cd (const char *path)
static void DecodeNameCycle (const char *namecycle, char *name, Short_t &cycle)
static void EncodeNameCycle (char *buffer, const char *name, Short_t cycle)
Protected Member Functions
Bool_t cd1 (const char *path)
Buffer for GetPath() function.
void FillFullPath (TString &buf) const
Bool_t cd1 (const char *path)
Buffer for GetPath() function.
void FillFullPath (TString &buf) const
Static Protected Member Functions
static Bool_t Cd1 (const char *path)
static Bool_t Cd1 (const char *path)
Protected Attributes
Bool_t fModified
Bool_t fWritable
TDatime fDatimeC
TDatime fDatimeM
Int_t fNbytesKeys
Int_t fNbytesName
Int_t fBufferSize
Long64_t fSeekDir
Long64_t fSeekParent
Long64_t fSeekKeys
TFile * fFile
TObject * fMother
TList * fList
TList * fKeys
TUUID fUUID
TString fPathBuffer
Private Member Functions
TDirectory (const TDirectory &directory)
void operator= (const TDirectory &)
TDirectory (const TDirectory &directory)
void operator= (const TDirectory &)
Detailed Description
Definition at line 43 of file TDirectory-example.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
kCloseDirectory
Definition at line 74 of file TDirectory-example.h.
{ kCloseDirectory = BIT(7) };
anonymous enum
Enumerator:
kCloseDirectory
Definition at line 74 of file TDirectory-example.h.
{ kCloseDirectory = BIT(7) };
Constructor & Destructor Documentation
TDirectory::TDirectory (const TDirectory & directory) [private]
TDirectory::TDirectory ()
TDirectory::TDirectory (const char * name, const char * title, Option_t * option = "", TDirectory * motherDir = 0)
virtual TDirectory::~TDirectory () [virtual]
TDirectory::TDirectory (const TDirectory & directory) [private]
TDirectory::TDirectory ()
TDirectory::TDirectory (const char * name, const char * title, Option_t * option = "", TDirectory * motherDir = 0)
virtual TDirectory::~TDirectory () [virtual]
Member Function Documentation
void TDirectory::Add (TObject * obj) [inline]
Definition at line 114 of file TDirectory-example.h.
References Append().
{ Append(obj); }
void TDirectory::Add (TObject * obj) [inline]
Definition at line 114 of file TDirectory-example.h.
References Append().
{ Append(obj); }
virtual void TDirectory::Append (TObject * obj) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::Append (TObject * obj) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Referenced by Add().
Int_t TDirectory::AppendKey (TKey * key)
Int_t TDirectory::AppendKey (TKey * key)
virtual void TDirectory::Browse (TBrowser * b) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::Browse (TBrowser * b) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
void TDirectory::Build (TFile * motherFile = 0, TDirectory * motherDir = 0)
void TDirectory::Build (TFile * motherFile = 0, TDirectory * motherDir = 0)
static Bool_t TDirectory::Cd (const char * path) [static]
virtual Bool_t TDirectory::cd (const char * path = 0) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
static Bool_t TDirectory::Cd (const char * path) [static]
virtual Bool_t TDirectory::cd (const char * path = 0) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Referenced by TRootanaEventLoop::ExecuteLoop(), main(), MyTestLoop::ProcessMidasEvent(), TDirectory::TContext::TContext(), and TDirectory::TContext::~TContext().
static Bool_t TDirectory::Cd1 (const char * path) [static, protected]
Bool_t TDirectory::cd1 (const char * path) [protected]
Buffer for GetPath() function.
static Bool_t TDirectory::Cd1 (const char * path) [static, protected]
Bool_t TDirectory::cd1 (const char * path) [protected]
Buffer for GetPath() function.
virtual void TDirectory::Clear (Option_t * option = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::Clear (Option_t * option = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::Close (Option_t * option = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::Close (Option_t * option = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::Copy (TObject &) const [inline, virtual]
Definition at line 120 of file TDirectory-example.h.
{ MayNotUse("Copy(TObject &)"); }
virtual void TDirectory::Copy (TObject &) const [inline, virtual]
Definition at line 120 of file TDirectory-example.h.
{ MayNotUse("Copy(TObject &)"); }
static void TDirectory::DecodeNameCycle (const char * namecycle, char * name, Short_t & cycle) [static]
static void TDirectory::DecodeNameCycle (const char * namecycle, char * name, Short_t & cycle) [static]
virtual void TDirectory::Delete (const char * namecycle = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::Delete (const char * namecycle = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::DeleteAll (Option_t * option = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::DeleteAll (Option_t * option = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::Draw (Option_t * option = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::Draw (Option_t * option = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
static void TDirectory::EncodeNameCycle (char * buffer, const char * name, Short_t cycle) [static]
static void TDirectory::EncodeNameCycle (char * buffer, const char * name, Short_t cycle) [static]
virtual void TDirectory::FillBuffer (char *& buffer) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::FillBuffer (char *& buffer) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
void TDirectory::FillFullPath (TString & buf) const [protected]
void TDirectory::FillFullPath (TString & buf) const [protected]
virtual TKey* TDirectory::FindKey (const char * keyname) const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual TKey* TDirectory::FindKey (const char * keyname) const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual TKey* TDirectory::FindKeyAny (const char * keyname) const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual TKey* TDirectory::FindKeyAny (const char * keyname) const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual TObject* TDirectory::FindObject (const TObject * obj) const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual TObject* TDirectory::FindObject (const char * name) const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual TObject* TDirectory::FindObject (const TObject * obj) const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual TObject* TDirectory::FindObject (const char * name) const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual TObject* TDirectory::FindObjectAny (const char * name) const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual TObject* TDirectory::FindObjectAny (const char * name) const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual TObject* TDirectory::Get (const char * namecycle) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual TObject* TDirectory::Get (const char * namecycle) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Referenced by HandleSample(), and MyTestLoop::ProcessMidasEvent().
virtual Int_t TDirectory::GetBufferSize () const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual Int_t TDirectory::GetBufferSize () const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
const TDatime& TDirectory::GetCreationDate () const [inline]
Definition at line 141 of file TDirectory-example.h.
References fDatimeC.
{ return fDatimeC; }
const TDatime& TDirectory::GetCreationDate () const [inline]
Definition at line 141 of file TDirectory-example.h.
References fDatimeC.
{ return fDatimeC; }
virtual TDirectory* TDirectory::GetDirectory (const char * namecycle, Bool_t printError = false, const char * funcname = "GetDirectory") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual TDirectory* TDirectory::GetDirectory (const char * namecycle, Bool_t printError = false, const char * funcname = "GetDirectory") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual TFile* TDirectory::GetFile () const [inline, virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Definition at line 142 of file TDirectory-example.h.
References fFile.
{ return fFile; }
virtual TFile* TDirectory::GetFile () const [inline, virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Definition at line 142 of file TDirectory-example.h.
References fFile.
{ return fFile; }
virtual TKey* TDirectory::GetKey (const char * name, Short_t cycle = 9999) const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual TKey* TDirectory::GetKey (const char * name, Short_t cycle = 9999) const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual TList* TDirectory::GetList () const [inline, virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Definition at line 144 of file TDirectory-example.h.
References fList.
{ return fList; }
virtual TList* TDirectory::GetList () const [inline, virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Definition at line 144 of file TDirectory-example.h.
References fList.
Referenced by ResetObject(), root_server_thread(), and xroot_server_thread().
{ return fList; }
virtual TList* TDirectory::GetListOfKeys () const [inline, virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Definition at line 145 of file TDirectory-example.h.
References fKeys.
{ return fKeys; }
virtual TList* TDirectory::GetListOfKeys () const [inline, virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Definition at line 145 of file TDirectory-example.h.
References fKeys.
Referenced by root_server_thread(), and xroot_server_thread().
{ return fKeys; }
const TDatime& TDirectory::GetModificationDate () const [inline]
Definition at line 146 of file TDirectory-example.h.
References fDatimeM.
{ return fDatimeM; }
const TDatime& TDirectory::GetModificationDate () const [inline]
Definition at line 146 of file TDirectory-example.h.
References fDatimeM.
{ return fDatimeM; }
TObject* TDirectory::GetMother () const [inline]
Definition at line 147 of file TDirectory-example.h.
References fMother.
{ return fMother; }
TObject* TDirectory::GetMother () const [inline]
Definition at line 147 of file TDirectory-example.h.
References fMother.
{ return fMother; }
TDirectory* TDirectory::GetMotherDir () const [inline]
Definition at line 148 of file TDirectory-example.h.
References fMother.
{ return fMother==0 ? 0 : dynamic_cast<TDirectory*>(fMother); }
TDirectory* TDirectory::GetMotherDir () const [inline]
Definition at line 148 of file TDirectory-example.h.
References fMother.
{ return fMother==0 ? 0 : dynamic_cast<TDirectory*>(fMother); }
virtual Int_t TDirectory::GetNbytesKeys () const [inline, virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Definition at line 149 of file TDirectory-example.h.
References fNbytesKeys.
{ return fNbytesKeys; }
virtual Int_t TDirectory::GetNbytesKeys () const [inline, virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Definition at line 149 of file TDirectory-example.h.
References fNbytesKeys.
{ return fNbytesKeys; }
virtual Int_t TDirectory::GetNkeys () const [inline, virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Definition at line 150 of file TDirectory-example.h.
References fKeys.
{ return fKeys->GetSize(); }
virtual Int_t TDirectory::GetNkeys () const [inline, virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Definition at line 150 of file TDirectory-example.h.
References fKeys.
{ return fKeys->GetSize(); }
template<class T > void TDirectory::GetObject (const char * namecycle, T *& ptr) [inline]
Definition at line 133 of file TDirectory-example.h.
References GetObjectChecked().
      {
         ptr = (T*)GetObjectChecked(namecycle,TBuffer::GetClass(typeid(T)));
      }
template<class T > void TDirectory::GetObject (const char * namecycle, T *& ptr) [inline]
Definition at line 133 of file TDirectory-example.h.
References GetObjectChecked().
      {
         ptr = (T*)GetObjectChecked(namecycle,TBuffer::GetClass(typeid(T)));
      }
virtual void* TDirectory::GetObjectChecked (const char * namecycle, const TClass * cl) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void* TDirectory::GetObjectChecked (const char * namecycle, const char * classname) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void* TDirectory::GetObjectChecked (const char * namecycle, const TClass * cl) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void* TDirectory::GetObjectChecked (const char * namecycle, const char * classname) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Referenced by GetObject().
virtual void* TDirectory::GetObjectUnchecked (const char * namecycle) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void* TDirectory::GetObjectUnchecked (const char * namecycle) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual const char* TDirectory::GetPath () const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual const char* TDirectory::GetPath () const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual const char* TDirectory::GetPathStatic () const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual const char* TDirectory::GetPathStatic () const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual Long64_t TDirectory::GetSeekDir () const [inline, virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Definition at line 151 of file TDirectory-example.h.
References fSeekDir.
{ return fSeekDir; }
virtual Long64_t TDirectory::GetSeekDir () const [inline, virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Definition at line 151 of file TDirectory-example.h.
References fSeekDir.
{ return fSeekDir; }
virtual Long64_t TDirectory::GetSeekKeys () const [inline, virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Definition at line 153 of file TDirectory-example.h.
References fSeekKeys.
{ return fSeekKeys; }
virtual Long64_t TDirectory::GetSeekKeys () const [inline, virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Definition at line 153 of file TDirectory-example.h.
References fSeekKeys.
{ return fSeekKeys; }
virtual Long64_t TDirectory::GetSeekParent () const [inline, virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Definition at line 152 of file TDirectory-example.h.
References fSeekParent.
{ return fSeekParent; }
virtual Long64_t TDirectory::GetSeekParent () const [inline, virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Definition at line 152 of file TDirectory-example.h.
References fSeekParent.
{ return fSeekParent; }
TUUID TDirectory::GetUUID () const [inline]
Definition at line 156 of file TDirectory-example.h.
References fUUID.
{return fUUID;}
TUUID TDirectory::GetUUID () const [inline]
Definition at line 156 of file TDirectory-example.h.
References fUUID.
{return fUUID;}
Bool_t TDirectory::IsFolder () const [inline]
Definition at line 157 of file TDirectory-example.h.
{ return kTRUE; }
Bool_t TDirectory::IsFolder () const [inline]
Definition at line 157 of file TDirectory-example.h.
{ return kTRUE; }
Bool_t TDirectory::IsModified () const [inline]
Definition at line 158 of file TDirectory-example.h.
References fModified.
{ return fModified; }
Bool_t TDirectory::IsModified () const [inline]
Definition at line 158 of file TDirectory-example.h.
References fModified.
{ return fModified; }
Bool_t TDirectory::IsWritable () const [inline]
Definition at line 159 of file TDirectory-example.h.
References fWritable.
{ return fWritable; }
Bool_t TDirectory::IsWritable () const [inline]
Definition at line 159 of file TDirectory-example.h.
References fWritable.
{ return fWritable; }
virtual void TDirectory::ls (Option_t * option = "") const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::ls (Option_t * option = "") const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual TDirectory* TDirectory::mkdir (const char * name, const char * title = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual TDirectory* TDirectory::mkdir (const char * name, const char * title = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Referenced by main().
void TDirectory::operator= (const TDirectory &) [private]
Reimplemented in TNetDirectory, and TNetDirectory.
void TDirectory::operator= (const TDirectory &) [private]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::Paint (Option_t * option = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::Paint (Option_t * option = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::Print (Option_t * option = "") const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::Print (Option_t * option = "") const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::Purge (Short_t nkeep = 1) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::Purge (Short_t nkeep = 1) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::pwd () const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::pwd () const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::ReadAll (Option_t * option = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::ReadAll (Option_t * option = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual Int_t TDirectory::ReadKeys () [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual Int_t TDirectory::ReadKeys () [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::RecursiveRemove (TObject * obj) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::RecursiveRemove (TObject * obj) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::rmdir (const char * name) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::rmdir (const char * name) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::Save () [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::Save () [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::SaveSelf (Bool_t force = kFALSE) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::SaveSelf (Bool_t force = kFALSE) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::SetBufferSize (Int_t bufsize) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::SetBufferSize (Int_t bufsize) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
void TDirectory::SetModified () [inline]
Definition at line 173 of file TDirectory-example.h.
References fModified.
{fModified = kTRUE;}
void TDirectory::SetModified () [inline]
Definition at line 173 of file TDirectory-example.h.
References fModified.
{fModified = kTRUE;}
void TDirectory::SetMother (const TObject * mother) [inline]
Definition at line 174 of file TDirectory-example.h.
References fMother.
{fMother = (TObject*)mother;}
void TDirectory::SetMother (const TObject * mother) [inline]
Definition at line 174 of file TDirectory-example.h.
References fMother.
{fMother = (TObject*)mother;}
virtual void TDirectory::SetName (const char * newname) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::SetName (const char * newname) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
void TDirectory::SetSeekDir (Long64_t v) [inline]
Definition at line 176 of file TDirectory-example.h.
References fSeekDir.
{ fSeekDir = v; }
void TDirectory::SetSeekDir (Long64_t v) [inline]
Definition at line 176 of file TDirectory-example.h.
References fSeekDir.
{ fSeekDir = v; }
void TDirectory::SetWritable (Bool_t writable = kTRUE)
void TDirectory::SetWritable (Bool_t writable = kTRUE)
virtual Int_t TDirectory::Sizeof () const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual Int_t TDirectory::Sizeof () const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual Int_t TDirectory::Write (const char * name = 0, Int_t opt = 0, Int_t bufsiz = 0) const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual Int_t TDirectory::Write (const char * name = 0, Int_t opt = 0, Int_t bufsiz = 0) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual Int_t TDirectory::Write (const char * name = 0, Int_t opt = 0, Int_t bufsiz = 0) const [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual Int_t TDirectory::Write (const char * name = 0, Int_t opt = 0, Int_t bufsiz = 0) [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::WriteDirHeader () [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::WriteDirHeader () [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::WriteKeys () [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual void TDirectory::WriteKeys () [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
template<class T > Int_t TDirectory::WriteObject (const T * obj, const char * name, Option_t * option = "") [inline]
Definition at line 182 of file TDirectory-example.h.
References WriteObjectAny().
      {
         return WriteObjectAny(obj,TBuffer::GetClass(typeid(T)),name,option);
      }
template<class T > Int_t TDirectory::WriteObject (const T * obj, const char * name, Option_t * option = "") [inline]
Definition at line 182 of file TDirectory-example.h.
References WriteObjectAny().
      {
         return WriteObjectAny(obj,TBuffer::GetClass(typeid(T)),name,option);
      }
virtual Int_t TDirectory::WriteObjectAny (const void * obj, const TClass * cl, const char * name, Option_t * option = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual Int_t TDirectory::WriteObjectAny (const void * obj, const char * classname, const char * name, Option_t * option = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual Int_t TDirectory::WriteObjectAny (const void * obj, const TClass * cl, const char * name, Option_t * option = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual Int_t TDirectory::WriteObjectAny (const void * obj, const char * classname, const char * name, Option_t * option = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Referenced by WriteObject().
virtual Int_t TDirectory::WriteTObject (const TObject * obj, const char * name = 0, Option_t * option = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
virtual Int_t TDirectory::WriteTObject (const TObject * obj, const char * name = 0, Option_t * option = "") [virtual]
Reimplemented in TNetDirectory, and TNetDirectory.
Member Data Documentation
Int_t TDirectory::fBufferSize [protected]
Definition at line 52 of file TDirectory-example.h.
TDatime TDirectory::fDatimeC [protected]
Definition at line 48 of file TDirectory-example.h.
Referenced by GetCreationDate().
TDatime TDirectory::fDatimeM [protected]
Definition at line 49 of file TDirectory-example.h.
Referenced by GetModificationDate().
TFile * TDirectory::fFile [protected]
Definition at line 56 of file TDirectory-example.h.
Referenced by GetFile().
TList * TDirectory::fKeys [protected]
Definition at line 59 of file TDirectory-example.h.
Referenced by GetListOfKeys(), and GetNkeys().
TList * TDirectory::fList [protected]
Definition at line 58 of file TDirectory-example.h.
Referenced by GetList().
Bool_t TDirectory::fModified [protected]
Definition at line 46 of file TDirectory-example.h.
Referenced by IsModified(), and SetModified().
TObject * TDirectory::fMother [protected]
Definition at line 57 of file TDirectory-example.h.
Referenced by GetMother(), GetMotherDir(), and SetMother().
Int_t TDirectory::fNbytesKeys [protected]
Definition at line 50 of file TDirectory-example.h.
Referenced by GetNbytesKeys().
Int_t TDirectory::fNbytesName [protected]
Definition at line 51 of file TDirectory-example.h.
TString TDirectory::fPathBuffer [protected]
Definition at line 61 of file TDirectory-example.h.
Long64_t TDirectory::fSeekDir [protected]
Definition at line 53 of file TDirectory-example.h.
Referenced by GetSeekDir(), and SetSeekDir().
Long64_t TDirectory::fSeekKeys [protected]
Definition at line 55 of file TDirectory-example.h.
Referenced by GetSeekKeys().
Long64_t TDirectory::fSeekParent [protected]
Definition at line 54 of file TDirectory-example.h.
Referenced by GetSeekParent().
TUUID TDirectory::fUUID [protected]
Definition at line 60 of file TDirectory-example.h.
Referenced by GetUUID().
Bool_t TDirectory::fWritable [protected]
Definition at line 47 of file TDirectory-example.h.
Referenced by IsWritable().
The documentation for this class was generated from the following files:
include/TDirectory-example.h
libNetDirectory/TDirectory-example.h