ROOT Analyzer: libNetDirectory/RootLock.cxx File Reference
RootLock.cxx File Reference
#include "RootLock.h"
#include <TSemaphore.h>
#include <TTimer.h>
Classes
class ServerTimer
Functions
static TSemaphore gRootSema (0)
static TSemaphore gWaitSema (0)
static TSemaphore gDoneSema (0)
void LockRoot ()
void UnlockRoot ()
void StartLockRootTimer (int period_msec)
Variables
bool gDebugLockRoot = false
Function Documentation
static TSemaphore gDoneSema (0) [static]
Referenced by ServerTimer::Notify(), and UnlockRoot().
static TSemaphore gRootSema (0) [static]
Referenced by LockRoot(), and ServerTimer::Notify().
static TSemaphore gWaitSema (0) [static]
Referenced by LockRoot(), and ServerTimer::Notify().
void LockRoot ()
Definition at line 23 of file RootLock.cxx.
References gDebugLockRoot, gRootSema(), and gWaitSema().
Referenced by LockRootGuard::LockRootGuard().
{
  if (gDebugLockRoot)
    printf("Try Lock ROOT!\n");
  gWaitSema.Post();
  gRootSema.Wait();
  if (gDebugLockRoot)
    printf("Lock ROOT!\n");
}
void StartLockRootTimer (int period_msec)
Definition at line 114 of file RootLock.cxx.
References ServerTimer::StartServerTimer().
Referenced by StartMidasServer(), and StartNetDirectoryServer().
{
  ServerTimer::StartServerTimer(period_msec);
}
void UnlockRoot ()
Definition at line 33 of file RootLock.cxx.
References gDebugLockRoot, and gDoneSema().
Referenced by LockRootGuard::Unlock().
{
  if (gDebugLockRoot)
    printf("Unlock ROOT!\n");
  gDoneSema.Post();
}
Variable Documentation
bool gDebugLockRoot = false
Definition at line 21 of file RootLock.cxx.
Referenced by LockRoot(), ServerTimer::Notify(), and UnlockRoot().