ROOT Analyzer: libMidasInterface/TMidasFile.cxx File Reference
TMidasFile.cxx File Reference
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <errno.h>
#include <assert.h>
#include "TMidasFile.h"
#include "TMidasEvent.h"
Defines
#define O_LARGEFILE 0
Functions
static int hasSuffix (const char *name, const char *suffix)
static int readpipe (int fd, char *buf, int length)
Define Documentation
#define O_LARGEFILE 0
Referenced by TMidasFile::Open(), and TMidasFile::OutOpen().
Function Documentation
static int hasSuffix (const char * name, const char * suffix) [static]
Definition at line 41 of file TMidasFile.cxx.
Referenced by TMidasFile::Open(), and TMidasFile::OutOpen().
{
  const char* s = strstr(name,suffix);
  if (s == NULL)
    return 0;
  return (s-name)+strlen(suffix) == strlen(name);
}
static int readpipe (int fd, char * buf, int length) [static]
Definition at line 255 of file TMidasFile.cxx.
Referenced by TMidasFile::Read().
{
  int count = 0;
  while (length > 0)
    {
      int rd = read(fd, buf, length);
      if (rd > 0)
        {
          buf += rd;
          length -= rd;
          count += rd;
        }
      else if (rd == 0)
        {
          return count;
        }
      else
        {
          return -1;
        }
    }
  return count;
}