.TH "OptStatMenu" 3 "Thu Apr 26 2012" "Roody" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OptStatMenu \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOptStatMenu\fP (const TGWindow *w)"
.br
.ti -1c
.RI "Bool_t \fBProcessMessage\fP (Long_t msg, Long_t parm1, Long_t parm2)"
.br
.ti -1c
.RI "void \fBGetOptStat\fP ()"
.br
.ti -1c
.RI "void \fBSetOptStat\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 794 of file Roody.cxx.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OptStatMenu::OptStatMenu (const TGWindow *w)\fC [inline]\fP"
.PP
Definition at line 797 of file Roody.cxx.
.SH "Member Function Documentation"
.PP 
.SS "void OptStatMenu::GetOptStat ()\fC [inline]\fP"
.PP
Definition at line 841 of file Roody.cxx.
.PP
Referenced by OptStatMenu().
.SS "Bool_t OptStatMenu::ProcessMessage (Long_tmsg, Long_tparm1, Long_tparm2)\fC [inline]\fP"
.PP
Definition at line 821 of file Roody.cxx.
.SS "void OptStatMenu::SetOptStat ()\fC [inline]\fP"
.PP
Definition at line 857 of file Roody.cxx.
.PP
Referenced by OptStatMenu(), and ProcessMessage().

.SH "Author"
.PP 
Generated automatically by Doxygen for Roody from the source code.
