.TH "RoodyXML.cxx" 3 "Thu Apr 26 2012" "Roody" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RoodyXML.cxx \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <ios>\fP
.br
\fC#include <time.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include 'RoodyXML.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Roody from the source code.
