.TH "RoodyXML.h" 3 "Thu Apr 26 2012" "Roody" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RoodyXML.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'mxml.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRoodyXML\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Roody from the source code.
