.TH "Roody.h" 3 "Thu Apr 26 2012" "Roody" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Roody.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br
\fC#include <assert.h>\fP
.br
\fC#include 'TGFrame.h'\fP
.br
\fC#include 'DataSourceBase.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPadObject\fP"
.br
.ti -1c
.RI "struct \fBPadObjectVec\fP"
.br
.ti -1c
.RI "class \fBRoody\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct mxml_struct * \fBPMXML_NODE\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct mxml_struct* \fBPMXML_NODE\fP"
.PP
Definition at line 29 of file Roody.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Roody from the source code.
