.TH "RoodyXML" 3 "Thu Apr 26 2012" "Roody" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RoodyXML \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RoodyXML.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBFindNode\fP (\fBPMXML_NODE\fP parent, int startIndex, const char *name)"
.br
.ti -1c
.RI "\fBPMXML_NODE\fP \fBGetNode\fP (\fBPMXML_NODE\fP parent, int index)"
.br
.ti -1c
.RI "std::string \fBGetNodeString\fP (\fBPMXML_NODE\fP node, int index)"
.br
.ti -1c
.RI "\fBRoodyXML\fP ()"
.br
.ti -1c
.RI "virtual \fB~RoodyXML\fP ()"
.br
.ti -1c
.RI "std::ofstream & \fBOpenFileForWrite\fP (char const *)"
.br
.ti -1c
.RI "std::string \fBEncode\fP (std::string const &)"
.br
.ti -1c
.RI "bool \fBOpenFileForRead\fP (char const *)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBlevel_\fP"
.br
.ti -1c
.RI "bool \fBelementIsOpen_\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBnames_\fP"
.br
.ti -1c
.RI "std::ofstream \fBoutputFile_\fP"
.br
.ti -1c
.RI "char const * \fBencoding_\fP"
.br
.ti -1c
.RI "char const * \fBversion_\fP"
.br
.ti -1c
.RI "\fBPMXML_NODE\fP \fBdocumentNode_\fP"
.br
.ti -1c
.RI "\fBPMXML_NODE\fP \fBroodyNode_\fP"
.br
.ti -1c
.RI "\fBPMXML_NODE\fP \fBhistParent_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file RoodyXML.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RoodyXML::RoodyXML ()"
.PP
Definition at line 14 of file RoodyXML.cxx.
.SS "RoodyXML::~RoodyXML ()\fC [virtual]\fP"
.PP
Definition at line 20 of file RoodyXML.cxx.
.SH "Member Function Documentation"
.PP 
.SS "std::string RoodyXML::Encode (std::string const &src)"
.PP
Definition at line 59 of file RoodyXML.cxx.
.PP
Referenced by Roody::SaveFile(), and Roody::SaveFilePadContents().
.SS "int RoodyXML::FindNode (\fBPMXML_NODE\fPparent, intstartIndex, const char *name)"
.PP
Definition at line 108 of file RoodyXML.cxx.
.PP
Referenced by OpenFileForRead(), Roody::RestoreFile(), and Roody::RestoreObjects().
.SS "\fBPMXML_NODE\fP RoodyXML::GetNode (\fBPMXML_NODE\fPparent, intindex)"
.PP
Definition at line 118 of file RoodyXML.cxx.
.PP
Referenced by Roody::RestoreFile(), and Roody::RestoreObjects().
.SS "std::string RoodyXML::GetNodeString (\fBPMXML_NODE\fPnode, intindex)"
.PP
Definition at line 126 of file RoodyXML.cxx.
.PP
Referenced by Roody::RestoreFile(), and Roody::RestoreObjects().
.SS "bool RoodyXML::OpenFileForRead (char const *file)"
.PP
Definition at line 89 of file RoodyXML.cxx.
.PP
Referenced by Roody::RestoreFile().
.SS "std::ofstream & RoodyXML::OpenFileForWrite (char const *file)"
.PP
Definition at line 23 of file RoodyXML.cxx.
.PP
Referenced by Roody::SaveFile().
.SH "Member Data Documentation"
.PP 
.SS "\fBPMXML_NODE\fP \fBRoodyXML::documentNode_\fP"
.PP
Definition at line 30 of file RoodyXML.h.
.PP
Referenced by OpenFileForRead().
.SS "bool \fBRoodyXML::elementIsOpen_\fP"
.PP
Definition at line 25 of file RoodyXML.h.
.SS "char const* \fBRoodyXML::encoding_\fP"
.PP
Definition at line 28 of file RoodyXML.h.
.PP
Referenced by OpenFileForWrite(), and RoodyXML().
.SS "\fBPMXML_NODE\fP \fBRoodyXML::histParent_\fP"
.PP
Definition at line 30 of file RoodyXML.h.
.SS "unsigned int \fBRoodyXML::level_\fP"
.PP
Definition at line 24 of file RoodyXML.h.
.SS "std::vector<std::string> \fBRoodyXML::names_\fP"
.PP
Definition at line 26 of file RoodyXML.h.
.SS "std::ofstream \fBRoodyXML::outputFile_\fP"
.PP
Definition at line 27 of file RoodyXML.h.
.PP
Referenced by OpenFileForWrite().
.SS "\fBPMXML_NODE\fP \fBRoodyXML::roodyNode_\fP"
.PP
Definition at line 30 of file RoodyXML.h.
.PP
Referenced by OpenFileForRead(), and Roody::RestoreFile().
.SS "char const* \fBRoodyXML::version_\fP"
.PP
Definition at line 29 of file RoodyXML.h.
.PP
Referenced by OpenFileForWrite(), and RoodyXML().

.SH "Author"
.PP 
Generated automatically by Doxygen for Roody from the source code.
