.TH "TGTextDialog.cxx" 3 "Thu Apr 26 2012" "Roody" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TGTextDialog.cxx \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'TGTextDialog.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBClassImp\fP (\fBTGTextDialog\fP) \fBTGTextDialog\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "ClassImp (\fBTGTextDialog\fP)"
.PP
Definition at line 16 of file TGTextDialog.cxx.
.SH "Author"
.PP 
Generated automatically by Doxygen for Roody from the source code.
