.TH "TGTextDialog.h" 3 "Thu Apr 26 2012" "Roody" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TGTextDialog.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <TGButton.h>\fP
.br
\fC#include <TRootEmbeddedCanvas.h>\fP
.br
\fC#include <TGLayout.h>\fP
.br
\fC#include <TH2.h>\fP
.br
\fC#include <TCanvas.h>\fP
.br
\fC#include <TSocket.h>\fP
.br
\fC#include <TMessage.h>\fP
.br
\fC#include <TGMsgBox.h>\fP
.br
\fC#include <TApplication.h>\fP
.br
\fC#include <TROOT.h>\fP
.br
\fC#include <TGListBox.h>\fP
.br
\fC#include <TString.h>\fP
.br
\fC#include <TObjArray.h>\fP
.br
\fC#include <TObjString.h>\fP
.br
\fC#include <TGMenu.h>\fP
.br
\fC#include <TGTab.h>\fP
.br
\fC#include <TGLabel.h>\fP
.br
\fC#include <TGTextEntry.h>\fP
.br
\fC#include <TGFrame.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTGTextDialog\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Roody from the source code.
