.TH "TPeakFindPanel" 3 "Thu Apr 26 2012" "Roody" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TPeakFindPanel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TPeakFindPanel.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTPeakFindPanel\fP (TGWindow const *, TGWindow const *, UInt_t, UInt_t)"
.br
.ti -1c
.RI "virtual \fB~TPeakFindPanel\fP ()"
.br
.ti -1c
.RI "virtual void \fBCloseWindow\fP ()"
.br
.ti -1c
.RI "virtual Bool_t \fBProcessMessage\fP (Long_t, Long_t, Long_t)"
.br
.ti -1c
.RI "\fBClassDef\fP (\fBTPeakFindPanel\fP, 1)"
.br
.in -1c
.SS "Protected Types"

.in +1c
.ti -1c
.RI "enum \fBECommandIdentifiers\fP { \fBM_FILE_EXIT\fP, \fBM_ATTEMPT_FIT_PEAKS_BUTTON\fP, \fBM_ADD_POLY_BUTTON\fP, \fBM_DO_UNZOOM_BUTTON\fP, \fBM_FIND_BUTTON\fP, \fBM_DEFAULT_BUTTON\fP, \fBM_CLOSE_BUTTON\fP, \fBM_CLEAR_BUTTON\fP, \fBM_NUMBER_ENTRY_PEAKS\fP, \fBM_NUMBER_ENTRY_RESOLUTION\fP, \fBM_NUMBER_ENTRY_SIGMA\fP, \fBM_NUMBER_ENTRY_THRESHOLD\fP }"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Double_t \fBfSigma\fP"
.br
.ti -1c
.RI "Double_t \fBfThreshold\fP"
.br
.ti -1c
.RI "Float_t \fBfResolution\fP"
.br
.ti -1c
.RI "Int_t \fBfNumberOfPeaks\fP"
.br
.ti -1c
.RI "TF1 * \fBfFit\fP"
.br
.ti -1c
.RI "Bool_t \fBfDoFit\fP"
.br
.ti -1c
.RI "Bool_t \fBfAddPoly\fP"
.br
.ti -1c
.RI "Bool_t \fBfDoUnzoom\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBFindPeak\fP ()"
.br
.ti -1c
.RI "void \fBDrawPeak\fP ()"
.br
.ti -1c
.RI "void \fBLayoutGUI\fP ()"
.br
.ti -1c
.RI "void \fBLayoutMenuBar\fP ()"
.br
.ti -1c
.RI "void \fBGetXYBounds\fP (Double_t &, Double_t &)"
.br
.ti -1c
.RI "void \fBInsertionSort\fP (Float_t *, Float_t *, Int_t, Int_t)"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBSetDefaults\fP ()"
.br
.ti -1c
.RI "TH1 * \fBGetHistogram\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "TGNumberEntry * \fBfNumberOfPeaksNE\fP"
.br
.ti -1c
.RI "TGNumberEntry * \fBfResolutionNE\fP"
.br
.ti -1c
.RI "TGNumberEntry * \fBfSigmaNE\fP"
.br
.ti -1c
.RI "TGNumberEntry * \fBfThresholdNE\fP"
.br
.ti -1c
.RI "TGCheckButton * \fBfAttemptFitCB\fP"
.br
.ti -1c
.RI "TGCheckButton * \fBfAddPolyFitCB\fP"
.br
.ti -1c
.RI "TGCheckButton * \fBfDoUnzoomCB\fP"
.br
.ti -1c
.RI "TGTextButton * \fBfFindTB\fP"
.br
.ti -1c
.RI "TGTextButton * \fBfDefaultsTB\fP"
.br
.ti -1c
.RI "TGTextButton * \fBfCloseTB\fP"
.br
.ti -1c
.RI "TGTextButton * \fBfClearPolyTB\fP"
.br
.ti -1c
.RI "TGVerticalFrame * \fBfMainFrame\fP"
.br
.ti -1c
.RI "TGHorizontalFrame * \fBfNumberOfPeaksHF\fP"
.br
.ti -1c
.RI "TGHorizontalFrame * \fBfResolutionHF\fP"
.br
.ti -1c
.RI "TGHorizontalFrame * \fBfSigmaHF\fP"
.br
.ti -1c
.RI "TGHorizontalFrame * \fBfThresholdHF\fP"
.br
.ti -1c
.RI "TGHorizontalFrame * \fBfFindDefaultsHF\fP"
.br
.ti -1c
.RI "TGHorizontalFrame * \fBfCloseClearPolyHF\fP"
.br
.ti -1c
.RI "TSpectrum * \fBfSpectrum\fP"
.br
.ti -1c
.RI "Int_t \fBfNfound\fP"
.br
.ti -1c
.RI "Float_t * \fBfXpeaks\fP"
.br
.ti -1c
.RI "Float_t * \fBfYpeaks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file TPeakFindPanel.h.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBTPeakFindPanel::ECommandIdentifiers\fP\fC [protected]\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIM_FILE_EXIT \fP\fP
.TP
\fB\fIM_ATTEMPT_FIT_PEAKS_BUTTON \fP\fP
.TP
\fB\fIM_ADD_POLY_BUTTON \fP\fP
.TP
\fB\fIM_DO_UNZOOM_BUTTON \fP\fP
.TP
\fB\fIM_FIND_BUTTON \fP\fP
.TP
\fB\fIM_DEFAULT_BUTTON \fP\fP
.TP
\fB\fIM_CLOSE_BUTTON \fP\fP
.TP
\fB\fIM_CLEAR_BUTTON \fP\fP
.TP
\fB\fIM_NUMBER_ENTRY_PEAKS \fP\fP
.TP
\fB\fIM_NUMBER_ENTRY_RESOLUTION \fP\fP
.TP
\fB\fIM_NUMBER_ENTRY_SIGMA \fP\fP
.TP
\fB\fIM_NUMBER_ENTRY_THRESHOLD \fP\fP

.PP
Definition at line 75 of file TPeakFindPanel.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TPeakFindPanel::TPeakFindPanel (TGWindow const *, TGWindow const *, UInt_t, UInt_t)"
.SS "virtual TPeakFindPanel::~TPeakFindPanel ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "TPeakFindPanel::ClassDef (\fBTPeakFindPanel\fP, 1)"
.SS "void TPeakFindPanel::Clear ()\fC [private]\fP"
.SS "virtual void TPeakFindPanel::CloseWindow ()\fC [virtual]\fP"
.SS "void TPeakFindPanel::DrawPeak ()\fC [private]\fP"
.SS "void TPeakFindPanel::FindPeak ()\fC [private]\fP"
.SS "TH1* TPeakFindPanel::GetHistogram ()\fC [private]\fP"
.SS "void TPeakFindPanel::GetXYBounds (Double_t &, Double_t &)\fC [private]\fP"
.SS "void TPeakFindPanel::InsertionSort (Float_t *, Float_t *, Int_t, Int_t)\fC [private]\fP"
.SS "void TPeakFindPanel::LayoutGUI ()\fC [private]\fP"
.SS "void TPeakFindPanel::LayoutMenuBar ()\fC [private]\fP"
.SS "virtual Bool_t TPeakFindPanel::ProcessMessage (Long_t, Long_t, Long_t)\fC [virtual]\fP"
.SS "void TPeakFindPanel::SetDefaults ()\fC [private]\fP"
.SH "Member Data Documentation"
.PP 
.SS "Bool_t \fBTPeakFindPanel::fAddPoly\fP\fC [protected]\fP"
.PP
Definition at line 95 of file TPeakFindPanel.h.
.SS "TGCheckButton * \fBTPeakFindPanel::fAddPolyFitCB\fP\fC [private]\fP"
.PP
Definition at line 53 of file TPeakFindPanel.h.
.SS "TGCheckButton* \fBTPeakFindPanel::fAttemptFitCB\fP\fC [private]\fP"
.PP
Definition at line 53 of file TPeakFindPanel.h.
.SS "TGTextButton * \fBTPeakFindPanel::fClearPolyTB\fP\fC [private]\fP"
.PP
Definition at line 54 of file TPeakFindPanel.h.
.SS "TGHorizontalFrame * \fBTPeakFindPanel::fCloseClearPolyHF\fP\fC [private]\fP"
.PP
Definition at line 57 of file TPeakFindPanel.h.
.SS "TGTextButton * \fBTPeakFindPanel::fCloseTB\fP\fC [private]\fP"
.PP
Definition at line 54 of file TPeakFindPanel.h.
.SS "TGTextButton * \fBTPeakFindPanel::fDefaultsTB\fP\fC [private]\fP"
.PP
Definition at line 54 of file TPeakFindPanel.h.
.SS "Bool_t \fBTPeakFindPanel::fDoFit\fP\fC [protected]\fP"
.PP
Definition at line 95 of file TPeakFindPanel.h.
.SS "Bool_t \fBTPeakFindPanel::fDoUnzoom\fP\fC [protected]\fP"
.PP
Definition at line 95 of file TPeakFindPanel.h.
.SS "TGCheckButton * \fBTPeakFindPanel::fDoUnzoomCB\fP\fC [private]\fP"
.PP
Definition at line 53 of file TPeakFindPanel.h.
.SS "TGHorizontalFrame* \fBTPeakFindPanel::fFindDefaultsHF\fP\fC [private]\fP"
.PP
Definition at line 57 of file TPeakFindPanel.h.
.SS "TGTextButton* \fBTPeakFindPanel::fFindTB\fP\fC [private]\fP"
.PP
Definition at line 54 of file TPeakFindPanel.h.
.SS "TF1* \fBTPeakFindPanel::fFit\fP\fC [protected]\fP"
.PP
Definition at line 94 of file TPeakFindPanel.h.
.SS "TGVerticalFrame* \fBTPeakFindPanel::fMainFrame\fP\fC [private]\fP"
.PP
Definition at line 55 of file TPeakFindPanel.h.
.SS "Int_t \fBTPeakFindPanel::fNfound\fP\fC [private]\fP"
.PP
Definition at line 60 of file TPeakFindPanel.h.
.SS "Int_t \fBTPeakFindPanel::fNumberOfPeaks\fP\fC [protected]\fP"
.PP
Definition at line 93 of file TPeakFindPanel.h.
.SS "TGHorizontalFrame* \fBTPeakFindPanel::fNumberOfPeaksHF\fP\fC [private]\fP"
.PP
Definition at line 56 of file TPeakFindPanel.h.
.SS "TGNumberEntry* \fBTPeakFindPanel::fNumberOfPeaksNE\fP\fC [private]\fP"
.PP
Definition at line 52 of file TPeakFindPanel.h.
.SS "Float_t \fBTPeakFindPanel::fResolution\fP\fC [protected]\fP"
.PP
Definition at line 92 of file TPeakFindPanel.h.
.SS "TGHorizontalFrame * \fBTPeakFindPanel::fResolutionHF\fP\fC [private]\fP"
.PP
Definition at line 56 of file TPeakFindPanel.h.
.SS "TGNumberEntry * \fBTPeakFindPanel::fResolutionNE\fP\fC [private]\fP"
.PP
Definition at line 52 of file TPeakFindPanel.h.
.SS "Double_t \fBTPeakFindPanel::fSigma\fP\fC [protected]\fP"
.PP
Definition at line 91 of file TPeakFindPanel.h.
.SS "TGHorizontalFrame * \fBTPeakFindPanel::fSigmaHF\fP\fC [private]\fP"
.PP
Definition at line 56 of file TPeakFindPanel.h.
.SS "TGNumberEntry * \fBTPeakFindPanel::fSigmaNE\fP\fC [private]\fP"
.PP
Definition at line 52 of file TPeakFindPanel.h.
.SS "TSpectrum* \fBTPeakFindPanel::fSpectrum\fP\fC [private]\fP"
.PP
Definition at line 58 of file TPeakFindPanel.h.
.SS "Double_t \fBTPeakFindPanel::fThreshold\fP\fC [protected]\fP"
.PP
Definition at line 91 of file TPeakFindPanel.h.
.SS "TGHorizontalFrame * \fBTPeakFindPanel::fThresholdHF\fP\fC [private]\fP"
.PP
Definition at line 56 of file TPeakFindPanel.h.
.SS "TGNumberEntry * \fBTPeakFindPanel::fThresholdNE\fP\fC [private]\fP"
.PP
Definition at line 52 of file TPeakFindPanel.h.
.SS "Float_t* \fBTPeakFindPanel::fXpeaks\fP\fC [private]\fP"
.PP
Definition at line 61 of file TPeakFindPanel.h.
.SS "Float_t* \fBTPeakFindPanel::fYpeaks\fP\fC [private]\fP"
.PP
[fNfound] 
.PP
Definition at line 62 of file TPeakFindPanel.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Roody from the source code.
