.TH "TPeakFindPanel.h" 3 "Thu Apr 26 2012" "Roody" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TPeakFindPanel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'TGFrame.h'\fP
.br
\fC#include 'TROOT.h'\fP
.br
\fC#include 'TVirtualX.h'\fP
.br
\fC#include 'TGResourcePool.h'\fP
.br
\fC#include 'TGClient.h'\fP
.br
\fC#include 'TGIcon.h'\fP
.br
\fC#include 'TGLabel.h'\fP
.br
\fC#include 'TGButton.h'\fP
.br
\fC#include 'TGTextEntry.h'\fP
.br
\fC#include 'TGNumberEntry.h'\fP
.br
\fC#include 'TGMsgBox.h'\fP
.br
\fC#include 'TGMenu.h'\fP
.br
\fC#include 'TGCanvas.h'\fP
.br
\fC#include 'TGComboBox.h'\fP
.br
\fC#include 'TGSlider.h'\fP
.br
\fC#include 'TGDoubleSlider.h'\fP
.br
\fC#include 'RQ_OBJECT.h'\fP
.br
\fC#include 'TGLayout.h'\fP
.br
\fC#include 'TH1.h'\fP
.br
\fC#include 'TF1.h'\fP
.br
\fC#include 'TFitter.h'\fP
.br
\fC#include 'TVirtualFitter.h'\fP
.br
\fC#include 'TCanvas.h'\fP
.br
\fC#include 'TRandom.h'\fP
.br
\fC#include 'TGTab.h'\fP
.br
\fC#include 'TList.h'\fP
.br
\fC#include 'TGStatusBar.h'\fP
.br
\fC#include 'TSpectrum.h'\fP
.br
\fC#include 'TPolyMarker.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTPeakFindPanel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Roody from the source code.
